### ISSUE TITLE
Model schemaOptions all getting merged and resulting in all models having same collection name

### ISSUE THREAD

**Issue by duro** [typegoose/typegoose#100]
## Versions

- NodeJS: 10.16.3
- Typegoose(NPM): 6.0.1
- mongoose: 5.7.6
  
## What is the Problem?

I have multiple schemas (models), which I name as classes like so:

`UserSchema`
`OrganizationSchema`
etc..

In order to make sure these get stored in collections that are not named `userschema` and `organizationschema` I have used model options to explicityly state what the collection name should be:

```
@modelOptions({schemaOptions: {collection: 'organizations'}})
export class OrganizationSchema {}
```

However, when I load in these multiple models into Typegoose, they are all ending up being assigned the same collection name. Here are some logs that I output from the buildSchema method of typegoose:

```
!!! CLASS NAME !!! PortalUserSchema
!!! OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
!!! MERGED OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
!!! CLASS NAME !!! PortalUserOrgRolesSchema
!!! OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
!!! MERGED OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
!!! CLASS NAME !!! OrgRoleSchema
!!! OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
!!! MERGED OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
!!! CLASS NAME !!! OrganizationSchema
!!! OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
!!! MERGED OPTIONS !!! { timestamps: true, collection: 'portaluserorgroles' }
```

## Code Example

https://gist.github.com/duro/ce2d4763a0c99ee468306822d163c259

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
wasnt this fixed already?

did you already try `6.0.4`?

**Comment by hasezoey** [comment]
cant reproduce, used code: https://github.com/typegoose/typegoose-testing/tree/verify100

**Comment by duro** [comment]
@hasezoey I didn't see anything in the release notes that looked like it addressed this, so didn't even think that was the case. Let me give it a shot.

**Comment by hasezoey** [comment]
> I didn't see anything in the release notes that looked like it addressed this, so didn't even think that was the case. Let me give it a shot.

i dont know *when* it was fixed, i think it was even when 6.0.0 was still in a pre-release

**Comment by duro** [comment]
@hasezoey I just tried upgrading to 6.0.4 and I'm still getting same result. I'll keep digging to see what could be causing it on my end, but when I log extensively through the typegoose code, I am seeing that whatever the last model is that calls `@modelOptions`, the collection it defines is applied to all models that are created via `getModelForClass`

**Comment by hasezoey** [comment]
> I log extensively through the typegoose code

already activated `setLogLeve("DEBUG")`?

**Comment by hasezoey** [comment]
can you modify the branch i already mentioned to trigger this behavior?

**Comment by duro** [comment]
@hasezoey This is the output from logging that way:

```
_buildSchema Called for BaseSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
_buildSchema Called for PortalUserSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
Applying Index: { fields: { email: 1 }, options: { unique: true } }
_buildSchema Called for BaseSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
_buildSchema Called for PortalUserOrgRolesSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
_buildSchema Called for BaseSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
_buildSchema Called for OrgRoleSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
_buildSchema Called for BaseSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
_buildSchema Called for OrganizationSchema with options: { timestamps: true, collection: 'portaluserorgroles' }
```

I will try using your reproduction repo and see what i can get. The only difference I can think of is that I am using `nestjs-typegoose` to actually bootstrap the models. That said, it doesn't do much else than handle creating a connection to mongo, and then bootstrapping the models by also passing in an `existingConnection`

**Comment by hasezoey** [comment]
also from your log output, it seems like everywhere the same options are applied ...

what might help, is the current structure of how thing *should* work:
```
(when i say `merge`, the new options will overwrite existing options with the same key)  
-> global options get assigned when `@modelOptions` is called, and is still "undefined / null"  
-> then (depending of how many `@modelOptions` you have on **one** model, it will merge with the previous (i dont know the execution order...)  
-> then, when build with `getModelForClass`, the options will merge, and get passed down to `buildSchema`  
  -> then in buildSchema, options will merge again (only `schemaOptions`) and are then passed down to each `_buildSchema` call  
    -> then in `_buildSchema` options will merge again (only `schemaOptions`)  
```

some might ask "why so many merges"? it is because each function can be called without the other  

and the `then in "_buildSchema" options will merge again` call, the schema is build with the top class's options, but will not get saved to any cache, so it shouldnt affect any other that is depending on it

PS: sorry if this is a bit unclear / undetailed, but it is the only way i found to "simplify" so that it fits here

**Comment by duro** [comment]
@hasezoey I agree, the same model options are being applied each time, however, when I added come console logs to the actual `modelOptions` decorator I could clearly see that different model options were being set into the metadata store.

However, the logging I had in `buildSchema` showed what your logs output, that the same options were being applied.

What my initial read of the logs makes me think is that the metadata is getting overwritten each time it gets saved into the reflect store. So whatever the last decorator that gets processed is, that's the options that end up getting applied to all models at buildSchema time.

**Comment by hasezoey** [comment]
every option passed into `getModelForClass` / `buildSchema` / `_buildSchema` is ***not*** saved, only calls from `@modelOptions` are saved

**Comment by duro** [comment]
@hasezoey I have a full reproduction now:

https://github.com/duro/typegoose-testing

When I pull that down, run `npm i` and then run `npm run run:directly` I get the following log output:

```
Collection name for OrganizationSchema: portaluserorgroles
Collection name for OrgRoleSchema: portaluserorgroles
Collection name for PortalUserSchema: portaluserorgroles
Collection name for PortalUserOrgRolesSchema: portaluserorgroles
Model name of selected model: PortalUserSchema
```

And as you can see, despite having set the modelOptions to each have their own collection names, they all get set to `portaluserorgroles`

Here is a screen of my collection names in my mongo browser (Robo3T):

<img width="259" alt="Robo_3T_-_1_3" src="https://user-images.githubusercontent.com/17632/67836486-f64a6b00-faa9-11e9-9cc1-350f9fdf8711.png">

**Comment by hasezoey** [comment]
added some logging, i noticed that all the schema-classes dont have an "ModelOptions" metadata, but "BaseSchema" has everything - i dont know why it is happening

**Comment by hasezoey** [comment]
Update: i think i know where the problem is, i never thought this would be the behavior of Reflect...

**Comment by duro** [comment]
@hasezoey glad to hear your on the hunt. You are clearly much more well versed in how Reflect works than I, otherwise I would keep trying to hunt with you. Glad my reproduction gave you something to go on.

**Comment by hasezoey** [comment]
Another Update: my thoughts were wrong, Reflect has no problem, the culprit is `Object.assign` and the ability to not "deep" copy

-> i hate JS for not having a native deep-copy

What i found is:
when using `Object.assing({}, Reflect.getMetadata())` it makes a clone of the top properties (like `schemaOptions, existingMongoose, existingConnection` ***BUT*** nested properties like `schemaOptions: { collection }` are still the same references, this is why it is problematic...

**Comment by duro** [comment]
@hasezoey might this be a case where you are forced to use something like lodash's `cloneDeep`?

**Comment by hasezoey** [comment]
i will look into it, but i never used lodash before - and i didnt want to require a whole library (i mean with other function than the clone), just for the "clone"/"merge"

**Comment by duro** [comment]
@hasezoey with lodash you can just include 1 function like so:

`yarn add lodash.clonedeep`

That said, I'm not exactly certain how it handles deeply nested structures which contain no-primitive values, but it might be worth a try

**Comment by duro** [comment]
@hasezoey since you are dealing with a pretty fixed set of keys, you could possibly try lodash `cloneDeepWith` and write a customizer which helps to restructure in a more safe way.

https://lodash.com/docs/4.17.15#cloneDeepWith

**Comment by hasezoey** [comment]
@duro do you think #101 does fix the issue?

**Comment by duro** [comment]
@hasezoey it very well looks like it could fix it. What's the best way for me to pull this in to my reproduction and test it? (this will have to wait till my morning, as it's 3am here, and I should have gone to bed hours ago 🤪)

Should I just fork that branch, do my own build, and pull in from github?

P.S. If you really don't want to pull in the entire lodash library, remember, you can import just single functions (eg. `yarn add lodash.clonedeepwith` and `yarn add lodash.mergewith`)

**Comment by hasezoey** [comment]
when your yarn works *with you* `yarn add https://github.com/typegoose/typegoose.git#r6/fixMerger`, when it works *against you*, clear your yarn cache and try again

**Comment by duro** [comment]
@hasezoey but I'll still have to build the typescript, no? Or is there a postinstall that will handle that?

**Comment by hasezoey** [comment]
there is a `prepare` script, which should compile it - because `postinstall` got deprecated, but already encountered where yarn dosnt want to execute it

**Comment by hasezoey** [comment]
just to add this here, for future readers:

> P.S. If you really don't want to pull in the entire lodash library, remember, you can import just single functions (eg. yarn add lodash.clonedeepwith and yarn add lodash.mergewith)

i dont use the special packages, because (at least for me) the `@types/lodash` didnt work with them (`lodash.mergewith` & `lodash.clonedeepwith`)

**Comment by duro** [comment]
@hasezoey many of the micro packages also have their own types packages. I use them all of the time. Can't speak with certainty that they functions you are using all have micro types, but I encourage you to check.

**Comment by hasezoey** [comment]
ok, i looked again and found (example) https://www.npmjs.com/package/@types/lodash.mergewith , but it seems like they still need `@types/lodash`...
