### ISSUE TITLE
Reason why "Converted Type to Mixed!" is a warning?

### ISSUE THREAD

**Issue by duro** [typegoose/typegoose#103]
We have a number of models which need to have properties typed to `Object` but on typegoose master this throws a warning "Converted Type to Mixed!". Is there a solid universal reason for that?

**Comment by hasezoey** [comment]
fixed in c10a04b6e93e1100398812513ad445107f927b92

otherwise #52 
& https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#allowmixed

**Comment by hasezoey** [comment]
fully fixed in 312c5c0b9bc285b8bbefc8abc9459887d86e01ba
-> closing this now, because "array" "Converted type to mixed!" is now handled by the same function
