### ISSUE TITLE
Clarification on arrays of Ref

### ISSUE THREAD

**Issue by chris-makaio** [typegoose/typegoose#104]
Dear all,

I've just started with typegoose and already love it. But what I don't get is referencing an array of documents. The docs are unclear about that (a lot of arrayProp stuff seems to be deprecated?) and I'm sure I'm just missing something here.

I have a schema to be stored in collection "contents":
```ts
@modelOptions({ schemaOptions: { collection: "contents" } })
export class ListContent extends ContentContainer {

    @prop({ ref: ListContentItem, refType: mongoose.Schema.Types.ObjectId })
    public items?: Ref<ListContentItem>[];

    constructor()
    {
        super(CONTENT_TYPE_LISTCONTENT);
    }
}
```

and this ListContent should reference multiple ListContentItems from collection listcontents.
This is the schema:
```ts

@modelOptions({ schemaOptions: { collection: "listcontents" } })
export class ListContentItem extends ContentContainer {

    @prop({ required: true })
    public title!: string;

    @prop()
    public position!: number;

    @prop({ default: CONTENT_TYPE_LISTCONTENTITEM })
    protected contentType!: string;
}
```

Then I try to create a new content(-container) for the items and add a single sub item:

> ```ts
>    const listContent = await listContentModel.create({
> 
>     } as ListContent);
>     const listContentItem = await listItemModel.create({
>         title: 'hallo'
>     } as ListContentItem);
> 
>     listContent.items = [listContentItem];
> 
>     await listContent.save();
> ```

The creates transform (correctly) to

`contents.insertOne({ contentType: 'ListContent', deleted: false, _id: ObjectId("5dbbeb9ee58a1b1103a59b81"), __v: 0 }, { session: null })`

and
`listcontents.insertOne({ contentType: 'ListContentItem', deleted: false, _id: ObjectId("5dbbeb9ee58a1b1103a59b82"), title: 'hallo2', __v: 0 }, { session: null })`

but the call to save() triggers

> ```
> ValidationError: ListContent validation failed: items: Cast to ObjectID failed for value "[ { contentType: 'ListContentItem',
>     deleted: false,
>     _id: 5dbbec6969e8d11137ac37d4,
>     title: 'hallo',
>     __v: 0 } ]" at path "items"
> ```

What am I doing wrong?

## Versions

- typegoose: 6.0.4
- mongoose: 5.7.7

**Comment by hasezoey** [comment]
> a lot of arrayProp stuff seems to be deprecated?

most get deprecated in 6.1.0, in favor of having less duplicate code (like `itemsRef` didnt behave anything different than `ref` and was just an alias for arrays)

---

> The docs are unclear about that

could you point me where the docs are unclear? - the docs are just basic docs, to even have a documentation, sorry for being unclear

---

> @prop({ ref: ListContentItem, refType: mongoose.Schema.Types.ObjectId })
>  public items?: Ref<ListContentItem>[];

when you have an array, always use `@arrayProp`, and for ref's that are with an normal ObjectId, you dont need to add `refType` (defaults to ObjectId)

-> Please report back if you have tried this

---

For your case to have multiple models in one collection, you should use discriminators

---

PS: i edited your code marks to be more clear (adding language to have highlighting)

**Comment by chris-makaio** [comment]
Thanks for the quick reply, @hasezoey 

So I changed only one line:
```
    **_@arrayProp_**({ ref: ListContentItem })
    public items?: Ref<ListContentItem>[];
```

_Note: you quoted me with only Ref[] instead of Ref<ListContentItem>[] - I tried it, but it's missing the type argument._

But it still fails with the same validation error. 

Regarding discriminators: I use them, but not in this case here - here two collections should be used. 

Regarding docs: sorry for not being clear here. I appreciate that there is documentation, but it actually isn't shown how to use an array property (including adding etc.)

**Comment by hasezoey** [comment]
Sorry for `Ref[]` it didnt copy over, i meant `Ref<ListContentItem>[];`

> I appreciate that there is documentation, but it actually isn't shown how to use an array property (including adding etc.)

because it is meant to be used like an normal array

> listContent.items = [mongoose.Types.ObjectId(listContentItem.id)];

this is not recommended, please try `listContent.items = [listContentItem._id];`

> And if I change ref in arrayProp to itemsRef, it works.. phew

and sorry about that - in 6.0.x `itemsRef` and `ref` have different behaviors, in 6.1.x, they can be used interchangeably (but recommended for 6.1.0+ is to use just `ref`)
