### ISSUE TITLE
"Bundle" subdoc references

### ISSUE THREAD

**Issue by chris-makaio** [typegoose/typegoose#107]
It's me again ;) I don't know if this is the right place to ask this, but I hope so.

Say, we have a simple "Mail" schema with sender, recipient, message
sender and recipient both ref to person schema.
When populating sender and recipient, two findOne queries are created instead of a single find-in query. 
On the other hand, querying multiple Mail docs and populating only sender, I can see only a single find-in query as expected (and I really love this!)

Is this intended behavior because mongoose or typegoose don't get that both attributes use the same ref collection?

**Comment by hasezoey** [comment]
this dosnt seem like an typegoose issue, try searching in mongoose / ask in mongoose repo

**Comment by chris-makaio** [comment]
thx!
