### ISSUE TITLE
Q: getModelForClass from string

### ISSUE THREAD

**Issue by nea** [typegoose/typegoose#109]
Hi there

Is there some way to get a model for a class by a string? Or is there another way to i.e. get the child references in a model from the model schema, class or something, so that I could iterate on references and execute e.g. automatic insertions etc.?

Thanks a lot in advance

**Comment by hasezoey** [comment]
> Or is there another way to i.e. get the child references in a model from the model schema, class or something,

i dont understand what you mean with that

> Is there some way to get a model for a class by a string?

there is currently not a way to get a model by string, because it would break the types, but as a workaround:
```ts
import { models } from "@typegoose/typegoose/lib/internal/data";

const yourModel = model.get('Model Name');
```
if you really want the model by string
