### ISSUE TITLE
Missing Tests for existingConnection & existingMongoose

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#111]
There are currently missing tests for:

- [ ] existingConnection
- [ ] existingMongoose

-> we are open for PR's

**Comment by TAYTS** [comment]
@hasezoey Hi, may I know is this issue still available? If yes, I would like to give it a try.

**Comment by hasezoey** [comment]
> may I know is this issue still available
as long as an issue is open here, then yes

@TAYTS

**Comment by TAYTS** [comment]
@hasezoey Hi sorry for the late start, may I ask for some context about the tests required?

`existingConnection`: Is this used to check whether if there is an existing MongoDB connection?
`existingMongoose`: Is this used to check version of the Mongoose installed which is to test the line 11 in `src/typegoose.ts`?

**Comment by hasezoey** [comment]
@TAYTS https://typegoose.github.io/typegoose/docs/api/decorators/model-options#options

https://github.com/typegoose/typegoose/blob/2199d9eb67ca0e7827f2cdaf2b0b8bb55f1e6a4c/src/typegoose.ts#L79-L82

**Comment by hasezoey** [comment]
tests added within 44643165e9890a042a8f3f10eadc46397c0c76bc
