### ISSUE TITLE
How to perform search on parent model

### ISSUE THREAD

**Issue by jakiwar** [typegoose/typegoose#115]
In this SO post https://stackoverflow.com/questions/19111800/is-it-possible-to-search-multiple-mongoose-models-at-once they define a People model, which has two extensions Employer and Employee.

Then they can search both employees and employers with People.find().

I have a typegoose base class and extended classes similarly to
```ts
export class AnimalInfo{
    @prop({ required: true, trim: true })
    name!: string
}

export class DogInfo extends AnimalInfo{
    @prop({ required: true, trim: true })
    preferredDogFod!: string
}

export class CatInfo extends AnimalInfo{
    @prop({ required: true, trim: true })
    napTime!: Date
}
```

I create instances of CatInfo and DogInfo using `getModelForClass(...)`

How can I search across all animals for all occurences of a name?

**Comment by hasezoey** [comment]
it seems like you want to use discriminators - these 3 models are stored in one collection, right?

**Comment by jakiwar** [comment]
Sorry for beeing late to reply.  My versions are (no problem to upgrade) "@typegoose/typegoose": "^6.0.4" and "mongoose": "^5.7.7",

I checked briefly here https://mongoosejs.com/docs/discriminators.html and most likely that is what I would like to do.

The models are stored in the same collection.

**Comment by hasezoey** [comment]
> I checked briefly here https://mongoosejs.com/docs/discriminators.html and most likely that is what I would like to do.
> 
> The models are stored in the same collection.

then i would recommend you do that - is this then closed?

**Comment by jakiwar** [comment]
I thought that the class that extended the base class automatically would call the discriminator function of mongoose "behind the scenes". Below is a try to implement it, but I got stuck at a typescript error. Maybe you could post a snippet on how to do it correctly?

The mongoose example on discriminators begin with 
```
var options = {discriminatorKey: 'kind'};

var eventSchema = new mongoose.Schema({time: Date}, options);
var Event = mongoose.model('Event', eventSchema);

// ClickedLinkEvent is a special type of Event that has
// a URL.
var ClickedLinkEvent = Event.discriminator('ClickedLink',
  new mongoose.Schema({url: String}, options));
```
which I interpret as I should instanciate the animal classes from earlier in the thread as follows:

```
var options = {discriminatorKey: 'kind'};
export const animalModel= getModelForClass(AnimalInfo);
export const catModel=  animalModel.discriminator("Cat", getModelForClass(CatInfo), options);
```
 but this gives me a typescript error.

**Comment by hasezoey** [comment]
> animalModel.discriminator

did you notice? in the mongoose example, the schema is used, but with typegoose you try to use the model to do it

[look in the documentation for more info](https://typegoose.github.io/typegoose/docs/functions/getDiscriminatorModelForClass/) (*i hope it helps*)

**Comment by jakiwar** [comment]
Yes that piece of documentation seems to be the answer to my question. For future googlers I can post a new snippet with the (hopefully) correct calls. If below is correct you can close the issue.

```
const AnimalModel= getModelForClass(AnimalInfo);
const CatModel= getDiscriminatorModelForClass(AnimalModel, CatInfo )
```

**Comment by hasezoey** [comment]
Yes this is the way, if you have problems, feel free to open a new issue
