### ISSUE TITLE
Link to typedoc gives 404

### ISSUE THREAD

**Issue by JeroenKops** [typegoose/typegoose#120]
Link to typedoc gives a 404 page:
https://typegoose.github.io/typegoose/typedoc

**Comment by hasezoey** [comment]
Known issue, cant fix:
- https://github.com/TypeStrong/typedoc/issues/1110
- https://github.com/TypeStrong/typedoc/pull/1129

i know the pr i linked is merged, but the version is not available on npm (latest there: 0.15.0

**Comment by lukeshiru** [comment]
Hi! When will the new version be published to npm? Just to know when to finally upgrade in my project using typedoc 😄

**Comment by hasezoey** [comment]
TypeDoc 0.15.1 released, which support typescript 3.7.2
