### ISSUE TITLE
Cannot find name 'Omit'. with the latest versions being thrown

### ISSUE THREAD

**Issue by michaelbats** [typegoose/typegoose#121]
```
node_modules/@typegoose/typegoose/lib/types.d.ts:15:56 - error TS2304: Cannot find name 'Omit'.

15 export declare type DocumentType<T> = T extends Base ? Omit<mongoose.Document, '_id'> & T : mongoose.Document & T;
```

Versions: 
```
    "mongoose": "^5.7.6",
    "@typegoose/typegoose": "^6.1.2"
```

Fails during build, I have reverted to 6.0.4 for now and all works fine.

**Comment by hasezoey** [comment]
typescript version?

**Comment by michaelbats** [comment]
```
    "typescript": "3.4.3"
```

**Comment by hasezoey** [comment]
The `Omit` utility type got added in typescript 3.5

**Comment by michaelbats** [comment]
Ahh, I remember now, I had this issue before with using Omit; 

I can't upgrade typescript for now as I'm using it with Angular and Nestjs which don't support 3.5 yet

**Comment by hasezoey** [comment]
as for nestjs: i got it to work without problems on typescript 3.7

as for angular: https://github.com/angular/angular-cli/issues/16071#issuecomment-551614783 (quick google search, never really used angular)
