### ISSUE TITLE
Old Enum Behaviour is used, please upgrade to the new one

### ISSUE THREAD

**Issue by mehmetnyarar** [typegoose/typegoose#124]
I suddenly started receiving:

> Old Enum Behaviour is used, please upgrade to the new one

warning, maybe 30 or more in a row.

**I didn't know where it was coming from**, so I asked in [StackOverflow](https://stackoverflow.com/questions/58836344/old-enum-behaviour-is-used-please-upgrade-to-the-new-one).

Based on the answer, although I do:

```ts
setGlobalOptions({
  globalOptions: {
    useNewEnum: true
  }
})

main()
```

warnings still appear.

My usage (as an example) is below. I always assign uppercase values to the enum keys/names and they are stored as uppercases in the database. So why is this happening?

```ts
export enum UserRole {
  Admin = 'ADMIN',
  Client = 'CLIENT',
  Provider = 'PROVIDER'
}

registerEnumType(UserRole, { name: 'UserRole' })

@ObjectType()
@modelOptions(getModelOptions('users'))
export class User {
  @Field(() => UserRole)
  @prop({ enum: UserRole, type: String, required: true })
  role: UserRole

  @Field(() => [UserRole])
  @arrayProp({ items: String, required: true, default: [] })
  roles: UserRole[]
}
```

Versions:

 "@typegoose/typegoose": "^6.1.2",
"mongoose": "^5.7.10",
"reflect-metadata": "^0.1.13",
"type-graphql": "^0.17.5"

**Comment by hasezoey** [comment]
old behaviour:
```ts
enum Some {
  Hello, // implicitly 0
  Hi, // implicitly 1
  Hi2, // implicitly 2
}
// would translate to
[ 'Hello', 'Hi', 'Hi2', 0, 1, 2 ]
```
and
```ts
enum Some {
    Cat = "CAT",
    Dog = "DOG",
}
// would translate to
[ 'CAT', 'DOG' ]
```

the new Enum behavior, only allows enums where all values have a string assigned, and then use that string

---

> warnings still appear.

are you sure you do it before any model imports? and only have **one** "app entry point"?

**Comment by mehmetnyarar** [comment]
@hasezoey just to be sure that

- I have one entry point
- and I imported it before any model imports

I did this (`index.ts`):

```ts
import 'reflect-metadata'

import { setGlobalOptions } from '@typegoose/typegoose'

import logger from './logger'
import { main } from './server' // this was the previous index.ts

setGlobalOptions({
  globalOptions: {
    useNewEnum: true
  }
})

main()
  .catch(error => logger.save({
    type: 'ERROR',
    source: '@index:main',
    error
  }))
```

> are you sure you do it before any model imports? and only have one "app entry point"?

So I'm pretty sure at this point

I use Typegoose along with TypeGraphQL. [Here](https://github.com/MichalLytek/type-graphql/blob/master/examples/typegoose/typegoose-middleware.ts) is the original example code and below is the latest Typegoose implementation (of mine). Could it be somehow related?

```ts
import { Document, Model } from 'mongoose'
import { MiddlewareFn } from 'type-graphql'

import { getClassForDocument } from '@typegoose/typegoose'

const convertDocument = (doc: Document) => {
  const convertedDocument = doc.toObject()
  const DocumentClass: any = getClassForDocument(doc)
  Object.setPrototypeOf(convertedDocument, DocumentClass.prototype)

  return convertedDocument
}

export const TypegooseMiddleware: MiddlewareFn = async (_, next) => {
  const result = await next()

  if (Array.isArray(result)) {
    return result.map(item => (item instanceof Model ? convertDocument(item) : item))
  }

  if (result instanceof Model) {
    return convertDocument(result)
  }

  return result
}
```

**Comment by hasezoey** [comment]
@mehmetnyarar does `import { main } from './server' // this was the previous index.ts` contain all the imports of the models?

**Comment by mehmetnyarar** [comment]
i import all the modules dynamically while building a GraphQL schema:

```ts
const main = async () => {
  let schema: GraphQLSchema | undefined

  try {
    schema = await buildSchema({
      resolvers: [path.join(__dirname, '/modules/**/resolvers.ts')],
      globalMiddlewares: [TypegooseMiddleware],
      scalarsMap: [{ type: ObjectID, scalar: ObjectIDScalar }],
      dateScalarMode: 'isoDate',
      authMode: 'null',
      validate: false
    })
  } catch (e) {
    //
  }
}
```

**Comment by hasezoey** [comment]
@mehmetnyarar is `buildSchema` the one from typegoose? (or graphql?)

**Comment by mehmetnyarar** [comment]
I discovered that I used a class (as a typing) from modules in `main.ts` which uses an enum type. maybe that's the problem...

**Comment by hasezoey** [comment]
@mehmetnyarar this shouldnt be a problem, because @Prop calls are executed only when `_buildSchema` is called (from like `buildSchema` or `getModelForClass` or `getDiscriminatorForClass`)

**Comment by mehmetnyarar** [comment]
regarding `buildSchema`, it's from `type-graphql`

> I discovered that I used a class (as a typing) from modules in main.ts which uses an enum type. maybe that's the problem...

If you mean this class, no, I don't call any of these functions. To be clear, it is:

```ts
@ObjectType()
export class Token {
  @Field()
  @prop({ required: true })
  value: string

  @Field()
  @prop({ required: true })
  expires: Date
}
```

But of course I do use `getModelForClass` for the entities.

I just used `any` everywhere just to be sure that I don't import anything from `modules`. Still getting warnings...

**Comment by hasezoey** [comment]
@mehmetnyarar where do you use `getModelForClass`?

**Comment by mehmetnyarar** [comment]
Adding `/* eslint-disable import/first */` at the top of the file and importing `main` later seems fixed it for now:

```ts
/* eslint-disable import/first */
import 'reflect-metadata'
import { setGlobalOptions } from '@typegoose/typegoose'

setGlobalOptions({
  globalOptions: {
    useNewEnum: true
  }
})

import { main } from './main'
import logger from './logger'

main()
  .catch(error => logger.save({
    type: 'ERROR',
    source: '@index:main',
    error
  }))
```

**Comment by mehmetnyarar** [comment]
> @mehmetnyarar where do you use `getModelForClass`?

I used a model class (UserModel) in authentication middleware to create cookies. I guess that was it :)

**Comment by ishan123456789** [comment]
Hi @hasezoey  how to handle the case when I'm running test case for some particular file I'm continuously getting the above error for my test cases I've just updated my typegoose version form @szokodiakos's repo to yours and I'm getting errors in my unit tests all in Jest. If you can please let me know if there's a quick fix for unit tests.

**Comment by hasezoey** [comment]
@ishan123456789 
https://typegoose.github.io/typegoose/guides/migrate-to-6/
https://typegoose.github.io/typegoose/docs/decorators/prop/#enum

otherwise, please open a new issue, or ask in our discord
