### ISSUE TITLE
Cast to ObjectId failed for value "{ active: true }" at path "user" for model "Rate""

### ISSUE THREAD

**Issue by amitnadhe** [typegoose/typegoose#126]
I have two entities as shown below

```ts
@ObjectType()
@modelOptions({ schemaOptions: { timestamps: true } })
export class Rate {

    @prop()
    @Field({ nullable: true })
    active?: boolean = true;

    @prop({ ref: 'User', required: false })
    @Field(() => User, { nullable: true })
    user?: Ref<User>;	
}

export const RateModel = getModelForClass(Rate);

@ObjectType()
@modelOptions({ schemaOptions: { timestamps: true } })
export class User {

    @prop()
    @Field({ nullable: true })
    active?: boolean = true;	
}

export const UserModel = getModelForClass(User);
```

Now when i am doing `RateModel.find({user:{active:true}})` i am getting `Cast to ObjectId failed for value "{ active: true }" at path "user" for model "Rate"`

## Versions

- typegoose: 6.1.2
- mongoose: 5.7.7

**Comment by hasezoey** [comment]
> Make sure you read [Mastering-Markdown](https://guides.github.com/features/mastering-markdown/)

---

Setting default like `active?: boolean = true;` is not supported, 1. it somehow transforms the object, as you can see, and 2. the constructor would need to be called, which it never is

**Comment by amitnadhe** [comment]
Thank you for your reply. This is not resolving issue.

**Comment by hasezoey** [comment]
@amitnadhe is it a different error after removing `= true`?

**Comment by amitnadhe** [comment]
No it is same error.

**Comment by hasezoey** [comment]
@amitnadhe sorry that i didnt notice this faster, but `RateModel.find({user:{active:true}})` is wrong, because you use `Ref` for `user` (property), you cant use values, you need to use the user's ObjectId that is where the cast fails

**Comment by amitnadhe** [comment]
It would be great if you can provide me some sample. The result i want is to fetch all Rate documents of which user is active.

**Comment by hasezoey** [comment]
@amitnadhe sorry, but i think i cant help you there, i think you should try aggregate? (im not sure for this case), so i would recommend aggregate for a pipeline, or searching all active users & searching for each of them the rate

**Comment by hasezoey** [comment]
i will close this, because the main issue is solved (https://github.com/typegoose/typegoose/issues/126#issuecomment-554719346)
