### ISSUE TITLE
Global schemaOptions not working

### ISSUE THREAD

**Issue by vkasraj** [typegoose/typegoose#128]
## Versions
- NodeJS: ^12.13.0
- Typegoose(NPM): ^6.1.2
- mongoose: ^5.7.11
- type-graphql: ^0.17.5

## What is the Problem?

`setGlobalOptions` doesn't merge global `schemaOptions` with every class's `schemaOptions`.
So when I set `timestamps: true` in `schemaOptions` on per model basis it works fine. But not with global `schemaOptions` as it doesn't generate `createdAt` and `updatedAt`.

I don't know if this is a bug or expected behaviour. As your [docs](https://typegoose.github.io/typegoose/docs/functions/setGlobalOptions/#schemaoptions) say it should be merged with every classes `schemaOptions`.

#### Entry Point
```ts
import "reflect-metadata";
import { setGlobalOptions } from "@typegoose/typegoose";

setGlobalOptions({
    schemaOptions: {
        timestamps: true,
    },
    globalOptions: {
        useNewEnum: true,
    },
});
```

#### User Schema

```ts
import { ObjectType, Field } from "type-graphql";
import { prop, getModelForClass } from "@typegoose/typegoose"

@ObjectType()
export class User {
    @Field()
    @prop({
        unique: true,
        required: true,
        trim: true,
        minlength: 3,
    })
    username: string;

    @Field()
    @prop({
        unique: true,
        required: true,
        trim: true,
    })
    email: string;
    @prop({
        required: true,
        trim: true,
    })
    password: string;
}

export const UserModel = getModelForClass(User);
```

## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
do you import the "User Schema" file before calling "setGlobalOptions"?

**Comment by vkasraj** [comment]
If I import the schema before calling `setGlobalOptions` then I get this warning `Old Enum Behaviour is used, please upgrade to the new one`.

**Comment by hasezoey** [comment]
i mean, `setGlobalOptions` ***must*** be called ***before*** any `buildSchema` / `_buildSchema` / `getModelForClass` is called to be applied

in this order:
```ts
import { setGlobalOptions } from "@typegoose/typegoose";
setGlobalOptions({ options });
import { model } from "./someModel";
```

PS: and currently `@modelOptions` must be called for globalOptions to be applied (i currently dont know a way to make it better, but i try)

**Comment by vkasraj** [comment]
Thanks man! 

The problem was that I was not using `@modelOptions` decorator. I was just using `getModelForClass` for the schema.

Just asking, `getModelForClass` can get the same behavior?

**Comment by hasezoey** [comment]
like i said, i didnt know of a better way, i will try to make it not need `@modelOptions`

**Comment by hasezoey** [comment]
i hope i didnt break anything with that commit....

**Comment by vkasraj** [comment]
So, if we define both globalOptions and modelOptions then it would be merged?

**Comment by hasezoey** [comment]
@vkasraj yes:
(with `@modelOptions`) if no modeloptions exists on target(class), then add globalOptions
if exists, skip (like when using inheritance and the parent class has them already defined)
(without `@modelOptions`) add globalOptions when `_buildSchema` gets called (not in `@prop`)

**Comment by huangapple** [comment]
SetGlobalOptions still does not work

    "@typegoose/typegoose": "^9.12.0",
    "mongoose": "^6.6.1"

**Comment by hasezoey** [comment]
@huangapple please open a new issue with the template and some code explaining what you are trying to do, because from what i can tell `setGlobalOptions` works correctly in the latest versions
