### ISSUE TITLE
.create typesafety

### ISSUE THREAD

**Issue by sakulstra** [typegoose/typegoose#129]
Disclaimer: not sure if this is a question or feature request

In the docs you wrote
> UserModel.create({ name: 'JohnDoe' } as User); 

Which lead to me writing this hundrets of times. Now I'm wondering: why is the explicit typecheck via `as sth` needed? As the model knows the schema couldn't it just automatically do this for me via some sort of generic?

Is there any good reason bout to do this in not aware of?

## Versions

- typegoose: latest

**Comment by hasezoey** [comment]
> Now I'm wondering: why is the explicit typecheck via as sth needed?

`@types/mongoose` on create: `(docs: any[])`, which means it accepts any value, and not using a type - and typegoose dosnt modify it, because the goal of typegoose is not to modify mongoose, only be a wrapper for schema / model (not functions)

**Comment by sakulstra** [comment]
wow, i really was certain that before we started using typegoose:
```
import mongoose, { Schema, Document, Model } from 'mongoose';

export interface ITest extends Document {
  foo: string;
}

const testSchema: Schema = new mongoose.Schema({
  foo: String,
});

const Test: Model<ITest> = mongoose.model<ITest>('Test', testSchema);

Test.create({ foo: 'bar' });
```

create would throw, but I double checked and you're right -> it doesn't due to:
> @types/mongoose on create: (docs: any[])

exactly like you said.
