### ISSUE TITLE
Allow to add multiple plugins with one decorator (plural version of @plugin)

### ISSUE THREAD

**Issue by nartc** [typegoose/typegoose#130]
## Describe what you need | want
A plural version of plugin decorator to add multiple plugins to a schema with 1 decorator

## Do you have already an idea for the implementation?
Accept a rest parameters and iterate through the plugins and add each plugin.

**Comment by hasezoey** [comment]
i dont think i will add this - but i'm open for PR's that add tests for it (without needing the actual implementation) (when possible keep it so that no other npm dependencies are needed)

**Comment by nartc** [comment]
@hasezoey I should be able to come up with something.

**Comment by hasezoey** [comment]
> But just curious, why did you say "I don't think I will add this"?

because you can already specify multiple plugins with multiple `@plugin`, and if you use that on all, you could add it [globally](https://mongoosejs.com/docs/plugins.html#global)

**Comment by nartc** [comment]
All good. Then I think this can close I suppose. Because I can make a `@plugins()` a custom decorator in my project. Just thought it'd be something nice to add to `typegoose`.

**Comment by nartc** [comment]
I will propose a PR with test cover sometimes soon though. If it's good then it's in. If not, all's good.
