### ISSUE TITLE
@prop({default: {}}) does not work correctly for nested documents

### ISSUE THREAD

**Issue by Manfredik** [typegoose/typegoose#131]
## @typegoose/typegoose": "^6.1.2"

When working with documents of strong structure, properties pointing to the default sub-document do not work correctly

## Code Example

```ts
@modelOptions({ schemaOptions: { _id: false } })
export class UserCampaignStage {
	@prop({ required: true, type: Number, default: 1 })
	stageId: number = 1;
	
	@arrayProp({ items: Number, innerOptions: {default: [] }})
	levels: number[] = [];
}

@modelOptions({ schemaOptions: { _id: false } })
export class UserCampaign {
	@prop({ default: 1, type: Number })
	current: number = 1;
	@arrayProp({items: UserCampaignStage, innerOptions: {default: () => [new UserCampaignStage()]}})
	stages: UserCampaignStage[] = [];
}

@modelOptions({ schemaOptions: { _id: false } })
export class UserState {
	@prop({
		type: UserCampaign, default: () => {
			return { current: 1, stages: [new UserCampaignStage()] };
		},
	})
	campaign: UserCampaign = new UserCampaign();
	
	@prop({ default: 1, type: Number })
	defaultLimit: number = 1;
}

@plugin(MongooseAutoIncrementID.plugin, { modelName: 'User', field: 'id' })
@plugin(findOneOrCreate)
@modelOptions({ schemaOptions: { collection: 'users' } })
export class User {
	@prop({ required: true, type: Number })
	id!: number;
	
	@prop()
	provider!: UserProvider;
	
	@prop({ default: () => new Date, type: Date })
	created!: Date;
	
	@prop()
	name!: string;
	
	@prop({ default: 0, type: Number })
	experience: number = 0;
	
	**@prop({type: UserState, default: () => new UserState() } )
	state!: UserState;**
}
```

I tried the spread options, won only cherries hook "pre save"
```ts
@pre<User>('save', async function (this: User & Document, next: (err?: Error) => void): Promise<any> {
	if (this.isNew) {
		this.$locals.isNew = true;
		this.state = {
			defaultLimit: 1,
			campaign: {
				current: 1,
				stages: [
					{
						stageId: 1, levels: []
					}
				]
			}
		}
	}
	next();
})
```

Maybe I 'm doing something wrong?

**Comment by hasezoey** [comment]
> innerOptions

any reason you need to use this?

---

> levels: number[] = [];

setting default this way will not work, because the class constructor will never be called

---

> @prop({ default: 0, type: Number })

for normal props that are not generic or an arrayProp / mapProp, you dont need to set the type this way

---

> default: () => new UserState()

will not work, because like stated in the documentation, the classes are only "wrappers" they get compiled to models (or schemas) and you cant use them directly

-> when you really need a default, try `default: {}` (this is untested, but should work?)

---

> state!: UserState;

just asking to confirm, do you want this really as embedded instead of a reference?

**Comment by Manfredik** [comment]
@prop({default: strongDefaultObject })
not work =(

**Comment by hasezoey** [comment]
because this issue didnt have any activity in the last month, it will be closed

**Comment by mohamedGamalAbuGalala** [comment]
If it's possible to put that 

> **the constructor is never called and typegoose is only a wrapper**

in the main readme, cuz I fall in the same bug for a couple of hours and searched for an open/closed issue but the issue name was not clear enough.

I even created a sample to report the same issue [here](https://codesandbox.io/s/vibrant-dust-8gbl0?file=/index.ts) but after I found this issue.
