### ISSUE TITLE
Add ability use capital letters in collection name

### ISSUE THREAD

**Issue by gr8den** [typegoose/typegoose#132]
## Describe what you need | want

Ability create/use collection with capital letters in name.
Now when I create model with option
`@modelOptions({options: {customName: 'MyCollection'}})`
Typegoose create collection with name "mycollection"

## Do you have already an idea for the implementation?

*no*

**Comment by gr8den** [comment]
Mongoose have this ability
```ts
import { model } from 'mongoose';
const MyCollection = model('MyCollection', MyCollectionSchema, 'MyCollection');
```

**Comment by hasezoey** [comment]
`{ options: { customName: "hi" } }` is to overwrite the Model-Name (default is the class name), use `{ schemaOptions: { collection: "YourCollection" } }`

- https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#customname
- https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#schemaoptions

PS: `.lowerCase` or `.upperCase` is not used in typegoose, so no names are transformed
