### ISSUE TITLE
Getting error: Old Enum Behaviour is used, please upgrade to the new on

### ISSUE THREAD

**Issue by ishan123456789** [typegoose/typegoose#134]
## Versions

- NodeJS: 10.16.3
- Typegoose(NPM): 6.1.5 
- Typegoose(GIT): commithash
- mongoose: 5.7.4
- mongodb: 3.2.7
- grahpql / type-graphql: 0.17.4 

## Code Example
I'm continuously getting error a large list of below
```
console.warn node_modules/@typegoose/typegoose/lib/prop.js:345
    Old Enum Behaviour is used, please upgrade to the new one

  console.warn node_modules/@typegoose/typegoose/lib/prop.js:345
    Old Enum Behaviour is used, please upgrade to the new one

  console.warn node_modules/@typegoose/typegoose/lib/prop.js:345
    Old Enum Behaviour is used, please upgrade to the new one

  console.warn node_modules/@typegoose/typegoose/lib/prop.js:345
    Old Enum Behaviour is used, please upgrade to the new one

  console.warn node_modules/@typegoose/typegoose/lib/prop.js:345
    Old Enum Behaviour is used, please upgrade to the new one

  console.warn node_modules/@typegoose/typegoose/lib/prop.js:345
    Old Enum Behaviour is used, please upgrade to the new on

```

## Do you know *why* it happenes?

I just upgraded from 5.7.2 to the 6.1.5

For development I'm running this snippet which removes the above logs but for my test cases I'm not able to fix the above logs.
I tried using this but no success:
```
import { setGlobalOptions } from "@typegoose/typegoose";

beforeEach(() => {
  // Clears the database and adds some testing data.
  // Jest will wait for this promise to resolve before running tests.
  setGlobalOptions({
    globalOptions: {
      useNewEnum: true,
    },
  });
});
```

**Comment by hasezoey** [comment]
> 5.7.2 to the 6.1.5

recommended is to first upgrade to 5.9.2

---

> mongoose: 5.7.4

you should upgrade to 5.7.7 or higher (https://github.com/typegoose/typegoose#requirements)

---

> beforeEach

try `beforeAll`

---

do you "compile" (buildSchema, getModelForClass, getDiscriminatorForClass) before setting global options? (like in the file where the class is defined / imported at the beginning of the file)

**Comment by ishan123456789** [comment]
Where should I place this beforeAll hook I've tried a couple of things but wasn't able to find anything with typescript can you please throw some light on that @hasezoey .

**Comment by hasezoey** [comment]
`beforeAll` on jest https://jestjs.io/docs/en/setup-teardown#one-time-setup
or
`before` in mocha https://mochajs.org/#hooks

or just at the beginning of the file (make sure you dont import any models first)

Note: you need to include the "before/beforeAll" in every suite, when it is not in a tree (like in this project)

-> im thinking about adding an environment variable for that

**Comment by ishan123456789** [comment]
But this one would be required in everyfile and I don't want to add the snippet in everyfile. I tried using setupFiles but got no success although the above piece of code runs before each file.

**Comment by hasezoey** [comment]
like i stated in https://github.com/typegoose/typegoose/issues/128#issuecomment-555117866 already, do you create a model before setting the globals?

like
```ts
// some class file
export class Something {}

export const SomethingModel = getClassForDocument(Something)

// test-file
import { SomethingModel, Something } from "someClassFile"

describe("some suite", () => {
  beforeAll(() => {
    setGlobalOptions({ globalOptions: { useNewEnum: true } })
  })

  it("should do something", () => {
    // usage
  }
}
```

when yes, it the model is "compiled" before even the "describe" statement

**Comment by fabioformosa** [comment]
I have the same warn 
```
console.warn node_modules/@typegoose/typegoose/lib/prop.js:135
      Old Enum Behaviour is used, please upgrade to the new one
```

typegoose 6.1.6
mongoose 5.7.13
mongodb 3.2.3

What should I upgrade? I haven't understood.

**Comment by hasezoey** [comment]
@fabioformosa you just need to set the global typegoose setting `useNewEnum` to true (because they are now differently handled

the option: https://typegoose.github.io/typegoose/docs/functions/setGlobalOptions/#usenewenum
explanation on why & what: https://typegoose.github.io/typegoose/docs/decorators/prop/#enum

**Comment by fabioformosa** [comment]
I wrote
```
setGlobalOptions({ globalOptions: { useNewEnum: true } });
```
in all `beforeAll` (jest) but that warning still appear. Why?

Moreover, it's rather uncomfortable must write `setGlobalOptions({ globalOptions: { useNewEnum: true } });` in all test files.

**Comment by hasezoey** [comment]
do you "compile" models in their files and import them? when yes, that is the most common problem - you need to set the "setGlobalOptions" before all "compiles"

**Comment by hasezoey** [comment]
Closed, because of the environment variables that i mentioned
