### ISSUE TITLE
Infer `required`

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#135]
## Describe what you need | want

It would be nice to infer if a property is required from its type:
- `prop?: string` -> not required
- `prop: string` or `prop!: string` -> required

Why should I also specify it in `@prop`?

## Do you have already an idea for the implementation?

*no*

**Comment by hasezoey** [comment]
not possible, if possible, please supply how / an prototype

**Comment by lcswillems** [comment]
How do you infer the model field type from the property type?

For example, how do you map "string" type to "String" type?

**Comment by hasezoey** [comment]
thanks to `design:type` and https://www.npmjs.com/package/reflect-metadata
-> that is why we need to have the type defined for arrays in the arguments too, because for an array it would result int `Array` (any)

**Comment by lcswillems** [comment]
Okay, thank you for your answer!
