### ISSUE TITLE
Getter `name` on a class breaks schema building

### ISSUE THREAD

**Issue by beaulac** [typegoose/typegoose#136]
##  Versions

- NodeJS: 12.13.0
- Typegoose(NPM): >=6.1.4 
- mongoose: 5.7.11
- mongodb: 4.0.4

## What is the Problem?

Having a virtual property (getter) called `name` on a model class breaks schema creation.

## Code Example

```typescript
class Foo {
  @prop()
  shouldAppearInPaths: string;

  public get name() {
    return '';
  }
}

const fooSchema = buildSchema(Foo);

console.log(fooSchema.path('shouldAppearInPaths'));
```
In 6.1.3, log outputs:
>     SchemaString {/*...*/}
In 6.1.4, log outputs `undefined`
## Do you know *why* it happens?

[This change ](https://github.com/typegoose/typegoose/commit/626c643af77a23615bf930aa69821b3c6e784040#diff-5dd6f32f81c5cb845f932b1ed7efabd7R84) in `_buildPropMetadata`:

It now passes in the decorator target instead of the constructor, which exposes getters. A getter called `name` returning a truthy value will make `getName` use it instead of the constructor's name.

**Comment by hasezoey** [comment]
ok, thanks - didnt thought about that, but wouldnt it just affect statics?
