### ISSUE TITLE
Import ObjectId from Typegoose?

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#138]
Is it possible to import ObjectId type from Typegoose? If not, it would be convenient to be able to import it.

Currently, I need to do:

```
import mongoose from 'mongoose';

mongoose.Schema.Types.ObjectId
```

I would like to do:

```
import {ObjectId} from '@typegoose/typegoose';
```

**Comment by hasezoey** [comment]
`import { mongoose } from "@typegoose/typegoose`
