### ISSUE TITLE
Why ref should be a string?

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#139]
In the old typegoose, ref didn't have to be a string. I don't understand why it should be the case now?

If I use:

```
@prop({ref: MyClass})
```

can't you transform MyClass with 'MyClass'?

The issue with giving a string is that it is bug-prone when class refactoring.

**Comment by hasezoey** [comment]
Nothing changed 

---

please always fill the template (at least the versions)

**Comment by lcswillems** [comment]
[Old documentation](https://github.com/szokodiakos/typegoose) says Typegoose is not taking a string as ref.

**Comment by hasezoey** [comment]
> Old documentation says Typegoose is not taking a string as ref.

it is not explicitly stated at the ***old*** documentation, but in the examples (way at the top), you can see that references are used as a string, so it was valid back then

---

[*the new documentation*](https://typegoose.github.io/typegoose/guides/advanced/reference-other-classes/)

**Comment by lcswillems** [comment]
It is written:

> ref: By adding the ref option with another Typegoose **class** as value

And all the examples take a class.

My question: is why it now takes a string? It is a regression, i.e. the new behavior is worse than the previous one.

**Comment by hasezoey** [comment]
> My question: is why it now takes a string? It is a regression, i.e. the new behavior is worse than the previous one.

it was always `string | Class` (pseudo), it was just not documented so
like:
- `Class` can be used, ***if*** it is ***not*** circular ***and*** the `Class` is already defined
- `string` can be used anytime, or in the cases where `Class` cannot be used

**Comment by lcswillems** [comment]
Okay, I see. Thank you!

But I think documentation should also be updated here: https://typegoose.github.io/typegoose/docs/decorators/prop/#ref

Because this is the page I looked for.

**Comment by hasezoey** [comment]
it should be better now, is this sufficient?

**Comment by lcswillems** [comment]
Yes, much better!
