### ISSUE TITLE
(ts 3.7.2) TS2304: Cannot find name 'Omit'.

### ISSUE THREAD

**Issue by wxs77577** [typegoose/typegoose#140]
```bash
$ nest start admin

ERROR in C:/work/code/yizhi/nest-server/node_modules/@typegoose/typegoose/lib/types.d.ts
ERROR in C:/work/code/yizhi/nest-server/node_modules/@typegoose/typegoose/lib/types.d.ts(15,56):
TS2304: Cannot find name 'Omit'.
```

![image](https://user-images.githubusercontent.com/1990059/69843711-bd1d3a80-12a3-11ea-968f-3c283a656fb6.png)

**Comment by hasezoey** [comment]
are you sure you have the version of typescript installed? `Omit` got added in ~3.5 - please try to clean your node_modules & reinstall (and/or check your global modules)

**Comment by wxs77577** [comment]
Thanks, I reinstalled my global `typescript` and `@nestjs/cli`, it works.
