### ISSUE TITLE
How to make `id` prop fallback to `_id`?

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#142]
I would like to add a `id` attr to my model that fallbacks to `_id`. I don't want to allias `_id` to `id`. I still want to be able to access `_id`. How could I do?

I tried something like:

```
class Article {
    @prop({fallback: '_id'})
    id: string
}
```

**Comment by hasezoey** [comment]
i dont understand your question, please explain what you would need that for

**Comment by lcswillems** [comment]
I want `article.id` to give me the ID. But also `article._id`

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/docs/virtuals/#get--set ?

**Comment by lcswillems** [comment]
That may do it! Thanks for your help :)
