### ISSUE TITLE
Give `_id` the type ObjectID by default

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#143]
## Describe what you need | want

I have a model:

```
class Article {}
```

Currently, the field `article._id` has type `any`. Could it be possible to have a type `ObjectID` if no type is specified for it?

**Comment by hasezoey** [comment]
when you want to give `_id` a specific type, use the default class `Base`, otherwise you need to overwrite it yourself (it is "hard")

**Comment by lcswillems** [comment]
Okay, thank you!
