### ISSUE TITLE
Ref's Type should automatically be inferred 

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#144]
## Describe what you need | want

Let's say I have two models:

```ts
class Article {
    @prop({ ref: 'Author' })
    authorId: Ref<Author>;
}

class Author {
    @prop()
    _id: string
}
```

then `article.authorId` gives a type of `Ref<Author, ObjectID>` instead of `Ref<Author, string>`.

**Comment by hasezoey** [comment]
Typescript has complex types - and i dont fully understand them, i already tried:
```ts
type Ref<R extends {_id?: RefType}, T extends RefType = R['_id']> = R | T;
```
but this would require that all classes define `_id` - which is redundant if only `ObjectId` is used

already tried
```ts
type Ref<R extends {_id?: RefType} | {}, T extends RefType = R['_id']> = R | T;
```
but typescript will complain that `R['_id']` does not exists on a type **and** i didnt find a way to set a default / fallback

**Comment by lcswillems** [comment]
What about:

```
type Ref<R extends {_id?: RefType} | {_id: ObjectID}, T extends RefType = R['_id']> = R | T;
```

?

**Comment by hasezoey** [comment]
it would still require that every class would have an `_id` field

**Comment by lcswillems** [comment]
Okay, but `{_id?: RefType}` means that `_id` is optional, isn't it?

**Comment by hasezoey** [comment]
yes, but typescript dosnt let me (i dont know why)

**Comment by JakobStaudinger** [comment]
Have you tried something along the lines of this already?
```typescript
type Ref<R, T extends RefType = '_id' extends keyof R ? R['_id'] : ObjectId> = R | T
```

**Comment by hasezoey** [comment]
@JakobStaudinger because `R['_id']` is `any`, it is not assignable to `RefType`

**Comment by JakobStaudinger** [comment]
Well then how about `type Ref<R extends { _id?: RefType }, T extends RefType = '_id' extends keyof R ? R['_id'] : ObjectId> = R | T;`?
That should fix it, right?

**Comment by hasezoey** [comment]
@JakobStaudinger this would work, when every class would have an definition of `_id`

**Comment by JakobStaudinger** [comment]
i don't think every class needs to have a definition of `_id` since `_id` is optional in the interface that `R` extends.

![image](https://user-images.githubusercontent.com/15521973/73475258-49290c80-4390-11ea-901f-cdf3ffde0992.png)

![image](https://user-images.githubusercontent.com/15521973/73475273-52b27480-4390-11ea-80db-5122dfcebeff.png)

For me it seems to work just fine.

**Comment by hasezoey** [comment]
@JakobStaudinger then try to clone this repo, go to `src/types.ts`, locate `export Ref<` and replace it with you own, and then try to run `npm run test` (after `npm i -D` to install all dependencies)

**Comment by JakobStaudinger** [comment]
Ok, after some testing I found this to work.
```typescript
export type Ref<R, T extends RefType = R extends { _id?: RefType } ? R['_id'] : mongoose.Types.ObjectId> = R | T;
```

![image](https://user-images.githubusercontent.com/15521973/73482993-03277500-439f-11ea-883a-3e759e26abc3.png)

**Comment by hasezoey** [comment]
@JakobStaudinger tested it, and see no issues - Thanks for doing this, but i will probably not include this until the next minor release - just to be sure to not break anything in the patch version

**Comment by JakobStaudinger** [comment]
Alright, no problem!

I have no need for this feature anyway, just thought it would be fun to implement :)

**Comment by hasezoey** [comment]
i would appreciate real-world testing, so i will ping @lcswillems (issue author) and @RyannGalea (uses typegoose for a long time) but anyone would be good too
to help it would only need to go into `node_modules/@typegoose/typegoose/lib/types.d.ts` search for `export declare type Ref` and replace that line with 
```ts
export type Ref<R, T extends RefType = R extends { _id?: RefType } ? R['_id'] : mongoose.Types.ObjectId> = R | T;
```
and report back if there are any errors popping up or some any types that are wrong

**Comment by lcswillems** [comment]
It works for me! I remove all the occurrences of `refType` and replaced `Ref<T, S>` by `Ref<T>` and it gives the good type to IDs.

Thank you @JakobStaudinger for your contribution! This is a really neat addition that prevents lot of bugs.

**Comment by hasezoey** [comment]
> This is a really neat addition that prevents lot of bugs.

and duplication :+1:

**Comment by RyannGalea** [comment]
Replaced, all seems good at the moment on my end. Didn't create any errors.
```
// export declare type Ref<R, T extends RefType = mongoose.Types.ObjectId> = R | T;
export type Ref<R, T extends RefType = R extends { _id?: RefType } ? R['_id'] : mongoose.Types.ObjectId> = R | T;
```

**Comment by hasezoey** [comment]
@RyannGalea thanks for testing

**Comment by hasezoey** [comment]
the new type will be in 6.3, because it *could* break *someones* code (together with updated dependencies) - it will be released in the next day, when nothing major comes up

**Comment by lcswillems** [comment]
Why could it break someones code?

**Comment by hasezoey** [comment]
@lcswillems when types change, they *could* break some code, so i made it a minor version

**Comment by lcswillems** [comment]
My question is: why, in this case, it could break some code?

**Comment by hasezoey** [comment]
@lcswillems i dont know, but it could happen - nobody will ever know

**Comment by hasezoey** [comment]
@JakobStaudinger it is shipped in typegoose 6.3 now, everything works fine, only when activating `strict` (tsconfig), it fails because `undefined` is not assignable to `ObjectId`

```ts
export type Ref<R, T extends RefType = R extends { 
  _id?: RefType; // when removing the "?" here, there error vanishes, but dosnt work anymore
} ? R['_id'] : mongoose.Types.ObjectId> = R | T;
```

(Note: `undefined` cannot be taken into `RefType`

**Comment by hasezoey** [comment]
additon: it seems like removing the `?` dosnt break anything, and solves the error in strict mode

**Comment by JakobStaudinger** [comment]
removing the `?` does not allow inferring the type if the property is optional.
e.g.
```typescript
class A {
  public _id?: string
}

class B {
  public ref: Ref<A>; // ref is of type A | ObjectId
}
```

other than that everything should work the same.

**Comment by hasezoey** [comment]
@JakobStaudinger in the typegoose tests, i didnt see any types being wrong, and when extending `Base` the `_id` is not with an `?`, so it *should* just work, thanks for replying back 

-> i will close this again because i think it is solved again (with removing the `?`)
