### ISSUE TITLE
How to change the reference type?

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#145]
I have these models:

```
class Article {
    @prop({ ref: 'Author' })
    authorId: Ref<Author>;
}

class Author {
    @prop()
    _id: string
}
```

I want the `authorId` reference to be a type string. Currently, it doesn't automatically infer it (see https://github.com/typegoose/typegoose/issues/144), so I tried to it manually with `authorId: Ref<Author, string>`.

However, `authorId` is still defined as an ObjectID in the schema. Because of this, Mongoose gives me errors everytime I do find operations saying the id I give is not a valid ObjectID (but this is normal, my IDs are strings).

**Comment by hasezoey** [comment]
> However, authorId is still defined as an ObjectID in the schema.

you would need to use the default class `Base` to overwrite it as a type, otherwise it should work

(like i mentioned in https://github.com/typegoose/typegoose/issues/143#issuecomment-560337029)

**Comment by lcswillems** [comment]
Okay, thanks! I will try! I didn't know it would do both :)

I close it if it works

**Comment by lcswillems** [comment]
From the docs, I don't understand how I can get the `Base` class. What should I import? The same for `Timestamps`

**Comment by hasezoey** [comment]
`import { defaultClasses } from "@typegoose/typegoose"` and `extends defaultClasses.Base`
or
`import { Base } from "@typegoose/typegooe/lib/defaultClasses"` and `extends Base`

Note: the default classes dont extends `Base`

**Comment by lcswillems** [comment]
Ok, thank you! I think this import should be specified somewhere in the doc.

So I tried what you suggest me but I still have problems. I tried two things, but none of them works.

### Trial 1

```
class Article {
    @prop({ ref: 'Author' })
    authorId: Ref<Author>;
}

class Author extends Base<string> {
    @prop()
    _id: string
}
```

but I still get the same error: `authorId` is defined as `ObjectID` (I tried with `Ref<Author, string>` too).

### Trial 2

```
class Article {
    @prop({ ref: 'Author' })
    authorId: Ref<Author>;
}

class Author extends Base<mongoose.Schema.Types.String> {
    @prop()
    _id: mongoose.Schema.Types.String
}
```

But now, I get this error: `Type 'String' does not satisfy the constraint 'RefType'. Type 'String' is not assignable to type 'string'.`

**Note:** There is a typo in the doc [here](https://typegoose.github.io/typegoose/guides/defaultClasses/#base): it should `mongoose.Schema.Types.String` instead of `mongoose.Schema.Type.String`.

**Comment by hasezoey** [comment]
> @prop()
>   _id: string

like i said in many other issues already: *dont use `@prop` on `_id`*
and when you use `Base`, you should not define it, because you are already setting it with `Base<string>`

**Comment by lcswillems** [comment]
But, I would like to set a default value for my _id. So, how could I do?

To give more context, I want my _id to be a shortid string. I am using [shortid](https://www.npmjs.com/package/shortid) package. With mongoose, I will usually put this in my schema:

```
_id: {
  'type': String,
  'default': shortid.generate
},
```

but I don't see how to do it with Typegoose.

I think what I am trying to do is something a lot of people do too.

**Comment by hasezoey** [comment]
`@prop` cant be used on `_id` because at the time typegoose tries to write an property `_id`, mongoose would throw because it already exists, so i would recommend you use a hook to set a default

-> can i ask why a shortid instead of an objectid?

**Comment by lcswillems** [comment]
Because it is a short id. It is very convenient for URLs. From the doc of shortid:

> ShortId creates amazingly short non-sequential url-friendly unique ids. Perfect for url shorteners, MongoDB and Redis ids, and any other id users might see.

**Comment by hasezoey** [comment]
> This is problematic to not be able to define @prop for _id...

sorry, but i dont know a way to avoid the mongoose "already defined" error...

**Comment by hasezoey** [comment]
PS: one way to avoid it (like i mostly do, when i work with mongodb), is to let `_id` as-is, and add a field like (for this case) `@prop() short: string`

**Comment by lcswillems** [comment]
> sorry, but i dont know a way to avoid the mongoose "already defined" error...

What is this error?

Moreover, why should I inherit from Base to change the `_id` type? Can't it be inferred from the code?

The current issue is very problematic because it means that with Typegoose, people can do less than with Mongoose (which is strange because Typegoose should just add types for Mongoose). This limitation should be written in big somewhere. I bet I could migrate my codebase to Typegoose, but I can't.

**Comment by lcswillems** [comment]
> PS: one way to avoid it (like i mostly do, when i work with mongodb), is to let `_id` as-is, and add a field like (for this case) `@prop() short: string` (i know this is just a quick-fix, but it should work...)

No, it would not work in my case because, as far as I know, a reference always points to the `_id` of the object.

So if I do:

```
Article.find({id: shortId, authorId: shortId})
```

it will not work because `authorId` will have to be an ObjectId, which I don't have because I only short ids.

**Comment by hasezoey** [comment]
> Moreover, why should I inherit from Base to change the _id type?

`Base<string>`, Base has a generic, with that you set `_id`

> Can't it be inferred from the code?

#144 

> What is this error?

i dont know it exactly, and i cant recall which issue it was with the error shown

> it will not work because authorId will have to be an ObjectId, which I don't have because I only short ids.

right, forgot about that one

**Comment by lcswillems** [comment]
Thank you again for all your quick answers!

I would like to find a way to solve this issue because it is a big problem for me.

I don't understand this:

> Base<T>, Base has a generic, with that you set _id (where T is the generic)

I have just seen the source of code of `defaultClasses.ts` and `Base` is defined as:

```
export abstract class Base<T_ID extends RefType = Types.ObjectId> {
  public _id: T_ID;
  // tslint:disable-next-line:variable-name
  public __v: number;
  // tslint:disable-next-line:variable-name
  public __t: undefined | string | number;
}
```

I think I miss what this code is doing special. Anyway, is there any workaround I could use in my case to be able to set a custom `_id` type and, at the same time, a default value?

**Comment by hasezoey** [comment]
> Anyway, is there any workaround I could use in my case to be able to set a custom _id type and, at the same time, a default value?

sorry, i dont know any, only setting _id to string and using a hook to define a default value

**Comment by lcswillems** [comment]
What do you mean by hook? A `set` method? Something like:

```
class extends Base<string> {
    set _id() {
        return shortid.generate();
    }
}
```

Moreover, could you tell me what this code is doing?

```
export abstract class Base<T_ID extends RefType = Types.ObjectId> {
  public _id: T_ID;
}
```

I don't understand why `class extends Base<string> {}` will make the `id` a string and not:

```
class {
   _id: string;
}
```

**Comment by lcswillems** [comment]
What if I do:

```
export abstract class Base<T_ID extends RefType = Types.ObjectId> {
  @prop({default: shortid.generate})
  public _id: T_ID;
}
```
?

**Comment by hasezoey** [comment]
> Moreover, could you tell me what this code is doing?

> I don't understand why class extends Base<string> {} will make the id a string and not:

https://www.typescriptlang.org/docs/handbook/generics.html

> What do you mean by hook? A set method? Something like:

https://typegoose.github.io/typegoose/docs/decorators/hooks/

> What if I do:

because without `@prop` it is essentially just a type, it would be the same as if you would define it in your class, only that you would affect all classes that extend Base

**Comment by hasezoey** [comment]
Sorry for that, until #147 i forgot about [`refType`](https://typegoose.github.io/typegoose/docs/decorators/prop/#reftype)

**Comment by lcswillems** [comment]
Okay, great! I missed it too! I close it if it works

**Comment by lcswillems** [comment]
It works with `refType`
