### ISSUE TITLE
Add a `refType` attribute to @prop()

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#147]
## Describe what you need | want

With a `refType` attribute, it could solve this issue: https://github.com/typegoose/typegoose/issues/145

The solution would be:

```
class Author {
    @prop({ default: shortid.generate })
    _id: string;
}

class Article {
    @prop({ref: 'Author', refType: string})
    authorId: Ref<Author, string>
}
```

**Comment by hasezoey** [comment]
already existing https://typegoose.github.io/typegoose/docs/decorators/prop/#reftype

**Comment by lcswillems** [comment]
Okay, great!!!
