### ISSUE TITLE
Custom query methods

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#148]
I can't find in the documentation how to define custom query methods that had been introduced in Mongoose 4.5:

https://thecodebarbarian.com/mongoose-custom-query-methods

**Comment by hasezoey** [comment]
Proposal:
class-decorator named `@query` / `@queryFunction`

where options are: `@query(func: (...args: any) => any)`

how to get it working after `.find()`: i dont know

**Comment by hasezoey** [comment]
update: i will probably add this as an class decorator (as per the last comment), but still have no clue about handling the types for this

**Comment by hasezoey** [comment]
234963ffe462f36822467494b39c61434bc75362 adds the class decorator `queryMethod`, and #236 is the tracking issue for the types
