### ISSUE TITLE
Type create, find... query parameter

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#150]
## Describe what you need | want

For example, if this is my model:

```ts
class Article {
    @prop({required: true})
    title: string;

    @prop();
    description: string;
}
```

it would be nice to have a TypeScript error if I do `Article.create()` (because I would have forgetten the required title) or if I do `Article.find({title2: 'my title'})` because `title2` is not a known attribute.

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/guides/faq/#why-does-new-model-dont-have-types

**Comment by lcswillems** [comment]
So, the model I get is the Mongoose model. Why do I have TypeScript errors if I do `article.title2`?

**Comment by hasezoey** [comment]
> Why do I have TypeScript errors

what errors?

PS: `new Model({} as Class)` you can always use the `as Class`, but if you have functions / getters without setters, typescript will complain...

**Comment by lcswillems** [comment]
Currently, with Typegoose, if I do `article.title2`, TypeScript detects that `title2` is not a valid prop and alerts.

What I don't understand is: how could I get this alert if the model I have is a Mongoose model? When I was using Mongoose models without TypeScript I was not getting these alerts.

**Comment by hasezoey** [comment]
could you give me the error typescript gives you (and with a repro example?)

**Comment by lcswillems** [comment]
```
import { prop, getModelForClass } from "@typegoose/typegoose";

class Article {
  @prop()
  title: string;
}

const ArticleModel = getModelForClass(Article);

const article = new ArticleModel();
article.title2;
```

Typescript error:

```
Property 'title2' does not exist on type 'Document & Article'. Did you mean 'title'?
```

Do you see what I mean?

**Comment by lcswillems** [comment]
I digged into the source code: https://github.com/typegoose/typegoose/blob/f291bd992bfaff39aa0e23d8715cb8a25d147b90/src/types.ts

Typegoose defines the type of the model, so Typegoose should be able to also type find, create, etc... So Typegoose is not working as intended, and can be improved.

This issue should be reopened.

**Comment by hasezoey** [comment]
@lcswillems 

- find https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L1886
- findOne https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L1897
- create https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L2990-L2993

all have something like `input: any`, and typegoose dosnt modify any mongoose functions

**Comment by lcswillems** [comment]
Yes, sure. They have a type `any` because `Mongoose` knows nothing about the types of the schema properties. But Typegoose knows them! (because it is its purpose...)

Typegoose already types the model properties (as I shew you) so it is completely able to also type its methods.

Moreover, it is not about modifying mongoose functions, but typing them! which is completely different.

This is completely feasible, so as I said, it should be reopened.

**Comment by hasezoey** [comment]
> Moreover, it is not about modifying mongoose functions, but typing them! which is completely different.

it is still the same, typegoose does ***NOT*** modify any mongoose functions (including its types), typegoose is just a wrapper around schema & model creation, not about behavior outside of that

**Comment by lcswillems** [comment]
> typegoose is just a wrapper around schema & model creation, not about behavior outside of that

Why?

**Comment by hasezoey** [comment]
@lcswillems 
original intend: https://typegoose.github.io/typegoose/guides/motivation/

and when you want to make typegoose "re-type" mongoose, just change `@types/mongoose`
or you could just make something like https://github.com/hasezoey/typegoose-v2
