### ISSUE TITLE
"Mixed" warning cannot be suppressed if property is defined with "@arrayProp"

### ISSUE THREAD

**Issue by telnet2** [typegoose/typegoose#151]
## Versions 

- NodeJS: 12.13.0
- Typegoose(NPM): 6.1.6 
- Typegoose(GIT): commithash
- mongoose: 5.7.13
- mongodb: 3.3.5

## What is the Problem?

Cannot suppress warning message 
`Implicitly setting "Mixed" is not allowed! (DrivableArea, areas)`

## Code Example

```ts
import 'reflect-metadata';
import {
  modelOptions,
  prop,
  arrayProp,
  index,
  getModelForClass,
  LogLevels,
} from '@typegoose/typegoose';
import {setGlobalOptions, Severity, setLogLevel} from '@typegoose/typegoose';
import {mongoose, Schema} from 'mongoose';

setLogLevel(LogLevels.INFO);
setGlobalOptions({options: {allowMixed: Severity.ALLOW}});

class ArrayWithMixed {
  @arrayProp({items: Object}) public arr: any[];
}

export const ArrayWithMixedModel = getModelForClass(ArrayWithMixed);

if (require.main === module) {
  async function main() {
    await mongoose.connect(process.env.DB_URL);
    console.log(await ArrayWithMixedModel.find({}));
  }
}
```

## package.json File
```json
{
  "name": "tgoose",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@typegoose/typegoose": "^6.1.6",
    "mongoose": "^5.7.13"
  },
  "devDependencies": {
    "@types/chai": "^4.2.6",
    "@types/jest": "^24.0.23",
    "@types/node": "^12.12.14"
  }
}
```

## Output
```
/r/t/src ❯❯❯ ts-node ./index.ts
"setGlobalOptions" got called with { options: { allowMixed: 0 } }
Assigning global Schema Options to "ArrayWithMixed"
Converting "Object" to mongoose Type
Implicitly setting "Mixed" is not allowed! (ArrayWithMixed, arr)
The Type "Mixed" does not have an OptionsConstructor
Class "ArrayWithMixed" already existed in the constructors Map
/r/t/src ❯❯❯
```

## Do you know *why* it happenes?

In `src/internal/utils.ts:386`, 

```ts
  const modelOptions = Reflect.getMetadata(DecoratorKeys.ModelOptions, target) ?? {};
```
should be like below?

```ts
  const modelOptions = Reflect.getMetadata(DecoratorKeys.ModelOptions, target.constructor) ?? {};
```

**Comment by hasezoey** [comment]
> Implicitly setting "Mixed" is not allowed! (DrivableArea, areas)

i think you provided a wrong model-class, because with what you have given, i couldnt reproduce it (no warning, different reason that im looking into)

**Comment by telnet2** [comment]
@hasezoey  Thanks for quick reply!

I included the full source code for your test and its output.

**Comment by hasezoey** [comment]
> The warning happens even if I set the logLevel to WARN.

that is the purpose, to WARN instead of erroring out (and exiting the app)

---

changed the title to reflect the current progress on what the problem is

**Comment by hasezoey** [comment]
b9660618fd30e7fb8ae381de9c178d2902d3b2f3 should have fixed it, could you test it?

npm `npm i -s github:typegoose/typegoose`

(yarn is known to not execute the `prepare` script, which makes installing from github difficult)

**Comment by telnet2** [comment]
Yes, it works! =)

Thank you!

**Comment by hasezoey** [comment]
version 6.1.7 released with this fix
