### ISSUE TITLE
warnMixed does not get trigger with ": any"

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#152]
## Versions

- NodeJS: 12.13.1
- Typegoose(NPM): 6.1.6
- mongoose: 5.7.13
- mongodb: 4.2-bionic (Docker)

## What is the Problem?

`warnMixed` does not get triggered by something like `: any`

## Code Example

```ts
// NodeJS: 12.13.1
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, setGlobalOptions, Severity } from "@typegoose/typegoose"; // @typegoose/typegoose@6.1.6
import * as mongoose from "mongoose"; // mongoose@5.7.13

setGlobalOptions({ options: { allowMixed: Severity.WARN } });

class SomeClass {
    @prop()
    public data?: any;
}
const SomeModel = getModelForClass(SomeClass);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

    await mongoose.disconnect();
})();
```

## Do you know *why* it happenes?

`: any` compiled to `Object` which `utils.isPrimitive(Type) === true` and there is no check against `Type.name === "Object"` - which results in no warning

**Comment by haritonstefan** [comment]
Hi @hasezoey 
I don't seem to find in the docs what's the issue with .Mixed, and what does the warning mean, something not working correctly?

**Comment by hasezoey** [comment]
@haritonstefan `Mixed` is mongoose's `any`, which has no validation, and something like `Object` will result in `Mixed` or something like
```ts
public someProp: {
  prop1: any;
}
```
will result in `someProp: Object` which will result in `Mixed`, so typegoose has an warning if `Mixed` is used, because its probably not what should be there, and if it should be so, then it can be disabled (but most cases you dont want to have `Mixed`)

**Comment by haritonstefan** [comment]
@hasezoey Thank you for the explanation.
