### ISSUE TITLE
Validation in nested models

### ISSUE THREAD

**Issue by dogabudak** [typegoose/typegoose#153]
- typegoose: 5.9.1
- mongoose: 5.7.11

So i have a specific question regarding a typegoose model with nested subdocuments;

Imagine that i have a user model which consists of multiple typed sub documents for example WorkModel and AddressModel 

Each time i save a document to the user database i call @pre save hook of the UserModel, but i also would like to trigger the WorkModels pre save hook since i want to keep Work specific checks there in order to keep the code cleaner.  I made a dummy example below;

```javascript 
@pre('save', UserModel._UserValidation)
export class UserModel extends Typegoose implements User {
 @prop({ required: true}) work: WorkModel;
 @prop({ required: true}) address: AddressModel;
}

public static _UserValidation() {
      console.log('I am triggered')
 }


@pre('save', WorkModel._WorkValidation)
export class WorkModel extends Typegoose implements Work {
  @prop({ required: false }) someProperty?: any;

  public static _WorkValidation() {
    console.log('I am not triggered');
    next();
  }
}
`

**Comment by hasezoey** [comment]
typegoose below 6.0 is not supported anymore, please try upgrading and report back

**Comment by hasezoey** [comment]
because this issue didnt have any activity in the last month, it will be closed
