### ISSUE TITLE
The Typegoose Class is deprecated ?

### ISSUE THREAD

**Issue by c0ncentus** [typegoose/typegoose#154]
(node:15344) DeprecationWarning: The Typegoose Class is deprecated, please try to remove it

I use Typegoose like this, just test...
```Typescript
import { Typegoose, prop } from '@typegoose/typegoose';
export class exemplegoose extends Typegoose {

    @prop()
    sheeps: String;

    @prop()
    wolves: Number;

}
const exemplegoose = getModelForClass(exemplegoose);

```
And later, i bind exemplegoose to a route create ... 

## Versions
- @types/mongoose: ^5.5.32
- mongoose: ^5.8.0
- typegoose: ^5.9.1

## Env
- npm: 6.13.0
- node: 12.13.1

Why node advice me to drop typegoose use ? 🙄 its scare me 😓 
```
mongoose.connect(appSettings.Run.local.url.mongodb, { useNewUrlParser: true, useUnifiedTopology: true, dbName:'Feanaro'})
  .then(() => console.log('💾 Service base de donnée 📸💾...'))
  .catch(((err: any) => { console.log(err); }));
```

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/guides/migrate-to-6/#getmodelforclass-setmodelforclass-buildschema

the `Typegoose` class got deprecated, because it is just unnecessary - just remove `extends Typegoose`  then it should vanish & work

PS: are you sure you are on 5.9.1? because this message only appears on 6.0+

**Comment by c0ncentus** [comment]
its sure. copy paste ... so sure 100%

![package](https://user-images.githubusercontent.com/25374826/70560542-154c1a80-1b89-11ea-841b-01ad7c268d81.jpg)

**Comment by hasezoey** [comment]
i should note that you use the old `typegoose`-npm package, use `@typegoose/typegoose` for 6.0, and anything <6.0 is not supported anymore - but this message was not in 5.x

**Comment by hasezoey** [comment]
i will close this because it is for a version that is not supported anymore
