### ISSUE TITLE
Model in static function

### ISSUE THREAD

**Issue by Christilut** [typegoose/typegoose#159]
## What to include in your Questions
I have static functions like so
```ts

class Library {
  async markInvalidated(this: DocumentType<Library>): Promise<Date> {
    const now = new Date()

    await LibraryModel.updateOne(
      {
        _id: this._id
      },
      {
        $set: {
          invalidatedAt: now
        }
      }
    )

    return now
  }
}

export const LibraryModel = getModelForClass(Library)
```

But TypeScript complains that LibraryModel is used before it is defined.

I can't move `LibraryModel` because it needs the class.

How should I resolve this?

Also it seems the same thing happens in the hooks, but I suppose I can move them below the LibraryModel, although I'd prefer to keep them before model declaration.

## Versions

- typegoose: 6.1.7
- mongoose: 5.8.0

**Comment by hasezoey** [comment]
yes this is known, and i dont know how to fix it - this is thanks to JS's exectution order

**Comment by Christilut** [comment]
Alright thanks, I'll ignore it for now

**Comment by hasezoey** [comment]
sorry, i thought about this again, but if you use a static method in 6.x you need to use the `static` keyword, otherwise it is NOT a static method

and when you use a static method, you need to set `this` to:
`this: ReturnModelType<typeof Library>`
so you can use `await this.updateOne`

---

and just for completion i add a way for instance methods:
```ts
public test(this: DocumentType<Library>) { // because in the current context "this" is the current document
    const model = getModelWithString<Library>(this.modelName); // you can get the model by name in typegoose, you could do this with native mongoose too, but this method uses typegoose's model-map
    // and this function you *need* the <>, because the class cannot be inferred for typeings 
    // an alternative method is:
    const model = this.constructor as ReturnModelType<typeof Library>;
}
```

**Comment by Christilut** [comment]
Thanks, static method works as you described. I coped the wrong function in the example.

But the instance method gives me this error again 
```
Type 'Library' does not satisfy the constraint 'AnyParamConstructor<any>'.
  Type 'Library' provides no match for the signature 'new (...args: any): any'
```

on this method
```ts
  async markInvalidated(this: DocumentType<Library>): Promise<Date> {
    const now = new Date()

    const model = getModelWithString<Library>(this.modelName)

    await model.updateOne(
      {
        _id: this._id
      },
      {
        $set: {
          invalidatedAt: now
        }
      }
    )

    return now
  }
```

**Comment by hasezoey** [comment]
sorry, i dont know what is wrong, here a working example:

```ts
class Library {
    public static markInvalidated(this: ReturnModelType<typeof Library>) {
        console.log(this);
    }

    public test(this: DocumentType<Library>) {
        const model = getModelWithString(this.modelName);
        console.log(model);
    }
}
const LibraryModel = getModelForClass(Library);
```

**Comment by Christilut** [comment]
Yeah but now model is `any`

**Comment by hasezoey** [comment]
sorry, i made this quick, here the fixed version:
`const model = getModelWithString<typeof Library>(this.modelName);`

**Comment by Christilut** [comment]
Thanks!

It's a bit confusing though, sometimes you need to use `<Library>` and sometimes with `typeof`. I don't really understand the complex TypeScript stuff so well, so these things are kind of beyond me. Would be cool if the Typegoose API can be simpler, if that's possible at all.

**Comment by hasezoey** [comment]
> I don't really understand the complex TypeScript stuff so well

me too

---

sorry, i always try to infer everything to not use `<>`, but when needed like in `DocumentType` the type just need the values (i think), and in something like `ReturnModelType` it needs he constructor

but i dont really know when and where to use it, i try to keep `typeof` usage as low as possible, but it cannot be avoided always

**Comment by dandv** [comment]
As of v7, I didn't have to use `DocumentType<...>`, and the code below worked, without any TypeScript errors (but then again, I also [don't get TypeScript autocomplete...](https://github.com/typegoose/typegoose/pull/245#issuecomment-623023353)):

```ts
export class Foo extends defaultClasses.TimeStamps {
  @prop({ default: nanoid })
  _id: string;

  @prop()
  time: Date;

  async ensureSave(this: Foo) {
    let result;
    while (!result)
      try {
        result = await this.save();
      } catch (e) {
        // If another error occurred than the id already existing, re-throw
        if (e.code !== 11000)
          throw e;
        this._id = nanoid();
      }
    return result;
  }
}
```

**Comment by hasezoey** [comment]
@dandv with the code you used (`this: Foo`) you should get an error like `function save dosnt exists on class Foo` and you probably dont return an class/model, but an document, right?
