### ISSUE TITLE
Help wanted for adding Guides & Documentation

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#16]
Anyone who wants to write guides can write one and Pull-Request it

Guidelines:
- the files must be markdown (.md)
- place them in `github-page/_guides`
- if they are "advanced behavior" put them in `github-page/_guides/advanced`
- if it is documentation put it into `github-page/_docs` and the folder most appropriate for it

jekyll got added in e37001a2a40a9a6a8bfae74608c02248b8614b20, help is here wanted too to make it better, its currently just bare-bones

PS: when someone wants to do an icon for typegoose, it would be appreciated :)

**Comment by hasezoey** [comment]
If someone finds missing documentation, please open a new issue

**Comment by captaincaius** [comment]
I'd be happy to help - do you have any particular focus areas you'd like to address first?

Personally, although it's minor, I think maybe a little semantics will help first - like what do we call the class that we send to getModelForClass (model configuration class?)?  What do we call the model that comes back (typed model)?  What about the schema configuration POJO?  Etc.

**Comment by hasezoey** [comment]
@captaincaius i currently target on undocumented things (which i add documentation when i find one), otherwise the docs are currently meant for basic understanding & common problems and to just have them, they need further improvement, because the docs i made are not good

> model configuration class?

i still dont really know what you are referencing with that

>  like what do we call the class that we send to getModelForClass (model configuration class?)? What do we call the model that comes back (typed model)? What about the schema configuration POJO? Etc.

i take models on an example that is logical (in most of the documentation i used the `Kitten`/`Cat` classes to show what is possible and being logical)

**Comment by hasezoey** [comment]
Currently missing Documentation / documentation that could need "major" improvements:

- Documentation of "How to use Plugins" is completly missing ( https://github.com/szokodiakos/typegoose/issues/56, https://typegoose.github.io/typegoose/docs/decorators/plugins/ )
- Documentation about some extra types are missing
- Documentation for Custom Schema Types is completly missing
- Documentation for hooks needs improvements ( https://typegoose.github.io/typegoose/docs/decorators/hooks/ )
- Documentation for `Ref`(type) could need some examples / advanced documentation ( https://typegoose.github.io/typegoose/docs/types/ref/ )
- the FAQ could need more F.A.Q.'s

<sub>this comment will get updated as more comes up / goes in</sub>

**Comment by captaincaius** [comment]
@hasezoey in playing with it more, I think I've got a couple more gotchas that could/should be added.

In reality, I'm not sure if what I'm about to mention belongs in typegoose's docs or mongoose's, because they're things that should be avoided if using just mongoose in typescript.

For example, any mongoose methods that mutate should be strictly avoided - for example, Schema.prototype.add() or Schema.prototype.remove()

**Comment by hasezoey** [comment]
> For example, any mongoose methods that mutate should be strictly avoided - for example, Schema.prototype.add() or Schema.prototype.remove()

such discussion would be better for the discord, otherwise, typegoose aims to simplify schemas & models, otherwise not modify mongoose, so sorry, this will not be done *(when you really want this, look at typegoose-v2, my side project, i do not mean to finish it right now, its just for testing & learning purposes)*

**Comment by captaincaius** [comment]
Ah I didn't realize there was a discord :)
Thanks

**Comment by hasezoey** [comment]
thanks to #68, all the documentation is now removed from the README and transfered to github-page
