### ISSUE TITLE
@index() decorator creates collection when it shouldn't

### ISSUE THREAD

**Issue by andreialecu** [typegoose/typegoose#161]
## Versions

Typegoose 6.1.7
Mongoose 5.8.1

## What is the Problem?

I'm using typegoose with type-graphql, nestjs-typegoose and nestjs.

When a model is defined with the `@index()` decorator it seems that the collection is automatically being created on the database, even though it looks like the default mongoose behavior is to not create a collection, as per:

https://mongoosejs.com/docs/guide.html#autoCreate

I'm not sure what's making it create the collection, but removing any `@index()` decorators stops this from happening.

`mongoose.get('autoCreate')` is `undefined`, and I have checked if any of the other packages ( set it to true but I couldn't find anything

Alternatively, being able to set `autoCreate` on the `@modelOptions({schemaOptions: {autoCreate: false}})` might also be helpful. But it is not available on the type. Seems like an oversight.

## Code Example

```ts
@index({ sortWeight: -1 })
export class Document {
   ...
}
```

## Do you know *why* it happens?

*no*

**Comment by andreialecu** [comment]
My use case for this is that I need to use different collection names at runtime, so I've set up a base model type with a fake collection name, and I'm overriding it at runtime with this code:

```
@index({ sortWeight: -1 })
@modelOptions({ schemaOptions: { collection: 'documents_notused' } })
export class Document {
   ...
}
```

```typescript
  private generateModel<T>(
    connection: mongoose.Connection,
    model: mongoose.Model<DocumentType<T>>,
    name: string,
  ): mongoose.Model<DocumentType<T>> {
    return connection.model(name, model.schema, name) as mongoose.Model<
      DocumentType<T>
    >;
  }

private getNamedModel(groupId: string) {
    const model = this.generateModel(
      this.connection,
      this.documentModel,
      `documents_${groupId}`,
    );

    return model;
  }
```

This lets me use collections such as `documents_abc123` at runtime instead. But it's also creating the `documents_notused` collection.

**Comment by andreialecu** [comment]
I think this happens because typegoose calls `schema.index()` rather than defining them in the schema itself, and letting mongoose create it based on that.

Ref: https://github.com/typegoose/typegoose/blob/f291bd992bfaff39aa0e23d8715cb8a25d147b90/src/internal/schema.ts#L92

**Comment by hasezoey** [comment]
and what about `mongoose.get('autoIndex')`?

> rather than defining them in the schema itself, and letting mongoose create it based on that.

it will not be changed, because modifying the schema itself instead of using a function would need to be changed on "every" mongoose update

PS: you are running mongoose 5.8, which is currently not officially supported by typegoose (im working on it in `r6/v6.2`) - so, does this happen in 5.7.x too?

**Comment by andreialecu** [comment]
Actually I'm on Mongoose 5.7.13. My bad.

Regarding the `schema.index()` call, I don't *think* it should result in the collection being created if `autoCreate` is false according to the mongoose documentation, since it is still just a schema change and not a db operation. 

It might be a mongoose bug instead. Though I haven't confirmed it with vanilla mongoose yet.

`mongoose.get('autoIndex')` is also undefined. however I think due to injection with NestJS there's a different instance of mongoose being used instead of the static one. I did look through the code for `nestjs-typegoose` and couldn't find anything related to `autoCreate` there though. So I assume the default would stand.

**Comment by andreialecu** [comment]
> Edit: i have never seen that it creates an index without calling an explicit ensureIndex / syncIndex / any "write" function that creates an collection

That's the weird part, I can see the collection appearing in the database while launching my app without any operations being done on the collection at all, with just the `@index()` decorator attached. 

Adding any new class, putting the `@intex()` decorator on it, then adding it to nestjs module imports via `TypegooseModule.forFeature([SomeTestClass])` immediately makes the collection appear once the app is started.

**Comment by hasezoey** [comment]
@andreialecu so you are using `nest-typegoose`, next time please specify it in the original issue (with the version) - because this seems to only happen with it
-> could you give the version you are using?

and could you give where you connect (like `forRoot` and `forFeature`) and and example model?

**Comment by andreialecu** [comment]
I did specify it in the first sentence of the original post. However nestjs-typegoose is a very simple wrapper so I'm not sure if it could introduce this behavior.

I'll try to set up a repro tomorrow.

**Comment by hasezoey** [comment]
Could you try mongoose 5.7.7 (the version typegoose requires at least) and 5.7.14?

**Comment by hasezoey** [comment]
Because this issue didn't have any activity in the last month, it will be closed

and because this seems like it is not directly an typegoose issue
