### ISSUE TITLE
mongoose autopopulate is incomplete 

### ISSUE THREAD

**Issue by techaks** [typegoose/typegoose#164]
have you read the docs, 

> https://plugins.mongoosejs.io/plugins/autopopulate

autopopulate must of type `any`

**Comment by hasezoey** [comment]
please expand your issue description, currently i cant understand what the problem is

**Comment by techaks** [comment]
Actually populate can take *object* also.. But you have defined as *boolean*
only

**Comment by hasezoey** [comment]
@techaks i still dont understand your issue, could you give an example code / reproduction code?

**Comment by techaks** [comment]
```
  @prop({
    ref: Language,
    autopopulate: { match: { status: 'ENABLED' } },
  })
  language?: Ref<Language>;
```
this must be worked .

According to Documentation of  `[mongoose-autopopulate](https://plugins.mongoosejs.io/plugins/autopopulate)`  

var bandSchema = new Schema({
  name: String,
  lead: { type: ObjectId, ref: 'people', autopopulate: { select: 'name' } }
});
bandSchema.plugin(autopopulate);

```
var bandSchema = new Schema({
  name: String,
  lead: { type: ObjectId, ref: 'people', autopopulate: { select: 'name' } }
});
bandSchema.plugin(autopopulate);
```


these all exmaples not working with typegoose because the type of `autopopulate` is `true`

**Comment by hasezoey** [comment]
@techaks would 5a5fd31291ee3b7bd239330f00920ff117490706 fix the issue?

**Comment by techaks** [comment]
@hasezoey  yup it will. Thanks
