### ISSUE TITLE
One-to-one lookup with localField/foreignField

### ISSUE THREAD

**Issue by Asgarv** [typegoose/typegoose#167]
I'm unable to get any documents to match using the localField and foreignField options.

I have two models, **Key** and **Team**.

In this example, the **teamId** field contains the ObjectID of the team's _id field. However no team field is returned in the result.
```ts
// This doesn't work:
export class Key {
  @prop({ ref: 'Team' })
  teamId: Ref<Team>;

  @prop({ ref: 'Team', localField: 'teamId', foreignField: '_id', justOne: true })
  team: Ref<Team>;
}
```

In this example, the **team** field contains the ObjectID of the team's _id field. The matched team object is returned in the result. I would however like to have separate fields, **teamId** (field in document) and **team** (populated) like in the above example.
```ts
export class Key {
  // This works:
  @prop({ ref: 'Team' })
  team: Ref<Team>;

  // This doesn't work:
  // @prop({ ref: 'Team', localField: 'team', foreignField: '_id', justOne: true })
  // team: Ref<Team>;
}
```

Does the Team model also have to reference the Key?

## Versions

- typegoose: 6.1.8
- mongoose: 5.8.1

**Comment by hasezoey** [comment]
because `team` has `localField` / `foreignField` it is a virtual, so it does not store any ID

do you call `.populate` after "finding"?

**Comment by Asgarv** [comment]
Yes, I do `KeyModel.find().populate('team').exec();`

I know, the second example is a bit weird. I edited the `team` field manually in the database to have the correct id. That's why `@prop({ ref: 'Team' })` works.

But shouldn't the first example work though, as it stores the id in the teamId field?

**Comment by hasezoey** [comment]
@Asgarv i dont see a problem with your code, did you just use "console.log(foundDoc)"? when yes, you might be tricked because mongoose dosnt show virtuals by default, and `team` is a virtual

used code:
```ts
// NodeJS: 12.14.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, modelOptions, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@6.1.8
import * as mongoose from "mongoose"; // mongoose@5.7.14

class Team {
    @prop()
    public something?: string;
}
const TeamModel = getModelForClass(Team);

@modelOptions({ schemaOptions: { toJSON: { virtuals: true }, toObject: { virtuals: true } } })
class Key {
    @prop({ ref: "Team" })
    public teamId?: Ref<Team>;

    @prop({ ref: "Team", localField: "teamId", foreignField: "_id", justOne: true })
    public team?: Ref<Team>;
}
const KeyModel = getModelForClass(Key);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify167", useCreateIndex: true, useUnifiedTopology: true });

    const team = await TeamModel.create({ something: "hi" });
    const key = await KeyModel.create({ teamId: team });

    const found = await KeyModel.find({}).populate("team").exec();

    console.log("found", found);

    await mongoose.disconnect();
})();
```

**Comment by Asgarv** [comment]
> 
> you might be tricked because mongoose dosnt show virtuals by default, and `team` is a virtual
> 

🤦‍♂ You are right! Thank you for your help!

This could maybe be added to the [Virtual Populate](https://typegoose.github.io/typegoose/docs/virtuals/#virtual-populate) documentation. What do you think? I could add some information there myself this weekend.

**Comment by hasezoey** [comment]
i close this because the question is solved
