### ISSUE TITLE
Getting error Invalid schema configuration: `MD` is not a valid type at path `updatedAt`

### ISSUE THREAD

**Issue by ishan123456789** [typegoose/typegoose#168]
## Versions

- NodeJS: 0.0.0
- Typegoose(NPM): 6.1.8 
- mongoose: 5.7.7
- mongodb: 3.3.6
- jest: 24.9.0,

## What is the Problem?

Getting error:
```
TypeError: Invalid schema configuration: `MD` is not a valid type at path `updatedAt`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.

      at Schema.Object.<anonymous>.Schema.interpretAsType (node_modules/mongoose/lib/schema.js:901:11)
      at Schema.Object.<anonymous>.Schema.path (node_modules/mongoose/lib/schema.js:602:27)
      at Schema.add (node_modules/mongoose/lib/schema.js:442:12)
      at Schema.Object.<anonymous>.Schema.setupTimestamp (node_modules/mongoose/lib/schema.js:1094:8)
      at new Schema (node_modules/mongoose/lib/schema.js:138:8)
      at Object._buildSchema (node_modules/@typegoose/typegoose/src/internal/schema.ts:56:11)
      at buildSchema (node_modules/@typegoose/typegoose/src/typegoose.ts:170:9)
      at Object.getModelForClass (node_modules/@typegoose/typegoose/src/typegoose.ts:105:58)
```

## Code Example

```ts

```
## Do you know *when* it happenes?
This error is thrown when I'm trying to run my jest test else it runs fine.

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
please give an code example

**Comment by ishan123456789** [comment]
@hasezoey can you please have a look at https://github.com/ishan123456789/jest-test-failing-example I've pushed some of my code there

**Comment by hasezoey** [comment]
> https://github.com/ishan123456789/jest-test-failing-example/blob/master/src/modules/orders-refactored/order.additional.interface.ts#L132-L133
> https://github.com/ishan123456789/jest-test-failing-example/blob/master/src/modules/orders-refactored/order.additional.interface.ts#L183-L184
> https://github.com/ishan123456789/jest-test-failing-example/blob/master/src/modules/orders-refactored/orders.interface.ts#L46-L47

you should use `@arrayProp`

---

```ts
logger.warn( // Cannot find name 'logger'.
   "Warning: order && order.deliveryTime not available during scheduleOrderIsLateCheck:",
    order,
);
```

---

otherwise, the only problem i see in your jest tests (and only there) is because you try to mock typegoose

**Comment by ishan123456789** [comment]
Thanks a ton dude you're the man! A ton of love and a merry christmas. I would have spent days in figuring out the issue. You're right it's because of mocking interface. Any suggestion on upgrading my concentration on minor things like this?

**Comment by hasezoey** [comment]
> Any suggestion on upgrading my concentration on minor things like this?

sorry, i dont know what you mean with that

---

it seems fixed, so i will close this issue

**Comment by ishan123456789** [comment]
Sorry @hasezoey I'm still having the same error could this error be due to some package versioning issue? I tried changing it to `arrayProp` but still I'm getting the same error. Can you please have a look again.

**Comment by hasezoey** [comment]
@ishan123456789 i know how to use jest, and when i will use it i will use the watchAll script i added (but not pushed) to automaticly re-run if changes happen

**Comment by ishan123456789** [comment]
Any suggestion on what the error could be I've fixed to arrayProp and pushed but still getting the same error.

**Comment by hasezoey** [comment]
> I've fixed to arrayProp and pushed

that were just sidenotes from me, when you would have stayed at `prop` you would have got a different schema than you would want, but "nothing actually to do with the error"

and no i couldnt look into it *yet*, but will and report back

**Comment by ishan123456789** [comment]
Thanks a lot for your effort

**Comment by hasezoey** [comment]
@ishan123456789 when i remove (comment out) `timestamps: true, strict: false`, i get different errors:

```
  ● Order Helper › Checks create

    TypeError: mockOrderModel.mockClear is not a function

      16 |     let orderService: OrderService;
      17 |     beforeEach(() => {
    > 18 |         mockOrderModel.mockClear();
         |                        ^
      19 |         orderService = new OrderService();
      20 |         advanceTo(new Date(2020, 5, 27, 12, 30, 30)); // reset to date time.
      21 |     });

      at Object.<anonymous> (src/modules/orders-refactored/tests/orders.service.test.ts:18:24)

  ● Order Helper › Checks create

    Cannot spyOn on a primitive value; undefined given

      23 |         mockOrderModel.create = jest.fn(() => exampleOrder) as any;
      24 |         const spy = jest
    > 25 |             .spyOn(orderService, "updateOrderAndIncident")
         |              ^
      26 |             .mockImplementation(() => Promise.resolve(exampleOrder) as any);
      27 | 
      28 |         await orderService.createOrder(exampleOrder);

      at ModuleMockerClass.spyOn (node_modules/jest-mock/build/index.js:832:13)
      at Object.<anonymous> (src/modules/orders-refactored/tests/orders.service.test.ts:25:14)

```

Note: i personally never used any mocking

**Comment by hasezoey** [comment]
Update: when i comment out the call to `advanceTo`, then the `MD at updateAt` vanishes - i dont know what `jest-date-mock` does

**Comment by ishan123456789** [comment]
It sets the current time like for `Date.now()` or `moment()` to a specific time.

**Comment by hasezoey** [comment]
at `node_modules/jest-date-mock/lib/mockDate.js` `MD is used, it probably comes from there, and mongoose expects an Date not an MD

**Comment by ishan123456789** [comment]
Do you know of any alternate to the above library which I can use? To update the current time to some other so that I can write tests with dates defined?

**Comment by hasezoey** [comment]
> Do you know of any alternate to the above library which I can use? To update the current time to some other so that I can write tests with dates defined?

no i dont - why not use normal dates?

**Comment by ishan123456789** [comment]
I have Date.now() at some places so to know what it was I have to use the above so that I come to know what it was then match both in the unit test.

**Comment by hasezoey** [comment]
> new Date(2020, 5, 27, 12, 30, 30));

when you just want a static date, why not just mock **just** `.now`? (like `Date.now = () => new Date('some time string')`?

**Comment by ishan123456789** [comment]
Thanks a lot @hasezoey for your time. I used mockdate module as I was using moment so didn't wanted to mock moment.

**Comment by HenokG** [comment]
> at `node_modules/jest-date-mock/lib/mockDate.js` `MD` is used, it probably comes from there, and mongoose expects an Date not an MD

wow thx for this, spent the whole day debugging, importing `jest-date-mock` after my custom package was the solution for me, as you said my custom package(with mongoose) was expecting vanilla `Date` object
