### ISSUE TITLE
Set more than one field in my schema as unique

### ISSUE THREAD

**Issue by AbderrazzakB** [typegoose/typegoose#171]
## Versions

- NodeJS: 13.2.0
- Typegoose(NPM): 6.1.8
- Typegoose(GIT): commithash
- mongoose: 5.8.1
- mongodb:4.0.13
- grahpql / type-graphql: 14.0.2 / 0.17.6

## What is the Problem?

I have more than one field in my schema to be unique, but only the last one in the schema has this constraint and sometimes no one gets the constraint and I can insert duplicated keys with no error.

## Code Example

```ts
        @Field()
	@Length(1, 50)
	@prop({ trim: true, unique: true })
	userName: string;

	@Field()
	@prop({ trim: true, unique: true })
	@Length(1, 50)
	identity: string;
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
did you already try the `@index` class-decorator? 

-> these options are passed to mongoose

**Comment by RyannGalea** [comment]
is this for your @ObjectType or @InputType using type-graphl ?

**Comment by AbderrazzakB** [comment]
> did you already try the `@index` class-decorator?
> 
> -> these options are passed to mongoose
Ok now it works, thank you.
So it's a bug or what? because I found in the documentation that I can pass the unique option to the Field decorator but it only works for one field!

**Comment by hasezoey** [comment]
@AbderrazzakB i dont know what is happening, but these options are passed to mongoose - but i will still investigate it

**Comment by hasezoey** [comment]
@AbderrazzakB i just tested it, i see no issues ...

code:

```ts
// NodeJS: 12.14.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@6.2.0
import * as mongoose from "mongoose"; // mongoose@5.8.3

class SomeSchema {
    @prop({ required: true })
    public nonunique!: string;

    @prop({ required: true, unique: true })
    public unique1!: string;

    @prop({ required: true, unique: true })
    public unique2!: string;
}
const SomeModel = getModelForClass(SomeSchema);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify171", useCreateIndex: true, useUnifiedTopology: true });

    const user1 = await SomeModel.create({ nonunique: "Hello1", unique1: "Hello2", unique2: "Hello3" } as SomeSchema);
    console.log(user1);

    const user2 = await SomeModel.create({ nonunique: "Hello1", unique1: "Hello2", unique2: "Hello3" } as SomeSchema);
    console.log(user2);

    await mongoose.disconnect();
})();
```

-> did you clear your indexes before chaning to unique | did you run `model.syncIndexes`? this might happen if you use something like nodemon and the collection was already created

**Comment by hasezoey** [comment]
@AbderrazzakB please respond in the next ~7 days, otherwise the issue will be closed

**Comment by AbderrazzakB** [comment]
@hasezoey I'm not sure what was the problem now it's work as I expected to, thank you.

**Comment by WangShuXian6** [comment]
model.syncIndexes is work for me!
