### ISSUE TITLE
Error importing 'prop' in node v12 ES modules

### ISSUE THREAD

**Issue by avaly** [typegoose/typegoose#172]
## Versions

- NodeJS: 12.14.0
- Typegoose(NPM): 6.2.1
- mongoose: 5.8.5
- mongodb: 3.4.1

## What is the Problem?

When trying to import `prop` from `@typegoose/typegoose` under node v12 with ES modules enabled and with Babel output, it throws an error.

This only happens when compiling the TS sources with ES modules syntax output.

## Code Example

Minimal test case from: https://gist.github.com/avaly/6c1a44a3ef4afc49d7206edcd323443d

```
$ node -v
v12.14.0

$ tsc

$ node --experimental-modules ./ts/User.js 
import { getModelForClass, modelOptions, prop } from '@typegoose/typegoose';
                                         ^^^^
SyntaxError: The requested module '@typegoose/typegoose' does not provide an export named 'prop'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:91:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:106:20)
    at async Loader.import (internal/modules/esm/loader.js:132:24)
```

## Do you know *why* it happenes?

Maybe.

The output of `tsc` generates a CommonJS syntax when importing and exporting `prop` from `./prop`:

See: https://unpkg.com/@typegoose/typegoose@6.2.1/lib/typegoose.js

```
tslib_1.__exportStar(require("./prop"), exports);
```

**Comment by hasezoey** [comment]
it shouldnt be a problem, so what do you think to do about that?

**Comment by avaly** [comment]
Workaround with:

```js
import typegoose from '@typegoose/typegoose';

const { getModelForClass, modelOptions, prop } = typegoose;
```

**Comment by sosoba** [comment]
Try use tslib esm proxy: ```sh
npm install tslib@npm:@sosoba/tslib
``` for diagnostic.
