### ISSUE TITLE
Virtual properties on sub schema bug?

### ISSUE THREAD

**Issue by olivierto** [typegoose/typegoose#173]
## Versions

- NodeJS: 8.12.0
- Typegoose(NPM): 6.0.4
- mongoose: 5.4.0
- mongodb: 3.6

## What is the Problem?

Sub schema holds a virtual property, but the parent Schema doesn't get the virtual property out. 

## Code Example

I have a model Order with subproperty quote
```ts
export class Quote {
  /**
   * the reference SKU or id in the billing solution
   */
  @prop()
  reference?: string;
  /**
   * will return the edit link url of the document
   */
  public get editLink() {
    const iBilling = new BillingInterface();
    return iBilling.provider.getEditUrl(this.reference!);
  }
}

export class Order extends TimeStamps {

  @prop({ _id: false })
  quote?: Quote;

  @prop({ enum: OrderStatus, default: OrderStatus.DRAFT })
  status!: OrderStatus;


  @prop({ unique: true })
  number!: String;
}

const OrderModel = getModelForClass(Order, {
  schemaOptions: { toJSON: { virtuals: true }, toObject: { virtuals: true } }
});

export { OrderModel };

```

the output of an inserted Oder is 
```json
{
    "_id": "5e135c4f4eab6707df23a8a9",
    "updatedAt": "2020-01-07T15:08:01.702Z",
    "createdAt": "2020-01-06T16:11:59.933Z",
    "number": "4568",
    "quote": {
        "status": "draft",
        "reference": "MOMOMO",
        "isTest": true
    },
    "status": "draft",
}
```

As you can see there is no virtual editLink property in the quote Object

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
does `doc.quote.editLink` work?

**Comment by olivierto** [comment]
Yes after checking _doc.quote.editLink_ the result is fine. 
As soon as the model is using toJSON the virtual is being deleted. 
May be the subschema should have options ```schemaOptions: { toJSON: { virtuals: true }, toObject: { virtuals: true } }```?

**Comment by olivierto** [comment]
Ok adding this 
```ts
@modelOptions({ schemaOptions: { id: false, toJSON: { virtuals: true }, toObject: { virtuals: true } } })
export class Quote {
...
```
Will make it work! 
thanks for giving me a clue. 
Anyway, does the schemaOptions of the Parent Schema should not be applied to the subSchema?

**Comment by hasezoey** [comment]
> Anyway, does the schemaOptions of the Parent Schema should not be applied to the subSchema?

i dont know how mongoose handles this, this would be an issue for mongoose...
