### ISSUE TITLE
Trying to recover document data using virtual prop

### ISSUE THREAD

**Issue by josecleiton** [typegoose/typegoose#174]
I've followed the virtual properties guide in documentation, but didn't work as expected.

## Versions

- NodeJS: 13.6.0
- Typegoose(NPM): 6.1.6 
- mongoose: 5.7.13
- mongodb: 4.2

## What is the Problem?

When i try to virtual populate my `User` class the query is executed but nothing appears in `habits` property.

### Habit && User classes
```
export class Habit extends Model {
  @IsNotEmpty()
  @IsDefined()
  @MinLength(2)
  @prop({required: true, trim: true})
  public title!: string;

  @prop({ref: 'User'})
  public user?: Ref<User>;
}

export class User extends Model {
  public _id: mongoose.Types.ObjectId;

  @IsDefined()
  @MinLength(5)
  @IsEmail()
  @prop({required: true, unique: true})
  public email: string;

  @IsDefined()
  @MinLength(3)
  @prop({required: true, alias: 'firstName'})
  public first_name: string;
  public firstName: string;

  @IsDefined()
  @MinLength(3)
  @prop({required: true, alias: 'lastName'})
  public last_name: string;
  public lastName: string;

  @IsDefined()
  @MinLength(7)
  @prop()
  public password: string;

  @IsOptional()
  @IsUrl()
  @prop()
  public photo?: string;

  @arrayProp({
    ref: 'Habit',
    foreignField: 'user',
    localField: '_id',
    justOne: false,
  })
  public habits?: Ref<Habit>[];

  get id() {
    return this._id;
  }

  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}
```

## Do you know *why* it happenes?

*no*

## Mongoose log from docker

```
const-api        | Mongoose: users.findOne({ email: 'teste@teste.com' }, { projection: {} })
const-api        | Mongoose: habits.find({ user: { '$in': [ ObjectId("5e17536e1703bf184ace4704") ] } }, { projection: {} })
const-api        | user: {
const-api        |   _id: 5e17536e1703bf184ace4704,
const-api        |   email: 'teste@teste.com',
const-api        |   first_name: 'Primeiro',
const-api        |   last_name: 'Último',
const-api        |   password: '$2a$10$b9.G8ZZBJcvFwFgOfpNH5e/GW8.0ZlCscmTc8jILT8Mb/6iLDbk1a',
const-api        |   __v: 0
const-api        | }
```

**Comment by josecleiton** [comment]
Also, how is the best way to hide fields from http responses? Like `password` from `User`

**Comment by hasezoey** [comment]
@josecleiton you try to log an virtual property? did you log it with or without `toObject: true, toJSON: true`? 

Possible Duplicate of #167

**Comment by josecleiton** [comment]
> @josecleiton you try to log an virtual property? did you log it with or without `toObject: true, toJSON: true`?
> 
> Possible Duplicate of #167
> 
> > Also, what is the best way to hide fields from http responses?
> 
> try prop option `select`

I need to select, but not to show it in http responses. I've tried to set  both toJSON  toObject to false in password property, but doenst work.

**Comment by hasezoey** [comment]
@josecleiton the `toJSON` and `toObject` options are only class-level options, and say if you want to have virtuals included in the an "output"

---

as for the `select` thing, it is an prop-level options and says if you want this property included *by default* in any fetching of the document, otherwise just remove it yourself (or use lodash)

**Comment by josecleiton** [comment]
Thank you! I'll send a PR to add these things to docs, ok?

**Comment by hasezoey** [comment]
@josecleiton i dont really know what you want to add, but feel free to do it
