### ISSUE TITLE
Basic examples missing

### ISSUE THREAD

**Issue by jovanxua** [typegoose/typegoose#176]
Basic examples in the documentation are missing. Example, this model returns any. Why?

![Screen Shot 2020-01-15 at 4 57 18 PM](https://user-images.githubusercontent.com/26292093/72419733-636fc180-37b8-11ea-8965-de52e8ce77e4.png)

<img width="436" alt="Screen Shot 2020-01-15 at 2 00 07 AM" src="https://user-images.githubusercontent.com/26292093/72421037-be0a1d00-37ba-11ea-9ecd-c227baabdeca.png">

**Comment by hasezoey** [comment]
what you are showing are 2 different things, the first image is about `getModelForClass` and the second is about `getDiscriminatorModelForClass`
-> please provide more info for *one*

aside from `create` i dont see anything wrong
-> could you give an full example?

PS: it is bad to overwrite any mongoose function / property (`create`)

**Comment by jovanxua** [comment]
My apologies for misleading and incorrect attachments. Second one should be about getModelForClass, but i got the wrong file attached.

But to clarify, below is the documentation example. 
![Screen Shot 2020-01-15 at 5 48 38 PM](https://user-images.githubusercontent.com/26292093/72439064-29ff7c00-37e1-11ea-934c-e0fba6566a78.png)

**Comment by hasezoey** [comment]
@jovanxua sorry, i cant confirm this (just tested), and it is fully working and typed, do you have `@types/mongoose` installed?

**Comment by jovanxua** [comment]
that worked @hasezoey, i missed to install @types/mongoose. Thanks!

**Comment by elie222** [comment]
Ran into this just now too. Would be good to include in README. Added here:
https://github.com/typegoose/typegoose/pull/183
