### ISSUE TITLE
Schema#pick()

### ISSUE THREAD

**Issue by ChrisLahaye** [typegoose/typegoose#177]
Hello,

Is there any plan to support a schema pick function (like https://thecodebarbarian.com/whats-new-in-mongoose-58-schema-pick-and-better-stack-traces.html), which allows you to use parts of another schema/class.

I would like to use parts of another class as property value. What is the best way of doing this?

Best

**Comment by hasezoey** [comment]
sorry, but i cant imagine a way to make this work with types consistently ... (| without breaking the getModelForClass one-function pipeline)

i will try to make a prototype if i get something in my mind

---

Small guess: (pseudo code, not made to work instantly)
```ts
// somefirstclass.ts
export class Something {
  @prop({ required: true, default: "hello" })
  public someprop: string;
}

export const SomethingModel = getModelForClass(Something);

// -----------------------------------------------
// somesecondclass.ts
class SomeActual {
  @prop({ required: true })
  public someadditonalprop: boolean;
}

const schema = buildSchema(SomeActual);
// types: getPickedModel(from: Schema, class: Class, pick: string[]): ReturnModelType
export SomeActualModel = getPickedModel(SomethingModel.schema, SomeActual, ["someprop"]);

// -----------------------------------------------
// test.ts
expect(SomeActualModel.schema.path("someprop")).to.equal(SomethingModel.schema.path("someprop"));
```

**Comment by ChrisLahaye** [comment]
Schema would be fine if it would be allowed to use schema for a prop, but that it not the case. From another perspective, it is not really a model since there is no collection associated

**Comment by hasezoey** [comment]
> From another perspective, it is not really a model since there is no collection associated

how so? with the `@modelOptions` decorator you can assign an collection, otherwise it will be an automatic (from mongoose), but yes i would add the normal `options` to this function too like in `getModelForClass`

**Comment by ChrisLahaye** [comment]
@hasezoey yes but not every class needs to be a model. I can have a model User that has a property address with the structure of class UserAddress. Now UserAddress does not need to be a model / have a collection associated.

**Comment by hasezoey** [comment]
@ChrisLahaye so you want to have something that works like schema.pick, but for class without creating a schema / model? this will be tricky

**Comment by ChrisLahaye** [comment]
I just want to use parts of another class as schema doe a property

**Comment by hasezoey** [comment]
like i said, it will be hard without creating a model and without having to **duplicate code**
