### ISSUE TITLE
Enum not working from other files

### ISSUE THREAD

**Issue by AliYusuf95** [typegoose/typegoose#181]
## Versions

- NodeJS: v12.13.1
- Typegoose(NPM): 6.2.2
- mongoose: 5.8.9
- mongodb: 0.0.0
- nestjs: 6.11.1

## What is the Problem?
I can't use enum prop field
```
Error: Invalid type used for map!, got: "function Object() { [native code] }" (OrganizationEntity.entityType)
    at Object._buildPropMetadata (/.../node_modules/@typegoose/typegoose/src/prop.ts:224:15)
    at Object._buildSchema (/.../node_modules/@typegoose/typegoose/src/internal/schema.ts:47:7)
    at buildSchema (/.../node_modules/@typegoose/typegoose/src/typegoose.ts:170:9)
    at getModelForClass (/.../node_modules/@typegoose/typegoose/src/typegoose.ts:105:58)
    ......
```

## Code Example
```ts
// some-type.enum.ts
export enum SomeType {
    Type1 = 'Type 1',
    Type2 = 'Type 2',
}
```
```ts
import { SomeType } from './some-type.enum';
export class Item {
    @prop({ enum: SomeType })
    type?: SomeType;
}
```

## Do you know *why* it happenes?
The enum is imported from another file when I use enum in the same class file, it's working!!

**Comment by AliYusuf95** [comment]
This is not working:
```ts
import { SomeType } from './some-type.enum';
export class Item {
    @prop({ enum: SomeType, type: mongoose.Schema.Types.String })
    type?: SomeType;
}
```

But thi is working:
```ts
import { SomeType } from './some-type.enum';
export class Item {
    @prop({ enum: SomeType, type: String })
    type?: SomeType;
}
```

**Comment by nasr18** [comment]
@AliYusuf95 me too facing same issue. waiting for the solution.

**Comment by hasezoey** [comment]
@AliYusuf95 for `type` you would need to use `String`
```ts
@prop({ enum: SomeType, type: mongoose.Schema.Types.String })
// to
@prop({ enum: SomeType, type: String })
```

and could you provide the type of the enum?
```ts
// do this once in the file the enum is exported in, and once in the file where it is imported in
console.log("typeof", typeof SomeType)
```

Do you use ts-node with `--transpile-only` or the nestjs toolchain (like @nasr18)?

**Comment by hasezoey** [comment]
because i didnt use nestjs much and couldnt reproduce without it, could someone prepare an reproduction repository with all the dependencies and point out the command used to run it?

**Comment by AliYusuf95** [comment]
@hasezoey this is the log: `typeof object`, both have object type.

Actually I use [nx](https://github.com/nrwl/nx) CLI to run the application which it's maybe different from nestjs.

**Comment by hasezoey** [comment]
@AliYusuf95 and what did you setup nx to use for compilation and running? ts-node? tsc + node? nest-toolchain?

**Comment by AliYusuf95** [comment]
@hasezoey I’m not sure about that, but I think nx use nest-toolchain under the hood for compiling and running.

**Comment by hasezoey** [comment]
@nasr18 could you try `nest start --tsc`?

**Comment by nasr18** [comment]
@hasezoey I think the issue is with `nx`. I'm also using `nestjs` generated via `nx cli`.

**Comment by nasr18** [comment]
@

> @nasr18 could you try `nest start --tsc`?

@hasezoey command i used to run/build my project is `ng serve api`

**Comment by hasezoey** [comment]
@nasr18 so you used the angular cli?

**Comment by nasr18** [comment]
@hasezoey not me. It's nx using angular cli.

**Comment by nasr18** [comment]
@hasezoey nx behind the scene using angular cli to build nestjs app. I checked their builder commands. I dont understand what they are doing. I will try in nestjs app and update here.

**Comment by linjie0928** [comment]
> @nasr18 so you used the angular cli?

![註解 2020-02-08 140713](https://user-images.githubusercontent.com/44791594/74080202-56bf5000-4a7c-11ea-9d1b-cddfbb0c207f.png)

angular cli use webpack to compile the code, that may cause the problem.

**Comment by nasr18** [comment]
@linjie0928 yes. but what's the solution for this?

**Comment by hasezoey** [comment]
@linjie0928 thanks for the insight that the chain is about:
nx -> angular -> webpack
so @nasr18 could you post your webpack config, if you have one?

**Comment by JakeAi** [comment]
@hasezoey I had this same problem in my NestJS server using nestjs-typegoose using NX (which actually doesn't matter since it uses `ng` commands) which uses Angular CLI which uses webpack to build the project. 
Changing
```TS
@prop({enum: CartType}) public cartType?: CartType;
```
To ( like you pointed out ) works for me
```TS
@prop({enum: CartType, type: String}) public cartType?: CartType;
```

**Comment by hasezoey** [comment]
@JakeAi sorry that i overlooked this long

---

when this change helps, then it is probably like [`ts-node: never run ts-node --transpile-only`](https://typegoose.github.io/typegoose/guides/known-issues/)

**Comment by AliYusuf95** [comment]
@hasezoey It's seems nx enable transpile-only option  by default 

https://github.com/nrwl/nx/issues/2147#issuecomment-609803071

https://github.com/nrwl/nx/blob/670a5f90846bd455ef31b8f5877c6bc697346c27/packages/node/src/utils/config.ts#L43

To solve the issue I have to do this:

```ts
// webpack.config.js
module.exports = (config, context) => {
    for (const rule of config.module.rules) {
        if (rule.loader !== 'ts-loader') {
            continue;
        }

        rule.options.transpileOnly = false;
    }

    return config;
};
```

```json5
// angular.json
"architect": {
    "build": {
        "builder": "@nrwl/node:build",
        "options": {
                "outputPath": "dist/apps/api",
                "main": "apps/api/src/main.ts",
                "tsConfig": "apps/api/tsconfig.app.json",
                "webpackConfig": "apps/api/webpack.config.js", // <--- add this line
                "assets": ["apps/api/src/assets"]
         },
```

**Comment by hasezoey** [comment]
@AliYusuf95 thanks for finding this

**Comment by hasezoey** [comment]
> This is not working:
> 
> ```ts
> import { SomeType } from './some-type.enum';
> export class Item {
>     @prop({ enum: SomeType, type: mongoose.Schema.Types.String })
>     type?: SomeType;
> }
> ```
> 
> ```
> Error: Invalid type used for map!, got: "function SchemaString(key, options) {
>   this.enumValues = [];
>   this.regExp = null;
>   SchemaType.call(this, key, options, 'String');
> }"
> ```
> 
> But this is working:
> 
> ```ts
> import { SomeType } from './some-type.enum';
> export class Item {
>     @prop({ enum: SomeType, type: String })
>     type?: SomeType;
> }
> ```

this is now fixed in de6897e9be29ff024f3b780d61110a298a3e135b (7.1.1)

**Comment by hasezoey** [comment]
since 59644613e3d4e884afa75a14297fd68dda6085ff it is mentioned that babel dosnt set the type of an enum correctly and [how to workaround it](https://typegoose.github.io/typegoose/docs/decorators/prop/#enum)

so i think this issue is solved by documentation

**Comment by patrickmichalina** [comment]
> @hasezoey It's seems nx enable transpile-only option by default
> 
> [nrwl/nx#2147 (comment)](https://github.com/nrwl/nx/issues/2147#issuecomment-609803071)
> 
> https://github.com/nrwl/nx/blob/670a5f90846bd455ef31b8f5877c6bc697346c27/packages/node/src/utils/config.ts#L43
> 
> To solve the issue I have to do this:
> 
> ```ts
> // webpack.config.js
> module.exports = (config, context) => {
>     for (const rule of config.module.rules) {
>         if (rule.loader !== 'ts-loader') {
>             continue;
>         }
> 
>         rule.options.transpileOnly = false;
>     }
> 
>     return config;
> };
> ```
> 
> ```js
> // angular.json
> "architect": {
>     "build": {
>         "builder": "@nrwl/node:build",
>         "options": {
>                 "outputPath": "dist/apps/api",
>                 "main": "apps/api/src/main.ts",
>                 "tsConfig": "apps/api/tsconfig.app.json",
>                 "webpackConfig": "apps/api/webpack.config.js", // <--- add this line
>                 "assets": ["apps/api/src/assets"]
>          },
> ```

updated in 2024:

```js
for (const rule of config.module.rules) {
    if (rule.loader?.includes('ts-loader')) {
      rule.options.transpileOnly = false;
    }
    continue;
  }
```
