### ISSUE TITLE
Is there a workaround to be able to use chaining in properties that are references (Ref <T>)?

### ISSUE THREAD

**Issue by LucioMF** [typegoose/typegoose#185]
When I have a class like the following:

```js
export class Application{
    @prop({ required: [true, 'app name is required'], unique: true })
    name!: string;

    @prop({ required: [true, 'component is required'], ref: Component})
    component!: Ref<Component>;
}
```

And assuming that the 'Component' class has a 'name' property, I can't do this 
```js
let app: Application
const appName = 'appTest';
app = await (await this.findOne({ name: appName })).populate('component').execPopulate();
console.log(app.component.name);
```
because it gives me the following error:
```
Property 'name' does not exist on type 'Ref<Component, ObjectId>'.
Property 'name' does not exist on type 'ObjectId'
```

Is there a way I can have the linter perceive the type as T (from Ref<T>) rather than ObjectId?
Thanks in advance

## Versions
- NodeJS: 10.15.3
- Typegoose(NPM): 6.2.2
- mongoose: 5.8.10
- mongodb: 4.2.1
- nestjs / nestjs-typegoose: 6.11.4 / 7.0.0

**Comment by hasezoey** [comment]
it would work in normal JS, but in typescript & typegoose the type is an OR between the class an the expected id type (in this case `Component` and `ObjectId`), which can still happen after populate that is why the [typeguards](https://typegoose.github.io/typegoose/docs/functions/typeguards/isDocument/) exists
