### ISSUE TITLE
Breaks swagger plugin

### ISSUE THREAD

**Issue by lepicekmichal** [typegoose/typegoose#188]
## Versions

- NodeJS: 10.18.1
- Typegoose(NPM): 6.2.2
- mongoose: 5.7.0
- mongodb: 4.2.3
- nestjs / nestjs-typegoose: 7.0.0

## What is the Problem?
When I use typegoose, it breaks swagger plugin for automatic generation of documentation.
https://trilon.io/blog/nestjs-swagger-4-whats-new#Introducing-the-NEW-Nest-Swagger-Plugin-
https://github.com/nestjs/swagger/tree/master/lib/plugin

nest-cli.json
```ts
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/swagger/plugin",
      }
    ]
  }
}
```

any.dto.json
```ts
@index({whatever: 1})
export class Whatever {
  @prop({
    required: true,
    lowercase: true,
  })
  public readonly whatever!: string
}
```

## Do you know *why* it happenes?

*no*

```
(node:30) UnhandledPromiseRejectionWarning: Error: A circular dependency has been detected (property key: "name"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").
api_1  |     at SchemaObjectFactory.createNotBuiltInTypeReference (/home/app/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:107:19)
api_1  |     at SchemaObjectFactory.mergePropertyWithMetadata (/home/app/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:88:25)
api_1  |     at modelProperties.map.key (/home/app/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:55:35)
api_1  |     at Array.map (<anonymous>)
api_1  |     at SchemaObjectFactory.exploreModelSchema (/home/app/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:54:52)
api_1  |     at ResponseObjectFactory.create (/home/app/node_modules/@nestjs/swagger/dist/services/response-object-factory.js:45:47)
api_1  |     at lodash_1.mapValues (/home/app/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:50:96)
api_1  |     at /home/app/node_modules/lodash/lodash.js:13401:38
api_1  |     at /home/app/node_modules/lodash/lodash.js:4905:15
api_1  |     at baseForOwn (/home/app/node_modules/lodash/lodash.js:2990:24)
api_1  |     at Function.mapValues (/home/app/node_modules/lodash/lodash.js:13400:7)
api_1  |     at mapResponsesToSwaggerResponses (/home/app/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:50:39)
api_1  |     at exports.exploreApiResponseMetadata (/home/app/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:26:16)
api_1  |     at explorers.reduce (/home/app/node_modules/@nestjs/swagger/dist/swagger-explorer.js:67:45)
api_1  |     at Array.reduce (<anonymous>)
api_1  |     at lodash_1.mapValues (/home/app/node_modules/@nestjs/swagger/dist/swagger-explorer.js:66:99)
```

**Comment by hasezoey** [comment]
@lepicekmichal please provide your code to reproduce the issue

**Comment by lepicekmichal** [comment]
@hasezoey no need, just turn it on. 
but sure, code provided

**Comment by hasezoey** [comment]
@lepicekmichal i dont know what you mean with "just turn it on" i never used nest outside of typegoose debugging and never swagger

**Comment by lepicekmichal** [comment]
Alright, but then it's too much code to share. Just create simplest app in nestjs (nest can generate it) and use typegoose in it.

**Comment by hasezoey** [comment]
@lepicekmichal just create an reproduction repository - with instructions how to start and where to look for the error

**Comment by hasezoey** [comment]
closing because no further information was given and is stale since February

**Comment by Bratishques** [comment]
Hi, I know the issue is closed, but if you stumble upon this post while googling the issue, I have managed to reproduce the issue with following packages

`
    "reflect-metadata": "0.1.13",
    "@typegoose/typegoose": "12.2.0",
    "@nestjs/swagger": "7.3.0",
`

The issue goes as following: both NestJs swagger and typegoose use Reflect.getMetadata in order to get the data about your classes, but when you import some typegoose functions that use Reflect the object gets redefined in global scope and method works differently. Kinda sloppy explanation, but this is what I found out during my nightly monkey patching session.

Fix: bump your reflect-metadata package, it somehow fixes it

**Comment by hasezoey** [comment]
@Bratishques the problem is that `reflect-metadata` 0.1.x *always* modified the global `Reflect` object, in 0.2.x, there is a *option* to use a non-global version, but typegoose is not making use of that at the moment.
FYI typegoose uses reflect-metdata 0.2.1 since [12.1.0](https://github.com/typegoose/typegoose/blob/master/CHANGELOG.md#1210-2024-01-17).

also please note that currently `reflect-metadata` is **not** a peer-dependency and cannot be replaced at the moment, see #761.

**Comment by Bratishques** [comment]
> @Bratishques the problem is that `reflect-metadata` 0.1.x _always_ modified the global `Reflect` object (to my understanding), in 0.2.x, there is a _option_ to use a non-global version, but typegoose is not making use of that at the moment. FYI typegoose uses reflect-metdata 0.2.1 since [12.1.0](https://github.com/typegoose/typegoose/blob/master/CHANGELOG.md#1210-2024-01-17).
> 
> also please note that currently `reflect-metadata` is **not** a peer-dependency and cannot be replaced at the moment, see #761.

Thanks for the explanation, I personally hate when something decides to go global, stuff just breaks. I guess you understood it, but I will clarify: when I said _bump your reflect-metadata package, it somehow fixes it_ I meant that the person that is googling the issue will resolve by doing so, typegoose itself causes no issue. And thanks for your hard work maintaining the package!
