### ISSUE TITLE
Webpack typescript plugin crashes

### ISSUE THREAD

**Issue by osayfun** [typegoose/typegoose#190]
## Versions
- NodeJS: 12.12.0
- NPM: 6.13.6
- Typegoose: 6.3.0
- mongoose: 5.8.11

## What is the Problem?
Release 6.3.0 crashes on typescript when using webpack and ts-loader.

```ts
ERROR in /node_modules/@typegoose/typegoose/lib/types.d.ts
ERROR in /node_modules/@typegoose/typegoose/lib/types.d.ts(259,48):
TS2344: Type 'R extends { _id?: string | number | Buffer | ObjectId | undefined; } ? R["_id"] : ObjectId' does not satisfy the constraint 'RefType'.
  Type 'ObjectId | R["_id"]' is not assignable to type 'RefType'.
    Type 'R["_id"]' is not assignable to type 'RefType'.
      Type 'string | number | Buffer | ObjectId | undefined' is not assignable to type 'RefType'.
        Type 'undefined' is not assignable to type 'RefType'.
          Type 'R["_id"]' is not assignable to type 'ObjectId'.
            Type 'R extends { _id?: string | number | Buffer | ObjectId | undefined; } ? R["_id"] : ObjectId' is not assignable to type 'ObjectId'.
              Type 'ObjectId | R["_id"]' is not assignable to type 'ObjectId'.
                Type 'R["_id"]' is not assignable to type 'ObjectId'.
                  Type 'string | number | Buffer | ObjectId | undefined' is not assignable to type 'ObjectId'.
                    Type 'undefined' is not assignable to type 'ObjectId'.
error Command failed with exit code 2.
```

**Comment by hasezoey** [comment]
this package is not intended to run in an browser - please provide an reproduction script (and when possible your typescript version)

**Comment by osayfun** [comment]
> this package is not intended to run in an browser - please provide an reproduction script (and when possible your typescript version)

I'm not running this package on a browser. It's running as backend code! Typescript version 3.7.5

**Comment by hasezoey** [comment]
@osayfun when it is run back-end, why would it need webpack?

PS:  please provide an reproduction script / reproduction repository

**Comment by osayfun** [comment]
What do you mean by that? I use webpack to minify my package. It's not a bug in webpack! The reproduction script is a usual webpack flow.
Please solve your package bug!

**Comment by hasezoey** [comment]
@osayfun please provide an reproduction repository or code, without it i cant see the problem

**Comment by osayfun** [comment]
#192 is my problem. Release v6.3.1 solved the problem. Thank you.
