### ISSUE TITLE
getModelForClass returns any type

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [typegoose/typegoose#191]
## Versions
- Typegoose : 6.3.0

## What is the Problem?

`getModelForClass` method returns `any` type

## Code Example

```ts
import { getModelForClass } from '@typegoose/typegoose';

class Test {

}

const TestModel = getModelForClass(Test);
```
![image](https://user-images.githubusercontent.com/15037839/73953440-d385e900-4919-11ea-87f1-cf339eb133dc.png)

[Try in playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=10&pc=1#code/JYWwDg9gTgLgBAbzgcwKYwLIQCaoDYBi0AwngIYDOFcAvnAGZQQhwDkAAjAJ5irIQQKqAPTde-QalYBuAFCyAxuSpwAKqgrwE8mvIUQAdprUbMOfHAC8KdFlyESyigAp1mgJRz5QA)

## Do you know *why* it happenes?

*no*. ~But this might be affecting #189 actually~ It seems it is by design there

**Comment by hasezoey** [comment]
no #189 does not have anything todo with it, it would just make the property `_id` as any, not the whole class

i dont see a problem, do you have `@types/mongoose` installed? typescript version over 3.7? already tried adding an property and still the same?

**Comment by OrkhanAlikhanov** [comment]
Yes #189 has nothing to do with this and I had already updated issue saying that. 

Yes I could not get it working no matter what. Even tried typescript 3.8beta.

**Comment by OrkhanAlikhanov** [comment]
@types/mongoose might not be installed. Will check it. Probably it's the reason

**Comment by OrkhanAlikhanov** [comment]
That was it! Thanks! Can you update https://github.com/typegoose/typegoose#install to include that. I thought it is auto-downloaded as dependency

**Comment by hasezoey** [comment]
@OrkhanAlikhanov yes, it is currently listed as an peer-dependency, because when it would be an normal dependency, and you would install it too (for some other reason), it would in some cases not be compatible (changed types)
