### ISSUE TITLE
New ref is broken

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#192]
## Versions

- Typegoose(NPM): 6.3

## What is the Problem?

I removed all the occurences of `refType` in my code and replaced all the `Ref<Ressource, objectIdType>` by `Ref<Ressource>`. It correctly type fields. However, now, all ref fields have a value of `undefined` (even if correctly typed).

**Comment by hasezoey** [comment]
`undefined` at runtime or as types? when was types, do you extend `Base` / have `_id` implemented yourself?

**Comment by lcswillems** [comment]
They are undefined at runtime. No, I have not extended `Base` and I specified a `string` type to all my `_id`.

**Comment by hasezoey** [comment]
@lcswillems could you provide some of your models for reproduction?

**Comment by lcswillems** [comment]
Something like the following should reproduce it:

```ts
class A {
  @prop()
  _id: string;

  @prop({ ref: 'B', required: true })
  bId: Ref<B>;
}

class B {
  @prop()
  _id: string;
}
```

`bId` should be correctly typed but `undefined` at runtime.

**Comment by hasezoey** [comment]
is your project in `strict`?

**Comment by lcswillems** [comment]
No

**Comment by hasezoey** [comment]
do you have any `noImplicit` rule on?

**Comment by lcswillems** [comment]
No

**Comment by hasezoey** [comment]
i ask because i noticed the prepare script failing when installing it into an strict project (the same error)

**Comment by hasezoey** [comment]
btw this is the reason i made it an minor version, because it could break someones code

**Comment by hasezoey** [comment]
@lcswillems could you try going to `node_modules/@typegoose/typegoose/lib/types.d.ts` and search for `export type Ref` and replace `{ _id?: RefType }` with `{ _id: RefType }` (removing the `?`) would this solve the error and would it break anything?

**Comment by hasezoey** [comment]
hopefully 6.3.1 will fix it

**Comment by hasezoey** [comment]
i will close this because of inactivity and assuming it is fixed
