### ISSUE TITLE
Dont support Bulk?

### ISSUE THREAD

**Issue by pandaiiz** [typegoose/typegoose#197]
## Versions

- typegoose: 6.2.2
- mongoose: 5.5.43

**Comment by pandaiiz** [comment]
- i want use these methods in typegoose
https://docs.mongodb.com/manual/reference/method/js-bulk/
- but typegoose only support bulkWrite mehthods, should i use bulkWrite methods continue? when can typegoose support these methods?

**Comment by hasezoey** [comment]
@pandaiiz i dont know much about bulk, and typegoose dosnt modify any methods from mongoose, so you should look up how to do it in mongoose

**Comment by hasezoey** [comment]
i will close this because it is not an typegoose issue (and inactivity)
