### ISSUE TITLE
Is there a way to index a nested object?

### ISSUE THREAD

**Issue by dzcpy** [typegoose/typegoose#200]
For example, how to implement this in typegoose?
```javascript
var PostSchema = new mongoose.Schema({
    nesteddoc: {
        field1: { type: String, unique: true, index: true },
    }
});
```

## Versions

- typegoose: 0.0.0
- mongoose: 0.0.0

**Comment by hasezoey** [comment]
if you use the `index` options, and not the decorator, it is [just the same](https://typegoose.github.io/typegoose/docs/decorators/prop/#index)

if you decide to use the [index *class decorator*](https://typegoose.github.io/typegoose/docs/decorators/indexes/), you need to use `nesteddoc.field1` to access it
