### ISSUE TITLE
How to use different databases using same connection pool ?

### ISSUE THREAD

**Issue by joravkumar** [typegoose/typegoose#201]
## How to use different databases using same connection pool in typegoose ?

- I want to use the (useDb feature) https://github.com/Automattic/mongoose/wiki/3.7-%28unstable%29-Release-Notes#connection-pool-sharing but I'm not sure how to do it with Typegoose.

I tried the following:
```
export function getModelForDb<T>(dbName, model) {
  const connection = mongoose.createConnection(
    `mongodb://${env.user}:${env.password}@${env.mongoURI}`,
    {
      authSource: env.authSource
    }
  );
  const db = connection.useDb(dbName);
  const DbModel = db.model(model.modelName, model.schema) as ModelType<T> & T;
  return DbModel;
} 

```
But It's not working.
Can anybody help ?

## Versions

- typegoose: 6.2.2
- mongoose: 5.6.9

**Comment by hasezoey** [comment]
i dont know what you want to achieve, here some things:
- you can pass in an connection to be used with `existingConnecton`  (default: `mongoose.connection`)
- you can pass in an existing mongoose with `existingMongoose` (default: `mongoose` itself)
- you could use `buildSchema` to build an schema from an typegoose class and assemble it yourself (`db.model`)

**Comment by joravkumar** [comment]
I want to use achieve something like this :

```
var db = mongoose.createConnection(uri);

// use another database without creating additional connections
var db2 = db.useDb('someDbName');
```
So above example uses one connection pool and i can switch to the another database using **useDb** but how can i achieve the same in **typegoose**.

I am using typegoose and nestjs-typegoose in my project.

**Comment by hasezoey** [comment]
because `useDb` returns an connection, you will need to use `existingConnection` as an [schema-option](https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#existingconnection)
-> but i dont know how to use it in nestjs-typegoose because i dont use it

**Comment by joravkumar** [comment]
It's working now. I got the current mongoose connection by using:

```
import { getConnectionToken } from 'nestjs-typegoose';
constructor(@Inject(getConnectionToken()) private connection: mongoose.Connection){}
const userLoggingModal = getModelForDb(
      this.connection,
      'dbName',
      this.yourModal
);
```

and I create a function in model file:
```
export function getModelForDb<T>(connection, dbName, model) {
  const db = connection.useDb(dbName);
  const DbModel = db.model(model.modelName, model.schema) as ModelType<T> & T;
  return DbModel;
}
```
Now i can switch db with the same connection pool.

**Comment by hasezoey** [comment]
@joravkumar i assume this question is solved now?

**Comment by joravkumar** [comment]
> @joravkumar i assume this question is solved now?

yes, It is solved now.

**Comment by olawalejuwonm** [comment]
Hi.

Please, how can I achieve this in pure typegoose?

**Comment by hasezoey** [comment]
@olawalejuwonm i dont know what you mean with pure typegoose, which approach do you mean to purify?

typegoose does not handle connection logic, so you still need to provide typegoose the connection to use via `existingConnection` either in the `@modelOptions` decorator or at `getModelForClass` / `buildSchema` options

**Comment by olawalejuwonm** [comment]
Can I have 2 database connections?:

- One db connected to 2 models/schema

- The other db connected to all other database connection serving as the
default

**Comment by hasezoey** [comment]
> Can I have 2 database connections?:

you can have multiple database connection (if you mean `mongoose.Connection`s), though you will need to register the model on each connection you want to use a schema on (and they will be different values), like in pure mongoose.

maybe consider also reading [Mongoose: Multiple connections](https://mongoosejs.com/docs/connections.html#multiple_connections)
