### ISSUE TITLE
Using typegoose causes requests to stay at pending

### ISSUE THREAD

**Issue by c739557637** [typegoose/typegoose#203]
## Versions

- NodeJS: 12.4.1
- Typegoose(NPM): 6.4.0 
- Typegoose(GIT): commithash
- mongoose: 5.9.2
- mongodb: 3.4.16-26-g315d49ee78

## What is the Problem?

I recieved many warnings like this when I use Typegoose

"mongoose: the method name "populated" is used by mongoose internally, overwriting it may cause bugs. If you're sure you know what you're doing, you
can suppress this error by using `schema.method('populated', fn, { suppressWarning: true })`"

I don't know if these warnings are the cause of the problem that all requests will stay at pending after running a while my node server.

I hope you can solve the problem

## Code Example

```ts

@modelOptions({schemaOptions: {versionKey: false, timestamps: true}})
export class Person extends Document {
    @prop({required: true})
    name?: string;
    @prop()
    number?: string;
    @prop({required: true})
    id?: string;
}

@modelOptions({schemaOptions: {versionKey: false, timestamps: true}})
export class Signer extends Document {
    @prop({required: true})
    team_name?: string;

    @prop({required: true, ref: 'Person'})
    captain?: Ref<Person>;

    @prop({required: true})
    great_select?: number;

    @prop({required: true})
    small_select?: number;

    @prop({ref: 'Person'})
    teammate_one?: Ref<Person> | null;

    @prop({ref: 'Person'})
    teammate_two?: Ref<Person> | null;
  
}


const _Signer = getModelForClass(Signer);
const _Person = getModelForClass(Person);

export default {
    Signer: _Signer,
    Person: _Person,
};
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
sorry but your provided code shouldnt cause this warning, please trace the warning and provide an code sample from the stacktrace of the warning

**Comment by c739557637** [comment]
The warning was reported at my server startup,so I dont have any stacktrace info. But the warning appears before the then hooks of the mongoose.connect

**Comment by c739557637** [comment]
const mountDB = async function (app: Application) {
    await mongoose.connect('mongodb://localhost:27017/sign_up_sys', {useNewUrlParser: true, useUnifiedTopology: true});
    app.context.connection = connection;
    app.context.models = models;
};

**Comment by c739557637** [comment]
import mongoose, {connection} from 'mongoose';
import models from './models';
import Application from 'koa';

const mountDB = async function (app: Application) {
    await mongoose.connect('mongodb://localhost:27017/sign_up_sys', {useNewUrlParser: true, useUnifiedTopology: true});
    app.context.connection = connection;
    app.context.models = models;
};

export default mountDB;

**Comment by hasezoey** [comment]
@c739557637 updated your comment to be better readable

but again, in this function i dont see any problem that this could cause, maybe try searching your whole project (exclude node_modules) for `populated` - maybe you use this as an function name on an different model than in the examples, when yes - please rename it

**Comment by c739557637** [comment]
Sorry,I missed the message.
I haven't used the function named populated .Actually,it warned more than a dozen messages,and they are the same question expect for the names (such as populated)
I searched a lot and I didn't find anything happend on others.
Maybe this problem happend in my PC only.
I have changed the way to connect mongo .
Anyway thank you for answering!

**Comment by hasezoey** [comment]
@c739557637 what other names and do you use them as values/functions or any mongoose plugins?

**Comment by hasezoey** [comment]
i will be closing this issue, if it should come again, feel free to write here

**Comment by ScreamZ** [comment]
Never extends `mongoose.Document`, it makes that issue of pending
