### ISSUE TITLE
How to get @props List in @pre ？

### ISSUE THREAD

**Issue by guotingchaopr** [typegoose/typegoose#204]
### How to get @props List in @pre ？
 
  I want to get all props for the current model,  Is there any way to achieve it ?

### code 

``` typescript
@pre('save', function() {
  // const doc = this.model(this.typegooseName());

  // const props = Reflect.getMetadata('typegoose:properties', doc);

  // console.log(props);

  // const paths = model.paths;

  // const keys = Object.keys(paths).filter((key: string) => {
  //   console.log('Console Debug: --------------------------------------');
  //   console.log('Console Debug: paths[key].', this.schema.obj);
  //   console.log('Console Debug: --------------------------------------');
  //   return key;
  // });

  console.log('Console Debug: ------------------------');
  // console.log('Console Debug: keys', keys);
  console.log('Console Debug: ------------------------');
})
@modelOptions({
  schemaOptions: {
    timestamps: true
  }
})
export abstract class BasicModel {
```

-->

## Versions

- nodejs v12.14.1
- @typegoose/typegoose@^6.2.1
- nestjs-typegoose@7.0.1
- typescript@3.8.3
- mongodb@v4.2.2
- **typegoose: 6.0.0**
- **mongoose: 6.0.0**

**Comment by hasezoey** [comment]
not an official way at least, you could try accessing the decorators with reflection, [look here for the decorator keys](https://github.com/typegoose/typegoose/blob/master/src/internal/constants.ts#L4-L21)

**Comment by guotingchaopr** [comment]
> not an official way at least, you could try accessing the decorators with reflection, [look here for the decorator keys](https://github.com/typegoose/typegoose/blob/master/src/internal/constants.ts#L4-L21)

Ok, i got.
But there is a problem you want to tell me . plz.
How can I get the model classes of this doc on @pre.
I'm trying to use ` Reflect.getMetadata('typegoose:properties',  this.model)`
No return value ,  i just got `undefined` value

**Comment by hasezoey** [comment]
`this.model` returns the *model* and not the *class*, but you could try:
```ts
const class = getClass(this.modelName);
```
https://typegoose.github.io/typegoose/docs/functions/getClass/

but this requires the class to be made with typegoose or registered with typegoose (getModelForClass / addModelToTypegoose)

**Comment by guotingchaopr** [comment]
The problem has been solved
