### ISSUE TITLE
The @pre hook doesn't provide the right value of an array of nested documents (array is empty)

### ISSUE THREAD

**Issue by UnlimitedX** [typegoose/typegoose#207]
## Versions
- NodeJS: 13.11.0
- Typegoose(NPM): 6.4.0
- mongoose: 5.9.5
- mongodb: 4.2.3

## What is the Problem?

I am working on a historic system that would persist each time a field is modified into an array with the value of the field and the timestamp for logging purposes. To do this in an automatic way, I use the @pre hook.

Nevertheless, once in the @pre hook, the length of the array is always 0. It doesn't get the previous value of the array.

## Code Example

```ts
import { pre, prop, mapProp, modelOptions, arrayProp, Ref, Typegoose } from "@typegoose/typegoose";
import * as mongoose from "mongoose";

class HistoricParameter {

    @prop({ required: true })
    value: string | Date | number | boolean

    @prop({ required: true })
    updated_at: Date

}

//Update historic, to prevent the array's size to increase dramatically, we set up a hard limit
@pre<ResourceParameter>('save', function (next) {
    console.log("ResourceParameter pre save, historic size " + this.historic.length); //HERE the length is always == 0
    let historicParameter = new HistoricParameter();
    historicParameter.value = this.value;
    historicParameter.updated_at = new Date();
    this.historic.push(historicParameter); //Works for the next document.save but the item won't be in the next @pre
    return next();
})

class ResourceParameter {

    @prop({ required: true })
    value!: string | Date | number | boolean

    @arrayProp({ items: HistoricParameter, _id: false })
    historic?: HistoricParameter[];

}

@modelOptions({ schemaOptions: { timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } } })
export class Resource {

    @mapProp({ of: ResourceParameter, _id: false })
    public parameters?: Map<string, ResourceParameter>;

}
```

I have an User entity that extends the Resource.
```ts
import { prop } from '@typegoose/typegoose';
import {Resource} from './resource';

export class User extends Resource{
    
    @prop({required:true})
    public exampleId!: string;

}
```

And now the code to test the issue :

```ts
let newUser = new User();
newUser.exampleId = "125478";
newUser.parameters = new Map();

newUser.parameters.set("isProfessional", {
    value: true
});

const { _id: id } = await UserModel.create(newUser); //Create entity
var user = await UserModel.findById(id).exec(); //Fetch it

await new Promise(resolve => setTimeout(resolve, 1500));
user.parameters.set("isProfessional", {
    value: false
});
await user.save();

await new Promise(resolve => setTimeout(resolve, 1500));
user.parameters.set("isProfessional", {
    value: true
});
await user.save();

await new Promise(resolve => setTimeout(resolve, 1500));
user.parameters.set("isProfessional", {
    value: false
});
await user.save();

console.log(user.exampleId + " array size " + user.parameters.get("isProfessional").historic.length); // length output 1 should be 4
```

And the output in the Database 
![image](https://user-images.githubusercontent.com/6625963/77561569-2c581380-6ebf-11ea-8491-65080468d217.png)

## Do you know *why* it happens?

No.

**Comment by hasezoey** [comment]
(updated your issue to make code into an code-segment)

---

typegoose decorators only have an effect if the class is compiled to an model (/ used as an reference / sub-documents)

---

the actual problem you are having is that you use `set` without setting the previous values, so you overwrite the `historical` array always to `[]`

normally the following should fix your issue
```ts
user.parameters.set("isProfessional", {
    ...user.parameters.get("isProfessional"),
    value_rp: false
  });
```
**but** somehow mongoose dosnt like Map.set in this case, it will run infinitely

**Comment by hasezoey** [comment]
made an issue at mongoose: https://github.com/Automattic/mongoose/issues/8722

**Comment by UnlimitedX** [comment]
Thank you so much for your reply and for the issue at mongoose. 
Would it be possible/recommended to use **get & set** for the **@mapProp** _parameters_ field to automatically get the previous value - instead of writing  ...user.parameters.get("isProfessional") ?

**Comment by hasezoey** [comment]
@UnlimitedX i dont know if `get & set` will have an effect on the `get & set` functions of an mapProp
(because normally they proxy the `get & set` of an *assignment*(`variable = value`) and an Map gets set with `.get` & `.set`

**Comment by hasezoey** [comment]
@UnlimitedX [the mongoose issue](https://github.com/Automattic/mongoose/issues/8722) is now closed with an fix in the next version (5.9.7 / 5.10.0 whatever comes first)

---

i will close this issue when the next version that includes the fix is released

**Comment by UnlimitedX** [comment]
Thanks @hasezoey. Hopefully this will fix the issue for Typegoose as well.

**Comment by hasezoey** [comment]
@UnlimitedX 5.9.7 is now released

> Hopefully this will fix the issue for Typegoose as well.

what issue for typegoose again? (from what i saw, it was just an mongoose issue)

**Comment by UnlimitedX** [comment]
I mean I hope the fix for mongoose will works well for Typegoose.

**Comment by hasezoey** [comment]
@UnlimitedX just tested with my test code that was not working before upgrading the version, and it works without an infinite loop, so i take it as "issue fixed"

**Comment by UnlimitedX** [comment]
Perfect, thank you so much.
