### ISSUE TITLE
Using lean() returns a conflicting type when using default Base class

### ISSUE THREAD

**Issue by danielsarsi** [typegoose/typegoose#208]
## Versions

- NodeJS: 13.11.0
- Typegoose(NPM): 6.4.0 
- mongoose: 5.9.6
- @types/mongoose: 5.7.7

## What is the Problem?
When using `lean()` in queries, the type returned conflicts with the model class when using the default `Base` class.

## Code Example

```ts
import { getModelForClass, prop } from "@typegoose/typegoose";
import { Base } from "@typegoose/typegoose/lib/defaultClasses";

class Person extends Base {
  @prop()
  public name: string;

  @prop()
  public age: number;
}

const PersonModel = getModelForClass(Person);

async function getAllPersons (): Promise<Person[]> {
  const persons = await PersonModel.find().lean();
  return persons
  /*
    Type 'Pick<DocumentType<Person>, "name" | "age" | "_id" | "__t" | "typegooseName">[]' is not assignable to type 'Person[]'.
    Property '__v' is missing in type 'Pick<DocumentType<Person>, "name" | "age" | "_id" | "__t" | "typegooseName">' but required in type 'Person'.ts(2322)
    defaultClasses.d.ts(12, 5): '__v' is declared here.
  */
}
```

## Do you know *why* it happens?
Not sure. Maybe it's because `DocumentDefinition` has a optional `__v` value, which has been omitted by the `lean()` type constructor.

**Comment by jjpark78** [comment]
i have same problem too.

**Comment by hasezoey** [comment]
i think it is because these extra values like `_id` and `__v` are added by `Base`, they dont get excluded by lean's types
i dont really know how i should fix this

**Comment by jjpark78** [comment]
currently i am manually remove _id, __v property from Document object.

**Comment by hasezoey** [comment]
d921d76ff238312164d9f83c5fac067ac2b5c608 should fix this by setting `__v` and `__t` as optional (`?`)
