### ISSUE TITLE
model .create doesn't validate fields?

### ISSUE THREAD

**Issue by meteorpublish** [typegoose/typegoose#215]
## Versions

- NodeJS: 13.12.0
- TypeScript 3.9.0 dev
- Typegoose(NPM): 6.4.0

## What is the Problem?

I've copied the example from the README but I'm not sure it's working. I added a field to UserModel.create that doesn't exist, and TypeScript didn't complain about it.

## Code Example

```ts
const { _id: id } = await UserModel.create({
  nome: 'JohnDoe',  // <-- typo in field name, TS should complain
  nonexistent: 123,  // <-- TS should complain, field not part of the model
} as User); // an "as" assertion, to have types for all properties
```

What am I doing wrong?

PS: the `as User` on that last line doesn't check types, it casts the object literal to User, which is not what I want.

**Comment by hasezoey** [comment]
the `as Class` type assertion provides the fields of the class, but dosnt prevent to set unkown fields (same behavior in strict mode), if you want to allow *just* these types, you will need to remove the indexing type (which should be `[key: string]; any` for this)

**Comment by hasezoey** [comment]
the last answer should have solved it, so im closing the issue now
