### ISSUE TITLE
addModelToTypegoose method didn't keep custom mongoose model type.

### ISSUE THREAD

**Issue by googlicius** [typegoose/typegoose#222]
## Versions

- NodeJS: v10.19.0
- Typegoose(NPM): ^6.4.0 
- Typegoose(GIT): commithash
- mongoose: ^5.9.7
- mongodb: 0.0.0
- type-graphql: ^0.17.6

## What is the Problem?
`addModelToTypegoose` method does not keep the passed model type.

## Code Example

```ts
// User class:
export class User {
  @prop({ required: true })
  firstName!: string;

  @prop({ required: true })
  lastName!: string;
}

// I define my custom model interface:
interface SofDeleteModel<T extends mongoose.Document> extends mongoose.Model<T> {
  /**
   * Find one with deleted document.
   */
  findOneWithDeleted(): string;
}

// Build schema from class:
const userSchema = buildSchema(User);

// Defines model with custom model interface:
const UserModel = mongoose.model<DocumentType<User>, SofDeleteModel<DocumentType<User>>>('UserModel', userSchema);

// Then add this model to Typegoose:
const TypeUserModel = addModelToTypegoose(UserModel, User);

TypeUserModel.findOneWithDeleted(); // Got `Property 'findOneWithDeleted' does not exist on type 'SofDeleteModel<DocumentType<User>>'.`
```

## Do you know *why* it happenes?

Return type of `addModelToTypegoose` is hard corded, it didn't reflect passed model type.

**Comment by hasezoey** [comment]
then you need to either dont rely on the return type of the function OR overwrite `<T, U>` of the function

https://github.com/typegoose/typegoose/blob/aa940331dafd0986cde3bf9cc9700c211c712a39/src/typegoose.ts#L189

**Comment by googlicius** [comment]
How can i overwrite it? could you give me an example?

**Comment by hasezoey** [comment]
sorry but im not so good with types, especially with this (T,U) and dont fully understand what typescript does there

**Comment by hasezoey** [comment]
sorry for the late response solving this

> addModelToTypegoose method does not keep the passed model type.

this is correct, `addModelToTypegoose`'s types are made to return the types generated by the passed class - so if you need custom types, that are not on the class, you need to re-assign the types (`const TypeUserModel: types_here =`)
