### ISSUE TITLE
language_override IndexOptions property is missing

### ISSUE THREAD

**Issue by peelmicro** [typegoose/typegoose#223]
## Versions

- NodeJS: 0.0.0
- Typegoose(NPM): 6.4.0 
- Typegoose(GIT): commithash
- mongoose: 5.9.7
- mongodb: 0.0.0
- nestjs / nestjs-typegoose: 7.0.0 / 0.0.0 
- grahpql / type-graphql: 14.5.8 / 0.0.0 

## What is the Problem?

I'm trying to specify the Language for a document with a text index, using the **language_override** option as explained on https://docs.mongodb.com/manual/tutorial/specify-language-for-text-index/, but the **language_override** option seems not to be implemented.

## Code Example

```ts
@ObjectType()
@index({ 'commands.command': 'text'} , { language_override: 'commands.locale' } )
export class BotRequest {
  @Field(() => ID)
  '_id': string

  @Field()
  @prop({ required: true, unique: true })
  code: string
```

## Do you know *why* it happens?

Yes, because the IndexOptions interface has no **language_override** property.

**Comment by hasezoey** [comment]
this options seems to be new, added it in c03f4242ce3631e9395600cae5847c97d5cf0ee0
