### ISSUE TITLE
SyntaxError: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (4:3)

### ISSUE THREAD

**Issue by fbjork** [typegoose/typegoose#225]
## Versions

- NodeJS: 12.14.0
- Typegoose(NPM): 6.4.0
- mongoose: 5.9.9
- mongodb: 4.2.0
- next.js: 9.3.3
- typescript: 3.8.3

## What is the Problem?

I get this error given the code below:

```
SyntaxError: ./src/models/database.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (4:3):
```

## Code Example

```ts
import { prop, getModelForClass } from '@typegoose/typegoose'

class DatabaseSchema {
  @prop({ required: true, unique: true, maxlength: 30 })
  slug!: string

  @prop({ required: true })
  url!: string
}

export const Database = getModelForClass(DatabaseSchema)
```

## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
sorry your example works, do you use ts-node or babel?

**Comment by fbjork** [comment]
@hasezoey I’m not using ts-node, but Next.js uses Babel I believe.

**Comment by hasezoey** [comment]
then please look at what https://github.com/typegoose/typegoose/pull/229 added to the documentation (requirements) if you have set the plugins up correctly

**Comment by dandv** [comment]
I ran into that error as well with Jest and Babel. Had to install some plugins. This `babel.config.cjs` solved it:
```js
module.exports = {
  // Enable Jest to parse .test.ts files through Babel
  presets: [
    '@babel/preset-typescript',
  ],
  plugins: [
    // Because Jest still doesn't support native ES modules - https://github.com/facebook/jest/issues/9430
    '@babel/plugin-transform-modules-commonjs',
    // For Jest - Babel equivalents for experimentalDecorators and emitDecoratorMetadata
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    'babel-plugin-transform-typescript-metadata',
  ],
};
```

**Comment by hasezoey** [comment]
this issue will be closed, because it is recommended to **not** use babel, and if still needed anyway, [here is the documentation](https://typegoose.github.io/typegoose/guides/known-issues/#babel)
