### ISSUE TITLE
@prop() Enum can't combine enums, Always takes the first

### ISSUE THREAD

**Issue by arrrrny** [typegoose/typegoose#226]
here is my enum 
```
  @prop({ enum: Volume || Length || Volume || OtherMeasurements })
```

each of these values are enums 

expected behavior is to allow any one of these enums, however it only allows the first one. If the first element is Volume it only allows Volume values, if it is weight only allows weight etc..

**Comment by hasezoey** [comment]
this is not possible, this statement is an OR between these and will return at runtime an boolean

**Comment by arrrrny** [comment]
Ok, what would be the proper way to specify an "OR" case for enums then?

**Comment by hasezoey** [comment]
mongoose dosnt accept multiple enums (from what i know), the only way to merge them is by using `Object.assign({}, yourenum1, yourenum2, etc)`

**Comment by arrrrny** [comment]
@hasezoey  thanks for the help
