### ISSUE TITLE
(node:26876) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

### ISSUE THREAD

**Issue by giltal1** [typegoose/typegoose#231]
## Versions

- NodeJS: 13.5.0
- Typegoose(NPM): 6.4.0
- mongoose: 5.7.12
- mongodb: 4.2

## What is the Problem?

adding a unique option to prop prints the following deprecation warning from mongoose
(node:26876) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

**Comment by hasezoey** [comment]
https://mongoosejs.com/docs/deprecations.html#ensureindex
