### ISSUE TITLE
Difference between using enum prop

### ISSUE THREAD

**Issue by bennyKY** [typegoose/typegoose#232]
There is an enum
```javascript 
enum MoveIn {
  ONLY_LOOKING = 'onlyLooking',
  NOT_IN_HURRY = 'notInHurry',
  NOW = 'now'
}
```

so in model's class:
```javascript 
 @prop({ enum: MoveIn })
  public moveIn: MoveIn;
```

but this will works as well
```javascript 
 @prop()
  public moveIn: MoveIn;
```

So what is the difference?

**Comment by hasezoey** [comment]
the difference is that if you set the `enum` option, then it will be validated against that enum, if you let it stay away, typescript will either compile the type of an enum to `string` or `number` or in the worst case to `Object` / `Function`, that is why it needs to be defined as an option
