### ISSUE TITLE
Adding null as enum value

### ISSUE THREAD

**Issue by aletorrado** [typegoose/typegoose#235]
Hi! I was wondering how to add null as a possible value for a enum of strings. Mongoose requires to add `null` to the enum array to allow an empty value to be used, even when required is false.

Thanks!

**Comment by hasezoey** [comment]
typescript dosnt allow adding `null` to an enum of strings (and probably numbers too) and typegoose has an additional check for this - could you leave a source of where you got this info from? (maybe try to use `undefined` instead of `null` this should work in an `required: false` environment

**Comment by aletorrado** [comment]
Yes, I know it's a typescript limitation, but Typegoose should provide a workaround to avoid limiting this use case. I'm migrating a Mongoose project to Typegoose, and I cannot change the internals of the project to avoid unintended changes of logic.

The simplest and most secure way I can think of, would be to add a sort of `enumAllowNull` option to `@prop`.

**Comment by aletorrado** [comment]
By the way, for the time being, knowing that the official typescript implementation compiles enums to a key-value object, I'm using this hack: `enum: [null, ... Object.values(MyEnum)]`. I'm not sure if every typescript implementation works like this, and if this may broke in other environments.

**Comment by hasezoey** [comment]
@aletorrado this is right that mongoose's enum is just an array of possible values - i will try to add this in 7.0 as an option that adds null to the list (but i dont know if the types are ok with this)

but still, why not use `undefined` or already tried it?

**Comment by aletorrado** [comment]
> but still, why not use `undefined` or already tried it?
As I stated before, I'm upgrading an existing project to Typescript+Typegoose, and changing this kind of things may break existing logic.

**Comment by aletorrado** [comment]
@hasezoey I've closed this issue by mistake. Are you able to re-open it?

**Comment by hasezoey** [comment]
@aletorrado just wanted to know if undefined *would work*

**Comment by aletorrado** [comment]
> @aletorrado just wanted to know if undefined _would work_

Oh, yes, that might be an option in some cases.

**Comment by hasezoey** [comment]
1b0d224b90ce4c87fde5a0b00fcb32dd6ac80eaa adds the option `addNullToEnum`
