### ISSUE TITLE
 Error: Virtual path "fullName" conflicts with a real path in the schema

### ISSUE THREAD

**Issue by Luarb** [typegoose/typegoose#238]
## Versions

- NodeJS: 10.16.3
- Typegoose(NPM): ^6.4.0
- mongoose: ^5.9.6
- mongodb: v3.6.3
- nestjs 6.10

## What is the Problem?
How can I implement a virtual method ? I read the docs but this error keeps on showing.

## Code Example

```ts

import { prop } from "@typegoose/typegoose";


export class User  {

    @prop()
    username: string;

    @prop()
    password: string;

    @prop()
    firstName?: string;

    @prop()
    lastName?: string;

    @prop()
    get fullName(): string {
        return `${this.firstName} ${this.lastName}`;
    }

}
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
if you use the keywords `set`/`get`/`static` (or an function), then you dont need to add an extra `@prop`
