### ISSUE TITLE
Implicitly setting "Mixed" is not allowed! even when Mixed is set explicitly

### ISSUE THREAD

**Issue by richardsimko** [typegoose/typegoose#239]
## Versions

- NodeJS: v12.16.2
- Typegoose(NPM):6.5.0 
- Typegoose(GIT): commithash
- mongoose: 5.9.10
- mongodb: v4.2.5

## What is the Problem?

The fix for #152 has made it so the `Implicitly setting "Mixed" is not allowed!` warning is shown even if `Mixed` is set explicitly according to the documentation.

## Code Example

```ts
@modelOptions({ schemaOptions: { timestamps: true }, options: { customName: 'foo' } })
class Foo {

  @prop({ type: mongoose.Schema.Types.Mixed })
  bar?: object;
}
```

The above model triggers the warning even though it's implemented according to https://typegoose.github.io/typegoose/docs/decorators/prop/#type

## Do you know *why* it happenes?

*no*

**Comment by richardsimko** [comment]
There is a somewhat related issue too that `ObjectId` is not automatically resolved. For example:

```ts
@modelOptions({ schemaOptions: { timestamps: true } })
class FooModel {
  @prop()
  userId: ObjectId;
}
```

This does not work, I need to specify `@prop({ type: mongoose.Schema.Types.ObjectId })` explicitly. Not sure if this is intended or not?

**Comment by hasezoey** [comment]
i know the text of the warning is kinda misleading and that i need to change it
this message will always appear when an `Mixed` is detected, even if set manually, you can change the Severity of the message [with this option](https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#allowmixed) (to throw, warn or allow it)

---

your second comment is unrelated to the issue, but what is this `ObjectId` you use there? (maybe imported from mongodb?)

**Comment by richardsimko** [comment]
Thanks for the info, I'll change the setting to allow then.

`ObjectId` comes from `mongoose` like so:

```
import mongoose from 'mongoose';
type ObjectId = mongoose.Types.ObjectId;
```

**Comment by hasezoey** [comment]
`mongoose.Types.ObjectId` this type cannot be used, it needs to be `mongoose.Schema.Types.ObjectId`

**Comment by richardsimko** [comment]
Ah, I see, thanks!

**Comment by richardsimko** [comment]
@hasezoey I don't know if you want me to open a new issue for this, but the second problem persists.
```ts
import mongoose from 'mongoose';
type ObjectId = mongoose.Schema.Types.ObjectId;
@modelOptions({ schemaOptions: { timestamps: true } })
class FooModel {
  @prop()
  userId: ObjectId;
}
```

This still generates the mixed warnings, I need to manually specify the type of the prop using `@prop({ type: mongoose.Schema.Types.ObjectId })` in order to get rid of it (Or of course allow mixed in the model options). Shouldn't `ObjectId` resolve automatically?

**Comment by richardsimko** [comment]
Adding on to that, the following problem arises:

```ts
import mongoose from 'mongoose';
import { prop, modelOptions, getModelForClass } from '@typegoose/typegoose';
type ObjectId = mongoose.Schema.Types.ObjectId;
@modelOptions({ schemaOptions: { timestamps: true } })
class FooModel {
  @prop({ required: true, type: mongoose.Schema.Types.ObjectId })
  userId: ObjectId;
}

const FooModel = getModelForClass(FooModel);
// mongoose: To create a new ObjectId please try `Mongoose.Types.ObjectId` instead of using `Mongoose.Schema.ObjectId`. Set the `suppressWarning` option if you're trying to create a hex char path in your schema.
FooModel.findOne({userId: new ObjectId('5e997f95d6a35f3a0def3339')})
// Type 'ObjectId' is not assignable to type 'Condition<ObjectId>'.
//  Type 'ObjectId' has no properties in common with type 'QuerySelector<ObjectId>'.
FooModel.findOne({userId: new mongoose.Types.ObjectId('5e997f95d6a35f3a0def3339')})
```

Regardless of which `ObjectId` I use when querying I get either an error or a warning. The only way to get rid of this (And again, I'm not sure if this is as intended) is to set the type of `userId` to `mongoose.Types.ObjectId` and the `type:` property to `mongoose.Schema.Types.ObjectId` like this:

```ts
import mongoose from 'mongoose';
import { prop, modelOptions, getModelForClass } from '@typegoose/typegoose';
type ObjectId = mongoose.Types.ObjectId;
@modelOptions({ schemaOptions: { timestamps: true } })
class FooModel {
  @prop({ required: true, type: mongoose.Schema.Types.ObjectId })
  userId: ObjectId;
}
const FooModel = getModelForClass(FooModel);
// Now valid
FooModel.findOne({userId: new mongoose.Types.ObjectId('5e997f95d6a35f3a0def3339')})
```

**Comment by hasezoey** [comment]
>  I don't know if you want me to open a new issue for this, but the second problem persists.

this is because using `type` to mask the type, it will result at compile time to `Object` which will translate to `Mixed`, so you need to directly use the full length one (defining it as an value with something like `const` will result in an `value cannot be used as an type` error)

---

> Adding on to that, the following problem arises:

sorry my mistake forgot you can use(/ need to use) `mongoose.Types.ObjectId` (it will automatically translate for the schema to the appropriate type) the problem was using `type ObjectId =` (as described above)

**Comment by richardsimko** [comment]
Thanks for the info! I think the documentation on this is a bit lacking, I'll make a PR to improve it :)

**Comment by ChrisLahaye** [comment]
@hasezoey how to add a prop with value `object` / `any` without triggering this warning?

**Comment by hasezoey** [comment]
@ChrisLahaye https://github.com/typegoose/typegoose/issues/239#issuecomment-618567959

**Comment by ChrisLahaye** [comment]
@hasezoey it has type ObjectId not any

**Comment by hasezoey** [comment]
@ChrisLahaye please explain what you mean in your last comment, if you want to disable the warning then look at the link i provided with https://github.com/typegoose/typegoose/issues/239#issuecomment-618567959 (https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#allowmixed)

**Comment by ChrisLahaye** [comment]
@hasezoey I want to add a property with as type any. How to avoid the warning?

**Comment by hasezoey** [comment]
@ChrisLahaye like i said in earlier comments you need to set the warning level for this to `ALLOW` then it will not print any warning to the console or throw an error, look at the link provided for information on how to do it

**Comment by anuraghazra** [comment]
settings allowMixed solves the issue

```ts
import { Severity } from "@typegoose/typegoose";

@modelOptions({
  options: {
    allowMixed: Severity.ALLOW,
    customName: 'notification',
  },
})
```

**Comment by hasezoey** [comment]
@anuraghazra thats what stands in the documentation

**Comment by chaseadamsio** [comment]
Docs for model options look like they've [moved here](https://typegoose.github.io/typegoose/docs/api/decorators/model-options/).

**Comment by benediktdertinger** [comment]
@hasezoey how do I use a type that has not been defined by a class (without getting the ”Mixed...” notification)?
Or is it always recommended to use a class for generating the type when using with typegoose classes? 

```ts
export type LatLng = {
  lat: number;
  lng: number;
};

export class Session extends defaultClasses.TimeStamps {
  @prop()
  public userLocation?: LatLng;
}

**Comment by hasezoey** [comment]
@benediktdertinger it is always recommended to use classes wherever possible (to be validated by mongoose), otherwise for types that are generic / can be many things, it can be mixed - but the warning has to be turned off on an class-level 
https://typegoose.github.io/typegoose/docs/guides/error-warnings-details/#setting-mixed-is-not-allowed-e017

**Comment by benediktdertinger** [comment]
> @benediktdertinger it is always recommended to use classes wherever possible (to be validated by mongoose), otherwise for types that are generic / can be many things, it can be mixed - but the warning has to be turned off on an class-level
> https://typegoose.github.io/typegoose/docs/guides/error-warnings-details/#setting-mixed-is-not-allowed-e017

@hasezoey Thank you for clarifying! Have a good day.

**Comment by dedeard** [comment]
try this on your model's decorator:

```
@ModelOptions({
  options: {
    allowMixed: Severity.ALLOW,
  },
})
```

**Comment by alexa-slotrent** [comment]
@benediktdertinger https://stackdev.space/questions/exploring-the-concept-of-embedding-documents-in-mongoose-through-modeling
