### ISSUE TITLE
Is it possible to use getModelForClass with generics?

### ISSUE THREAD

**Issue by mouimet-infinisoft** [typegoose/typegoose#246]
Hi 
Is there a way to get a the model with a generic type like following?

```ts
export class GenericClass<T> {
    private readonly m: ModelType<T>;

    constructor() {        
        this.m = getModelForClass(T);
    }
}
```

**Comment by hasezoey** [comment]
i think mongoose dosnt support multiple types, so no, generic types are not supported when you want to save them to the database (or you set the type to `Mixed` which will have no validation)

**Comment by mouimet-infinisoft** [comment]
That is not what I meant. Would it be possible for the function getModelForClass() to resolve to the concrete class? Not save a generic in the database. Look at the following example:

Would it be possible somehow?

```
export class Main {

    public execute(){
        let dogService: GenericCRUDService<Dog> = new GenericCRUDService<Dog>();
        let catService: GenericCRUDService<Cat> = new GenericCRUDService<Cat>();

        dogService.create({isBarking: true, race: 'bulldog'});
        catService.create({ age: 10, color: 'black'});
        
    }
    
}

export class GenericCRUDService<T> {
    private readonly dataModel: ModelType<T>;

    constructor() {        
        this.dataModel = getModelForClass(T);
    }

    public create(data: T) {
        this.dataModel(data);
    }
}

export class Cat {
    public age: number;
    public color: string;
}

export class Dog {
    public isBarking: boolean;
    public race: string;
}
```

**Comment by hasezoey** [comment]
i think what you need are discriminators
[typegoose docs](https://typegoose.github.io/typegoose/docs/functions/getDiscriminatorModelForClass/)
[mongoose docs](https://mongoosejs.com/docs/discriminators.html)

**Comment by mouimet-infinisoft** [comment]
A discriminator is for a Model Class Hierarchy which is totally different from what I need.

**Comment by hasezoey** [comment]
@mouimet-infinisoft its not really different, just make one base class that all T classes inherit and make them discriminators, there is no other way (except making that path an `Mixed` which means no validation)

**Comment by ggurkal** [comment]
@mouimet-infinisoft Are you trying to encapsulate some logic (other than simple CRUD) in a service class?

**Comment by mouimet-infinisoft** [comment]
@ggurkal no! the goal is to have 1 generic CRUD Service pour all my Models and avoid having a CRUD service per model.

**Comment by ggurkal** [comment]
Don't you create CRUD service per model here in your example?

```ts
```

**Comment by mouimet-infinisoft** [comment]
@ggurkal true that, but I don't copy paste the same code on 2 concrete classes there is only one GenericService class and 2 instances. That's the point.

**Comment by ggurkal** [comment]
You need to pass the actual class to the constructor in order to get its model, so the following should do:

```ts
export class GenericCRUDService<T, U extends AnyParamConstructor<T> = AnyParamConstructor<T>> {
  private readonly dataModel: ReturnModelType<U, T>;

  constructor(cls: U) {
      this.dataModel = getModelForClass<T, U>(cls);
  }

  public create(data: T) {
      this.dataModel.create(data);
  }
}
```

Then you can use it as:
```ts
let dogService: GenericCRUDService<Dog> = new GenericCRUDService(Dog);
```

**Comment by hasezoey** [comment]
i think i misunderstood the situation, i thought `GenericCRUDService` was gonna be an typegoose class that has sub-documents in `dataModel`

thanks @ggurkal for helping :+1:

**Comment by mouimet-infinisoft** [comment]
@hasezoey @ggurkal Thanks alot for the great support! Much appreciated! :) You guys rock!

**Comment by hasezoey** [comment]
i think this issue is solved, closing it
