### ISSUE TITLE
mapProp together with Array?

### ISSUE THREAD

**Issue by asio1337** [typegoose/typegoose#256]
Hey, is there a way to use mapProp together with an Array of Primitives and same for subdocuments?

Example:
```js
genres: {
„de“: [„Klassik“, „Volksmusik “]
„en“:[„Classic“, „Folk Music“]
}
```

and

```ts
class Image {
  @prop({ required: true })
  public url!: string;

  @prop()
  public height?: number;

  @prop()
  public width?: number;
}
```
```js
images: {
„de“: [image-subdocument,image-subdocument]
„en“:[image-subdocument,image-subdocument]
}
```

Thanks for any help

## Versions

- typegoose: 7.0.0
- mongoose: 5.9.13

**Comment by hasezoey** [comment]
*next time please properly format your issue*

sorry, but i dont understand your question - what are you trying to achieve?

**Comment by asio1337** [comment]
I need a map which holds array's of strings.
I need this for a multilingual application.

The key of the map is an iso 639 string and the value is an array of strings.

like this but it doesn't work

```js
@mapProp({ of: String[] })
 public genres?: Map<string, string[]>;
```

Hope you understand what i mean.

**Comment by hasezoey** [comment]
@asio1337 
the only solutions are:
either defining an Array, which will have no validation:
```ts
class SomeClass {
  @mapProp({ of: Array })
  public genres?: Map<string, string[]>;
}
```
or to define an subdocument
```ts
// NodeJS: 12.16.3
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, mapProp, arrayProp } from "@typegoose/typegoose"; // @typegoose/typegoose@7.0.0
import * as mongoose from "mongoose"; // mongoose@5.9.13 @types/mongoose@5.7.16

class Nested {
  @arrayProp({ items: String, required: true })
  public genres!: string[];
}

class SomeClass {
  @mapProp({ of: Nested })
  public genres?: Map<string, Nested[]>;
}
const NestedModel = getModelForClass(Nested);
const SomeModel = getModelForClass(SomeClass);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify256", useCreateIndex: true, useUnifiedTopology: true });

  const doc = new SomeModel({ genres: { key1: { genres: ["some1", "some2"] } } });

  console.log(doc);

  await mongoose.disconnect();
})();
```
sorry, otherwise it is not possible in typegoose (i know its an valid case in mongoose, but not possible in typegoose)

**Comment by asio1337** [comment]
Thanks a lot!

I will try it out and give a feedback

But is the ' Nested[]' correct, because the subdocment already has an array?

**Comment by asio1337** [comment]
Works, thank you very much :)
Great work btw <3

**Comment by hasezoey** [comment]
> But is the ' Nested[]' correct, because the subdocment already has an array?

in typegoose you currently cant define an array in an map without an intermediate class, so this is correct

**Comment by asio1337** [comment]
Yes, you helped me much.
Is there maybe a plan in the future for something like Array<String> or Array<Nested> for validation?

**Comment by hasezoey** [comment]
@asio1337 with the current why how typescript handles reflection (`string[]` is at runtime `Array`), and how typegoose handles things, its not possible without adding further options

**Comment by asio1337** [comment]
thanks for everything, it works as intended, without validation but in my case this is not really important because the data types are always the same anyway and without other conditions.
