### ISSUE TITLE
Schema object configuration

### ISSUE THREAD

**Issue by rkgrep** [typegoose/typegoose#260]
Is there a way to implement simple object within schema?
```
{
   key: String,
   nested: {
      propA: Boolean,
      propB: Boolean
   }
}
```

Whenever I do it with classes, it produces a separate schema.
I found this issue in the [original repository](https://github.com/szokodiakos/typegoose/issues/54), but couldn't find any resolution.

I am migrating a huge project to typegoose and got seriously stuck with this. There is no way to refactor all models, so really need a way to do that, even if it would be "hacky"

**Comment by hasezoey** [comment]
without having the type be `mongoose.Schema.Types.Mixed`, no it is not possible to set an object without an extra class
