### ISSUE TITLE
typegoose automatically pick from type on select

### ISSUE THREAD

**Issue by wcjord** [typegoose/typegoose#262]
```ts
export class User {
  @prop()
  public username!: string;
  @prop()
  public email: string;
}

export const UserModel = getModelForClass(User);

UserModel.findById(userId).select("-username -_id").then((userJustName) => {
  const email = userJustName.email;
});

```
Desired behavior:
I'd like a TypeError on asking for userJustName.email. That is, I'd like typegoose to automatically use Omit/Pick to filter selected from User type.

Actual behavior:
The type of userJustName is Pick<DocumentType<User>, "_id" | "username" | "email" | "typegooseName">.

Is there way to do this already or is this a new feature request? Thank you!

## Versions
- typegoose: 7.0.0
- mongoose: 5.9.14

**Comment by hasezoey** [comment]
typescript cant filter out keys by an function parameter for an different thing, at least not that i know of

**Comment by wcjord** [comment]
Ok thank you for the quick reply!
