### ISSUE TITLE
Static properties are not available in the model

### ISSUE THREAD

**Issue by rubenvereecken** [typegoose/typegoose#263]
## Versions

- NodeJS: v12.x
- Typegoose(NPM): 7.0.0
- mongoose: 5.9.10

## What is the Problem?
While it seems I can happily access static methods, I can't figure out how to get access to static properties. I use them in a few cases. Is this by design, or am I missing something?

```ts
class UserSchema {
	public static readonly forbiddenProperties = new Set(['_id', 'publicId', 'pictures']);

	public static sanitize(this: ModelType<UserSchema> & typeof UserSchema, obj) {
                assert(forbiddenProperties) // <--- fails!
		return _.pickBy(obj, (v, k) => User.forbiddenProperties.has(k));
	}
}

export const User = getModelForClass(UserSchema);

User.sanitize({...}) // Fails because of above
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
static properties are unsupported, `schema.loadClass` dosnt load such things

**Comment by rubenvereecken** [comment]
Right. Ehm. Nothing to be done.
