### ISSUE TITLE
arrayProp of union type

### ISSUE THREAD

**Issue by autsada** [typegoose/typegoose#265]
I have this union type

`export type Role = 'CLIENT' | 'ITEMEDITOR' | 'ADMIN' | 'SUPERADMIN'`

And I want to make a User class that has a property named roles as an array of Role which I want to set the default value to ['CLIENT'], what should I specify as a value of items ? 

```
export class User {
  @arrayProp({ items: ???, default: ['CLIENT'] })
  public roles: Role[ ]
}
```
Thank you for your help.

## Versions

- typegoose: 7.0.0
- mongoose: 5.9.11

**Comment by hasezoey** [comment]
`items: String` should do it, but if you *only* want these string, i would recommend to use enums with the `enum` option

**Comment by autsada** [comment]
Thank you for your quick reply, I just took a look at the docs for enum option. Will try if it works.

**Comment by hasezoey** [comment]
it seems like the question is solved, closing

**Comment by autsada** [comment]
Thanks, now it works. Here is what I end up doing.

```
export enum RoleOptions {
  client = 'CLIENT',
  itemEditor = 'ITEMEDITOR',
  admin = 'ADMIN',
  superAdmin = 'SUPERADMIN',
}

export class User {
  @arrayProp({
    items: String,
    enum: RoleOptions,
    default: [RoleOptions.client],
  })
  public roles: RoleOptions[]
}
```
