### ISSUE TITLE
Where do I import @queryMethod from?

### ISSUE THREAD

**Issue by vrn-dev** [typegoose/typegoose#267]
I tried using `@queryMetod` decorator, but there are no valid options to import it from the typegoose library. Is it actually exported?

**Comment by ggurkal** [comment]
It's strange that it's not exported from `typegoose.ts` but it will be in the next release (7.1.0) as far as I see.

For the time being, you can import it as `import { queryMethod } from '@typegoose/typegoose/lib/queryMethod';`

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/changelog#710

i forgot to export from typegoose.ts, it will be exported in 7.1
in the meantime to following should work
```ts
import { queryMethod } from "@typegoose/typegoose/lib/queryMethod";
```
