### ISSUE TITLE
Can you use arrProp with Ref?

### ISSUE THREAD

**Issue by wcjord** [typegoose/typegoose#268]
```ts
import User from '.user.class'

export class Students {
  @arrProp({items: String, ref: User})
  public students!: Ref<User>[];
}
```
Is is something like that?

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/guides/advanced/reference-other-classes/#referencing-other-classes

**Comment by wcjord** [comment]
Ah ok - I saw that but wasn't sure if it applied to a document that you wanted to populate. I get it now - thanks
