### ISSUE TITLE
Documentation not properly indexed?

### ISSUE THREAD

**Issue by dandv** [typegoose/typegoose#272]
I'm searching for "validate" at https://typegoose.github.io/typegoose/ but it doesn't return the [validate heading](https://github.com/typegoose/typegoose/blob/master/github-page/_docs/decorators/prop.md#validate) from `props`.

![image](https://user-images.githubusercontent.com/33569/82136367-1d585800-97c2-11ea-8add-7a329d9276d1.png)

**Comment by hasezoey** [comment]
i dont know how this search thing is working

**Comment by hasezoey** [comment]
should be fixed by #273

**Comment by dandv** [comment]
Happy to test when it gets deployed.

**Comment by hasezoey** [comment]
this should work now since fd02c813405f52baf0108f49b8e07ea73c6ccb42
