### ISSUE TITLE
Move documentation to docusaurus

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#273]
Move all documentation to be built with https://docusaurus.io

**Comment by LORD-KAY** [comment]
i want to help with this one

**Comment by hasezoey** [comment]
since f4f9a1d16757deab507bd44edd5a14ee5aca217d the documentation is moved to docusaurus, now the only thing left is to wait for an response from https://docsearch.algolia.com

**Comment by hasezoey** [comment]
search should now work, added in fd02c813405f52baf0108f49b8e07ea73c6ccb42
