### ISSUE TITLE
Autopopulate with virtuals not working

### ISSUE THREAD

**Issue by Tobjoern** [typegoose/typegoose#274]
Versions

- NodeJS: 10.16.0
- Typegoose(NPM): 7.1.1
- mongoose: 5.9.14

## What is the Problem?
Autopopulate doesn't work with virtuals.

Autopopulate is a mongoose plugin, which automatically populates references. It works with 'normal' references, bug not with virtuals

## Code Example
https://github.com/Tobjoern/typegoose-virtual-autopop-bug

```ts
// autopopulate doesn't work
@prop({ ref: getName(ReferenceEntity), foreignField: 'productId', localField: 'productId', autopopulate: true })
planInfo!: Ref<ReferenceEntity>;

// autopopulate does work
@prop({ ref: getName(ReferenceEntity), autopopulate: true })
planInfo2!: Ref<ReferenceEntity>;
```

**Comment by hasezoey** [comment]
fixed by 799f0637e725e1d3f766dc682f8601b18f9c8057
