### ISSUE TITLE
Error in d.ts files, inspite of skipLibCheck with tsc

### ISSUE THREAD

**Issue by Tobjoern** [typegoose/typegoose#276]
I recently tried compiling a project with tsc, but I got a bunch of error messages, like
```
node_modules/@typegoose/typegoose/lib/typeguards.d.ts:2:49 - error TS1005: ';' expected.

2 import type { DocumentType, Ref, RefType } from './types';
```
This is weird, as ts-node works fine, and I was of the conception that ts-node uses tsc, but nevermind.

I tried to fix the issue by enabling 'skipLibCheck', and excluding 'node_modules' in my tsconfig.json, but nothing seems to work.

This could very well be a typescript related issue, but I'm sure someone else here has faced this problem before, so this could be of great help.

I have reproduced this problem [here](https://github.com/Tobjoern/typegoose-virtual-autopop-bug)

Thanks for your help.

## Versions

- typegoose: 7.1.3
- mongoose: 5.9.14

**Comment by hasezoey** [comment]
2 issues i see with your provided project:
- it dosnt have typescript as an devDependency, so it uses the global installation (not really an issue, just note that typegoose needs typescript 3.9+)
- the compile target is "es5", where as typegoose requires "es6"

this error seems like its related to an outdated typescript version (this error seems to be about the `type` in `import type`, which was added in typescript 3.8)

**Comment by Tobjoern** [comment]
Thank you! Installing ts and changing the target to es6 fixed it, I completely missed those.
