### ISSUE TITLE
findOne $or typescript demands all possible object attributes

### ISSUE THREAD

**Issue by johndcarmichael** [typegoose/typegoose#277]
## Versions

- typegoose: 7.1.3
- mongoose: latest

## Question

I have a simple document
```
import { getModelForClass, modelOptions, prop } from '@typegoose/typegoose';
import { v1 } from 'uuid';

export class ChannelSubscription {
  @prop({ required: true, index: true })
  slug: string;

  @prop({ required: true, enum: SubscriptionStatus })
  subscriptionStatus: string;

  @prop({ required: true, default: false })
  canAdd: boolean;
}

@modelOptions({
  schemaOptions: {
    collection: 'userSubscriptions',
    timestamps: true,
  },
})

export class UserSubscriptions {
  @prop({ default: v1 })
  _id: string;

  @prop({ required: true, unique: true })
  username: string;

  @prop({ required: true, items: ChannelSubscription, default: [] })
  channels: ChannelSubscription[];
}

export const UserSubscriptionsModel = getModelForClass(UserSubscriptions);
```

I have a simple repository class:
```
import { ReturnModelType } from '@typegoose/typegoose';
import {
  ChannelSubscription,
  UserSubscriptions,
  UserSubscriptionsModel
} from './models/UserSubscriptionsModel';
import RabbitMQService from '@/events/rabbitMQ/RabbitMQService';

class UserSubscriptionsRepository {
  public model: ReturnModelType<typeof UserSubscriptions>;

  constructor () {
    this.model = UserSubscriptionsModel;
  }

  userIsMemberOfChannel (username: string, channelSlug: string) {
    return this.model.findOne({
      username,
      $or: [{
        channels: {
          slug: channelSlug,
          subscriptionStatus: 'Invited',
        },
      }, {
        channels: {
          slug: channelSlug,
          subscriptionStatus: 'JoinRequestAccepted'
        },
      }]
    });
  }
}
```

But "userIsMemberOfChannel" complains as the "canAdd" attribute is missing from the query object... but I don't care about the value of the canAdd attribute.. 

Have I missed something in the setup, I can also not find anything in the docs on this either...

**Comment by LORD-KAY** [comment]
have you tried making that particular field optional in typescript's perspective 
`canAdd?: boolean` 
so the canAdd can be optional

**Comment by johndcarmichael** [comment]
Yea, but that is only a work-around to the problem..

**Comment by hasezoey** [comment]
@johndcarmichael sorry, there isnt any fix for this, only workarounds, like casting the whole query as `any` or making error-ing properties optional or `ts-ignoring` it

**Comment by smolinari** [comment]
For my curiosity, what is the actual error?

Scott

**Comment by Acrontum-Carmichael** [comment]
Just the usual typescript error of missing attributes.

For data entry this error makes perfect sense. But for searching to me it makes not much sense specially in the NoSQL world where you are likely to have older documents of varying structure.

![Screenshot from 2020-06-03 18-17-35](https://user-images.githubusercontent.com/16192806/83661616-a810c380-a5c6-11ea-9cbc-0e437d8cd9a5.png)

I another query however when using the aggregate mongodb function there are no type errors:
```
await this.model.aggregate([
      {
        $match: {
          username: username,
        },
      },
      {
        $project: {
          'channels': {
            $filter: {
              input: '$channels',
              as: 'channel',
              cond: {
                $in: ['$$channel.subscriptionStatus', [
                  SubscriptionStatus.InviteAccepted,
                  SubscriptionStatus.JoinRequestAccepted
                ]],
              },
            },
          },
        },
      },
    ])
```

**Comment by johndcarmichael** [comment]
Just the usual typescript error of missing attributes.

For data entry this error makes perfect sense. But for searching to me it makes not much sense specially in the NoSQL world where you are likely to have older documents of varying structure.

My my team though we use tslint and don't permit tsignore as this typically results in nasty bugs that are horrible to find @hasezoey 

![Screenshot from 2020-06-03 18-17-35](https://user-images.githubusercontent.com/16192806/83661616-a810c380-a5c6-11ea-9cbc-0e437d8cd9a5.png)

I another query however when using the aggregate mongodb function there are no type errors:
```
await this.model.aggregate([
      {
        $match: {
          username: username,
        },
      },
      {
        $project: {
          'channels': {
            $filter: {
              input: '$channels',
              as: 'channel',
              cond: {
                $in: ['$$channel.subscriptionStatus', [
                  SubscriptionStatus.InviteAccepted,
                  SubscriptionStatus.JoinRequestAccepted
                ]],
              },
            },
          },
        },
      },
    ])
```

**Comment by ggurkal** [comment]
@johndcarmichael If you're not using any plugin/middleware for your queries, this is the expected behaviour since `canAdd` is a required field. Apart from the error, you won't be able to retrieve any data from mongodb, since it requires an exact match as stated here: https://docs.mongodb.com/manual/tutorial/query-array-of-documents/#query-for-a-document-nested-in-an-array

You can revisit your query with dot notation like
```
...
$or: [
  {
    ...
    'channels.subscriptionStatus': 'Invited'
  },
  {
    ...
    'channels.subscriptionStatus': 'JoinRequestAccepted'
  }
]
...
```

If you do use a plugin/middleware, then I'm afraid you need to define your own filter type.

**Comment by smolinari** [comment]
So, it is a Mongoose/ MongoDB issue? @ggurkal 

Scott

**Comment by johndcarmichael** [comment]
@smolinari  yes i think @ggurkal is completely right! Thank you!

**Comment by smolinari** [comment]
Awesome. I'm relatively new to all this and wanted to mention it sounds like something coming from Mongoose/MongoDB and not TypeScript. But, I was uncertain. Good to know I was on the right track.

Scott
