### ISSUE TITLE
Using transactions

### ISSUE THREAD

**Issue by dandv** [typegoose/typegoose#279]
I'm trying to use [transactions](https://mongoosejs.com/docs/transactions.html). Are they supported?

`MyModel.startSession` says

> TS2339: Property 'startSession' does not exist on type 'ReturnModelType '.

## Versions

- typegoose: 7
- mongoose: 5.9.16

**Comment by smolinari** [comment]
@dandv - Isn't it `MyModel.db.startSession` or rather the startSession method is on the db object?

Scott

**Comment by hasezoey** [comment]
@dandv could you list an full code example of how you want to use transactions? (and where the error happens?)

**Comment by ChrisLahaye** [comment]
@dandv startSession needs to be called on a mongoose connection as suggested by @smolinari  and not on a model.

I use the following helper which also allows nesting / using existing transactions:
```ts
/**
 * Start a session and use withTransaction.
 */
export const withTransaction = async function withTransaction(
  fn: (session: mongoose.ClientSession) => Promise<any>,
  existingSession?: mongoose.ClientSession,
): Promise<void> {
  if (existingSession) {
    if (existingSession.inTransaction()) return fn(existingSession);

    return existingSession.withTransaction(fn);
  }

  const session = await mongoose.startSession();

  try {
    await session.withTransaction(fn);
  } finally { session.endSession(); }
};
```

**Comment by LucienLee** [comment]
What if I use mongoose with the dependency injection pattern? 
Your example assumes that mongoose is initiated at global.

**Comment by ChrisLahaye** [comment]
> What if I use mongoose with the dependency injection pattern?
> Your example assumes that mongoose is initiated at global.

You are right, I assume the mongoose default export (the default connection) imported as mongoose. However, you can just add an extra parameter called mongoose with as type I believe mongoose.Connection.

**Comment by hasezoey** [comment]
closing because this dosnt seem like it is an problem with typegoose and because the issue is stale

**Comment by wellmmer** [comment]
> @dandv startSession needs to be called on a mongoose connection as suggested by @smolinari and not on a model.
> 
> I use the following helper which also allows nesting / using existing transactions:
> 
> ```ts
> /**
>  * Start a session and use withTransaction.
>  */
> export const withTransaction = async function withTransaction(
>   fn: (session: mongoose.ClientSession) => Promise<any>,
>   existingSession?: mongoose.ClientSession,
> ): Promise<void> {
>   if (existingSession) {
>     if (existingSession.inTransaction()) return fn(existingSession);
> 
>     return existingSession.withTransaction(fn);
>   }
> 
>   const session = await mongoose.startSession();
> 
>   try {
>     await session.withTransaction(fn);
>   } finally { session.endSession(); }
> };
> ```

Could you please make this example more clear? How do you use it?

**Comment by ChrisLahaye** [comment]
The `withTransaction` function on a mongoose session receives a (retry-able) function that is executed as part of the transaction. This means that queries part of this transaction, i.e. they are using this mongoose session, will either:
a) commit all together successfully, or
b) not commit at all in the case where one of the queries failed.

You can see examples at https://mongoosejs.com/docs/transactions.html. Note that the (retry-able) function, the first parameter of `Session.withTransaction` is actually called with the session as argument. This is not clear in the example because they are explicitly creating the session before calling `Session.withTransaction`, so it does not make sense to read the same session from the first argument.

The `withTransaction` function that I shared takes care of two additional things:
1. It creates the session for you and then calls `withTransaction` on the created session.
2. It allows you to nest `withTransasction` calls by reusing sessions.

See the following example:
```ts
function workA(existingSession?: mongoose.Session) {
  withTransaction(async (session) => {
    await SomeModel.updateOne(someQuery1, someUpdate1, { session });
    await SomeOtherModel.updateOne(someOtherQuery1, someOtherUpdate1, { session });
  }, existingSession);
}

function workB(existingSession?: mongoose.Session) {
  withTransaction(async (session) => {
    await SomeModel.updateOne(someQuery2, someUpdate2, { session });
    await SomeOtherModel.updateOne(someOtherQuery2, someOtherUpdate2, { session });
  }, existingSession);
}

workA(); // transaction 1
workB(); // transaction 2
```
`workA` and `workB` will create a session as no existing session is given. 

You can also do the following:
```ts
function workNested() {
  withTransaction(async (session) => {
    await workA(session);
    await workB(session);
  });
}

workNested(); // single transaction containing workA and workB
```
`workA` and `workB` will now be part of the same transaction while still having the ability to call them separately.

**Comment by charlietyn** [comment]
> @dandv startSession needs to be called on a mongoose connection as suggested by @smolinari and not on a model.
> 
> I use the following helper which also allows nesting / using existing transactions:
> 
> ```ts
> /**
>  * Start a session and use withTransaction.
>  */
> export const withTransaction = async function withTransaction(
>   fn: (session: mongoose.ClientSession) => Promise<any>,
>   existingSession?: mongoose.ClientSession,
> ): Promise<void> {
>   if (existingSession) {
>     if (existingSession.inTransaction()) return fn(existingSession);
> 
>     return existingSession.withTransaction(fn);
>   }
> 
>   const session = await mongoose.startSession();
> 
>   try {
>     await session.withTransaction(fn);
>   } finally { session.endSession(); }
> };
> ```


Hi i need some help with that can ypu share your code with nestjs please , thank you in advance

**Comment by thomas88** [comment]
I'm using a modified version of @ChrisLahaye's `withTransaction` helper that uses the `Connection#transaction()` function of Mongoose, which handles resetting document state in the event of a failed transaction.

See https://thecodebarbarian.com/whats-new-in-mongoose-5-10-improved-transactions.html for an explanation.

```typescript
export async function withTransaction(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  fn: (session: mongoose.ClientSession) => Promise<any>,
  existingSession?: mongoose.ClientSession
): Promise<void> {
  if (existingSession) {
    if (existingSession.inTransaction()) return fn(existingSession);

    return mongoose.connection.transaction(fn);
  }

  const session = await mongoose.startSession();
  try {
    await mongoose.connection.transaction(fn);
  } finally {
    session.endSession();
  }
}

```

I've also written unit test for the helper: https://gist.github.com/thomas88/ce2aede67a25a40be32b7a8ae9df7a0b.

**Comment by alimoli** [comment]
Why isn't possible to call `Model.create(doc)` with SaveOptions `{session}`?
I mean, it is possible only with an array of documents, but not with a single one.

```ts
 create(docs: (AnyKeys<T> | AnyObject)[], options?: SaveOptions): Promise<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>[]>;
    create(docs: (AnyKeys<T> | AnyObject)[], callback: Callback<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>[]>): void;
    create(doc: AnyKeys<T> | AnyObject): Promise<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>>;
    create(doc: AnyKeys<T> | AnyObject, callback: Callback<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>>): void;
    create<DocContents = AnyKeys<T>>(docs: DocContents[], options?: SaveOptions): Promise<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>[]>;
    create<DocContents = AnyKeys<T>>(docs: DocContents[], callback: Callback<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>[]>): void;
    create<DocContents = AnyKeys<T>>(doc: DocContents): Promise<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>>;
    create<DocContents = AnyKeys<T>>(...docs: DocContents[]): Promise<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>[]>;
    create<DocContents = AnyKeys<T>>(doc: DocContents, callback: Callback<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>>): void;
```

**Comment by hasezoey** [comment]
@alimoli if it is available when arrays are passed but not single one, then this is probably a mistake on mongoose's side, please open a issue there

but i think `$session` would be correct (though note that i ever use sessions like that before)
