### ISSUE TITLE
GitHub discussions?

### ISSUE THREAD

**Issue by dandv** [typegoose/typegoose#281]
Hi and thanks again for all the work on this library!

Would it be a good idea to enable the Discussions feature for this repo on GitHub? I'm thinking that new users search here when they have issues, and that might help prevent asking the same questions on Discord, which is not that searchable (not indexed by Google, doesn't include the codebase etc.).

I'm suggesting this based on the good experience with [Discussions since RHF enabled it](https://github.com/react-hook-form/react-hook-form/discussions), and many conversations from Spectrum moved within the project, under Discussions.

**Comment by hasezoey** [comment]
this is an pretty new feature that i didnt know about, but currently it cant be enabled by any repository,
quote: (from [here](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/))
> We are in beta with a few open source communities and will be making Discussions available to other projects soon.

i will enable this as soon as they make it public and i get reminded about it

**Comment by hasezoey** [comment]
github discussions are now available to be used
https://github.com/typegoose/typegoose/discussions
