### ISSUE TITLE
Cannot make subdocuments/embedded schema work in latest version

### ISSUE THREAD

**Issue by akash-rajput** [typegoose/typegoose#289]
## Versions

- NodeJS: 10.15.1
- Typegoose(NPM): 7.2.0
- Typegoose(GIT): NA
- mongoose: 5.19.11
- mongodb: 4.2.3
- grahpql / type-graphql: graphql@14.6.0 / type-graphql@0.17.6

```ts
@GqlType()
export class GeoPlan implements IGeoPlan {
  @GqlField(_type => String)
  readonly _id: ObjectId;

  @GqlField()
  @Property({ required: true })
  name: string;

  @GqlField(_type => LatLng)
  @Property({ required: true, type: mongoose.Types.Subdocument })
  rawPoint: LatLng;
}
```

While inserting rawPoint it discards the `lat` & `lng` fields & inserts `_id` as if it is a `ref`?

**Comment by hasezoey** [comment]
in this case, the `type` option needs to be either not provided or be `type: LatLng`

this way, you are overwriting `LatLng` with `mongoose.Types.Subdocument`

**Comment by akash-rajput** [comment]
Same result @hasezoey

**Comment by akash-rajput** [comment]
Happens with `new Model(data)`

**Comment by akash-rajput** [comment]
Resolved lat long were missing prop() on attributes in older versions this was not needed

**Comment by hasezoey** [comment]
> in older versions this was not needed

it is required, since at least 5.x
