### ISSUE TITLE
Since @arrayProp is deprecated better to add an example 

### ISSUE THREAD

**Issue by iamchathu** [typegoose/typegoose#293]
Since `@arrayProp` and items are deprecated it will be good if we can have an example how to migrate to `@prop`

**Comment by hasezoey** [comment]
the docs still need to be updated, but as the messages say, just replace `arrayProp` with just `prop`, it still needs `items` (/`type`), and the correct Typescript-type (`public something: type`)

**Comment by iamchathu** [comment]
I got issue `CastError: Cast to string failed for value "[]" at path "banners"`

Old version
```ts
 @arrayProp({ items: String, default: [] })
```

New version
```ts
@prop({ type: String, default: [] })
```

**Comment by hasezoey** [comment]
@iamchathu this warning & error only comes when using an version before 7.2.0, because before then, `arrayProp` & `mapProp` & `prop` were not interchangeable, so try to upgrade your typegoose version
