### ISSUE TITLE
Unable to populate refPath which is inside an object;

### ISSUE THREAD

**Issue by tar-aldev** [typegoose/typegoose#294]
## Versions

- NodeJS: 14.0.0
- Typegoose(NPM): ^6.5.0 
- Typegoose(GIT): commithash
- mongoose: ^5.9.14
- mongodb: 0.0.0

## What is the Problem?
It looks like I cannot populate document by `refPath` which is inside an object.
I am not sure what is wrong here. Feel free to ask for more details.
## Code Example
**Models** are like this:
```ts
export class Owner {
  // I also tried typescript enum with no luck
  @prop({
    required: true,
    enum: ['School', 'Center', 'User'] 
  })
  onModel: string;

  @prop({ required: true, refPath: 'onModel' })
  ownerId: Ref<User | School | Center>;

  @prop({ required: true })
  ownerType: OwnerType;
}

@modelOptions({
  schemaOptions: {
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
  }
})
export class Curriculum {
  @prop({ required: true })
  _id: Types.ObjectId;
  @prop({ required: true, _id: false })
  owner: Owner; // this is a plain object which contains _refPath_
  @arrayProp({
    ref: 'EfacitySession',
    localField: '_id',
    foreignField: 'curriculum'
  })
  sessions?: Ref<EfacitySession>[];
  //...other non related stuff
}

// What I am trying to do:
    this.curriculumModel.findById(curriculumId).populate({
      path: 'owner.ownerId' // No luck, this doesn't populate it by refPath
    })
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
maybe try to upgrade your versions, mainly `mongoose` and `typegoose`

**Comment by tar-aldev** [comment]
```
Yes, sorry, I just missed this in example. We have await in our code. Will try to upgrade versions.
this.curriculumModel.findById(curriculumId).populate({
      path: 'owner.ownerId' // No luck, this doesn't populate it by refPath
    })
```

**Comment by tar-aldev** [comment]
The models left the same. Updated typegoose to `7.1.3` and mongoose to `^5.9.17`.
Still have no luck
I tried
```
this.curriculumModel.findById(curriculumId).populate({
      path: 'owner.ownerId',
      model: 'onModel'
});
```
With no luck as well. Howver, if I statically do it like this
```
this.curriculumModel.findById(curriculumId).populate({
      path: 'owner.ownerId',
      model: 'School' // NOTICE exact model name
});
```
It is able to populate. Any ideas what's going wrong?

**Comment by hasezoey** [comment]
@tar-aldev could you explain why the following should work?
```ts
this.curriculumModel.findById(curriculumId).populate({
      path: 'owner.ownerId',
      model: 'onModel'
});
```

because i dont see any model that is named `onModel`

and like i said, did you already try adding `.exec()` to the end of the query?

**Comment by tar-aldev** [comment]
Yes, It didn't help unfortunately. We decided to create three fields for now... Not good but too much time was spent on this.
```
this.curriculumModel.findById(curriculumId).populate({
      path: 'owner.ownerId',
      model: 'onModel'
});
```
Yes maybe you are right. But doing it with just 
```
this.curriculumModel.findById(curriculumId).populate({
      path: 'owner.ownerId',
});
```
didn't work at all... only when exact model is specified it is working. But that's breaks the entire idea of refPath.

**Comment by hasezoey** [comment]
did you already try `.populate("owner.ownerId")`? (this shouldnt actually matter)
and was already tried to set `refPath` to `owner.onModel`?

**Comment by jannomeister** [comment]
Im also experiencing this issue, it seems like the `Ref` class together with `refPath` isn't populating the data :(

**Comment by hasezoey** [comment]
@jannomeister if you have this issue, please open an new issue, fill out the template, and maybe reference this issue
