### ISSUE TITLE
stupid question: what type should we assign for the autogenerated ObjectId?

### ISSUE THREAD

**Issue by sebastiangug** [typegoose/typegoose#296]
I've been defining some of them as: 
```
    @prop({ auto: true })
    _id?: mongoose.Schema.Types.ObjectId;
```

But it eventually started to cause issues when making references to it and treating it as string in my app.

Does it make any difference if I just define it as as tring as opposed to the ObjectId type?

Thanks!

**Comment by sebastiangug** [comment]
I've also thought of using it like this instead of string throughout my app: 

``` import * as mongoose from "mongoose";
export type ObjectId = mongoose.Schema.Types.ObjectId;
 ``` and then defining types as that ObjectId -- but again, have no idea what difference it makes if anything at all

**Comment by hasezoey** [comment]
the correct type for an working `_id` definition is `mongoose.Types.ObjectId`, it will automatically be translated to `mongoose.Schema.Types.ObjectId` for the schema, and the correct type for typescript

**Comment by sebastiangug** [comment]
@hasezoey sadly usinvg mongoose.Types.ObjectId part of a dynamic package has resulted in compilation errors within those apps themselves. But going via Schema.Types.ObjectId seems to work. 

Won't however the value be essentially a string when formatting to json?

Thanks!

**Comment by hasezoey** [comment]
@sebastiangug when calling `toJSON` everything within will be transformed to an POJO, so yes, and ObjectId will be made to an string, but storing it in the db it is an `ObjectId`

**Comment by sebastiangug** [comment]
Hmm, but if I use the type mentioned, I'll be getting this error when using the exported package: 

```
12:57:36 - Found 0 errors. Watching for file changes.
mind-the-backend\server\node_modules\entities\lib\models\company.model.js:75
        __metadata("design:type", mongoose.Types.ObjectId)
                                                 ^

TypeError: Cannot read property 'ObjectId' of undefined
 mind-the-backend\server\node_modules\entities\lib\models\company.model.js:75:50
```

with versions: 

```
  "@typegoose/typegoose": "^7.1.3",
        "@types/mongoose": "^5.7.21",
        "mongoose": "^5.9.16",
     "typescript": "^3.9.3"
``` 

Is this not normal?

**Comment by hasezoey** [comment]
@sebastiangug do you want to use the same class for front-end and back-end? when yes, on which is it failing?

**Comment by sebastiangug** [comment]
@hasezoey yes -- the backend one is failing at compile time of the node app that's using it

**Comment by sebastiangug** [comment]
However if I use the mongoose.Schema.Types.ObjectId, it works and this is what gets saved to the db: 

![image](https://user-images.githubusercontent.com/27768313/84896858-99351100-b09c-11ea-997d-ad8a2937f8d5.png)

**Comment by hasezoey** [comment]
you said something about "dynamic package" could you explain a bit more? maybe if you cant import everything, try `import { Types } from "mongoose"; Types.ObjectId`

**Comment by sebastiangug** [comment]
[entities-bug.zip](https://github.com/typegoose/typegoose/files/4792436/entities-bug.zip)

I've attached a toned down version of the whole package

I will also try your latest suggestion, thanks again!

**Comment by sebastiangug** [comment]
Your suggestion seems to work & is producing the same object ID's inside mongodb! Thanks a bunch! I'll keep that in mind in the future

**Comment by hasezoey** [comment]
might be related to your "dynamic package" or `esModuleInterop` being `true`

**Comment by sebastiangug** [comment]
@hasezoey sadly came to find out later that this will cause the saving of documents to just fail silently.

it seems that if you import { Types } from "mongoose" to use with _id, it will let you be but when you try to save the document, it will result in unhandled exception due to not having an _id. 

If you import { Schema } and do the same, same result. 

If you import * as mongoose and use mongoose.Types.ObjectId -- I'll get

```
TypeError: Cannot read property 'ObjectId' of undefined
```

It seems the only thing working is: 

import * as mongoose from "mongoose" and using

_id: mongoose.Schema.Types.ObjectId.

**Comment by sebastiangug** [comment]
So ehrm, why is using mongoose.Schema.Types.ObjectId wrong as to me it seems to be the only thing that works at all -- weird.

**Comment by hasezoey** [comment]
`mongoose.Schema.Types.ObjectId` will get you an `SchemaType` if you try to use it like `new mongoose.Schema.Types.ObjectId()` and the the type is incompatible with the actual ObjectId Type

> it seems that if you import { Types } from "mongoose" to use with _id, it will let you be but when you try to save the document, it will result in unhandled exception due to not having an _id.

you have added an `@prop` to the `_id`, right? if this should be an ObjectId, and auto-generated, dont add an decorator

**Comment by amkazan** [comment]
also i had: 
TypeError: Cannot read property 'ObjectId' of undefined
for this: `mongoose.Types.ObjectId`

Changed this to this:

```
// import * as mongoose from 'mongoose';
import mongoose from 'mongoose';
```
