### ISSUE TITLE
stupid question 2: get key types of nested object in mongoose, not ref/subcollections

### ISSUE THREAD

**Issue by sebastiangug** [typegoose/typegoose#297]
Take this example: 
```ts
@prop({ default: {}, _id: false })
openid: OpenId;
```
where OpenId is another class like this: 

```ts
export class OpenId {
    @prop({ index: true, sparse: true, unique: true })
    google?: string;

    @prop({ index: true, sparse: true, unique: true })
    microsoft?: string;

    @prop({ index: true, sparse: true, unique: true })
    apple?: string;
}
```

But then when for example when trying to update an object with mongoose saying: 

```ts
 manager.findByIdAndUpdate(_id, {
    openid.google: "something"
});
```

will throw an error as it doesn't tell you what keys you have on the "openid" object. 

Is it possible to get the types right there without having to work with populating refs/subcollections? 

I have worked in the past with proper subcollections & refs and that's fine for that use case, but sometimes you just need a plain nested object. 

Is this supposed to work or am I just doing things wrong?

**Comment by smolinari** [comment]
For my curiosity, could you offer the actual error message?

Scott

**Comment by hasezoey** [comment]
if you use something like `prop.subprop: something` this will not have any types, you would need to do 
```ts
{
  openid: {
    google: "something"
  }
}
```
to have some types, and from what i know there cannot be done much about it

**Comment by sebastiangug** [comment]
@smolinari 
![image](https://user-images.githubusercontent.com/27768313/85586134-8e4c2480-b638-11ea-8cb3-ec666f07e7ba.png)

@hasezoey  won't that ditch other properties that exist on that nested object? judging by the syntax I'd think that query will overwrite the whole openid object. 

My current workaround is to modify the object locally and then update it as a whole, but I thought its still worth investigating if there's better ways. 

Thanks!

**Comment by hasezoey** [comment]
> won't that ditch other properties that exist on that nested object?

probably yes, but when doing it "the dottet way", you wont have typing support

**Comment by andreialecu** [comment]
@sebastiangug take a look at https://docs.mongodb.com/manual/reference/operator/update/set/#set-fields-in-embedded-documents

This will leave other fields alone:
```ts
manager.findByIdAndUpdate(_id, {
	$set: { "openid.google": "something" }
});
```

**Comment by hasezoey** [comment]
@andreialecu thanks, but i think this issue is about "types for property access with `.`"

**Comment by andreialecu** [comment]
I was replying to this part:

> @hasezoey won't that ditch other properties that exist on that nested object? judging by the syntax I'd think that query will overwrite the whole openid object.

> if I do it using your syntax I do indeed get the subproperties, its just mainly my concern above on the overwriting that's preventing me from doing it like that

> My current workaround is to modify the object locally and then update it as a whole, but I thought its still worth investigating if there's better ways.

It's unnecessary to modify it locally, I provided an alternative.

Also the syntax in the original post was invalid JS or TS:

```
manager.findByIdAndUpdate(_id, {
    openid.google: "something"
});
```

So I believe the question was more of a JS/mongo question than a Typegoose one.

**Comment by hasezoey** [comment]
closing because this question seems to be answered
