### ISSUE TITLE
Refactor parameters for `prop` decorator

### ISSUE THREAD

**Issue by andreialecu** [typegoose/typegoose#299]
## Describe what you need | want

There's a common pattern for specifying types using deferred functions, like:

```ts
type => Cat
// or for typegoose:
@prop({ type: ObjectId, ref: of => Cat })

// additionally, it might make sense to allow a deferred func as the first parameter for prop directly (without going through the object via { type: of => Cat }:
@prop(type => Cat)

// maybe deprecate `type` within the options object
@prop({ /* deprecated */ type: ... })
```

For example both NestJS and TypeORM use this pattern:
https://docs.nestjs.com/graphql/resolvers
https://typeorm.io/#/one-to-one-relations

## Do you have already an idea for the implementation?

*yes*

DeferredFunc can be replaced with:

```ts
export declare type DeferredFunc<T = any> = (of?: any) => T;
```

And the prop decorator could have several overloads to allow `DeferredFunc` as the first parameter. See https://github.com/nestjs/graphql/blob/master/lib/decorators/field.decorator.ts#L42-L65 for inspiration.

**Comment by hasezoey** [comment]
> // maybe deprecate `type` within the options object

i would be against this one

otherwise it might be better to use that patter

**Comment by andreialecu** [comment]
It's hard to keep a consistent style if `type` is not deprecated/still recommended.

By deprecated, I mean that it can be kept (for backward compatibility), just recommended against being used by new users.

```ts
@prop({ type: type => Cat }) // this is confusing
```

**Comment by hasezoey** [comment]
`type: () => Class` would still be allowed, and will not be changed

**Comment by hasezoey** [comment]
does this pattern have an name?

**Comment by andreialecu** [comment]
I guess it could be called a forward declaration: https://en.wikipedia.org/wiki/Forward_declaration

In Angular `forwardRef` does something similar: https://angular.io/api/core/forwardRef

**Comment by hasezoey** [comment]
i meant to have an `type => any` and not the whole function

**Comment by andreialecu** [comment]
No special name for it, but both could be referred to as `type functions`.

**Comment by hasezoey** [comment]
`@prop(type => any)` could *not* be implemented, because without an `ref` it would still error out if used like:
```ts
class First {
  @prop(type => Second) // it also errors when using `{ type: () => Second }`
  public reference?: Second;
}

class Second {
  @prop()
  public dummy?: string;
}
```

it errors thanks to how typescript compiles decorators and classes

here what it compiles to:
```ts
let First = /** @class */ (() => {
        class First {
        }
        tslib_1.__decorate([
            typegoose_1.prop(type => Second) // it also errors when using `{ type: () => Second }`
            ,
            tslib_1.__metadata("design:type", Second) // the error happens here
        ], First.prototype, "reference", void 0);
        return First;
    })();
    let Second = /** @class */ (() => {
        class Second {
        }
        tslib_1.__decorate([
            typegoose_1.prop(),
            tslib_1.__metadata("design:type", String)
        ], Second.prototype, "dummy", void 0);
        return Second;
    })();
```

so the only use case would have been if the class was defined before, or in another file
