### ISSUE TITLE
Reflect on the documentation that @arrayProp is deprecated

### ISSUE THREAD

**Issue by cerino-ligutom** [typegoose/typegoose#301]
Was reading the [decorators](https://typegoose.github.io/typegoose/guides/decorators/) section in the documentation and found `@arrayProp` described as:

![image](https://user-images.githubusercontent.com/6721822/85449949-e0eef780-b5ca-11ea-8e1d-8e966a226943.png)

However, intellisense mentions this is deprecated:

![image](https://user-images.githubusercontent.com/6721822/85450049-f6fcb800-b5ca-11ea-84ff-89924be6209d.png)

I think the documentation should warn us about this and encourage to use `@prop` ahead.

**Comment by hasezoey** [comment]
it is mentioned, just not on the site where all existing decorators are mentioned

but i guess this doc-site needs an update as well (like it dosnt even mention `@queryMethod`)
