### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by DoubleHub** [typegoose/typegoose#302]
I can only install up to 5.9.1, but that version doesn't include many things that I want. Any eta for version 7.2.0 on NPM? Thanks in advance

**Comment by hasezoey** [comment]
all versions from 6.0+ are on npm, you probably tried to use `typegoose`, which is the old repo/package, use `@typegoose/typegoose`

**Comment by DoubleHub** [comment]
Thank you! Such a silly mistake ^^
