### ISSUE TITLE
No documentation related to adding instanceMethods and staticMethods

### ISSUE THREAD

**Issue by andrico1234** [typegoose/typegoose#304]
Hi crew,

We've just started migrating our Mongoose models over to Typegoose.

I just wanted to share my experiences with migrating one of our models, since I stumbled across a few gotchas. These could have been easily avoided through more comprehensive documentation. 

The quickstart guide was really helpful in getting me creating a very simple model. Unless I'm wrong, there doesn't seem to be any mention of adding instance methods and static methods to the class. What's amazing about the library is that it's  intelligent enough to distinguish between the two without any need for a decorator. However, this isn't made clear in the documentation, and I only discovered this through rummaging through old changelogs. 

After doing some digging, it was apparent that versions of typegoose prior to 6.1.0 had these decorators but were ultimately removed due to the reasons mentioned above. It would be super useful to just have an extended example, or even just a note to say that there's no additional work needed in creating static and instant methods. 

If I've been silly and missed something in the documentation, then i'll close this issue. If you feel that this is worthy of adding, then I'll be happy opening up a pull request with some changes in the docs. 

Thanks for your time, and thanks for maintaining this repo.

**Comment by hasezoey** [comment]
yes you are right, there is no mention currently of how to make instance & static classes, the decorators for it got removed in 6.0.0(pre) and since then didnt make it into the documentation examples

-> i think adding an example for static & instance methods to the quick-start-guide would be enough (because they are like normal js class methods)

**Comment by hasezoey** [comment]
i think the examples and mentions added in 46dc6d0e9dfd85b9313648545c8cebb5425e5d15 should be enough
