### ISSUE TITLE
Alias with embedded documents

### ISSUE THREAD

**Issue by paul590** [typegoose/typegoose#305]
Hello Typegoose team, 

I had a question regarding Aliases. Is it possible to do an alias on a a variable inside an embedded object? I understand I can do a virtual get to achieve this as well. For example something along the lines as follows?:

```ts
export class Embedded {
   @prop({nullable: false}, alias: "Parent.testName")
   name: string; // Variable I want to get
}

export class Parent {
   @prop({nullable: false})
   ObjectWithName: Embedded; 

   testName: string
}
```

Thank you for your help!

**Comment by hasezoey** [comment]
sorry, i dont think this is possible, [here is the documentation](https://typegoose.github.io/typegoose/docs/decorators/prop/#alias) of how to use the mongoose provided alias
