### ISSUE TITLE
Documentation not clear about the use of class and objects

### ISSUE THREAD

**Issue by billouboq** [typegoose/typegoose#309]
Hi,

I'm using typegoose and I have hard time understanding how to use simple class.

First readme show this exemple :

```js
class Job {
  @prop()
  public title?: string;

  @prop()
  public position?: string;
}

class Car {
  @prop()
  public model?: string;
}

class User {
  @prop()
  public name?: string;

  @prop({ required: true })
  public age!: number;

  @prop()
  public job?: Job;

  @prop({ ref: Car })
  public car?: Ref<Car>;
}
```

Here we have two exemple of class integration : Job with only :

```js 
@prop()
public job?: Job;
```

And Car with : 

```js
@prop({ ref: Car })
public car?: Ref<Car>;
```

And lastly I saw this documentation page :
https://typegoose.github.io/typegoose/guides/advanced/reference-other-classes/#common-problems

So I'm pretty confused on which one to use, why and if they will work the same ?
Can you enlight me ?

**Comment by hasezoey** [comment]
this should be better understandable if you know mongoose

simple explanation (for more extensive documentation look at the mongoose documentation)
- the option `ref` is used if you want to reference an document (like from an different collection), and this only stores the `_id` of the referenced document, needs to be populated to show the actual reference
- without the option `ref` it is an *subdocument*, which dosnt need to be populated (its integrated into the parent document)

```ts
class Job {
  @prop()
  public someprop: string
}
class SubDocument {
  @prop()
  public nested: Job;
}
// would result in
{ nested: { someprop: "hello" } }

class Car {
  @prop()
  public model: string;
}
class AReference {
  @prop({ ref: Car })
  public reference: Ref<Car>;
}
// would result in
{ reference: ObjectId("the id of the car document") }
```

**Comment by billouboq** [comment]
Thanks that’s clear and consize !
