### ISSUE TITLE
_id field should not accept 'unique' prop

### ISSUE THREAD

**Issue by dandv** [typegoose/typegoose#311]
## Versions

- NodeJS: 13.x
- Typegoose(NPM): 7.2.0
- mongoose: 5.9.20

## What is the Problem?

Passing `unique` to the _id field generates this warning message:

> mongoose: Cannot specify a custom index on `_id` for model name "Discussion", MongoDB does not allow overwriting the default `_id` index. See http://bit.ly/mongodb-id-index

## Code Example

```ts
@prop({ unique: true, default: nanoid, maxlength: 100, trim: true, validate: validName })
```

**Comment by hasezoey** [comment]
sorry but the propoptions cannot be changed based on what the property name is

from what i know this is because mongodb already applies an unique index to all collections for `_id` (see the link the warning provided)

**Comment by hasezoey** [comment]
because this is not an typegoose issue how to fix it is given (just remove `unique: true`), this will be closed
