### ISSUE TITLE
Support for props in custom validators

### ISSUE THREAD

**Issue by dandv** [typegoose/typegoose#314]
## Which feature

- [Custom validators](https://mongoosejs.com/docs/validation.html#custom-validators) accept `props` in the message, to display the invalidat value:

    message: props => `${props.value} is not a valid phone number!`

## Code Examples

https://codesandbox.io/s/typegoose-starter-9yzrk?file=/src/index.ts

## Additional Notes

Works, but there's a type error

> Types of property 'message' are incompatible.
    Type '(props: any) => string' is not assignable to type 'string'.

**Comment by hasezoey** [comment]
easy fix, the `message` property in `ValidatorOptions` is just set to `string`, and not allowing any functions,

should be fixed in 7.3.0

**Comment by dandv** [comment]
Thanks for the quick fix!

BTW what do you think of using that Code sandbox as a template (you may want to tweak it) for the [code example in issues](https://github.com/typegoose/typegoose/blob/master/.github/ISSUE_TEMPLATE/bug.md#code-example)? It has the MongoDB connection already setup to a free mLab account. Code sandbox runs Node 10 though, not sure if that's a problem.

**Comment by hasezoey** [comment]
sorry i rather run it locally

**Comment by dandv** [comment]
Sure, my too, but as a minimal template for people who want to report a bug

**Comment by hasezoey** [comment]
this fix should be included in 7.3.0-1, if you want to test it
