### ISSUE TITLE
Help! How to capture database connection events

### ISSUE THREAD

**Issue by hehehai** [typegoose/typegoose#315]
## What to include in your Questions
I currently use typegoose in the nestjs project, but I now want to set the database connection event, like this
```ts
mongoose.connection.on('connecting', () => {
   console.log('数据库连接中...');
});

mongoose.connection.on('open', () => {
   console.info('数据库连接成功！');
   clearTimeout(reConnectionTask);
   reConnectionTask = null;
});

mongoose.connection.on('disconnected', () => {
   console.error(`数据库失去连接！尝试 ${RECONNET_INTERVAL / 1000}s 后重连`);
   reConnectionTask = setTimeout(connection, RECONNET_INTERVAL);
});
```
But i don't know how to do it now

## Versions

- typegoose: 7.2.0
- mongoose: 5.9.21

**Comment by smolinari** [comment]
This is more a Mongoose question than a Typegoose question.

Nonetheless, at some point you should be making a connection. You should put those event listeners after you set up/ initialize the connection. 

https://stackoverflow.com/questions/24100119/mongoose-connection-events-with-createconnection

Scott

**Comment by hehehai** [comment]
ok, Sorry, I should ask a question at [nestjs typegoose](https://github.com/kpfromer/nestjs-typegoose)

**Comment by smolinari** [comment]
@hehehai - They'll tell you the same. It is a mongoose question, which I gave you the answer anyway in the SO post.

Scott

**Comment by andreialecu** [comment]
@hehehai See here how to get the connection token: https://github.com/kpfromer/nestjs-typegoose/issues/46#issuecomment-561643757
