### ISSUE TITLE
arrayProp deprecation and usage

### ISSUE THREAD

**Issue by bennyKY** [typegoose/typegoose#318]
Hi, why is `arrayProp` been deprecated?

Another thing, can you please mention what is the difference between `prop` and `arrayProp`? in your docs its very not clear.
The only thing i know is that the default value is empty array - `[]` instead of null. Maybe can you add a use case.

p.s 
great library! we are using it in prod and we're very happy!

**Comment by hasezoey** [comment]
since [7.2.0](https://typegoose.github.io/typegoose/changelog#720) there isnt actually anything different, and since then `arrayProp` just forces the type to be an array (which can now be done as an second parameter to `@prop`)

the only thing needed for this to work is that the type is an array:
```ts
// all of the following examples will be considered as an Array
class SomeArrayProps {
  @prop({ type: String })
  public normalArray: string[];

  @prop({ type: String })
  public normalArray: Array<string>;

  @prop({ type: String })
  public normalArray: mongoose.Schema.Types.Array<string>;

  @prop({ type: String })
  public normalArray: mongoose.Types.Array<string>;

  @prop({ type: String }, WhatIsIt.ARRAY) // this is what the `@arrayProp` decorator now just does
  public normalArray: string; // note, this will actually have the wrong type for typescript

  @arrayProp({ type: String })
  public normalArray: string; // note, this will actually have the wrong type for typescript
}
```

i hope this clarifies what you are asking

**Comment by bennyKY** [comment]
Thx.
So now, if the field is an array type, i should decorate it with `@prop({ type: <> })` instead of `@arrayProp`.
Except of validation the this value is an array during write to mongo time, there is another benefit or capability using `@prop({ type: <> })`?

**Comment by hasezoey** [comment]
there isnt any benefit to using it, because it is needed to work, look [at this typescript issue](https://github.com/microsoft/TypeScript/issues/7169) to know in more detail why it is needed

**Comment by hasezoey** [comment]
closing because this question seems to be answered

**Comment by OFLVBHBH** [comment]
Mentions with an array of Contact are now deprecated ?

**Comment by hasezoey** [comment]
> Mentions with an array of Contact are now deprecated ?

please explain what you mean, this Issue is quite old and the mentioned feature has been removed for quite some time (since typegoose 8.0), see earlier comments (or documentation) on how to use arrays nowadays
