### ISSUE TITLE
Consider Opening Public Organizations on GitHub and NPM to Host Typegoose Project

### ISSUE THREAD

**Issue by thoughtentity** [typegoose/typegoose#32]
#### Overview
As `typegoose` is in the middle of a repo migration. I would suggest opening official `orgs` on GitHub and NPM to host the official versions of `typegoose`. Fortunately, the `typegoose` org names are available on `npm` and `GitHub` as the time of this issue creation.

This would allow users to install `typegoose` via the `npm` scope `@typegoose`:

```
npm install @typegoose/typegoose
```

#### Notes
Thanks @hasezoey for taking over this project. Our team was planning to start adopting this project in the near future.

**Comment by hasezoey** [comment]
Im not sure about this, i never made such thing before, i think (at least for the time being) it is not needed

(i will let this issue open until decided)

**Comment by joemckie** [comment]
I'd +1 this, orgs are free and it means that there can be multiple owners for larger projects

**Comment by hasezoey** [comment]
@thoughtentity @joemckie this package is now in typegoose/typegoose (github), and will be `@typegoose/typegoose` when i go to release v6.0.0

**Comment by joemckie** [comment]
@hasezoey nice!

**Comment by hasezoey** [comment]
Closing this because the github repo got moved into an org, and v6.0.0 got released in the npm org package
