### ISSUE TITLE
Enum array behaves differently between prop and arrayProp

### ISSUE THREAD

**Issue by Jonas-Witt** [typegoose/typegoose#320]
### Versions
- @typegoose/typegoose@6.4.0
- mongoose@5.9.5

Hi everyone,

I have an issue with transitioning from `arrayProp` to `prop`. Judging from the documentation the two versions below should perform identically, yet they don't.

```ts
export class Account {
  // This works.
  // @arrayProp({ required: true, enum: Role, items: String })
  // roles!: Role[];

  // This gives the error below.
  @prop({ required: true, enum: Role, items: String })
  roles!: Role[];
}
```
I'm getting this error for the `prop` version (I have already tried `type` instead of `items` and also tried `[String]` for the `type` version).
```
[Nest] 15647   - 07/09/2020, 11:39:59 AM   [ExceptionHandler] Invalid type used for map!, got: "function Array() { [native code] }" (Account.roles) +1ms
Error: Invalid type used for map!, got: "function Array() { [native code] }" (Account.roles)
    at Object._buildPropMetadata (/node_modules/@typegoose/typegoose/lib/prop.js:149:23)
    at Object._buildSchema /node_modules/@typegoose/typegoose/lib/internal/schema.js:36:20)
    at buildSchema (/node_modules/@typegoose/typegoose/lib/typegoose.js:149:20)
    at Object.getModelForClass (/node_modules/@typegoose/typegoose/lib/typegoose.js:91:39)
    at InstanceWrapper.modelFactory [as metatype] (/node_modules/nestjs-typegoose/dist/typegoose.providers.js:21:58)
    at Injector.instantiateClass (/node_modules/@nestjs/core/injector/injector.js:291:55)
    at callback /node_modules/@nestjs/core/injector/injector.js:75:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It would also be great if we could add an enum array example to the documentation after this is resolved.

**Comment by hasezoey** [comment]
the documentation is for the *latest* version, currently being 7.3.0, and `prop` & `arrayProp` & `mapProp` became unified in [7.1.1 ](https://typegoose.github.io/typegoose/changelog#711)(and deprecated in 7.2.0)

**Comment by Jonas-Witt** [comment]
Thanks for the quick response! I'll see if I can update my dependencies in the next couple days and verify that this resolves it.

**Comment by hasezoey** [comment]
closing because this updating to 7.2+ should solve it (because documentation from 7.2 got applied to 6.4)
