### ISSUE TITLE
InsertOne not validating and filling default values

### ISSUE THREAD

**Issue by underfisk** [typegoose/typegoose#325]
## Versions

- NodeJS: 7x
- Typegoose(NPM): 7.2
- mongoose: 5.8.4

## What is the Problem?
Simply insert a document using collection.insertOne and it is not running any validation nor adding the default values and can lead to corrupted data very easily. I migrated from Mongoose to Typegoose and the inserts that were working now they simply corrupt data

## Code Example

Example of a property in the schema that is supposed to fill Active in case i omit it in the document
```ts
	@ApiProperty()
	@IsEnum(CharterStatus)
	@prop({ enum: CharterStatus, default: CharterStatus.Active })
	status: CharterStatus
```
A simple insert
```ts
this.charterModel.collection.insertOne({ })
```
## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
from what i know is when you use `model.collection.*`, then they are direct-mongodb functions - no mongoose validation or defaults, try `model.insertOne`

**Comment by underfisk** [comment]
@hasezoey I did try model.insert but there is no insertOne, only insertMany
So Typegoose does not interfere when we invoke collection.* ?

**Comment by hasezoey** [comment]
typegoose dosnt interfere with any actual functions, typegoose just maps an class to an schema and to an model and provides extra functions, but dosnt change any mongoose stuff

**Comment by underfisk** [comment]
@hasezoey What i meant was if for example, the decorators such as validators will run even when i use collection.* because they aren't doing anything right now if i insert wrong values
I'm aware it just maps

**Comment by hasezoey** [comment]
like i said, no mongoose intervention is done when using `.collection.*`
