### ISSUE TITLE
InvalidTypeError: Type is invalid! Type is: "undefined" 

### ISSUE THREAD

**Issue by winterNebs** [typegoose/typegoose#326]
## Versions

- typegoose: 7.3.0
- mongoose: 5.9.24
'''

Using the following definition for `UserClass`:
```ts
@pre<UserClass>("save", async function (next: HookNextFunction): Promise<void> {
    ...
})
@index({ name: 1 }, { collation: { locale: "en", strength: 1 }, unique: true })
export class UserClass {
    @prop({
        required: true,
        trim: true,
        unique: true,
        minlength: 3,
        maxlength: 20
    })
    public name!: string;
...
}
```

 I get the following unhelpful error:
```
@typegoose\typegoose\lib\internal\processProp.js:160
        throw new errors_1.InvalidTypeError(name, key, Type);
        ^

InvalidTypeError: "UserClass.name"'s Type is invalid! Type is: "undefined"
    at Object.processProp (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\node_modules\@typegoose\typegoose\lib\internal\processProp.js:160:15)
    at Object._buildSchema (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\node_modules\@typegoose\typegoose\lib\internal\schema.js:37:27)
    at buildSchema (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\node_modules\@typegoose\typegoose\lib\typegoose.js:120:20)
    at Object.getModelForClass (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\node_modules\@typegoose\typegoose\lib\typegoose.js:70:39)
    at Object../database/schema/user.ts (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:2121:28)
    at __webpack_require__ (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:20:30)
    at Object../gameAppServer.ts (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:2409:16)
    at __webpack_require__ (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:20:30)
    at Object../app.ts (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:1351:25)
    at __webpack_require__ (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:20:30)
    at C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:84:18
    at Object.<anonymous> (C:\Users\winterNebs\source\repos\AscensionGame\AscensionGame\dist\app.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```

As far as I can tell the type for `name` is `string`, not `undefined`. 
Can anyone spot what I did wrong or is this error not related to this code?

I migrated from ts-mongoose since that project doesn't look like its being updated anymore, so sorry that I don't have a very minimal example.

**Comment by JohnDeved** [comment]
encountering the same issue right now.
setting `"emitDecoratorMetadata": true` in the tsconfig.json fixed it for me

**Comment by hasezoey** [comment]
@winterNebs there dosnt seem to be anything wrong with the provided code, please confirm the following:

- that your typescript version is above 3.9
- that you have enabled the mentioned tsconfig options [in requirements](https://github.com/typegoose/typegoose#requirements)
- that you are **not** running typegoose on the client side (#33)

**Comment by winterNebs** [comment]
Shoot, that's my bad guys. I had the `experimentalDecorators` set but I missed the metadata option as well.

Thanks for the quick responses

**Comment by josh-feldman** [comment]
I am seeing this same error if `module` in tsconfig is set to `es6` instead of `commonjs`. All [requirements](https://github.com/typegoose/typegoose#requirements) are set properly and dependencies are met. Is `module = commonjs` required?

If I use `commonjs` it works fine, but I would prefer to compile to `es6` for the rest of the project if possible. This should be listed as a requirement if it is actually required.

**Comment by hasezoey** [comment]
@josh-feldman from what i know, this shouldnt matter, there is already an issue about shipping esm #214 

and without the full error, i cannot say for sure what is happening

**Comment by josh-feldman** [comment]
My apologies, some detail:

Error:
```
/package/node_modules/@typegoose/typegoose/lib/internal/processProp.js:160
        throw new errors_1.InvalidTypeError(name, key, Type);
              ^
/package/node_modules/@typegoose/typegoose/lib/internal/processProp.js:1
Error: "User.userId"'s Type is invalid! Type is: "undefined"
    at Object.processProp (/package/node_modules/@typegoose/typegoose/lib/internal/processProp.js:160:15)
    at Object._buildSchema (/package/node_modules/@typegoose/typegoose/lib/internal/schema.js:37:27)
    at buildSchema (/package/node_modules/@typegoose/typegoose/lib/typegoose.js:120:20)
    at getModelForClass (/package/node_modules/@typegoose/typegoose/lib/typegoose.js:70:39)
    at Object.<anonymous> (/package/dist/models/UserModel.js:21:26)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/package/dist/app.js:1)
    at Generator.next (<anonymous>)
```

User Model.ts
```ts
import { prop, modelOptions, getModelForClass, DocumentType } from '@typegoose/typegoose';

@modelOptions({ schemaOptions: { timestamps: true, strict: 'throw', collection: 'user' } })
export class User {
  @prop({ required: true, index: true })
  userId!: number;
}

export type UserDocument = DocumentType<User>;
export const UserModel = getModelForClass(User);
```

tsconfig:
```json
{
  "compilerOptions": {
    "target": "ES6",
    "lib": [
      "es6",
    ],
    "downlevelIteration": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "es6",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "outDir": "./dist/",
    "rootDir": "./src",
    "preserveSymlinks": true
  },
  "include": [
    "src",
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
  ]
}
```

Command to start:
```
tsc --project ./tsconfig.json && node -r esm dist/app.js
```

**Comment by hasezoey** [comment]
@josh-feldman at least in my nodejs version (14.7), if i would try to run it in esm, i would get the error
```
import { getModelForClass, prop, modelOptions } from "@typegoose/typegoose";
                           ^^^^
SyntaxError: The requested module '@typegoose/typegoose' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from '@typegoose/typegoose';
const { getModelForClass, prop, modelOptions } = pkg
```

**Comment by hasezoey** [comment]
i tried it with esm modules (after i figured out on how to do so), and had no errors, the only problem i came across was "typegoose dosnt have an default export and commonjs dosnt support named exports" (which i still dont quite understand on why)

**Comment by josh-feldman** [comment]
I am seeing this issue on Node 10 & use the `esm` package to resolve the ESM modules per the start command.

For your record, this is what the above `UserModel` file gets compiled down to in both cases:

`module: ES6` (throws the error I mentioned above):
```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
import { prop, modelOptions, getModelForClass } from '@typegoose/typegoose';
let User = class User {
};
__decorate([
    prop({ required: true, index: true }),
    __metadata("design:type", Number)
], User.prototype, "userId", void 0);
User = __decorate([
    modelOptions({ schemaOptions: { timestamps: true, strict: 'throw', collection: 'users' } })
], User);
export { User };
export const UserModel = getModelForClass(User);
```

`module: commonjs` works:
```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserModel = exports.User = void 0;
const typegoose_1 = require("@typegoose/typegoose");
let User = class User {
};
__decorate([
    typegoose_1.prop({ required: true, index: true }),
    __metadata("design:type", Number)
], User.prototype, "userId", void 0);
User = __decorate([
    typegoose_1.modelOptions({ schemaOptions: { timestamps: true, strict: 'throw', collection: 'users' } })
], User);
exports.User = User;
exports.UserModel = typegoose_1.getModelForClass(User);
```

**Comment by josh-feldman** [comment]
It also doesn't work if I try [this workaround](https://github.com/typegoose/typegoose/issues/214#issuecomment-626123528)

UserModel.ts:
```ts
import { DocumentType } from '@typegoose/typegoose';
import * as typegoose from '@typegoose/typegoose';

// @ts-ignore
const { prop, modelOptions, getModelForClass } = typegoose.default || typegoose;
@modelOptions({ schemaOptions: { timestamps: true, strict: 'throw', collection: 'users' } })
export class User {
  @prop({ required: true, index: true })
  userId!: number;
}

export type UserDocument = DocumentType<User>;
export const UserModel = getModelForClass(User);
```

compiled UserModel.js:
```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
import * as typegoose from '@typegoose/typegoose';
// @ts-ignore
const { prop, modelOptions, getModelForClass } = typegoose.default || typegoose;
let User = class User {
};
__decorate([
    prop({ required: true, index: true }),
    __metadata("design:type", Number)
], User.prototype, "userId", void 0);
User = __decorate([
    modelOptions({ schemaOptions: { timestamps: true, strict: 'throw', collection: 'users' } })
], User);
export { User };
export const UserModel = getModelForClass(User);
```

**Comment by josh-feldman** [comment]
I have tested converting

`import { prop, modelOptions, getModelForClass } from '@typegoose/typegoose';`

in the compiled output to

`const { prop, modelOptions, getModelForClass } = require('@typegoose/typegoose');`

and this works as well. I am thinking perhaps it has something to do with the typegoose import getting hoisted above the `__metadata` and `__decorate` references.

**Comment by JMPJNS** [comment]
for people using babel instead of tsc, this [plugin](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata) also fixes it

**Comment by aderchox** [comment]
I have correct tsconfig with required metadata options enabled according to the manual and according to the comments here, I'm also using commonjs, however, I still get the same error for a case as simple as this:
```
class UsersClass {
  @prop({ required: true })
  public username!: string;

  @prop()
  public email?: string;
}
```

> InvalidTypeError: "UsersClass.username"'s Type is invalid! Type is: "undefined" [E009]
    at processProp (D:\projects\khodam\swagger\express-tsrest-react-mongo\api\node_modules\@typegoose\typegoose\src\internal\processProp.ts:277:11)
    at _buildSchema (D:\projects\khodam\swagger\express-tsrest-react-mongo\api\node_modules\@typegoose\typegoose\src\internal\schema.ts:59:7)
    at buildSchema (D:\projects\khodam\swagger\express-tsrest-react-mongo\api\node_modules\@typegoose\typegoose\src\typegoose.ts:187:9)
    at getModelForClass (D:\projects\khodam\swagger\express-tsrest-react-mongo\api\node_modules\@typegoose\typegoose\src\typegoose.ts:102:60)
    at <anonymous> (d:\projects\khodam\swagger\express-tsrest-react-mongo\api\src\routes\features\users\users.model.ts:14:16) 
    at Object.<anonymous> (d:\projects\khodam\swagger\express-tsrest-react-mongo\api\src\routes\features\users\users.model.ts:14:43)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.F (D:\projects\khodam\swagger\express-tsrest-react-mongo\api\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1037:32)  
    at Module._load (node:internal/modules/cjs/loader:878:12)

**Comment by hasezoey** [comment]
@aderchox if your stack-trace is anything to go by, then you are using `esbuild`, which does not support outputting decorator metadata because it does not have type information, see https://github.com/evanw/esbuild/issues/257#issuecomment-658053616

your options are:
- switch to use the `tsc` compiler for you esbuild chain
- use `tsc` directly
- or use [typegoose: Use Without "emitDecoratorMetadata"](https://typegoose.github.io/typegoose/docs/guides/use-without-emitDecoratorMetadata)

**Comment by senher** [comment]
When I use it in nuxt3
`"emitDecoratorMetadata": true` is not effective

**Comment by hasezoey** [comment]
@senher please open a new issue for your case, this issue is quite old. also from what i can tell, nuxt is using esbuild, which does not support that option unless using typescript directly https://github.com/nuxt/nuxt/issues/14126, at least from my quick skim
