### ISSUE TITLE
DocumentType<> not setting instance methods correctly

### ISSUE THREAD

**Issue by TwoAbove** [typegoose/typegoose#329]
## Versions

- NodeJS: 12.18.2
- Typegoose(NPM): 7.3.0 
- mongoose: 5.7.32
- mongodb: 3.5.25

## What is the Problem?

DocumentType for some reason does not set instance methods.

Type error is `Property 'setPassword' does not exist on type 'DocumentType<User>'`

## Code Example
in custom.d.ts,
```ts
import { User } from './models/user';
import { DocumentType } from '@typegoose/typegoose';

declare global {
	namespace Express {
		interface Request {
			user?: DocumentType<User>;
		}
	}
}

```
in the method,
```ts
export const updateUser = async (
	req: Request,
	res: Response,
	next: NextFunction
) => {
	const body = req.body;

	if (body.password) {
           req.user!.setPassword()
	}

	next();
};

```
User class
```ts

@modelOptions({ options: { allowMixed: Severity.ALLOW } })
export class User {
	@prop()
	password?: string;

	public async setPassword(this: DocumentType<User>, password: string) {
            ...
	}
}
```

## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
what version of `typescript` and `@types/mongoose` are installed?

**Comment by TwoAbove** [comment]
Hi @hasezoey !

Sorry I missed that info

Typescript 3.9.4
@types/mongoose 5.7.27

**Comment by hasezoey** [comment]
if that are really these versions and the example given, then this error shouldnt happen
-> but i need to say, i never declared something globally (but this shouldnt matter)

**Comment by ggurkal** [comment]
@TwoAbove How and where do you set `req.user`?

**Comment by TwoAbove** [comment]
@hasezoey Just re-check the lock file — @types/mongoose is 5.7.32

@ggurkal 
```ts
	let user = await User.findOne({ email });
        ... (checks)
	req.user = user;
```
But it shouldn't matter, since this is a typing issue, not at runtime.

@hasezoey I suspect this is an issue with how I declared the global, since the typing in vscode gives me 
```ts
(property) Express.Request.user?: DocumentType<Express.User> | undefined
```

I also tried to replicate this locally (using `type t = DocumentType<User>`), and everything seems okay:
```ts
type t = DocumentType<U>
const a = {} as t;
a.validPassword('asfasfafs') // works correctly
```
I guess this can be closed. I'm sorry for the confusion — I should have made more checks locally.

**Comment by TwoAbove** [comment]
On further testing, in custom.d.ts,
```ts
import { User } from './models/user';
import { DocumentType } from '@typegoose/typegoose';

declare global {
	namespace Express {
		interface Request {
			user?: DocumentType<User>;
		}
	}
}
```
changing user to `any` type actually changes it to `any`, so it looks like there are some express shenanigans going on

**Comment by TwoAbove** [comment]
Solved!

It was an express gimmick:
```ts
import { User as U } } from './models/user';
import { DocumentType } from '@typegoose/typegoose';

declare global {
	namespace Express {
		interface Request {
			user?: DocumentType<U>;
		}
	}
}
```
There was some closure where `User` was already defined!
