### ISSUE TITLE
How I create and fill a referenced class array?

### ISSUE THREAD

**Issue by Mdsp9070** [typegoose/typegoose#332]
## Versions

- typegoose: 7.3.0
- mongoose: 5.9.25

I have this class:
```typescript
import { prop, getModelForClass } from "@typegoose/typegoose";

export class Incident {
  @prop()
  title: string;

  @prop()
  description: string;

  @prop()
  value: number;

  @prop()
  ongId: string;
}

export default getModelForClass(Incident);
```

And I created the reference like this:
```typescript
import * as autopopulate from "mongoose-autopopulate";
import { prop, Ref, getModelForClass, plugin } from "@typegoose/typegoose";

import { Incident } from "./incident";

@plugin(autopopulate as any)
class Ong {
  @prop()
  id: string;

  @prop()
  name: string;

  @prop()
  email: string;

  @prop()
  wpp: string;

  @prop()
  city: string;

  @prop()
  uf: string;

  @prop({ ref: () => Incident, autopopulate: true, type: Incident })
  incidents: Ref<Incident[]>;
}

export default getModelForClass(Ong);
```

How I could fill these incidents?

I'm doing like this, but `push` doesn't exist on type `Incident[] | ObjectId`:
```typescript
await OngModel.findOne({ id: ongId }, async (err, foundOng) => {
      if (err || !foundOng) throw new AppError("No ong was found", 401);

      const createdIncident = await IncidentsModel.create(incident);
      foundOng.incidents?.push(createdIncident)
      foundOng.save();

      return (ctx.body = createdIncident._id);
    });
```

**Comment by hasezoey** [comment]
you didnt define your type to be an array (your type is wrong), it would need to be `Ref<Class>[]`

indepth:
`Ref<Class[]>` compiles to "design:type" of "Object" and gets overwritten by option `type`
`Ref<Class>[]` compiles to "design:type" of "Array" (and the array type is set by option `type`)

src reference:
https://github.com/typegoose/typegoose/blob/8f6eb5501fd72a615f6595f64d3b4fb63dc66cbd/src/internal/processProp.ts#L25-L26
https://github.com/typegoose/typegoose/blob/8f6eb5501fd72a615f6595f64d3b4fb63dc66cbd/src/internal/processProp.ts#L438-L455

**Comment by Mdsp9070** [comment]
Well, Now I see and understand my error, thank you so much!
