### ISSUE TITLE
Missing "delete" type for middleware hooks

### ISSUE THREAD

**Issue by TAYTS** [typegoose/typegoose#333]
## Versions

- NodeJS: 12.16.1
- Typegoose(NPM): 7.3.0 
- mongoose: 5.9.25
- mongodb: 4.2

## Code Example

```ts
@post<Case>('findOneAndDelete', async (doc, next) => { ... })
```

## Do you know *why* it happens?

Missing "delete" type hooks.
Using `findOneAndDelete` as it is recommended in the mongoose documentation: https://mongoosejs.com/docs/api.html#query_Query-findOneAndDelete

**Comment by smolinari** [comment]
Note you can't use arrow functions!!

![image](https://user-images.githubusercontent.com/3314957/88164625-a94c8d00-cc14-11ea-9fbc-728bd62bac59.png)

See if that helps. 

Scott

**Comment by TAYTS** [comment]
Thank you so much, it is working now, but the type for "delete" hook is missing in the type definition, could I submit a PR to update the type definition?

**Comment by smolinari** [comment]
Can you point me to the type definition you are looking at? I'm curious more than anything. 

Scott

**Comment by TAYTS** [comment]
https://github.com/typegoose/typegoose/blob/8f6eb5501fd72a615f6595f64d3b4fb63dc66cbd/src/hooks.ts#L31-L36

**Comment by TAYTS** [comment]
The "delete" hook type I mentioned: https://mongoosejs.com/docs/middleware.html#types-of-middleware

**Comment by smolinari** [comment]
Yep. I see what you mean. I'd say yes on the PR, but I'm not the maintainer and also not the most experienced with this package. (But, I'm loving it more and more. :) )

Scott
