### ISSUE TITLE
How to define a double object in Schema?

### ISSUE THREAD

**Issue by cuiko** [typegoose/typegoose#334]
js code
```js
new Schema({
  meta: {
    createdAt: {
      type: Date,
      default: Date.now
    },
    updatedAt: {
      type: Date,
      default: Date.now
    }
  }
})
```
And..., I have only recently begun to learn TypeScript, one more question, what is mean about '!' '?' '&' in TypeScript?
thanks for you help me.

**Comment by cuiko** [comment]
emmmmm, Is this correct?
```js
export class BasicSchemaClass {
  @prop({ default: { 'meta.createdAt': Date.now, 'meta.updatedAt': Date.now } })
  public meta?: {
    createdAt: Date,
    updatedAt: Date
  }
}
```

**Comment by cuiko** [comment]
emmmmm, or this one?
```js
class Meta {
  @prop({ default: Date.now })
  public createedAt?: Date
  @prop({ default: Date.now })
  public updatedAt?: Date
}

export default class BasicSchemaClass {
  @prop()
  public meta?: Meta
}
```

**Comment by hasezoey** [comment]
> emmmmm, or this one?
> 
> ```js
> class Meta {
>   @prop({ default: Date.now })
>   public createedAt?: Date
>   @prop({ default: Date.now })
>   public updatedAt?: Date
> }
> 
> export default class BasicSchemaClass {
>   @prop()
>   public meta?: Meta
> }
> ```

you need to do it like this in typegoose

**Comment by cuiko** [comment]
> > emmmmm, or this one?
> > ```js
> > class Meta {
> >   @prop({ default: Date.now })
> >   public createedAt?: Date
> >   @prop({ default: Date.now })
> >   public updatedAt?: Date
> > }
> > 
> > export default class BasicSchemaClass {
> >   @prop()
> >   public meta?: Meta
> > }
> > ```
> 
> you need to do it like this in typegoose

oh, Thank you for your reply.
