### ISSUE TITLE
ES6 required for nestedDiscriminators; TypeError thrown in processProp on ES5, utils.getType(...).map is not a function

### ISSUE THREAD

**Issue by gitschwifty** [typegoose/typegoose#335]
I was filing a bug but I figured it out, here's the writeup I had before I realized what was causing it. Proposed steps are at the end, include me creating/updating some documentation to help out.

## Versions

- NodeJS: 13.12.0
- Typegoose(NPM): 7.3.0 
- mongoose: 5.9.25
- mongodb: 0.0.0

don't have mongodb in my repro but 3.5.9 in the project I'm working on where I first encountered this

## What is the Problem?

Receiving TypeError: utils.getType(...).map is not a function

```
.../typegooseDiscriminatorRepro/node_modules/@typegoose/typegoose/lib/internal/processProp.js:80
            .map((val, index) => {
             ^

TypeError: utils.getType(...).map is not a function
    at Object.processProp (.../typegooseDiscriminatorRepro/node_modules/@typegoose/typegoose/lib/internal/processProp.js:80:14)
    at Object._buildSchema (.../typegooseDiscriminatorRepro/node_modules/@typegoose/typegoose/lib/internal/schema.js:37:27)
    at buildSchema (.../typegooseDiscriminatorRepro/node_modules/@typegoose/typegoose/lib/typegoose.js:120:20)
    at Object.getModelForClass (.../typegooseDiscriminatorRepro/node_modules/@typegoose/typegoose/lib/typegoose.js:70:39)
    at Object.<anonymous> (.../typegooseDiscriminatorRepro/index.js:77:29)
```
(removed user path before the repo)

## Code Example

Made a repro using the example code in the documentation, then updated it to match the nestedDiscriminators test code (using enums) in case that made a difference, it did not, should've known beforehand on that since I already had enums implemented in the project I'm working on.
[typegooseDiscriminatorRepro](https://github.com/gitschwifty/typegooseDiscriminatorRepro)

## Do you know *why* it happens?

The discriminators function was being transpiled to a regular function () {}, due to the target being ES5. Submitting this as documentation since I struggled with this for around 3 hours trying to figure out what the issue was, modifying processProp.js to log types & see what happened if I didn't use getType and just called rawOptions.discriminators() then mapped it, and a bit more, til I finally thought about it and checked your tsconfig. 

## Moving Forward

I would like to know what you think about it, as I don't know a lot about the differences between ES5 & ES6, and I think I only had ES5 because that's the default from running tsc --init, so it's no issue for me switching to ES6 afaict but I couldn't say if it would be for others.

I'll probably submit a pull request soon with a small to medium documentation update, to flag that ES6 is required for discriminators & fix up the docs a bit to explain their use better if possible. I did see the issues #99 , #98 and unluckily I don't know a ton about discriminators right now, but I need to use them so I'll try to help out with the documentation however I can (both discriminator specific & not).

Thanks a ton for making this lib!
Let me know if I should file this in another way, haven't filed issues before & I wrote up a whole bug before I figured it out, might be helpful in some way.

**Comment by gitschwifty** [comment]
After I knew what I was looking for, very quickly found replies mentioning that typegoose is ES6, pretty hard to find that in closed issues if you don't know that's what you're looking for, so I feel like a bit less of an idiot. Putting it in requirements would probably work.

**Comment by hasezoey** [comment]
i take the blame, thought i already put it there, but when looking at it again (and searching the whole documentation) i only found mentions of `ES6` in changelog & known-issues, sorry about that

**Comment by hasezoey** [comment]
> I would like to know what you think about it, as I don't know a lot about the differences between ES5 & ES6, and I think I only had ES5 because that's the default from running tsc --init, so it's no issue for me switching to ES6 afaict but I couldn't say if it would be for others.

Why ES6? here are some of the reasons why i decided to go ES6
- the least required nodejs version (at that time being 8) supports ES6
- this package(typegoose) is based on the use with classes, and in ES5 the class syntax dosnt exists (at least typescript dosnt compile it to the class syntax)
- it makes the package smaller in size
- it actually makes it way easier to debug the compiled package in ES6
(there are probably more that i dont remember)

**Comment by gitschwifty** [comment]
No worries, I got myself into it by using the tsc default, should've checked the config as soon as I tried the test suite & they all passed and my repro wasn't working.

Makes sense to me, especially since it's not client side, guess I'm more surprised about the default being ES5 for tsc.
