### ISSUE TITLE
Types on NPM are badly published

### ISSUE THREAD

**Issue by PabloSzx** [typegoose/typegoose#337]
@typegoose/typegoose@7.3.0

I don't know if this error is more deep than just types, but in the URLs I put here you can see that at least the type `QueryMethod` in the Source Code is not the same as in the published version, I discovered it since I needed to add a `pre` hook for `countDocuments`, and in the published package it's not declared, but in the source code here in the repo it is declared.

https://github.com/typegoose/typegoose/blob/master/src/hooks.ts#L35

https://unpkg.com/@typegoose/typegoose@7.3.0/lib/hooks.d.ts

**Comment by hasezoey** [comment]
these methods got added in 347c570733a7cfcd5438984218c0140d53235527, which is *after* the 7.3.0 release
