### ISSUE TITLE
Documentation Link Dead

### ISSUE THREAD

**Issue by NickBolles** [typegoose/typegoose#338]
I got a warning about mixed mode, but the link is dead.
https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#allowmixed

Obviously it was easy to find the correct link: https://typegoose.github.io/typegoose/docs/api/decorators/model-options/#allowmixed

Is this just because I'm on an old version of typegoose that hasn't been updated since the documentation changed? I'm on 7.3.0.

**Comment by hasezoey** [comment]
forgot to change this, thanks for reporting

**Comment by FMGordillo** [comment]
Still not fixed :c

**Comment by hasezoey** [comment]
@FMGordillo what is not fixed? the mentioned link in the error for `mixed` is fixed since 9dcf274 (7.3.2)

**Comment by FMGordillo** [comment]
Sorry, the link is still broken: https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#allowmixed

**Comment by hasezoey** [comment]
@FMGordillo if you mean this old link in general, this will *not* be fixed, the links in the code were just outdated
(there was an path change, after `/docs/` there is now either `api` or `guides`)
