### ISSUE TITLE
Possible to have Query type support?

### ISSUE THREAD

**Issue by kkoomen** [typegoose/typegoose#340]
I have a users service class like so (using NestJS):

```ts
import { UpdateQuery, FilterQuery } from 'mongoose';
import { User } from './schemas/users.schema.ts';

class UsersService {
  constructor(@InjectModel(User.name) private readonly usersModel: Model<User>) {}

  async updateOne(
    conditions: FilterQuery<User>,
    fields: UpdateQuery<User>,
    options: Record<string, unknown> = {},
  ): Promise<T> {
    try {
      const result = await this.usersModel.findOneAndUpdate(
        conditions,
        fields,
        { new: true, ...options },
      );
      return result;
    } catch (err) {
      console.log(err);
    }
}
```

The `User` schema can look like something like this:

```ts
import { Document } from 'mongoose';

class User extends Document {
  username: string;
}
```

When I have my controller with this:

```ts
class MyController {
  constructor(private readonly usersService: UsersService) {}

  @Get()
  async update(@Body() body: UpdateUserDTO): Promise<User> {
    // This expression below should cause an error that 'test' does not exists on `User` which doesn't happen.
    return this.usersService.updateOne({ test: true });
  }
}
```

This can be fixed for some part by modifying the `updateOne()` in the `UsersService` like so:

```ts
 async updateOne(
    conditions: Partial<Record<keyof User, any>>,
    fields: Partial<Record<keyof User, any>>,
    options: Record<string, unknown> = {},
  ): Promise<T> {
    try {
      const result = await this.usersModel.findOneAndUpdate(
        conditions as FilterQuery<User>,
        fields as UpdateQuery<User>,
        { new: true, ...options },
      );
      return result;
    } catch (err) {
      console.log(err);
    }
  }
```

but the custom approach above doesn't work for fields named like `$addToSet`.

The `FilterQuery<T>`, `UpdateQuery<T>`, `CreateQuery<T>` and `DeleteQuery<T>` (and other similar types) should all check whether the key is keyof `T`, in my case `T` is `User` but mongoose does not do this. Do you perhaps support some kind of solution to this?

**Comment by hasezoey** [comment]
form what i know the `*Query` types only accept an type that is "extending" `Document` - but it seems you are not setting the right types and it seems like you use an version before 6.0, please try to upgrade to 7.x [(and read the migration guides)](https://typegoose.github.io/typegoose/docs/guides/migrate-6)

---

here are the most notable things to change:
`private readonly usersModel: Model<User>` is not the correct type, use `ReturnModelType<typeof User>`
```ts
// they are the wrong types, use `*Query<DocumentType<User>>` but they should automatically infer if the model has the correct types
conditions as FilterQuery<User>,
fields as UpdateQuery<User>,
```
dont `extends Document`, when you need the types, use [`DocumentType<Class>`](https://typegoose.github.io/typegoose/docs/api/types/document-type) and for model functions [`ReturnModelType`](https://typegoose.github.io/typegoose/docs/api/types/return-model-type)

PS: [here is an quick-start-guide](https://typegoose.github.io/typegoose/docs/guides/quick-start-guide) which should show how to properly use 6.0/7.0 "types"

**Comment by kkoomen** [comment]
I don't use typegoose specifically, but I first created this issue at mongoose, then got redirected to DefinitelyTyped or so and then got redirected to this one.


I'll test it out soon and see if I have any problems. Thanks for now.

**Comment by kkoomen** [comment]
It doesn't work the way you mentioned it and the way I want it. This is my service method:

```ts
@Injectable()
export class WalletService {
  constructor(
    @InjectModel(Wallet.name) private readonly walletModel: ReturnModelType<typeof Wallet>,
  ) {}

  async findOne(
    conditions: FilterQuery<DocumentType<Wallet>>,
    projection: string | Record<string, unknown> = {},
    options: Record<string, unknown> = {},
  ): Promise<Wallet> {
    //
  }
}
```

This my schema:

```ts
import { Schema } from '@nestjs/mongoose';
import { getModelForClass, prop } from '@typegoose/typegoose';
import { Schema as MongooseSchema } from 'mongoose';
import { User } from 'src/modules/users/types';

@Schema({ timestamps: true })
export class Wallet {
  @prop()
  _id?: MongooseSchema.Types.ObjectId;

  @prop({
    type: MongooseSchema.Types.ObjectId,
    refPath: 'userModel',
    index: true,
  })
  idUser: MongooseSchema.Types.ObjectId | User;
}

export const WalletSchema = getModelForClass(Wallet);
```


and inside my controller I have this:

```ts
@Controller('wallet')
export class WalletController {
  constructor(private readonly walletService: WalletService) {}

  @Get()
  async getWallet(@CurrentUser() user: User): Promise<Wallet> {
    await this.walletService.findOne({ test: true });
    return this.walletService.findOne({ idUser: user._id });
  }
}
```

The `{ test: true }` should throw a TS error that `test` does not exists on the `Wallet` and should accept `idUser` since this one is defined in the schema, yet both are being accepted right now.

**Comment by hasezoey** [comment]
> yet both are being accepted right now.

accepted as *types* or on *runtime*? im asking because these are two different things

as for *runtime* you would need to enable [`strictQuery`](https://mongoosejs.com/docs/guide.html#strictQuery) on the model (or globally) 

but as for types, i dont know, do you have `@types/mongoose@5.7.30` or higher installed?

**Comment by kkoomen** [comment]
> accepted as types or on runtime? 
compile time should throw an error, I am not looking for this to be on runtime. The whole idea is that we can get an error immediately when typos are being made.

**Comment by hasezoey** [comment]
so, basically you want the types from these querys be passed-through? then just copy the types

the type of `conditions` should be right, and for options it should be `mongoose.QueryFindBaseOptions`

tried the following code, no problems
```ts
// NodeJS: 14.7.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, Ref, DocumentType } from "@typegoose/typegoose"; // @typegoose/typegoose@7.3.1
import * as mongoose from "mongoose"; // mongoose@5.9.26 @types/mongoose@5.7.34

class Wallet {
  @prop({ index: true, })
  public idUser?: string; // changed for the example
}

const WalletModel = getModelForClass(Wallet);

async function findOne(
  conditions: mongoose.FilterQuery<DocumentType<Wallet>>,
  projection: string | Record<string, unknown> = {},
  options: Record<string, unknown> = {},
): Promise<DocumentType<Wallet>> {
  return await WalletModel.findOne(conditions, projection, options).orFail();
}

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify341", useCreateIndex: true, useUnifiedTopology: true });

  const wallet1 = await WalletModel.create({ idUser: "hi" });

  console.log(await findOne({ _id: wallet1._id }));

  await mongoose.disconnect();
})();
```

**Comment by kkoomen** [comment]
> await WalletModel.create({ idUser: "hi" });

So if you add a field here named `test` then it will throw an error?

**Comment by hasezoey** [comment]
> So if you add a field here named test then it will throw an error?

at least for me, yes (only an compile-time error)

**Comment by kkoomen** [comment]
Well, the setup I use is good I presume, but it's different. You're testing it in a different way. I do use a service which uses `ReturnModelType`. My code ain't working still so perhaps you should test with the way I use your plugin.

**Comment by hasezoey** [comment]
> You're testing it in a different way

what do you mean with that, i know you are using nestjs, but i dont know nestjs (and this isnt the repo for it), so i just removed the parts from nestjs but tried to keep it in that style
(if the example i provided is not what you were trying to achieve, then i dont understand what you are trying to achieve)

PS: `@nestjs/mongoose` and typegoose are not compatible (instead of `@Schema` you should use `@modelOptions`)

**Comment by kkoomen** [comment]
I'll test it out later, but as for now, it ain't working with the code I sent to you.

**Comment by hasezoey** [comment]
> but as for now, it ain't working with the code I sent to you.

and what exactly?

**Comment by kkoomen** [comment]
That `test` is not a valid property on my schema and yet it passes. You can setup a net project yourself and test my code and see what works and what. `npx nest new <name>`

**Comment by hasezoey** [comment]
when you want an error on compile-time, then you need to enable `noImplicitAny` / `strict` in tsconfig
when you want an error on runtime, then you would need to enable `strict` or `strictQuery` (im unsure) in `modelOptions` (`schemaOptions`)

**Comment by hasezoey** [comment]
closing because stale
