### ISSUE TITLE
Why is populating a @prop in a Schema not possible?

### ISSUE THREAD

**Issue by jawil003** [typegoose/typegoose#341]
## Why is populating a @prop in a Schema not possible?

I created a Schema this way and want to resolve the Ref prop:

```ts
import { ObjectType, Field, ID } from "type-graphql";
import {
  prop,
  getModelForClass,
  Ref,
} from "@typegoose/typegoose";
import { Cities } from "../cities/cities.model";

@ObjectType({
  description: "A Model for all States of a Country",
})
export class States {
  @Field(() => ID)
  _id!: string;
  @Field(() => String)
  name!: string;
  @Field(() => [Cities], { nullable: true })
  @prop({ ref: () => Cities })
  cities!: Ref<Cities[]>;
}
```
I tried it the following way in a GraphQL Fieldresolver:

```ts
@Resolver(States)
export default class StateResolver {
...
@FieldResolver()
  async cities(
    @Root() state: States
  ): Promise<Ref<Cities[], ObjectId | undefined>> {
    const stateResolved = await StatesModel.find({
      _id: state._id,
      name: state.name,
    }).populate("cities");
    return state.cities;
  }
}
```

But somehow the actual Array of Cities Entities is never returned, but I don't get an Error either.
Is there a known Issue or is there may something I did in a wrong way?

-->

## Versions

- typegoose: ^7.3.1
- mongoose: ^5.9.27

**Comment by hasezoey** [comment]
fistly, your type is a bit wrong, you need to use `Ref<Cities>[]`, and you need to enable `virtuals: true` for `toJson / toObject` (that includes logging to the console)

PS: are you sure you use *that* version of typegoose?

**Comment by jawil003** [comment]
> fistly, your type is a bit wrong, you need to use `Ref<Cities>[]`, and you need to enable `virtuals: true` for `toJson / toObject` (that includes logging to the console)
> 
> PS: are you sure you use _that_ version of typegoose?

Pretty sure with the version it is right from my Package.json is that an old one?

**Comment by jawil003** [comment]
> fistly, your type is a bit wrong, you need to use `Ref<Cities>[]`, and you need to enable `virtuals: true` for `toJson / toObject` (that includes logging to the console)
> 
> PS: are you sure you use _that_ version of typegoose?

How do I enable virtuals in @typegoose is there a Decoratior for it or can I do it global?

**Comment by hasezoey** [comment]
> Pretty sure with the version it is right from my Package.json is that an old one?

yes, actually it is just an "compatability release" (to easily transfer from the old package without doing migration right away)
current version: 7.3.1

> How do I enable virtuals in @typegoose is there a Decoratior for it or can I do it global?

actually, it is *mongoose* you either `.toJson({ settings })` 

[if you read the docs, there is an section just about this](https://typegoose.github.io/typegoose/docs/api/virtuals/#why-is-my-virtual-not-included-in-the-output)

**Comment by jawil003** [comment]
> > Pretty sure with the version it is right from my Package.json is that an old one?
> 
> yes, actually it is just an "compatability release" (to easily transfer from the old package without doing migration right away)
> current version: 7.3.1
> 
> > How do I enable virtuals in @typegoose is there a Decoratior for it or can I do it global?
> 
> actually, it is *mongoose* you either `.toJson({ settings })` 
> 
> [if you read the docs, there is an section just about this](https://typegoose.github.io/typegoose/docs/api/virtuals/#why-is-my-virtual-not-included-in-the-output)

Ok I think it is the latest version then because I installed it through npm yesterday 😅 Never know where to look for version number because package.json does not always show it correct. So why is it necessary to enable virtuals support because a ref in normal mongoose isn't a virtual but a ref. So is this a Typegoose way of handling it?

**Comment by smolinari** [comment]
@jawil003 

> Never know where to look for version number

`npm list @typegoose/typegoose`

Scott

**Comment by jawil003** [comment]
> @jawil003
> 
> > Never know where to look for version number
> 
> `npm list @typegoose/typegoose`
> 
> Scott

Yeah saw the reason had both `typegoose` and `@typegoose(typegoose` installed but used the newer one, my version is ^7.3.1

**Comment by jawil003** [comment]
@hasezoey Did what you sad but no change I cant even call toJson on my `Typegoose` Models, idk what I should try... It seems like populate not working and i always just get the refs _id in graphql

**Comment by jawil003** [comment]
Could try to provide some kind of codepen if this helps? I#m at the end I don't get it really...

**Comment by jawil003** [comment]
Activated debugging on Mongoose and got this Query for populate and got this: 
```
cities.find({ _id: { '$in': [
ObjectId("5f14bdb883e65a946827cd1f"), 
ObjectId("5f14bdb883e65a946827cd1f"), 
ObjectId("5f14bdb883e65a946827cd1f"), 
ObjectId("5f14bdb883e65a946827cd1f"), 
ObjectId("5f14bdb883e65a946827cd23"),
 ObjectId("5f14bdb883e65a946827cd23"), 
ObjectId("5f14bdb883e65a946827cd25")
   ]
}) 
```
But wheather this is supported in Mongoose it seems like it is returning just the unpopulated value back idk

**Comment by hasezoey** [comment]
btw, `States.name` dosnt have an `@prop`, so it might not be contained in the schema

and i tried it myself, but i couldnt reproduce your problem, code used:
```ts
// NodeJS: 14.7.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@7.3.1
import * as mongoose from "mongoose"; // mongoose@5.9.26 @types/mongoose@5.7.34

class Cities {
  @prop({ required: true })
  public someProp!: string;
}

class States {
  @prop() // required if setting "_id" to something else than ObjectId
  public _id!: string;

  @prop({ required: true })
  public name!: string;

  @prop({ ref: () => Cities })
  public cities!: Ref<Cities[]>;
}
const CitiesModel = getModelForClass(Cities);
const StatesModel = getModelForClass(States);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify341", useCreateIndex: true, useUnifiedTopology: true });

  const city = await CitiesModel.create({ someProp: "hi" });
  const state = await StatesModel.create({ _id: "someId", name: "SomeState", cities: [city._id] }); // the "_id" needs to be always set if not ObjectId

  const stateResolved = await StatesModel.find({
    _id: state._id,
    name: state.name,
  }).populate("cities");

  console.log(stateResolved);

  await mongoose.disconnect();
})();
```

PS: `and you need to enable virtuals: true` was not needed for this case, sorry

**Comment by jawil003** [comment]
Issue was indeed that i missed the `@prop()` Decoratior for my ID Field and that I set it to string which seems not to work with the `Schema.find()`function at least in my cases, seems like Typegoose is a little different under the hood than mongoose because I could do that in Mongoose according to docs

**Comment by hasezoey** [comment]
@jawil003, sorry, but typegoose dosnt modify an functions of mongoose, it only wraps the schema and model creation, but dosnt modify anything beyond that (only having extra utility functions, like the typeguards)
