### ISSUE TITLE
clarification on class definitions

### ISSUE THREAD

**Issue by lostrouter** [typegoose/typegoose#342]
given the following class, i get typescript errors
```
export default class Company {
  @prop({ required: true })
  public companyName: string;

  @prop({ ref: () => User })
  public users: Ref<User>[];
}

export const CompanyModel = getModelForClass(Company);
```

`Property 'companyName' has no initializer and is not definitely assigned in the constructor.`
`Property 'users' has no initializer and is not definitely assigned in the constructor.`

I cannot find any example in the documentation regarding usage of the constructor.  Can someone help me understand what i'm missing based on the docs?

**Comment by hasezoey** [comment]
this error means you have either `strictPropertyInitialization` or `strict` enabled in the tsconfig, this means you need to use `!` & `?` between property name and `:` (`public propName?: Type;`)

examples: https://typegoose.github.io/typegoose/docs/guides/quick-start-guide

**Comment by lostrouter** [comment]
thanks for clearing that up.
