### ISSUE TITLE
[Question] Are transactions supported for deleteMany?

### ISSUE THREAD

**Issue by Tobjoern** [typegoose/typegoose#343]
Hey, I noticed that the 'session' option (used for transactions) is not supported in the types (at least).
Now I'm wondering if it is at all supported for deleteMany?
Reading up online I noticed that deleteMany [wasn't supported](https://github.com/Automattic/mongoose/issues/6805) for quite a while, but now transactions are [supported](https://mongoosejs.com/docs/api.html#query_Query-setOptions) on all operations.

Is this a mistake, or are transactions not supported?

**Comment by smolinari** [comment]
See this issue: https://github.com/typegoose/typegoose/issues/279

Maybe it might help.

Scott

**Comment by Tobjoern** [comment]
> See this issue: #279
> 
> Maybe it might help.
> 
> Scott

I'm aware of how to use transactions. I have no problem using them on other operations, like 'deleteOne':

```
    await SomeModel.deleteOne({}, {
        session: session
    })
```

the function is nicely typed, so it works perfectly. The problem is with deleteMany in particular, as it doesn't have a parameter for options, where the session object could be supplied:

```
    await SomeModel.deleteMany({

    }, {
        session: session // this throws a type error!
    })
```

So I'm wondering if the type was forgotten, or it in fact wasn't implemented yet.

**Comment by hasezoey** [comment]
does it work on runtime (ts-ignore)?

**Comment by Tobjoern** [comment]
After investigating the issue further, I found out that the deleteMany function is fully implemented via mongoose, I thought it was proxied through typegoose, but it wasn't. After updating mongoose and @types/mongoose to the latest version, I'm now able to pass in { session } as the second argument, without any type errors.

Thanks for your help!
