### ISSUE TITLE
 Cast to ObjectId failed for value "xxx" at path "yyy" for model "zzz"

### ISSUE THREAD

**Issue by InsOpDe** [typegoose/typegoose#345]
## Versions

- NodeJS: v13.13.0
- Typegoose(NPM): 7.3.1
- mongoose: 5.9.27
- mongodb: bitnami/mongodb:latest (docker)

## What is the Problem?

When trying to find by reference the error in the title gets thrown:
> Cast to ObjectId failed for value \"73ea91d1-d0fe-42a2-8a76-8debdbbdef44\" at path \"status\" for model \"UserStatusClass\"
```typescript
		const result = await userStatusModel
			.findOne({
				"status": statusId,
				userId
			})
			// .populate("status")
```
Where `statusId` is a `uuid`. Now it seems logical that i cannot cast a `uuid` to a `ObjectId` but I declared my schema like this:

## Code Example
```typescript
// BaseModel.ts
import {v4 as uuidv4} from "uuid";
@pre<BaseModel>("save", function (next) {
	if (!this._id) {
		this._id = uuidv4()
	}
	next()
})
export class BaseModel extends Base<string> {
	@prop()
	public _id!: string
}
```
```typescript
// StatusClass.ts
export class StatusClass extends BaseModel {
}
```
```typescript
// UserStatusClass.ts
export class UserStatusClass extends BaseModel {
	@prop({
		ref: StatusClass,
		select: false
	})
	status!: Ref<StatusClass>
	@prop({
		required: true
	})
	userId!:string
}
```

## Do you know *why* it happens?

I assume that typegoose (or mongoose) tries to cast the provided `uuid` to `ObjectId` because it does not know that the referenced `id` is of type `string`.

if I try it via cli it works:
```javascript
db.userstatusclasses.find({
    userId: "userId1",
    status: "73ea91d1-d0fe-42a2-8a76-8debdbbdef44"
})
```

**Comment by hasezoey** [comment]
you have 2 problems in your code:
- if you have an empty class, it is like an runtime `any` so you should always add at least one prop (even if it just an dummy)
- in `UserStatusClass.status` you are not setting the ref-type, which is automatically inferred for the type (if Base is extended) but for the runtime you need to set it manually with option `type: String`

so your final `UserStatusClass` should look like:
```ts
export class UserStatusClass extends BaseModel {
  @prop({
    ref: StatusClass,
    select: false,
    type: String
  })
  status!: Ref<StatusClass>;
  @prop({
    required: true
  })
  userId!: string;
}
```
and your `StatusClass`
```ts
export class StatusClass extends BaseModel {
  @prop() // optional property, and because of "any" will warn on runtime that it is "Mixed" (good for not forgetting this is just an dummy)
  dummy: any; 
}
```

**Comment by InsOpDe** [comment]
Thank you so much for your input!
Actually setting the type solved my problem. I could not find this part anywhere in the docs.
(As for the empty class: I just wanted to provide a minimal example, but thanks for the clarification anyway!)
I will close this issue, but maybe we could add this to the docs here: https://typegoose.github.io/typegoose/docs/guides/advanced/reference-other-classes
