### ISSUE TITLE
How to deal with circularity in hooks?

### ISSUE THREAD

**Issue by Tobjoern** [typegoose/typegoose#346]
Hi,
In my project I have one model 'user', and one model 'custom media'.
One user can have multiple custom medias, which is no problem, as it is a one sided dependency.
But, I want to remove all custom medias from the db, once a user is deleted, using a 'remove' hook.
This means User->CustomMedia->User...
When I run the code I provided I get the following error:
Error: There is no metadata for the "user" property.
This error makes absolute sense, but I'm unsure how I should deal with this problem.

Abridged Code:

```ts
//User.ts
@pre<User>('remove', async function (next) {
    const user = this

    await CustomMediaModel.deleteMany({
        user
    })

    next();
})

//CustomMedia.ts
class CustomMedia extends TimeStamps {
    @prop({ ref: 'user' })
    user!: User;
}
```

Thanks for your guidance :)

## Versions

- typegoose: ^6.5.0
- mongoose: ^5.9.28

**Comment by hasezoey** [comment]
firstly, you are using an outdated version of typegoose, secondly how does this error make sense? and aside from that, without an custom name the ref would need to be `User` from what i know (case sensitive)

**Comment by Tobjoern** [comment]
Sorry for the confusion, I thought this was a widespread problem, and that the error was justified, because the two models depend on each other, and are imported directly, but I failed to reproduce the problem in an isolated environment.

Thanks for your help
