### ISSUE TITLE
Independence from NodeJS

### ISSUE THREAD

**Issue by wcjord** [typegoose/typegoose#347]
## Describe what you need | want

I'd like typegoose to be able to run in a browser. For that, we should not use any NodeJS built-in functions.

## Do you have already an idea for the implementation?

Ye! 

We can use the libraries format-util and util-deprecate in lieu of the functions from the NodeJS util library. The only bigger mod needed is to change the tests in warnings.test.ts to something that doesn't use the "mock" property of the deprecate function.

Before using anything like "process," we should check it exists. We can add something like this:

`export function isNodeJs(): boolean {
  return typeof process === 'object' && typeof module !== 'undefined' && module.exports;
}`

Tracker Issues:
- #344 util-deprecate
- #348 format-util

**Comment by hasezoey** [comment]
> that doesn't use the "mock" property of the deprecate function.

then couldnt we just mock the *new* deprecate function form the package?

**Comment by wcjord** [comment]
I supposed so. We can probably import the function into utils, add that functionality, and use the new function elsewhere. I'm not really sure what the "mock" is doing.

**Comment by Birbe** [comment]
How do you propose that it would even be *used* in the browser?

**Comment by wcjord** [comment]
I've defined all my models and interfaces in a library that is shared by the client and the server.

**Comment by hasezoey** [comment]
@Birbe mongoose has browser support, as in: schema & model creation, validation, but not actual querys, and because typegoose is just about schema & model creation, it could support it

-> but there are also other ways, like typegraphql or similar things

**Comment by hasezoey** [comment]
@wcjord 
> I'm not really sure what the "mock" is doing.

the mock is just *an empty function* just so that the deprecation warning is not send to the console (to not spam)

**Comment by hasezoey** [comment]
i tried replacing `util.format` with `format-util`, which did not work because it is an ESModule
and i wanted to ask, if using typegoose on an client, wouldnt it usually be packed with either browerify or webpack? when yes, shouldnt the package [`util`](https://www.npmjs.com/package/util) be automatically installed (which is more-or-less an drop-in replacement)?

**Comment by wcjord** [comment]
My app has web pack but I was getting a util module not found error so I guess not? Maybe with browserify. I don’t know.

Some honest user feedback: 

Even with Typegoose, I still had to manually define the modified results with .select, .lean, .populate mongoose queries which was one of the big things I was hoping to get from it. I think I understand now that was not possible to do automatically. 

I kept having little issues with things like a string not wanting to be assigned to Ref<Doc> and the various issues trying to make the same library work on the client. Then the final straw was mongoose documents inexplicably not supporting the ‘myDoc.myprop’ style of getting and setting variables.

For me, the big problem Typegoose solves is the human errors of defining interfaces and schema separately. But, I ran into too many snags chasing that. I’m more interested now in finding a lighter way of just checking against the two, maybe at runtime would be fine.

**Comment by hasezoey** [comment]
i just wanted to confirm if it actually is autoinstalled, because that is what i read on `util`'s README, but it seems like it is only browerify where it is automatically installed
-> did you already try just installing ´util´ manually and running typegoose?

**Comment by hasezoey** [comment]
@wcjord with dd3436c95fbc6623f2e41f13f49d4aaa6733913f and e1bae1a641212896161ca6e081b4d067159a839b the tracker issues got closed, could you try typegoose on client again with latest master?

**Comment by wcjord** [comment]
Yep! It’s working on the client for me!

**Comment by hasezoey** [comment]
closing because original goal is reached
