### ISSUE TITLE
Warning of use mongoose's `ensureIndex` method is deprecated

### ISSUE THREAD

**Issue by radAragon** [typegoose/typegoose#349]
## Versions

- NodeJS: 12.18.2
- Typegoose(NPM): 7.3.1
- Typegoose(GIT): commithash
- mongoose: 5.9.24
- mongodb: 3.5.9

## What is the Problem?

Warning received `"ERROR	(node:8) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead."`

## Code Example

```ts
// a very basic example of property index, although it also happens with @index model
class Asset {

  @prop({ index: true })
  myIndexedProp: string
}
```

## Do you know *why* it happens?

Typegoose calls in the background the Mongoose **deprecated** function `ensureIndex`.

**Comment by smolinari** [comment]
You need to set `useCreateIndex: true` in your Mongoose connection config.

https://mongoosejs.com/docs/deprecations.html#ensureindex

Scott

**Comment by hasezoey** [comment]
closing, because @smolinari already gave the answer to this error
