### ISSUE TITLE
Is it possible to use my mongoose instance in typegoose

### ISSUE THREAD

**Issue by Timmatt-Lee** [typegoose/typegoose#356]

**Comment by hasezoey** [comment]
please explain what you mean with `mongoose instance`, do you mean schema option `existingMongoose` or `existingConnection` or something else?

**Comment by Timmatt-Lee** [comment]
like this
`import { Mongoose: myMongooseInstance } from 'mongoose'`
I would love to pass `myMongooseInstance` to typegoose, and let typegoose use my mongoose instance

**Comment by hasezoey** [comment]
i dont know what type your value is, but i think you are searching for https://typegoose.github.io/typegoose/docs/api/decorators/model-options#existingmongoose

**Comment by Timmatt-Lee** [comment]
I think I found the point. Here is the line that I can use my mongoose instance.
I wonder if i can use my mongoose instance when `buildSchema`
https://github.com/typegoose/typegoose/blob/master/src/typegoose.ts#L129

**Comment by hasezoey** [comment]
sorry i still dont understand you then, please clarify: do you mean an `Mongoose Instance` or `Mongoose Connection` or `Mongoose Schema`?

**Comment by Timmatt-Lee** [comment]
Accurately saying, in this line
https://github.com/typegoose/typegoose/blob/2199d9eb67ca0e7827f2cdaf2b0b8bb55f1e6a4c/src/internal/schema.ts#L50
`const Schema = mongoose.Schema;`
I would like to use my mongoose instance
`const Schema = myMongooseInstance.Schema`
and `myMongooseInstance` is from `import { Mongoose: myMongooseInstance } from 'mongoose'`
the type of `myMongooseInstance` is mongoose module itself
the expression is equal `import * as myMongooseInstance from 'mongoose'`

For clarify, I want to use my `Mongoose Instance` to get `Mongoose Schema`
and **new** this custom `Mongoose Schema` in 
https://github.com/typegoose/typegoose/blob/2199d9eb67ca0e7827f2cdaf2b0b8bb55f1e6a4c/src/internal/schema.ts#L67
`sch = new Schema(schemas.get(name), schemaOptions);`

**Comment by hasezoey** [comment]
currently not possible without overwriting (/mocking) `mongoose.Schema` itself
-> why would you need this, what is the practical use of this?

**Comment by Timmatt-Lee** [comment]
We have two servers connecting one db.
In db repo we use mongoose to build model.
but every mongoose instance in db repo is passed from above either two server repo.
for the reason because we want to have mongoose validation or some mongoose functions in two server repo.
However, if we let db repo init its mongoose instance, and passed it to server repos, validation and those required mongoose functions will be invalid.
That's our workaround.
Init mongoose instance at top layer (server repo), and pass it to db repo.
To make all work, we need to use our mongoose instance build everything in db repo.
We've tried use your default mongoose instance to build models.
But, same, it does not work.

**Comment by hasezoey** [comment]
so if i understand correctly and put it shortly, you have an "abstract package" to share functions between 2 similar projects connection to different servers?

**Comment by Timmatt-Lee** [comment]
exactly

**Comment by hasezoey** [comment]
its currently not possible, but if that are just instance methods, model methods, hooks or virtuals, why dont just make an default class and extend all others from that?
https://typegoose.github.io/typegoose/docs/guides/quick-start-guide#extra-examples

**Comment by Timmatt-Lee** [comment]
the main reason we want to construct like that (like below)

A server   B server
             \    /
              db

`db` define model and schema. it is the pce we would like to use typegoose.

`A` and `B` provide mongoose instance to `db`, for the sake of `A` or `B` can validate **sub document** of models in `db`. We've tried `db` use it's own mongoose instance to build model. it lead to sun document validation invalid when `A` or `B` access the model. That's why we need to pass mongoose instance from `A` or `B` to `db`.

**Comment by hasezoey** [comment]
Reopen because of new activity: #511

**Comment by Timmatt-Lee** [comment]
It seems like no error, I'll keep tracking this issue. Once there is any issue related to this, i'll reopen it.

**Comment by dickeylth** [comment]
> its currently not possible, but if that are just instance methods, model methods, hooks or virtuals, why dont just make an default class and extend all others from that? https://typegoose.github.io/typegoose/docs/guides/quick-start-guide#extra-examples

I'm wondering if it's possible to be set via `setGlobalOptions` API?

**Comment by hasezoey** [comment]
@dickeylth it may be possible to set those `schemaOptions` with `setGlobalOptions`, but it is not tested
