### ISSUE TITLE
Extending the TimeStamps class results in MongoError: Updating the path 'createdAt' would create a conflict at 'createdAt'

### ISSUE THREAD

**Issue by trydalch** [typegoose/typegoose#358]
## Versions

- NodeJS: 14.2.0
- Typegoose(NPM): 7.3.4 
- Typegoose(GIT): commithash
- mongoose: ^5.10.2
- mongodb: 4.4.0

## What is the Problem?

I'm attempting to do a Model.findByIdAndUpdate(), which is resulting in `MongoError: Updating the path 'createdAt' would create a conflict at 'createdAt'`. 

## Code Example

```ts
class User extends TimeStamps {

  id: any; 
  

  @prop()
  email?: string;

  @prop()
  password?: string;

  @prop()
  firstName?: string;

  @prop()
  lastName?: string;

  @prop({ enum: Gender })
  gender?: Gender;

  constructor(data: { email?: string, password?: string, firstName?: string, lastName?: string, gender?: Gender, createdAt?: Date, updatedAt?: Date, _id: any }) {
    super();
    this.email = data.email || undefined
    this.password = data.password
    this.firstName = data.firstName
    this.lastName = data.lastName
    this.gender = data.gender
    this.id = data._id
    this.createdAt = data.createdAt
    this.updatedAt = data.updatedAt
  }
}

const UserModel = getModelForClass(User, { schemaOptions: { timestamps: true } });

const updateTo = new User({firstName: 'updatedValue'})

await UserModel.findByIdAndUpdate('some-valid-id-here', updateTo, { useFindAndModify: false, omitUndefined: false, new: true })

```

(I've simplified here, but I'm actually getting the updateTo from req.body and the id from req.params.id, both are valid.)

If I remove the `extends TimeStamps`, the update performs as expected.

## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
if this is really not how it should be, it is not an typegoose problem, from what i know `createdAt` and `updatedAt` are automatically created (and updated) by mongoose (typegoose only provides the typescript types, and an class that sets `schemaOptions: { timestamps: true }`)

one thing i could suggest, try `.findByIdAndUpdate('some-valid-id-here', { $set: updateTo })`
