### ISSUE TITLE
Question about Types and the Save function

### ISSUE THREAD

**Issue by campbebj** [typegoose/typegoose#359]
I'm having isssues with typing in my typegoose setup

```ts
import { Base } from "@typegoose/typegoose/lib/defaultClasses";

export class User extends Base<string> {}
```
```ts
const userModel: ReturnModelType<typeof User, unknown> = getModelForClass(User);
const user: User = await userModel.findOne({ user: userId }).exec();
user.save();
```
typescript tells me i dont have a save method, when debugging javascript tells me the method is present, but i cant figure out how to get the typing correct to actually have the save method show up. 
I see it used in the [documenation](https://typegoose.github.io/typegoose/docs/api/decorators/prop/#type), but i cant seem to figure out what typing needs to be set to see that method.

## Versions
"mongoose": "^5.10.2",
"@typegoose/typegoose": "^7.3.4",

**Comment by hasezoey** [comment]
firstly, yes `ReturnModelType` has 2 generic, but only the first should be defined (the second is an side-product of the first)
secondly, your type `User` (which i guess is the Class), dosnt have any mongoose methods, and `findOne` dosnt return plain `User` - it returns (without `.orFail()`) `DocumentType<User> | null`

**Comment by campbebj** [comment]
Thanks a ton I'll try that. (also for the orFail)
