### ISSUE TITLE
Possiblity to get model type in constructor param!

### ISSUE THREAD

**Issue by shahidcodes** [typegoose/typegoose#360]
Hi, is it possible to get the model type in the constructor param?
Example code -
```javascript
const UserModel = getModelForClass(User);

const user = new UserModel({
// no type info here, 
})
```
Current signature shows this, as it can be seen type of `doc` is `any`
```javascript
new UserModel(doc?: any): DocumentType<Queue> (+1 overload)
```
Edit: 
Looking at `@types/mongoose` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/afb01664add8c74eccc86d14b10ba9a31728dc12/types/mongoose/v4/index.d.ts#L2450 it is there. Am I doing something wrong? 

## Versions

- typegoose: ^7.3.4
- mongoose: 5.9.9

**Comment by hasezoey** [comment]
the link you provided is for mongoose v4

**Comment by shahidcodes** [comment]
@hasezoey sorry my bad.
