### ISSUE TITLE
Array of methods in Post hook causing TS error

### ISSUE THREAD

**Issue by smolinari** [typegoose/typegoose#362]
## Versions

Node 12 LTS latest version.
Latest versions of Typegoose and Mongoose. 
nestjs/typegoose latest version 

## What is the Problem?

I'm trying to add multiple methods to a post hook...
@post(['find', 'findOne'], TypegooseMiddleware)
but, I'm getting this error from TS.
    Argument of type 'string[]' is not assignable to parameter of type '"insertMany"'.ts(2769)

## Do you know *why* it happens?

Not really. I have an idea, but my TS is so bad, I couldn't pinpoint the issue.

Scott

**Comment by hasezoey** [comment]
after writing about this in discord, i looked at this again, and noticed
`ModelMethod` (includes `insertMany`) is included in `QMR` which is included in `QDM`, which has an array form

and i couldnt get this error reproduced, could you provide an repro-script + tsconfig?

**Comment by smolinari** [comment]
I'm not going to be able to make a reproduction any time soon (like the next few days). So, I'll close this for now. Maybe someone else might run into the same problem and offer a reproduction. Or, if I find some time on the weekend, I'll try to make a reproduction. I did try to play with my tsconfig to see if that made a difference. No luck. 

Roger on the versions too. I'll admit, I was being lazy. 😊 

Scott

**Comment by nico29** [comment]
Hello, I'm currently facing the same issue.
I've put together a [sample repository](https://github.com/nico29/typegoose--post-no-overload) where this issue occurs.
Let me know how I can help.
Thank you.

**Comment by smolinari** [comment]
@hasezoey - Thanks for fixing this! :) 👍 

Scott

**Comment by nicolas-marien** [comment]
Thank you 🎄
