### ISSUE TITLE
Error message isn't very descriptive

### ISSUE THREAD

**Issue by NickBolles** [typegoose/typegoose#363]
It took me a bit to understand what this error meant

```
Error: Type of "Recipe.image" property is not a string.
```

I had converted the field from a string to a sub document. The cause was that I had left the `trim: true` option in the `@prop` decorator. 

It seems like a quick additional message could be added to [these errors](https://github.com/typegoose/typegoose/blob/master/src/internal/processProp.ts#L305-L316) that could help make this more descriptive.

**Comment by hasezoey** [comment]
Errors in typegoose could need a bit of an rework anyway

**Comment by NickBolles** [comment]
dang! that was quick!
