### ISSUE TITLE
How to autopopulate an array field by custom property

### ISSUE THREAD

**Issue by meirkl** [typegoose/typegoose#367]
## Versions

- typegoose: 7.3.3
- mongoose: 5.10.0

How to autopopulate an array filed based on custom field?
Iv'e tried:
```ts
@prop({
  ref: Source,
  type: [String],
  autopopulate: true,
})
sources?: Ref<Source, 'id'>[];
```
and I've added the `plugin` decorator to the model. 
I'm getting the flowing error:
```json
{
  "errors": {
    "sources.0": {
      "stringValue": "\"CApa3QJ38T\"",
      "kind": "ObjectId",
      "value": "CApa3QJ38T",
      "path": "sources.0",
      "reason": {},
      "$originalErrorPath": "sources"
    },
    "sources": {
      "stringValue": "\"[ 'CApa3QJ38T' ]\"",
      "kind": "Array",
      "value": [
        "CApa3QJ38T"
      ],
      "path": "sources",
      "reason": "sources"
    }
  },
  "_message": "Campaign validation failed",
  "message": "Campaign validation failed: sources.0: Cast to ObjectId failed for value \"CApa3QJ38T\" at path \"sources\", sources: Cast to Array failed for value \"[ 'CApa3QJ38T' ]\" at path \"sources\""
}
``` 
If I remove the `autopopulate: true` i can create a new document ans the `sources` field will contain an array of string.
If I add the `localField: 'sources'` and `foreignField: 'id'` properties the the document is saved without a `sources` field

Thanks!

**Comment by hasezoey** [comment]
if you use `type: [String]` below 7.4.0, it will result in an Mixed (this got added in 7.4.0) - for this version use `type: String`
and otherwise i dont think `, 'id'` is an correct `RefType`
