### ISSUE TITLE
Swc compatibility

### ISSUE THREAD

**Issue by PabloSzx** [typegoose/typegoose#368]
Recently [swc](https://github.com/swc-project/swc) released support for decorators and metadata, but at first glance when I tried to use [swc-node](https://github.com/Brooooooklyn/swc-node) for improved performance in a project with TypeGraphQL + Typegoose, I encountered the bug somewhat related to “ts-node —transpile-only” over the **enums** not being recognized correctly. ~~I hope that later today I will be able to give a minimal reproduction repo of the problem~~.

Reproduction here: https://github.com/PabloSzx/typegoose-swc

**Comment by hasezoey** [comment]
already an known issue, https://typegoose.github.io/typegoose/docs/guides/known-issues#transpile-only

**Comment by PabloSzx** [comment]
> already an known issue, https://typegoose.github.io/typegoose/docs/guides/known-issues#transpile-only, the only way to fix it, is always manually providing the type with `PropOptions.type`

The docs don't explicitly say "type: String" for enums when it happens, that should be added, but at the same time, why not the code can simply add it automatically if `enum` field is specified?.

The reproduction repo is there, and specifying `type: String` seems to work fine, and the enum validation still applies via mongoose

**Comment by hasezoey** [comment]
> The docs don't explicitly say "type: String" for enums when it happens, that should be added, but at the same time, why not the code can simply add it automatically if enum field is specified?.

because since an 5.9.x version of mongoose, enums can be numbers too

> and the enum validation still applies via mongoose.

yes, but typegoose transforms the typescript-enums to the mongoose-consumeable array

> why not the code can simply add it automatically if enum field is specified?.

currently in typegoose the enum-translation code is based on "if string then that, if number then that", yes *it could* figure it out, but this would require more complex code (pr's welcome)

**Comment by PabloSzx** [comment]
Fair, I think this issue doesn't need to be open then, but pretty sure it still was useful to be created if somebody else encounters the same situation, thanks 😁
