### ISSUE TITLE
Debugging experience with getters and setters

### ISSUE THREAD

**Issue by Christilut** [typegoose/typegoose#369]
![image](https://user-images.githubusercontent.com/3471363/92609230-a1c17000-f2b6-11ea-8d74-ede7ebfd0f18.png)

I'm seeing the above everywhere typegoose/mongoose related when I debug in VSCode. This used to be better, but I think a recent VSCode version caused this, since they started upgrading the debug experience (which in other places does work better).

The getters and settings used to be just readable like a normal object.

Is this a Typegoose problem or maybe caused by my tsconfig? I have no idea where to start looking or asking here.

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es2017",
    "outDir": "dist",
    "rootDir": "",
    "moduleResolution": "node",
    "module": "commonjs",
    "sourceMap": true,
    "declaration": false,
    "importHelpers": true,
    "incremental": true,
    "listFiles": false,
    "traceResolution": false,
    "pretty": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2017",
      "dom",
      "esnext"
    ],
    "types": [
      "node",
      "long"
    ],
    "baseUrl": "."
  },
  "include": [
    "**/*.ts"
  ],
  "compileOnSave": false
}
```

## Versions

- typegoose: 7.3.5
- mongoose: 5.10.3

**Comment by hasezoey** [comment]
i dont see anything wrong within the screenshot, and what problem are you speaking about?

**Comment by Christilut** [comment]
It used show the property values instead of `get` and `set` for each property

**Comment by hasezoey** [comment]
didnt know that, but from what i can tell, this has nothing to do with your tsconfig, either this is an setting in the nodejs debugger to vscode debugger or they changed it without an setting back

**Comment by Christilut** [comment]
Okay, I'll look around in there, thanks!
