### ISSUE TITLE
Overwrite option to disable default usage of $set is missing from types

### ISSUE THREAD

**Issue by vincent-chapron** [typegoose/typegoose#372]
## Versions

- NodeJS: 12.18.3
- Typegoose(NPM): 7.3.5
- mongoose: 5.10.0
- mongodb: 3.6.2
- nestjs / nestjs-typegoose: 7.4.2 / 7.1.32

## What is the Problem?

I want to use `overwrite` option in `findOneAndUpdate` to disable default usage of `$set`, but option is missing in types.

## Code Example

```ts
await ObjectModel.findOneAndUpdate(
    { _id: currentObjectId },
    { foo: 'bar' },
    { overwrite: true }, // error TS2769: No overload matches this call.
);
```

> The last overload gave the following error.
>     Argument of type '{ overwrite: boolean; }' is not assignable to parameter of type 'QueryFindOneAndUpdateOptions'.
>       Object literal may only specify known properties, and 'overwrite' does not exist in type 'QueryFindOneAndUpdateOptions'.

`overwrite` is a valid option in mongoose: https://mongoosejs.com/docs/api.html#query_Query-update

for now I bypass using `as any`:

```ts
await ObjectModel.findOneAndUpdate(
    { _id: currentObjectId },
    { foo: 'bar' },
    { overwrite: true } as any,
);
```

code runs and $set is disabled.

## Do you know *why* it happens?

`overwrite?: boolean` is not define in types

**Comment by hasezoey** [comment]
not an typegoose issue, please report in https://github.com/DefinitelyTyped/DefinitelyTyped/issues
