### ISSUE TITLE
One schema out of many isnt being picked up.

### ISSUE THREAD

**Issue by campbebj** [typegoose/typegoose#373]
## Versions
(npm)
"@typegoose/typegoose": "^7.3.4"
"mongoose": "^5.10.2"

## What is the Problem?

one of my typegoose schemas isnt being picked up by typegoose when i start it up.

## Code Example

Class defined
```ts
import { modelOptions, prop } from "@typegoose/typegoose";
import { Base } from "@typegoose/typegoose/lib/defaultClasses";

@modelOptions({ schemaOptions: { collection: "skills", autoIndex: true } })
export class Skill extends Base<string> {
    @prop({ required: true })
    public name!: string;

    @prop({ required: true })
    public description!: string;

    @prop({ required: true })
    public source!: string;

    @prop({ required: true })
    public sourceLink!: string;
}
```
referenced here
```ts
@prop({ ref: Skill, autopopulate: { skipInvalidIds: true } })
public skills!: Array<Ref<Skill>>;
```
I get the following error
```
MissingSchemaError: Schema hasn't been registered for model "Skill".
```

If i debug and view the mongoose connection object and the list of models it lists all of my other models defined in the same manner in the same folder.

## Do you know *why* it happens?

Something is probably happening when registering the model.

Is there some place i can debug the initial processing of the model to see whats going wrong?

**Comment by campbebj** [comment]
nvm figured it out on my own

**Comment by VottusCode** [comment]
Okay, you know what no. I hate this, it happens all the time. People open an issue, asking for help, but then they figure it out and say "nvm figured it out on my own" and close it, without saying what actually was the issue.

**Comment by hasezoey** [comment]
@campbebj could you please provide how you solved it / what was actually wrong?

**Comment by campbebj** [comment]
I wasn't using the model directly anywhere, only as a reference, so I
hadn't ever called classToModel. I went and made a setup method that called
classToModel on all the model classes and that did the trick.

Sorry for not putting it in the closing comment. Was more embarrassed than
anything.
