### ISSUE TITLE
Using @prop decorator fails (over @arrayProp)

### ISSUE THREAD

**Issue by yurivangeffen** [typegoose/typegoose#374]
I recently started using `typegoose` for a project and the premise is very appealing. Trying it out I'm running into a validation error which I can't seem to resolve. It is related to an array type. I have a Project and ProjectModel defined like this:

```typescript
class Project {
  @prop({ type: mongoose.Types.ObjectId, required: true })
  public users!: mongoose.Types.ObjectId[];

  @prop({ type: mongoose.Types.ObjectId, required: true })
  public owners!: mongoose.Types.ObjectId[];

  <...>
}

const ProjectModel = getModelForClass(Project);
```

Then I try to populate the database with a simple create like this:
```typescript
ProjectModel.create({ 
  users: new Array<mongoose.Types.ObjectId>(), //one kind of initialization
  owners: [] // another kind
})
  .then((project) => console.log('Added test project:', project));
```

However, the creation validation fails with the following message: `CAUGHT Error: Project validation failed: users: Cast to ObjectId failed for value "[]" at path "users", owners: Cast to ObjectId failed for value "[]" at path "owners"`. It seems that both ways fail because of the inability to cast `"[]"` to an ObjectId (which makes sense to me, but why the casting?).
However, when I replace both `@prop`s with an `@arrayProp`, the document does get created. 

- How do I properly insert an empty array?
- Also, is there a better way to link to other types (using an ObjectId in the database, but populating returned documents)?

## Versions

- typegoose: 7.3.5
- mongoose: 5.10.3

Edit: I am aware that the actual type checking is not done by typegoose, but it does give mongoose different types than I mean to, hence the question here :+1: .

**Comment by smolinari** [comment]
> Also, is there a better way to link to other types (using an ObjectId in the database, but populating returned documents)?

Yes, it's called references or refs with populate. 

https://mongoosejs.com/docs/populate.html
https://docs.mongodb.com/manual/reference/database-references/
https://typegoose.github.io/typegoose/docs/api/decorators/prop#ref

```ts
class Project {
  @prop({ ref: 'User', required: true })
  public users!: Ref<User>[];

  @prop({ ref: 'Owner', required: true })
  public owners!: Ref<Owner>[];

  <...>
}
``` 

I'm also using the autopopulate plugin. 

https://plugins.mongoosejs.io/plugins/autopopulate

Scott

**Comment by hasezoey** [comment]
if @smolinari answer dosnt help, could you provide the schema? with `console.log(ProjectModel.schema.path('users'))` and [debug output from typegoose](https://typegoose.github.io/typegoose/docs/guides/advanced/logger#set-the-loglevel)?

**Comment by yurivangeffen** [comment]
@smolinari That might be the way to go yes. It would be nice if the fields could be auto-populated somehow (with a flag or otherwise), but good to know that that's the way to go.

@hasezoey This is the DEBUG output:
```
Added "Project.users" to the Decorator Cache
Added "Project.owners" to the Decorator Cache
buildSchema called for "Project"
Assigning global Schema Options to "Project"
_buildSchema Called for Project with options: {}
Detecting WhatIsIt
Starting to process "Project.users"
Detecting WhatIsIt
Starting to process "Project.owners"
Class "Project" already existed in the constructors Map
```
and the schema for 'users':
```ObjectId {
  path: 'users',
  instance: 'ObjectID',
  validators: [
    {
      validator: [Function],
      message: 'Path `{PATH}` is required.',
      type: 'required'
    }
  ],
  getters: [],
  setters: [],
  options: SchemaObjectIdOptions {
    type: [Function: ObjectId] {
      schemaName: 'ObjectId',
      defaultOptions: {},
      get: [Function],
      set: [Function: set],
      _checkRequired: [Function],
      _cast: [Function: castObjectId],
      cast: [Function: cast],
      checkRequired: [Function]
    },
    ref: 'ObjectID',
    required: true
  },
  _index: null,
  isRequired: true,
  requiredValidator: [Function],
  originalRequiredValue: true,
  [Symbol(mongoose#schemaType)]: true
}
```

**Comment by hasezoey** [comment]
@yurivangeffen yes, the debug-log and the schema output are definitely wrong, are you sure you are using the right package & version?

**Comment by yurivangeffen** [comment]
This is the output of yarn list for both mongoose and typegoose:

```
├─ @typegoose/typegoose@7.3.5
│  ├─ lodash@^4.17.19
│  ├─ loglevel@^1.6.8
│  ├─ reflect-metadata@^0.1.13
│  ├─ semver@^7.3.2
│  ├─ semver@7.3.2
│  └─ tslib@^2.0.0
├─ mongoose@5.10.5
│  ├─ bson@^1.1.4
│  ├─ kareem@2.3.1
│  ├─ mongodb@3.6.2
│  ├─ mongoose-legacy-pluralize@1.0.2
│  ├─ mpath@0.7.0
│  ├─ mquery@3.2.2
│  ├─ ms@2.1.2
│  ├─ regexp-clone@1.0.0
│  ├─ safe-buffer@5.2.1
│  ├─ sift@7.0.1
│  └─ sliced@1.0.1
├─ @types/mongoose@5.7.36
│  ├─ @types/mongodb@*
│  └─ @types/node@*
```
(I updated mongoose to 5.10.5 in the meantime, that doesn't make a difference though)

**Comment by hasezoey** [comment]
did you already try an re-install / re-generate of the lock file (and look in there)? because this shouldnt be happening since ~7.1
-> i dont think this will change anything in this case, but maybe try to upgrade to typegoose@next (7.4.0-3)

**Comment by yurivangeffen** [comment]
I regenerated everything (node-modules and yarn.lock) before that post. Will change to next and see if it changes anything :+1: . Thanks for the help!

**Comment by yurivangeffen** [comment]
Still experiencing the same on `next` with the following model (incorporated the suggestion of using Ref):
```typescript
class Project {
  @prop({ ref: () => User, required: true })
  public users!: Ref<User>[];

  @prop({ ref: () => User, required: true })
  public owners!: Ref<User>[];
}

const ProjectModel = getModelForClass(Project);
```

**Comment by yurivangeffen** [comment]
I'll create a minimal project.

**Comment by yurivangeffen** [comment]
@hasezoey https://github.com/yurivangeffen/array-typegoose here you go!

**Comment by smolinari** [comment]
> It would be nice if the fields could be auto-populated somehow

That is what the autopopulate plugin is for. You can also control the level of depth for recursive refs, like a "Last Modified By" field being a user on a User document. 

Scott

**Comment by hasezoey** [comment]
easy solution, you are missing `"emitDecoratorMetadata": true` in the tsconfig

**Comment by yurivangeffen** [comment]
That indeed solves the issue! Thanks for the support :+1:.
