### ISSUE TITLE
@types this variable in default option function of a prop

### ISSUE THREAD

**Issue by ricosandyca** [typegoose/typegoose#379]
Hello,

Refers to [this](https://mongoosejs.com/docs/defaults.html#default-functions-and-this) documentation, there's still no types suggestion for `this` variable in default option on a prop that refer to the other properties in the library. It's just showing warning types, but working properly

## Version
```
mongoose: ^5.10.4
@types/mongoose: ^5.7.36
@typegoose/typgoose: ^7.3.5
typescript: ^4.0.2
```

**Comment by hasezoey** [comment]
i dont see an way to implement this without the user specifying at least *something*

currently the only way to do it is set it yourself: `default: function (this: DocumentType<Class>) {}`

and the only way i see to implement this is to set an generic on the decorator, which would need to be provided (from what i know, it cannot be inferred)
