### ISSUE TITLE
Getters and setters on props

### ISSUE THREAD

**Issue by josepmorey** [typegoose/typegoose#38]
Hi!

Why prop decorator don't accept get and set option? Thanks

[https://mongoosejs.com/docs/tutorials/getters-setters.html](url)

**Comment by hasezoey** [comment]
When you ask such question(s), please always provide which versions you are using (mongoose & typegoose)

**Comment by hasezoey** [comment]
pushed it, when travis has build & github has updated, it can [be found here](https://hasezoey.github.io/typegoose/docs/decorators/prop/#get--set)

**Comment by hasezoey** [comment]
Closing this because `get` & `set` are confirmed working, but only in version 6
