### ISSUE TITLE
Allow nested paths (no schemas)

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#382]
## Describe what you need | want

Allow nested paths like in mongoose, without wrapping it in an schema:
```ts
new Schema({
  nested: {
    another: String
  }
})
```

## Do you have already an idea for the implementation?

maybe using an custom wrapper class named like `new Passthrough({})` (`{}` can be an normal mongoose path or an class that will get compiled down without an schema)

**Comment by harrycollin** [comment]
@hasezoey I would absolutely love to see this. I'm currently battling having to use nested schemas for complex types.

**Comment by smolinari** [comment]
👍 from me too!

Scott

**Comment by fmonper1** [comment]
Yes please, i really need this

**Comment by wise-introvert** [comment]
I second this.

**Comment by hasezoey** [comment]
i just noticed in an unrelated testing that nested paths without an extra schema are actually of type `Mixed` (at least in mongoose 5.13.x)

**Comment by hasezoey** [comment]
PR #578 adds the `Passthrough` class, it will not be merged for now, because it still needs some testing to see if it is done right and if it has any side-effects (feedback welcomed on the PR)
