### ISSUE TITLE
Can't set a default for a field belonging to a subdocument in a subdocument array

### ISSUE THREAD

**Issue by thomas901** [typegoose/typegoose#384]
## Versions

- NodeJS: 14.9.0
- Typegoose(NPM): 7.4.0 
- Typegoose(GIT): commithash
- mongoose: 5.10.6
- mongodb: 3.6.2

## What is the Problem?

I'm trying to set a default for a field in a subdocument schema. In the parent schema, these subdocuments will be in an array and I want a default to apply to any subdocuments added to that array, including on creation. 

In the parent schema, if I use a single child subdocument, the default is set without any issues.

## Code Example

```ts
import { getModelForClass, prop } from "@typegoose/typegoose";
import mongoose from "mongoose";

export class Child {
  @prop({ default: "n/a" })
  public name?: string;
}

export class Parent {
  @prop()
  public child!: Child[];
}

const ParentModel = getModelForClass(Parent);

(async () => {
  await mongoose.connect("mongodb://localhost:27017", {
    useNewUrlParser: true,
    dbName: "verifyMASTER",
    useCreateIndex: true,
    useUnifiedTopology: true,
  });

  const parent = await ParentModel.create({ child: [{}] });

  console.log(parent.child); // doesn't have name default [[{}]]

  await mongoose.disconnect();
})();
```
Defaults work fine when using a single subdocument
```ts
// child is now a single Child subdocument
export class Parent {
  @prop()
  public child!: Child;
}
// creation
const parent = await ParentModel.create({ child: {} });

// result
{ name: 'n/a', _id: 5f6af6138dea594644e18580 }
```
## Do you know *why* it happens?

*no*

**Comment by smolinari** [comment]
Try it with 

`  @prop({ type: Child })`

https://github.com/typegoose/typegoose/issues/300
https://typegoose.github.io/typegoose/docs/api/decorators/prop#array-options
https://typegoose.github.io/typegoose/docs/api/decorators/prop#type

Scott

**Comment by thomas901** [comment]
> 
> 
> Try it with
> 
> ` @prop({ type: Child })`
> 
> #300
> https://typegoose.github.io/typegoose/docs/api/decorators/prop#array-options
> https://typegoose.github.io/typegoose/docs/api/decorators/prop#type
> 
> Scott

I spent hours on this, that worked perfectly. Thank you.
