### ISSUE TITLE
Problem when using an alias for a property 

### ISSUE THREAD

**Issue by kerolloz** [typegoose/typegoose#389]
## Versions

- NodeJS: v12.18.0
- @typegoose/typegoose: 7.4.1
- mongoose: 5.10.7
- @types/mongoose: 5.7.36
  

## What is the Problem?

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ email: string; password: string; }' is not assignable to parameter of type 'Pick<{ email: string; password: string; _password: string; _id: any; } & { _id: any; }, "email" | "password" | "_password"> & { _id?: any; }'.
      Property '_password' is missing in type '{ email: string; password: string; }' but required in type 'Pick<{ email: string; password: string; _password: string; _id: any; } & { _id: any; }, "email" | "password" | "_password">'.ts(2769)
user.ts(8, 3): '_password' is declared here.
index.d.ts(3301, 5): The last overload is declared here.
```

## Code Example

```ts
import { getModelForClass, prop } from "@typegoose/typegoose";

class User {
  @prop({ unique: true })
  email!: string;

  @prop({ alias: "password" })
  _password!: string;
  password!: string; // not stored in DB
}

export const UserModel = getModelForClass(User);

UserModel.create({ email: "email@email.com", password: "password" });

```

## Do you know *why* it happens?

*no*

![Screenshot from 2020-09-27 19-32-24](https://user-images.githubusercontent.com/36763164/94371667-76cd7d80-00f8-11eb-8ee1-950b78efe9e9.png)

**Comment by kerolloz** [comment]
I have to write the following to fix it 

```ts
UserModel.create({ email: "email@email.com", password: "password", _password: "password"  });
```

**Comment by hasezoey** [comment]
there is nothing typegoose can do about this, here are proposals to fix this:
- dont use `alias`
- replace `!` with `?` in `_password!:`
- use `any` in `.create<any>(`

**Comment by kerolloz** [comment]
So I should prefer **`new Model({ ...data }).save()`** syntax over ~`Model.create({ ...data })`~ syntax, right?

```ts
new UserModel({ email: "email@email.com", password: "password"  }).save()
```

**Comment by hasezoey** [comment]
i dont know if this was fast-typing, but the correct syntax would be

```ts
(new UserModel({ email: "email@email.com", password: "password"  })).save()
```

but actually, no, it would be more-or-less equal to create with `<any>`, but i would recommend the way to replace `!` with `?`

**Comment by kerolloz** [comment]
Okay. Thank you @hasezoey
