### ISSUE TITLE
How can I make sure that a referenced ID exists? 

### ISSUE THREAD

**Issue by kerolloz** [typegoose/typegoose#391]
Is there a way to prevent saving the document through validating that the provided ObjectID for the document really exists?

```ts
class A {
}

class B {
  @prop({ ref: () => A })
  myA!: Ref<A>;
}

const ModelB = getModelForClass(B);

const ID = "aaaaaaaaaaaaaaaaaaaaaaaa"; // a valid ObjectId that doesn't exist
const b = new ModelB({ myA: ID });
b.save(); // will save the document succesfully! the desired behaviour is to throw an error that 'myA' references a non existing ID
```

I have found this package https://github.com/CampbellSoftwareSolutions/mongoose-id-validator but it doesn't support TypeScript. 
any suggestions? or other packages that support TS?

**Comment by hasezoey** [comment]
from what i know, mongoose dosnt provide this by default, so you either have to create an [custom validator](https://mongoosejs.com/docs/validation.html#custom-validators) or use an [pre-save-hook](https://typegoose.github.io/typegoose/docs/guides/quick-start-guide#hooks)
-> but both options would need to execute an query on the target collection (with target model) to probe for that document
