### ISSUE TITLE
Write concern definition feature request

### ISSUE THREAD

**Issue by Kinetix-Lee** [typegoose/typegoose#395]
## Describe what you need | want

Will Typegoose support **write concern** definition while creating a schema? 

## Do you have already an idea for the implementation?

Typegoose uses mongoose, so write concern can be one parameter when definiting a schema. (But I'm not familiar with Typegoose' code, thus I have no realisation yet)

**Comment by smolinari** [comment]
You can put basically any schema option inside the `@modelOptions` decorator, including write concern. 

https://typegoose.github.io/typegoose/docs/api/decorators/model-options

Scott

**Comment by Kinetix-Lee** [comment]
> You can put basically any schema option inside the `@modelOptions` decorator, including write concern.
> 
> https://typegoose.github.io/typegoose/docs/api/decorators/model-options
> 
> Scott

Thanks for comment, I see, I'll check the docs before submitting an issue next time. 😅

**Comment by smolinari** [comment]
@Kinetix-Lee - Yes, always consult the docs first. But, also ask on the Typegoose Discord channel, if an issue is an issue. You'll get guidance from there, as to what to do. 

https://discord.gg/vYjz7F

Scott

**Comment by Kinetix-Lee** [comment]
Okay. Thank @smolinari again.
