### ISSUE TITLE
Injected model not working right with typings

### ISSUE THREAD

**Issue by sdunnin** [typegoose/typegoose#398]
Injected model not working right with typings

I thought I'd post this to the Typegoose experts since I'm flailing around a bit trying to get this right. I am using NestJS and injecting the model which is generated in a provider class into a generic CRUD service.

Provider Class
```ts
import { getModelForClass } from '@typegoose/typegoose';
import { Connection } from 'mongoose';

import { DATABASE_CONNECTION } from '@nevco-one/service-engine/mongo-database';
import { VenueDbModel, VENUE_DB_MODEL } from '@nevco-one/shared';

export const venuesProviders = [
  {
    provide: VENUE_DB_MODEL,
    useFactory: (connection?: Connection) => {
      if (connection) {
        return getModelForClass(VenueDbModel);
      }
    },
    inject: [DATABASE_CONNECTION]
  }
];
```
Model Class
```ts
export class VenueDbModel extends OrgResourceDbModel implements Venue {
  @prop({ type: mongoose.Schema.Types.ObjectId })
  orgId!: string;

  @prop({ required: true })
  belongsToOrg!: boolean;

  @prop({ required: true })
  name!: string;

  @prop()
  description?: string;

  @prop()
  logo?: string;

  //TODO: Turn into ref: after sport is converted to typegoose
  @prop()
  sportTypes?: string[];

  @prop()
  location!: LocationInfo;
}
```
Base Service
```ts
export class BaseService<
  R extends OrgResourceDbModel,
  D extends OrgRestResourceDto
> {
  constructor(
    protected readonly model: ReturnModelType<AnyParamConstructor<R>>,
    protected authService: AuthService
  ) {}

  async get(id: string): Promise<R> {
    const resource = await this.model.findById(id).exec();
    if (!resource) {
      throw new NotFoundException();
    }
    if (!this.authService.validateResourceOrg(resource.orgId)) {
      throw new ForbiddenException();
    }
    return resource;
  }

  async getAll(orgId: string): Promise<R[]> {
    const foo = await this.model.find({ orgId: orgId }).exec();
    return foo;
  }
  
  //... other crud methods
```

Generic Type class definitions
```ts
export class ResourceDbModel implements RestResource {
  public get id() {
    return this._id.toString();
  }
  public set id(val: string) {
    this._id = new mongoose.Types.ObjectId(val);
  }
  @prop({ default: mongoose.Types.ObjectId })
  _id!: mongoose.Types.ObjectId;
  ver!: number;
}

export class OrgResourceDbModel extends ResourceDbModel {
  @prop({ type: mongoose.Schema.Types.ObjectId })
  orgId!: string;
}
```

In the BaseService findById in get() does not complain but in getAll() Typescript does not like `orgId: string` and throws a "No overload matches this call" for model.find.  If I change to `orgId: any` it makes it happy and the code works as intended. This is not ideal of course and I'm sure there is something wrong in my typing but I am having a hard time trying to pin it down.

Any suggestions would be greatly appreciated.

## Versions
- typegoose: 7.4.1
- mongoose: 5.10.7

**Comment by hasezoey** [comment]
i would recommend to not use `AnyParamConstructor` outside of generic-constraints
-> so replace `protected readonly model: ReturnModelType<AnyParamConstructor<R>>,` with `protected readonly model: ReturnModelType<R>,` or `protected readonly model: ReturnModelType<typeof R>,` (i dont know which of them is the right one atm)

other than that, i dont see any wrong code related to typegoose / mongoose 

PS: 
- for property `sportTypes` you forgot to set option `type` [look here on why](https://typegoose.github.io/typegoose/docs/api/decorators/prop#array-options)
- as for return types, i would recommend to use `Promise<DocumentType<R>>` / `Promise<DocumentType<R>[]>` instead of current one (because that would be more correct, or use `.toObject()` and remove all functions from the return type)

**Comment by sdunnin** [comment]
@hasezoey thanks so much for the quick reply. What you mentioned for the constructor props makes sense but unfortunately TS still does not like it.
`ReturnModelType<R>` generates
```
Type 'R' does not satisfy the constraint 'AnyParamConstructor<any>'.
  Type 'OrgResourceDbModel' is not assignable to type 'AnyParamConstructor<any>'.
    Type 'OrgResourceDbModel' provides no match for the signature 'new (...args: any): any'.ts(2344)
```
and `ReturnModelType<typeof R>` generates
```
'R' only refers to a type, but is being used as a value here.ts(2693)
```

**Comment by hasezoey** [comment]
@sdunnin could you provide what `OrgResourceDbModel` is? is it an class, or maybe an abstract-class or maybe an interface?

**Comment by sdunnin** [comment]
It's up in my original post under _Generic Type class definitions_. It is a class having a property decorated with a Typegoose Prop decorator.

**Comment by sdunnin** [comment]
@hasezoey One other note regarding your suggestion to 
> recommend to use `Promise<DocumentType<R>>`

When I change the method return type to that it gives me a `Type 'DocumentType' is not generic.ts(2315)` error.

**Comment by hasezoey** [comment]
> It's up in my original post under Generic Type class definitions

sorry didnt see it below that `ResourceDbModel` class

> When I change the method return type to that it gives me a Type 'DocumentType' is not generic.ts(2315) error.

if you get that error, then you imported an wrong type

---

here is the code i used to make better types:
```ts
// NodeJS: 14.13.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, ReturnModelType } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.1
import { DocumentType } from "@typegoose/typegoose/lib/types";
import * as mongoose from "mongoose"; // mongoose@5.10.8 @types/mongoose@5.7.36

interface Venue { } // was not provided
interface RestResource { } // was not provided

class LocationInfo {
  @prop()
  public dummy?: string; // was not provided
}

export class ResourceDbModel implements RestResource {
  public get id() {
    return this._id.toString();
  }
  public set id(val: string) {
    this._id = new mongoose.Types.ObjectId(val);
  }
  @prop({ default: mongoose.Types.ObjectId })
  public _id!: mongoose.Types.ObjectId;
  public ver?: number;
}

const ResourceDbModelModel = getModelForClass(ResourceDbModel);

export class OrgResourceDbModel extends ResourceDbModel {
  @prop()
  public orgId?: string;
}

const OrgResourceDbModelModel = getModelForClass(OrgResourceDbModel);

export class VenueDbModel extends OrgResourceDbModel implements Venue {
  @prop({ required: true })
  public belongsToOrg!: boolean;

  @prop({ required: true })
  public name!: string;

  @prop()
  public description?: string;

  @prop()
  public logo?: string;

  @prop({ type: String })
  public sportTypes?: string[];

  @prop()
  public location!: LocationInfo;
}

const VenueDbModelModel = getModelForClass(VenueDbModel);

export class BaseService<R extends typeof OrgResourceDbModel> {
  constructor(
    protected readonly model: ReturnModelType<R>
  ) { }

  public async get(id: string): Promise<DocumentType<InstanceType<R>>> {
    const resource = await this.model.findById(id).exec();
    if (!resource) {
      throw new Error();
    }
    return resource;
  }

  public async getAll(orgId: string): Promise<DocumentType<InstanceType<R>>[]> {
    const foo = await this.model.find({ orgId } as any).exec(); // i dont know why this find type dosnt work
    return foo;
  }
}


(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const baseService1 = new BaseService(VenueDbModelModel);
  const baseService2 = new BaseService(ResourceDbModelModel); // i dont know why the "extends OrgResourceDbModel" constraint dosnt work (even without "typeof")

  await mongoose.disconnect();
})();
```
Notes:
- you dont need to specify `id`, because that adds mongoose already
- you dont need to defined an `@prop` on `_id` when the type is `ObjectId`
- with the provided code, i dont know why the `find` (`FilterQuery`) type dosnt work correctly and needs to be casted to `any`
- with the provided code, i dont know why the constraint `extends OrgResourceDbModel` (even without `typeof`) dosnt constrain (as seen in the async code)

**Comment by sdunnin** [comment]
Thanks for all the effort, I really appreciate it. I will look through your modifications to make improvements as needed.

One note on the `id` field. The reason for that is we want to expose `id` to the application rather than `_id` which would have been visible in the interfaces (such as Venue) that I did not supply.

**Comment by sdunnin** [comment]
Was able to clean up the injected model and remove AnyParamConstructor which results in `protected readonly model: ReturnModelType<R>`. 
Was also able to update the method response declarations `: Promise<DocumentType<InstanceType<R>>>` 

Still odd that I have to specify `any` type for the find query, as well as, on an updateOne query. I will try and investigate further as time permits but it seems to be working now.
