### ISSUE TITLE
[Question] Update data with findByIdAndUpdate

### ISSUE THREAD

**Issue by dgutoryan** [typegoose/typegoose#399]
Hello,

I use method `findByIdAndUpdate`. And I would like to change `updated` field (this is date) every time when I update document.

I've tried to do it with `@pre` and `@post` but nothing worked. Could you help me with this?

## Versions

- typegoose: 7.4.1
- mongoose: 5.10.8

**Comment by hasezoey** [comment]
please provide the class and how you tried in an hook

**Comment by dgutoryan** [comment]
Find and update document
```
public async update(id: string, exercise: ExerciseDto): Promise<void> {
    await this.exerciseModel.findByIdAndUpdate(id, exercise);

    return null;
}
```

Model
```
@modelOptions({ schemaOptions: { collection: 'exercises', versionKey: false } })
@pre<ExerciseEntity>('save', function (next: HookNextFunction) {
  this.created = DateTime.utc().toISO();
  this.updated = DateTime.utc().toISO();
  next();
})
@pre<ExerciseEntity>('findOneAndUpdate', function(next: HookNextFunction) {
  this.updated = DateTime.utc().toISO(); <--- Property 'updated' does not exist on type 'Query<ExerciseEntity>'
})
export class ExerciseEntity {
  @prop({ required: true, unique: true })
  public name: string;

  @prop()
  public created: string;

  @prop()
  public updated: string;
}
```

**Comment by hasezoey** [comment]
the error `Property 'updated' does not exist on type 'Query<ExerciseEntity>'` is because in the hook `findOneAndUpdate` the `this` object is not the document, but an query, so you have to modify the query

so you would have to do something like:
```ts
@pre<ExerciseEntity>('findOneAndUpdate', function(next: HookNextFunction) {
  this.updateOne(this.getFilter(), { $set: { updated: DateTime.utc().toISO() } });
})
```
-> i typed this in github comments, so i didnt try this code (but its something like this)

**Comment by dgutoryan** [comment]
This works. Thank you so much!
