### ISSUE TITLE
Better ModelType & ReturnModelType Documentation

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#40]
*Continuation of hasezoey#22*

Make Better Documentation of the difference between `ModelType` and `ReturnModelType`

Current situation: sometimes `ReturnModelType` cannot be used (needs repo script, because i cant find a case where it happens) and `ModelType` seems to solve it, but has actually not a good documentation on what it does

@Ben305 @B-Stefan

---

Help is appreciated, because i dont really understand what `ModelType` and `ReturnModelType` do differently (i know i made `ReturnModelType`, but only because i dont really understand `ModelType`) ... they seem to do the same thing, but actually dont

**Comment by Ben305** [comment]
@hasezoey Here's a small sample that contains the important parts: https://github.com/Ben305/typegoose-sample/blob/master/src/helper.ts

Any solution for this?

**Comment by B-Stefan** [comment]
Just to see the typing in this issue to understand what we are talking about:
````
export type ModelType<T> = mongoose.Model<DocumentType<T>> & T;

export type ReturnModelType<U extends NoParamConstructor<T>, T = any> = ModelType<InstanceType<U>> & U;`

```

@Ben305  @hasezoey  
If I understood the typing correctly the main difference is that ReturnModelType uses: `ModelType<InstanceType<U>>` instead of `ModelType<U>` which is more accurate because `InstanceType<U>` returns the class type of `U` and in `mongoose.Model<U>` U should be the class type. 

The current restriction of this solution is that `InstanceType<U>` doesn't support generics completely. See, https://github.com/Microsoft/TypeScript/issues/1213 and  https://stackoverflow.com/questions/52655236/typescript-instancetype-with-generic-parameter)

My suggestion would be that we just export `ModelType<U>` instead of `ModelReturnType<U>`. Are there any drawbacks of using `ModelType` instead of `ModelReturnType`?

**Comment by hasezoey** [comment]
Im working on a fix, i noticed what is wrong and try to fix it (non-breakingly)

**Comment by hasezoey** [comment]
i couldnt find a workaround now, [so i made an issue at typescript to try to solve it](https://github.com/microsoft/TypeScript/issues/33491)

**Comment by hasezoey** [comment]
@B-Stefan is the example @Ben305 gave the same problem as yours?

**Comment by hasezoey** [comment]
@Ben305 @B-Stefan made a WIP PR, could you two test it if it would be what you want it todo? (#40)

**Comment by Ben305** [comment]
@hasezoey Would like to test, but cannot build the branch.

**Comment by hasezoey** [comment]
> @hasezoey Would like to test, but cannot build the branch.

with testing it i meant to try if the types are correct, not if it builds, because that is the current problem

**Comment by hasezoey** [comment]
@Ben305 @B-Stefan if what came out of [the typescript issue](https://github.com/microsoft/TypeScript/issues/33491#issuecomment-532774512) is correct, then typescript "is working as intended", so i cant fix it "officially" ... and currently not even "hacky"

**Comment by Ben305** [comment]
Unfortunately that's a real showstopper/blocker for all my projects using Typegoose. I usually handle all other things like limit, sorting, populating in the helper class, that's why I need to pass the models around.

**Comment by hasezoey** [comment]
i know, it is a valid use case, in my opinion

i cant get it to work on abstract classes without needing multiple types (that are incompatible) or a non-restrictive types, what in turn means no type information and it seems that we dont get any help / support from typescript itself

**Comment by Ben305** [comment]
I refactored my application so that the helpers could be removed, I've added a mongoose plugin that provides the helper methods as static methods on the models.

**Comment by amorgulis** [comment]
Hi all, is this related to the behavior I'm currently seeing in my project where TypeScript thinks the type is `any` instead of `ReturnModelType<T>`?

`const user: ReturnModelType<typeof User>; // <-- TypeScript thinks this is type 'any'

@Ben305 which Mongoose plugin did you end up using?

Thanks!

**Comment by Ben305** [comment]
@amorgulis I wrote my own plugin fitting my needs

**Comment by hasezoey** [comment]
@Ben305 is it public?
