### ISSUE TITLE
Unable to get child class properties populated with discriminators

### ISSUE THREAD

**Issue by sdunnin** [typegoose/typegoose#400]
## Overview
I have a class with a property array that seemed like a case for [embedded discriminators](https://typegoose.github.io/typegoose/docs/api/decorators/prop/#discriminators). Try as I might the child class propertiess will not populate in the Mongo document.

I'm not really sure if I am doing something wrong or if Typegoose can't support what I am trying to do. Based upon the docs it seems that what I am trying to do should work. Any assistance or guidance would be most appreciated.

I've tried to include all of the relevant pieces to recreate. If there is something missing please let me know.

**Typegoose model classes**
```ts
class ResourceDbModel implements RestResource {
  public get id() {
    return this._id.toString();
  }
  public set id(val: string) {
    this._id = new mongoose.Types.ObjectId(val);
  }
  _id!: mongoose.Types.ObjectId;

  public get ver() {
    return this.__v;
  }
  public set ver(val: number) {
    this.__v = val;
  }
  __v!: number;
}

@modelOptions({
  options: { allowMixed: Severity.ALLOW },
  schemaOptions: {
  toJSON: {
    virtuals: true,
    transform: (_doc: any, ret: { _id: any; __v: any }, _opt: any) => {
      delete ret._id;
      delete ret.__v;
      return ret;
    }
  },
  toObject: {
    virtuals: true,
    transform: (_doc: any, ret: { _id: any; __v: any }, _opt: any) => {
      delete ret._id;
      delete ret.__v;
      return ret;
    }
  },
    collection: 'match-profiles'
  }
})
class MatchProfileDbModel extends ResourceDbModel
  implements MatchProfile {
  @prop({ required: true })
  name!: string;
  @prop()
  sportId!: SportIDs;
  @prop({
    type: mongoose.Schema.Types.Mixed
    // type: StatSchemaDbModel,
    // discriminators: () => [
    //   { type: ConditionalStatDbModel, value: StatType.CONDITIONAL },
    //   { type: DerivedStatDbModel, value: StatType.DERIVED },
    //   { type: DisplayStatDbModel, value: StatType.DISPLAY },
    //   { type: HornStatDbModel, value: StatType.HORN },
    //   { type: PeriodStatDbModel, value: StatType.PERIOD },
    //   { type: TimeOutStatDbModel, value: StatType.TIMEOUT },
    //   { type: TimerStatDbModel, value: StatType.TIMER }
    // ]
  })
  statSchemas!: StatSchema[];
  @prop({ type: mongoose.Schema.Types.Mixed })
  defaultConfigs!: ScoreboardOptions;  //Not relevant to this issue can be any for reproduction
  @prop({ required: true })
  trackPlayerStats!: boolean;
  @prop()
  defaultTeams?: {
    promptDefaultTeamNameConfirmation: boolean;
    teamNames: string[];
  };
}

class StatSchemaDbModel implements StatSchema {
  @prop()
  id!: string;
  @prop()
  label!: string;
  @prop()
  caption?: string;
  @prop()
  type!: StatType;
  @prop()
  valueType!: StatValueType;
  @prop()
  scope!: StatScope;
  @prop()
  disabledBy?: string[];
  @prop()
  initialValue?: number;
  @prop()
  subStats?: { title: string; values: { id: string; label: string }[] };
  @prop()
  attempts?: { track: boolean; label: string };
  @prop()
  trackByPeriod?: boolean;
  @prop()
  automation?: AutomationRule[];  //not relevant for example can be any
}

class PeriodStatDbModel extends StatSchemaDbModel
  implements PeriodStatSchema {
  @prop()
  numberPerMatch!: number;
  @prop()
  timeBetween?: number[];
  @prop()
  overtime?: {
    numberPer: number;
    duration?: number;
    timeBetween?: number;
    repeat: boolean;
  };
}
```
**Statschema type definitions**
```ts
interface StatSchema {
  id: string;
  label: string;
  caption?: string;
  type: StatType;   //string enum
  valueType: StatValueType; //string enum
  scope: StatScope; //string enum
  disabledBy?: string[]; 
  initialValue?: number;
  subStats?: {
    title: string;
    values: { id: string; label: string }[];
  };
  attempts?: {
    track: boolean;
    label: string;
  };
  trackByPeriod?: boolean;
  automation?: AutomationRule[];  //not relevant for example can be any
}

// For brevity only including one of the child classes

interface PeriodStatSchema extends StatSchema {
  numberPerMatch: number;
  timeBetween?: number[];
  overtime?: {
    numberPer: number;
    duration?: number; 
    timeBetween?: number; 
    repeat: boolean;
  };
}
```
**Data Objects**
```ts
const matchProfileSeeds: MatchProfile[] = [{
    id: '459ffd5835814e6b9474001a',
    ver: 0,
    name: 'Varsity Baseball',
    sportId: SportIDs.BASEBALL,
    statSchemas: BaseballStatSchema,
    defaultConfigs: {
      hornVolume: 100,
      hornTone: HornTone.BUZZER,
      brightness: 100,
      digitConfig: { leadingZeros: false, leftAlign: false },
      textConfig: {
        alignment: TextAlignment.CENTER,
        isInverted: false,
        fontName: 'FONT_8x48'
      }
    },
    trackPlayerStats: false,
    defaultTeams: {
      promptDefaultTeamNameConfirmation: true,
      teamNames: ['Home', 'Guest']
    }
  }
];

const BaseballStatSchema: StatSchema[] = [
  {
    id: BaseballStatIDs.POINTS,
    label: 'Runs',
    type: StatType.BASIC,
    valueType: StatValueType.NUMBER,
    scope: StatScope.TEAM_ONLY,
    trackByPeriod: true
  },
  {
    id: BaseballStatIDs.INNING,
    label: 'Inning',
    type: StatType.PERIOD,
    valueType: StatValueType.NUMBER,
    scope: StatScope.MATCH,
    numberPerMatch: 9,
    overtime: {
      numberPer: 1,
      duration: 0,
      repeat: true
    }
  } as PeriodStatSchema ];
```

We seed our db collections using static objects (i.e. matchProfileSeeds) with a model.create() passing in the object array.

**Code snippet of collection population**
```ts
const matchProfileModel = getModelForClass(MatchProfileDbModel);
//...
matchProfileModel.create(matchProfileSeeds)
```

If I use StatSchemaDbModel as the type for statSchemas in MatchProfileDbModel I cannot get the statSchemas subdocs to populate the values from the child (discriminator) classes. The only way that they will populate is to make the type `Schema.Types.Mixed` which is how it was originally implemented in the mongoose schema.

I've tried various flavors of trying to push the appropriate statSchema child class type onto the statSchemas array within the MatchProfileDbModel object without any luck. The child class specific properties, which in this case would be `overtime` and `numberPerMatch` are never saved to the document in the db.

**My futile various attempts at adding the discriminated class objects**
```ts
const statSchemaModel = getDiscriminatorModelForClass(
  this.matchProfileModel,
  StatSchemaDbModel
);

// const matchProfilesToSave: MatchProfile[] = [];
matchProfileSeeds.map(async matchProfile => {
  // const profileToSave = cloneDeep(matchProfile);
  const profileToSave: MatchProfileDbModel = this.matchProfileModel.hydrate(
    { _id: matchProfile.id, ...matchProfile }
  );
  profileToSave.statSchemas = [];
  matchProfile.statSchemas.map(schema => {
    switch (schema.type) {
      case StatType.PERIOD:  //'period'
        // const statSchema = schema
        const statSchema = statSchemaModel.hydrate(schema);
        profileToSave.statSchemas.push(statSchema);
        // profileToSave.statSchemas.push(statSchema as PeriodStatDbModel);
        break;
      default:
        break;
    }
  });
  // matchProfilesToSave.push(profileToSave);
  // await new this.matchProfileModel(profileToSave).save();
  await this.matchProfileModel.update(
    { _id: profileToSave.id },
    profileToSave,
    { upsert: true }
  );
});
```
## Versions
- typegoose: 7.4.1
- mongoose: 5.10.7

**Comment by hasezoey** [comment]
did you already try manually setting the discriminator type? (in your case, [the default](https://mongoosejs.com/docs/discriminators.html#discriminator-keys), `__t`)

**Comment by sdunnin** [comment]
You mean the discriminatorKey?  I originally had it as `discriminatorKey: 'type'` but that conflicted with the property named type in the class so I removed it when I found out that mongoose just uses __t as a default name.

**Comment by hasezoey** [comment]
> You mean the discriminatorKey?

yes, did you already try to manually set the `__t` property (inside `BaseballStatSchema`)

**Comment by sdunnin** [comment]
Ahhh, I see where you are going. No I did not.  Can't I just set `discriminatorKey: 'type'` in schemaOptions on StatSchemaDbModel to achieve the same thing?

**Comment by hasezoey** [comment]
@sdunnin from my experience, there are 2 ways to get it working:
- set an default for `__t` (or the key manually defined) on *each* discriminator extended class (sometimes doesnt work?)
- manually add the `__t` to the value on creation time

and from what i see, your `type` property is the value that is used to identify the discriminator, so yes, set `discriminatorKey: 'type'`, otherwise it would just duplicate data

> I originally had it as discriminatorKey: 'type' but that conflicted with the property named type in the class

what was the error for that?

**Comment by sdunnin** [comment]
I don't remember. let me revisit. It might be a little bit as my app repo is in flux working on another feature.

**Comment by sdunnin** [comment]
@hasezoey That seemed to do the trick. I think what I originally did wrong was put the discriminatorKey on the parent class MatchProfileDbModel rather than the class StatSchemaDbModel which is the type definition for the discriminated property `statSchemas`.

One other minor thing I'm trying to figure out is that the statSchemas sub-docs are being created with an _id. I've tried adding `_id: false` to the prop of the parent's discriminated property but it doesn't seem to do anything.

**Comment by hasezoey** [comment]
> One other minor thing I'm trying to figure out is that the statSchemas sub-docs are being created with an _id. I've tried adding _id: false to the prop of the parent's discriminated property but it doesn't seem to do anything.

"common" problem, i already asked in mongoose to implement the `_id: false` as an property option, which was resolved, but i think this had no effect on discriminators, maybe try to set schema option `_id: false`, if that doesnt work, then `_id` is required for discriminators

**Comment by sdunnin** [comment]
@hasezoey setting `_id: false` did work to remove the _id from the discriminated classes. Thanks for all of your help!
