### ISSUE TITLE
Array of nested object

### ISSUE THREAD

**Issue by ides15** [typegoose/typegoose#406]
I have a class with an array of the same nested class:
```ts
class Task {
    public id: string
    public subtasks: Task[]
}
```
How should I go about modeling this with Mongo / typegoose? Not sure if / how I should be using Refs in this case.

**Comment by hasezoey** [comment]
this might just be because its example code, but you always need to use `@prop` on the properties that you want in your model

> How should I go about modeling this with Mongo / typegoose? Not sure if / how I should be using Refs in this case.

as for that i recommend to read #42 or an [TL;DR](https://typegoose.github.io/typegoose/docs/guides/known-issues#self-containing-classes)

**Comment by ides15** [comment]
All the examples I've seen are for just a single nested object, except the `Category` example in #42 

Is this the correct way to do this?
```
@ObjectType()
class Task {
    @prop()
    public id: string

    @prop({ ref: Task })
    public subtasks: Ref<Task[]>
}
```

Or can I just do `Ref<Task>`?

**Comment by hasezoey** [comment]
if you want arrays, then `public name: Ref<Class>[];` (the prop options are the same, as long as you have `emitDecoratorMetadata`(tsconfig) enabled)

**Comment by ides15** [comment]
Thanks!
