### ISSUE TITLE
How can I use document type properly when this field is undefinable?

### ISSUE THREAD

**Issue by xkguq007** [typegoose/typegoose#408]
## Versions

- typegoose: 7.4.1
- mongoose: 5.10.7

```Typescript
export interface User extends defaultClasses.Base {}

@modelOptions({ schemaOptions: { collection: 'user' } })
export class User extends defaultClasses.TimeStamps {
  @prop({ ref: () => File })
  public avatar?: Ref<File>;
}
```
I want to use this avatar with full intellisense when this field is populated.

```Typescript
const user = await this.userModel.find({}).populate('avatar').exec();
if (user.avatar && !isDocument(user.avatar)) {
  throw new Error('error.');
}
user.avatar; // it still DocumentType<mongoose.Types.ObjectId | File>;
// what I expected is, DocumentType<File> | undefined;
```
How can I achieve like this??

I think above codes looks pretty simple,
but If you need more detail, I'll update as soon as possible.

**Comment by hasezoey** [comment]
i tried your code, and the only problem i encountered was that you didnt check for `user` if its `undefined | null`, aside from that i removed the `user.avatar &&` which is unnecessary, because that function also does `!isNullOrUndefined` on the value

```ts
// NodeJS: 14.13.0
// MongoDB: 4.2-bionic (Docker)
import { defaultClasses, getModelForClass, isDocument, modelOptions, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.1
import { assertion, isNullOrUndefined } from "@typegoose/typegoose/lib/internal/utils";
import * as mongoose from "mongoose"; // mongoose@5.10.8 @types/mongoose@5.7.36

class File {
  @prop()
  public dummy?: string;
}

export interface User extends defaultClasses.Base { }

@modelOptions({ schemaOptions: { collection: "user" } })
export class User extends defaultClasses.TimeStamps {
  @prop({ ref: () => File })
  public avatar?: Ref<File>;
}
const FileModel = getModelForClass(File);
const UserModel = getModelForClass(User);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const file = await FileModel.create({ dummy: "hi" });
  const doc = await UserModel.create({ avatar: file });

  const user = await UserModel.findOne({}).populate("avatar").exec();
  assertion(!isNullOrUndefined(user), new Error("Found User is undefined")); // or do this with an if, or use `.orFail` on the query
  if (!isDocument(user.avatar)) {
    throw new Error("error.");
  }

  console.log(user.avatar.dummy); // type is "DocumentType<File>"

  await mongoose.disconnect();
})();
```

**Comment by xkguq007** [comment]
@hasezoey Thanks for reply,
First of all, sorry for confusing because of forgot to checking null after exec.
```Typescript
const user = await this.userModel.find({}).populate('avatar').exec();
```
Above codes must be changed following code.
```Typescript
const user = await this.userModel.find({}).populate('avatar').exec();
if (user === null) {
  throw new Error('not found');
}
```

Next, There is little problem here.
if avatar is undefined, it must be not error.
That's why I try to use `user.avatar &&` within if phrase.
So,
```Typescript
  if (!isDocument(user.avatar)) {
    throw new Error("error.");
  }
```
above code, must be divide into 2 phrase, like following code.
```Typescript
if (user.avatar) {
  if (!isDocument(user.avatar)) {
    throw new Error("error.");
  }
}
```
When you coded like this, then following problem comes out.
```Typescript
user.avatar; // it still DocumentType<mongoose.Types.ObjectId | File>;
// what I expected is, DocumentType<File> | undefined;
```

**Although I solved this problem, I still don't know why it works.**
Following code is works.
```Typescript
// It works!
const user = await this.userModel.find({}).populate('avatar').exec();
if (user === null) {
  throw new Error('not found');
}

// I did just change the sequence that 'user.avatar and isDocument' to 'isDocument and user.avatar'
if (!isDocument(user.avatar)) {
  if (user.avatar !== undefined) {
    throw new Error('error');
  }
}
user.avatar; //  DocumentType<File> | undefined;
```

**Comment by hasezoey** [comment]
@xkguq007 like i said, `isDocument` returns an boolean, and in that functions `isNullOrUndefined` if the input is done, so that means your code above does: (pseudo)
- if `user === null` throw error `not found`
- if `user.avatar === null | undefined | not and document` execute
  - if `user.avatar !== undefined` throw error `error`
(after end of if)
- usage of `user.avatar`

the type is correct there, because with what you provided in your code, you checked if its not an document, and because you dont *early return* (either by return or throw), it can still be anything after the if, you can resolve this by:
- putting `user.avatar` in an `else` of the if
- or put an early return inside the if (and not within another if)

example:
```ts
// put it in an else
if (!isDocument(user.avatar)) {
  if (user.avatar !== undefined) {
    throw new Error('error');
  }
} else {
  user.avatar;
}

// or do an early return
if (!isDocument(user.avatar)) {
  if (user.avatar !== undefined) {
    throw new Error('error');
  }
  // either by
  throw new Error('hello');
  // or
  return;
}
user.avatar;
```

but either way, it wont add `| undefined` to the case, because `isDocument` uses `assert` (type) and if the functions returns `true`, then it definitely means that the input value is that type, nothing else (not even undefined)

**Comment by xkguq007** [comment]
@hasezoey thanks for detail examples!, it works.
thank you for your effort.
