### ISSUE TITLE
Support for mongoose Model.aggregate() ?

### ISSUE THREAD

**Issue by donmatheo** [typegoose/typegoose#409]
Hello,

I was trying to find some information about using Mongoose.aggregate in combination with typegoose.  (https://mongoosejs.com/docs/api.html#model_Model.aggregate)

When I try to call .aggregate() in my typegoose Model, I get the message.

`Property 'aggregate' does not exist on type 'DocumentQuery<DocumentType<Product>[], DocumentType<Product>, {}>'.ts(2339)`

My Model Class looks like:

```ts
@ObjectType()
export default class Product {
    @Field((type) => ID)
    readonly _id: ObjectId;

    @prop({ required: true, enum: ProductTypes })
    @Field()
    type: ProductTypes;

    @prop()
    @Field((type) => ProductFeatures, { nullable: true })
    features: ProductFeatures;

    @prop({ required: true })
    @Field((type) => ID)
    manufactoryId: ObjectId;

    @prop({ required: true })
    @Field((type) => ID)
    ownerId: ObjectId;

    @prop({ required: true })
    @Field((type) => ID)
    public worldId: ObjectId;
}

export const ProductModel = getModelForClass(Product);
```

Is there a way to use aggregate() with typegoose or is this not supported yet? If no, an example would be very helpful.

best regards

## Versions

- typegoose: 7.4.1
- mongoose: 5.10.10

**Comment by hasezoey** [comment]
i dont see an problem, do you have `@types/mongoose` installed and have the latest version?

anyway, if the type should not be working for you, typegoose is not modifing such things, these functions are directly mongoose (typegoose just brings classes to mongoose schemas & models)

code used:
```ts
// NodeJS: 14.15.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.1
import * as mongoose from "mongoose"; // mongoose@5.10.12 @types/mongoose@5.7.37

class ProductTypes {
  @prop()
  public dummy?: string;
}

class ProductFeatures {
  @prop()
  public dummy?: string;
}

class Product {
  public readonly _id!: mongoose.Types.ObjectId;

  @prop({ required: true, enum: ProductTypes })
  public type!: ProductTypes;

  @prop()
  public features?: ProductFeatures;

  @prop({ required: true })
  public manufactoryId!: mongoose.Types.ObjectId;

  @prop({ required: true })
  public ownerId!: mongoose.Types.ObjectId;

  @prop({ required: true })
  public worldId!: mongoose.Types.ObjectId;
}

export const ProductModel = getModelForClass(Product);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  await ProductModel.aggregate([{}]);

  await mongoose.disconnect();
})();
```

**Comment by donmatheo** [comment]
Hi, thanks for the quick reply. I got it working with your answer. Thanks for the example!

My fault was I did try to use Model.find().aggregate() instead of Model.aggregate().
