### ISSUE TITLE
How to create a conditional ttl index?

### ISSUE THREAD

**Issue by blatoo** [typegoose/typegoose#414]
I want to create a conditional ttl to delete document after certain time under certian condition. How can I do that? With `@index`?

For example: if a user doesn't **confirm** his **email** in 15 seconds, then, his account will be deleted. How can I do that? I did the following code, but somehow, it doesn't work... 

It looks like also the `{createdAt: -1}`  reverse index doesn't work...

```ts
@modelOptions({ schemaOptions: { collection: "users", timestamps: true } })
@index(
  { createdAt: -1, confirmed: 1 },
  { expireAfterSeconds: 15, partialFilterExpression: { confirmed: false } }
)
class UserClass {
  @prop({ required: true, unique: true })
  public email!: string

  @prop({ default: false })
  public confirmed?: boolean

@prop({ default: Date.now, index: true })
  public createdAt?: Date
}
```

## Versions
- typegoose: 7.4.2
- mongoose: 5.10.15

**Comment by blatoo** [comment]
Hi all, 

Sorry, I think, it was my mistake, I didn't wait for enough time. I saw it works now. Sorry for the inconvenient. 

Another question: does the `index: true` over the `public createAt?: Date` necessary ? Shall I also set `confirmed ` as index?

**Comment by hasezoey** [comment]
@blatoo the `index: true` just adds *another* plain index (to make lookups with this property faster)
