### ISSUE TITLE
Cannot use same model on two connections.

### ISSUE THREAD

**Issue by dcarniel** [typegoose/typegoose#419]
In order to split database I'm trying to use the same model on multiple databases depending on context (running a service platform for multiple tenants, I'd like to keep data in separate mongoose instances for security and scalability).

Unfortunately, when invoking the "getModelForClass" the internal cache used to build model only once ignores the connection as illustrated here: https://github.com/typegoose/typegoose/blob/51329a0ef6498075c71144fe94b35c2bd911695d/src/typegoose.ts#L75

It would be interesting that this cache take the existingConnection (or existingMongoose) in account to allow instantiating multiple times the same model with a different underlying connection.

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/docs/guides/advanced/models-with-same-name

**Comment by dcarniel** [comment]
Thanks for the pointer but this unfortunately doesn't address my use case.

I want the same code to run on different connections (pointing to separate instances) depending on the request context (tenant). What I would need is simply the same model with a different database connection, the "caching mechanism prevents this because it ignores the "existingConnection" provided.

I'm not sure it would be an issue with the "getClass" methods since I'm always pointing to the same class, regardless of the underlying connection.

My understanding is that using Mongoose directly I could achieve what I want using the "conn.getModel(...)" method simply using different connections, that would get me twice the same model with different underlying connections. That cache mechanism seems to get in the way.

Happy to help and contribute if I can.

**Comment by hasezoey** [comment]
the problem with this is, currently typegoose applies models to the *mongoose instance* not an *connection* (directly), and if you would do this in native mongoose you would also get an error that says "Model with that name already exists" (if using the way typegoose does currently)

the only fix there is currently: use `automaticName` / `customName`, you can provide these options not only in `@modelOptions` but also in `getModelForClass` as second parameter

**Comment by dcarniel** [comment]
You're right my first answer was a bit too quick, I looked again at the `customName` and it might work.

Though it looks like the `getName` function only looks at the options from the decorator and not the options merged from the `getModelForClass`: https://github.com/typegoose/typegoose/blob/51329a0ef6498075c71144fe94b35c2bd911695d/src/internal/utils.ts#L316

As a result getModelForClass doesn't see a change in the name and therefore keeps returning the same model.

Would it make sense to pass the merged options as an optional parameter to `getName` and use it it instead of what is gathered from the decorator if present ?

**Comment by hasezoey** [comment]
sorry, forgot about this problem - this is not fixable without assigning an unique id and having to manage them

so the other way would be for you to extend the class into another (with a different name) and add `@modelOptions` to the extending class

**Comment by dcarniel** [comment]
I'm okay with the principle of having different names (my initial answer was a bit too quick), now my problem is if I try to set the customName through the optional `options` when calling `getModelForClass` it doesn't work.
I've used the following test which exhibits the problem:

`it('if options.customName is defined to be used with automaticName through override', () => {
  @modelOptions({})
  class CustomNameOverride { }

  const model = getModelForClass(CustomNameOverride, { options: { customName: 'Suffix', automaticName: true } });
  expect(model.modelName).toEqual('CustomNameOverride_Suffix');

  const doc = new model();
  const gotClass = getClassForDocument(doc);
  expect(gotClass).toEqual(CustomNameOverride);
});`

I've got a potential fix too but can't push to the repository, let me know if you think the test case is valid I can send you a diff.

**Comment by hasezoey** [comment]
@dcarniel sorry, but chaning `getName` isnt that easy, because it is used to lookup the properties, and after making it an schema / model to be able to look it up again (current working is modelName = getName, internalName = getName)

**Comment by dcarniel** [comment]
@hasezoey the fix I've put together seems to be working (at minimum all tests are passing), and if you try to add the test I wrote above in the current code base it simply doesn't work whereas I think it should.

If you allowed my account I could push a branch with the test and the changes I made so you can review it and tell me where I'm missing something.

As it stands now the override of options through `getModelForClass` simply does not work as it ignores the `customName` option.

**Comment by hasezoey** [comment]
> If you allowed my account I could push a branch with the test and the changes I made so you can review it and tell me where I'm missing something.

just do an fork and then an pull request

> As it stands now the override of options through getModelForClass simply does not work as it ignores the customName option.

it was not easy to change that earlier, because in 5.x and below everything was executed on the spot without clear names, in 6.0 many thing were changed to be unified but still was outsourced to an map in `data.ts`, and then finally in 7.0 everything possible got changed to reflection

---

when i have the time i will try to re-think the names and will try to change it
just to clarify: you want the ability to change the *modelName* in `buildSchema` (options passed from `getModelFromClass`) and still that everything works?

**Comment by dcarniel** [comment]
I'll see to do a fork.

Regarding the need, it is indeed simply to be able to use the following:
```
@modelOptions({})
class CustomNameOption { }

const model = getModelForClass(CustomNameOption, { options: { customName: 'CustomName', automaticName: true } });
```

instead of:
```
@modelOptions({ options: { customName: 'CustomName', automaticName: true } })
class CustomNameOption { }

const model = getModelForClass(CustomNameOption);
```

Simply because I want to be able to dynamically set the customName (or a suffix actually) instead of doing it at compile time.

Of course this means I'll have multiple model with different names using the same underlying class.

**Comment by hasezoey** [comment]
> Of course this means I'll have multiple model with different names using the same underlying class.

i will try to change this so that these things do not affect the class-names, but the model names and just get linked to the original class

**Comment by smolinari** [comment]
@hasezoey - I think what we've added in #470 could help out @dcarniel possibly? 

Scott

**Comment by dcarniel** [comment]
Curing my tests I tried to use options passed to the `getModelForClass` method, though it didn't work because those options were not applied in a consistent manner. I'll give it a try with this new option to see if that addresses my need.

Thanks for pointing out that change 👍

**Comment by hnviradiya** [comment]
Oh man. I need to have this. I am also using same model in different connection. I can't have different names :(

**Comment by hasezoey** [comment]
> I can't have different names

where cant you have different names? in the collection or in mongoose's storage or in code (variable name)?

**Comment by hnviradiya** [comment]
in collection

**Comment by hasezoey** [comment]
@hnviradiya then i would recommend to use different variable / model names, but have the same collection (via `@modelOptions({ schemaOptions: { collection: "namehere" } })`

**Comment by hnviradiya** [comment]
I have one databases per tenant. all having same model. In the world of large datasets, this practice is common I believe. Caching them will take away all the flexibilities. :(

**Comment by dcarniel** [comment]
That was exactly the same issue I had, if the code is updated to allow dynamic collection naming through the "getModelForClass" options it would work.
Looking at the code it didn't seem that difficult, only at some stage the collection name from the options parameter is disregarded in favour of the annotation (or default name), simply making this work as expected (i.e. taking in account the name provided through options parameter) would I think enable having one database per tenant with the some model everywhere.

**Comment by hasezoey** [comment]
> dynamic collection naming through the "getModelForClass" options it would work.

actually, this is fully possible since 7.6.0 (but still requires different model names)

just as a note, here is how naming works:

collection name = schemaOptions-overwrite or (default) (by mongoose) model name, lowercased, maybe pluralized
model name = (by typegoose) overwrite with `customName`, or when `automaticName` is activated and `customName` is defined its joined with variable name, or when `customName` is not defined but `automaticName` is active, variable name is joined with collection-overwrite, or (by default) (by typegoose) the variable name
variable name = what the user sets the class name to in the code

**Comment by hnviradiya** [comment]
@hasezoey Thanks a lot for the help. I was able to use same model by passing different customName and using same collection name by passing same collection name. Typegoose is just so perfect thing and is a future I believe (mongoose will get outdated :P :D).

**Comment by hasezoey** [comment]
as a note, typegoose does not replace mongoose, it is just an layer on top of it to make it more compatible on existing features

**Comment by hnviradiya** [comment]
Yeah, I got it. Just wanted to convey the same. like C# doesn't replace machine language. But thanks a lot for this perfect framework.
