### ISSUE TITLE
GetModelForClass generic approach is confusing and impossible to understand from the documentation

### ISSUE THREAD

**Issue by IliaSmagloy** [typegoose/typegoose#423]
Hello!

I've been trying to create a generic CRUD class in order to avoid code duplication. 
In the search for such implementation (as I've discovered this is not as simple as I thought - my generic class should extend `types.AnyParamConstructor`) I've found that the documentation is fairly hard to understand on the matter.

This is why I've worked mostly with 2 issues posted here: #303 and #246 . Unfortunately, and even though the code borrowed from issue #303 seems perfectly fine, it doesn't compile:

```
import { getModelForClass, prop, types, ReturnModelType, DocumentType } from "@typegoose/typegoose"; // @typegoose/typegoose@7.2.0
import * as mongoose from "mongoose"; // mongoose@5.9.18 @types/mongoose@5.7.27

export class GenericCRUDService<U extends types.AnyParamConstructor<any>> {
  public dataModel: ReturnModelType<U>;

  constructor(cls: U) {
    this.dataModel = getModelForClass(cls);
  }
}

export class Cat {
  @prop()
  public age?: number;

  @prop()
  public color?: string;
}
(()=>{
//Connecting to mongoDB
   const CatService = GenericCRUDService(Cat);
//disconnecting from mongoDB
})()
```

Here TypeScript requires a constructor for Cat, so I've implemented it in a default way. Ok, going forward, now I want to add the actual CRUD methods.

So:
`
addNewItem(itemToBeAdded:U) {
    const itemReadyToBeSaved = new this.dataModel(itemToBeAdded);
    itemReadyToBeSaved.save();
}
`

And after adding to the actual function code:
`
const cat = new Cat(14,"meow");
CatService.addNewItem(cat);
`

And I get the following error:
`Argument of type Cat is not assignable to parameter of type 'typeof Cat'.

After failing to fix it I've attempted to change the main code from the line
`   const CatService = GenericCRUDService(Cat);`
to the line 
`   const CatService = GenericCRUDService<Cat>(Cat);`

Which makes the `addNewItem(cat)` work, but fails compilation on the changed line with the error:
`type Cat does not satisfy the constraint  'AnyParamConstructor<any>'`

So now I'm completely confused.
The second version seems to be correct but it's illogical to expect the class to create a `constructor(...any)`  method. On the other hand the `addNewItem` fails to work with the original code.
The documentation failed to help me here as to how to work with generics, which seemed strange enough - as if I'm expected to duplicate code even though the whole point of typegoose is to prevent unneeded duplication.

When tryng to read the documentation it seems that it is not updated to current versions other than the patch notes.
For example ReturnModelType doesn't show the default option for the Query class to be {} and so on.

I work with:
`@typegoose/typegoose: 7.4.2`
`types/mongoose:5.10.1`
`mongoose:5.10.15`

Would be glad for any advice, thanks.

**Comment by IliaSmagloy** [comment]
Fixed it using the following fix:
```
 addNewItem(itemToBeAdded: **InstanceType**<U>) { 
    const itemReadyToBeSaved = new this.dataModel(itemToBeAdded);
    itemReadyToBeSaved.save(); 
}
```

Now it works

**Comment by anlauren** [comment]
@IliaSmagloy i'm having trouble implementing the generic version how did you manage to set up the update part? 
It seems like the type system won't accept any of the object id updateOne 🤔 
```typescript
export class BaseRepository<Model extends types.AnyParamConstructor<any>> {
  public model: ReturnModelType<Model>;
  constructor(entity: Model) {
    this.model = getModelForClass(entity);
  }
  async findOne(id: ObjectId): Promise<Model | undefined> {
    const result = await this.model.findById(id);
    if (result === undefined || result === null) {
      return undefined;
    }
    return result;
  }
  async update(id: ObjectId, updateArgs: Omit<Model, "id">): Promise<Model> {
    /**
     * all the implementations below raise the same typescript error:
     * Argument of type 'ObjectId' is not assignable to parameter of type 'MongooseFilterQuery<Pick<DocumentType<InstanceType<Model>>
     */
    let result = await this.model.updateOne(id, updateArgs);
    result = await this.model.updateOne({ id }, updateArgs);
    result = await this.model.updateOne({ _id: id }, updateArgs);
    result = await this.model.updateOne({ _id: id.toHexString() }, updateArgs);
    result = await this.model.updateOne(id.toHexString(), updateArgs);
  }
}
```

**Comment by hasezoey** [comment]
@anlauren depends, what is your `ObjectId` in long form? `mongoose.Types.ObjectId`?

**Comment by anlauren** [comment]
Yep, i had aliased it by extending the based class:
```typescript
import { mongoose } from "@typegoose/typegoose";

export class ObjectId extends mongoose.Types.ObjectId {}

```

i have just tried to replace all references to `mongoose.Types.ObjectId` it seems to be the same.
it makes some kind of sense that if you have a generic `Model`, you can't really know what is going to be the type of `_id` i guess.
I am trying to set up a full Crud generics, if I manage to i'll post the solution here because i see some people asking for it

**Comment by anlauren** [comment]
If use `findOneAndUpdate` i get the right return type though

**Comment by IliaSmagloy** [comment]
> 
> 
> @IliaSmagloy i'm having trouble implementing the generic version how did you manage to set up the update part?
> It seems like the type system won't accept any of the object id updateOne thinking
> 
> ```ts
> export class BaseRepository<Model extends types.AnyParamConstructor<any>> {
>   public model: ReturnModelType<Model>;
>   constructor(entity: Model) {
>     this.model = getModelForClass(entity);
>   }
>   async findOne(id: ObjectId): Promise<Model | undefined> {
>     const result = await this.model.findById(id);
>     if (result === undefined || result === null) {
>       return undefined;
>     }
>     return result;
>   }
>   async update(id: ObjectId, updateArgs: Omit<Model, "id">): Promise<Model> {
>     /**
>      * all the implementations below raise the same typescript error:
>      * Argument of type 'ObjectId' is not assignable to parameter of type 'MongooseFilterQuery<Pick<DocumentType<InstanceType<Model>>
>      */
>     let result = await this.model.updateOne(id, updateArgs);
>     result = await this.model.updateOne({ id }, updateArgs);
>     result = await this.model.updateOne({ _id: id }, updateArgs);
>     result = await this.model.updateOne({ _id: id.toHexString() }, updateArgs);
>     result = await this.model.updateOne(id.toHexString(), updateArgs);
>   }
> }
> ```
> 
> _EDIT_
> using `UpdateQuery<DocumentType<InstanceType<Model>>>` seems to work, but it's a bit counter intuitive not to be able to use objectId.
> I am guessing it's because the objectId might actually not exist on the model definition since it's a generic ( i have tried to enforce the `Model` to extend one that always has an id but i had the same kind of error)
> 
> ```ts
> async updateOne(
>     findArgs: UpdateQuery<DocumentType<InstanceType<Model>>>,
>     updateArgs: InstanceType<Model>
>   ): Promise<Model> {
>     let result = await this.model.update(findArgs, updateArgs); 
>     return result
>   }
> ```
> 
> _EDIT 2_
> with this definition it seems that update returns any thinking

I'm a little bit confused by your implementation. 
I'd say that me myself I didn't use update, but I did get all of the other CRUD's.
In your code I'm not sure as to why you chose to return Model, you say typescript required it to be any?

**Comment by hasezoey** [comment]
@anlauren from what i know `await Model.update` returns an query result, not an actual document
