### ISSUE TITLE
SomeModel.create() with no values doesnt create an instance

### ISSUE THREAD

**Issue by dcsan** [typegoose/typegoose#425]
## Versions

npm ls mongoose
bot@1.0.0 /Users/dc/dev/ten/puzzleparty/server
└── mongoose@5.11.1

npm ls @typegoose/typegoose
bot@1.0.0 /Users/dc/dev/ten/puzzleparty/server
└── @typegoose/typegoose@7.4.2

npm -v
6.14.9
node -v
v14.5.0
npx tsc -v
Version 4.1.2

## What is the Problem?

Trying to create a model instance without passing any params doesn't create an object.

```
const obj = SomeModel.create()  // returns undefined, nothing created
const obj = SomeModel.create({foo: "bar" }) // ok
```

There are some default values in the model

## Do you know *why* it happens?

*no* :/
but at least I know a workaround, to add some values!

**Comment by hasezoey** [comment]
closing because this is not an typegoose issue:
typegoose dosnt modify behaviour / functions of mongoose, typegoose only "transpiles" classes into schemas (and then to models)
