### ISSUE TITLE
Types of referenced objects default to ObjectId

### ISSUE THREAD

**Issue by dcsan** [typegoose/typegoose#426]
## Versions
npm ls mongoose
bot@1.0.0 /Users/dc/dev/ten/puzzleparty/server
└── mongoose@5.10.18

npm ls @typegoose/typegoose
bot@1.0.0 /Users/dc/dev/ten/puzzleparty/server
└── @typegoose/typegoose@7.4.4

npm -v
6.14.9
node -v
v14.5.0
npx tsc -v
Version 4.1.2

(FYI mongoose 5.11 is also out)

## What is the Problem?
Adding a 'ref' to another class/model results in errors when trying to access that referenced object.

## Code Example

```ts
class Topic extends defaultClasses.TimeStamps {
  @prop({ default: '' })
  public name?: string
}

class Game extends defaultClasses.TimeStamps {
  @prop({ ref: Topic })
  public topic: Ref<Topic>
}


const topic: Topic = game.topic!

// fails with 
Type 'Topic | ObjectId' is not assignable to type 'Topic'.
  Type 'ObjectId' has no properties in common with type 'Topic'.

```

the workaround I'm looking at is:
```
    const topic: Topic = game.topic! as Topic
    const submitter = `submitted by ${topic?.submitter}`
```

## Do you know *why* it happens?

I guess it needs an ObjectId to make the foreign Key, and typegoose is unclear if returning values [would be populated ](https://typegoose.github.io/typegoose/docs/api/virtuals/#virtual-populate) or not? 

FWIW I did add:

```ts
@modelOptions({
  schemaOptions: {
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
  }
})
```

**Comment by hasezoey** [comment]
that is the reason [`isDocument`](https://typegoose.github.io/typegoose/docs/api/functions/typeguards/is-document) and [`isRefType`](https://typegoose.github.io/typegoose/docs/api/functions/typeguards/is-ref-type) exist
