### ISSUE TITLE
Jest type checking fails after getting find result

### ISSUE THREAD

**Issue by IliaSmagloy** [typegoose/typegoose#430]
Hi again,

I've been trying to integrate Typegoose in my project, and unfortunately I've stumbled upon problems with the types returned from my quarries.

I'm having a generic CRUD wrapper for the functions, that has the following function:

```ts
async find(filter: FilterQuery<DocumentType<InstanceType<T>>>): Promise<InstanceType<T>>{
    const resultObject : InstanceType<T> = ((await this.classModel.find(filter).select('-__v -_id').exec())[0];
    result resultObject;
}
```
Where `this.classModel` is the model in my wrapper function. Now, I know it seems kind of ugly but other than using the select I didn't manage to find any other method to return it to the original form of the object. `toObject` that supposedly exists in Mongoose didn't appear possible after the switch to Typegoose(?)

Other than that I have some custom class Color with some attributes, and the following files:

```ts
export class Cat {
  @prop( required: true, unique: true, type: Number)
  public id: number;

  @prop(required: true)
  public color: Color;

  constructor(id: number, color: Color){...}
}

```

And in my jest test I have the following:
```ts
const storage = StorageWrapper(Cat)//Works, already checked
const cat = generateRandomCat() // Some function that randomly creates an instance
storage.addNewItem(cat)//Also works, i've see the new items in studio3t

const foundCat: Cat = await storage.find({id:cat.id}) as Cat;

expect(foundCat).toEqual(cat);
```

Now, the toEqual seems to fail each time even though by value the comparison is correct - but the types are wrong (For example
```
expected:
Cat { 
   "id": 5
   ...
}
Received:
Object{
   "id": 5
   ...
}
```
And the same happens inside color and so forth recursively. 
It seems no one on the internet is not troubled by the fact that the queries do not return a type which makes me think that I should be able to cast the returned objects to my type - but I don't seem to find such ways. Any help would be appreciated. 

Thanks a lot!

**Comment by hasezoey** [comment]
if i understand correctly, you are searching for [this](https://typegoose.github.io/typegoose/docs/guides/quick-start-guide#instance-methods):
> `public async setSpeciesAndSave(this: DocumentType<KittenClass>, species: string) {`

and i recommend to not use method names already used by mongoose (like `find`) - even though they are not an document method

**Comment by IliaSmagloy** [comment]
Do you mean to change my save() method? I'm confused as to how will it help me to cast the found objects to the right type.

Also, noted the other comment and I'll implement - it does makes sense.

Thanks for the quick response!

**Comment by hasezoey** [comment]
if you didnt see the embedded link, here it is in full, it is an snippit of the documentation's example:
https://typegoose.github.io/typegoose/docs/guides/quick-start-guide#instance-methods

**Comment by IliaSmagloy** [comment]
Hi! I've indeed read the link but I do not understand how is it related. 
My problem is the fact that after creating the document object - the document forgets all about the Typescript types inside, and I cannot cast it back. An example inspired by the given link:

```
class KittenClass {
  @prop()
  public name?: string;

  @prop()
  public species?: string;

  public async setSpeciesAndSave(this: DocumentType<KittenClass>, species: string) {
    this.species = species;
    return await this.save();
  }
}
const KittenModel = getModelForClass(KittenClass);

const doc = new KittenModel({ name: "SomeCat", species: "SomeSpecies" });
const kittenObject = doc.toObject() as KittenClass; //Trying to cast!
console.log(kittenObject instanceof KittenClass);
```

Will print false, which makes all the Typescript code fail afterward.
In othe words - even if I get the right object values from Mongodb, I can't work further due to it's type becoming `Object` instead of the original `KittenClass` in this example.

**Comment by hasezoey** [comment]
this is because `save` actually dosnt return what "should be", so try doing
```ts
await this.save();
return this;
```

> Hi! I've indeed read the link but I do not understand how is it related.

i had this, because at first i thought it was a typing option (not having set the correct `this` type) that is why i quoted that line

**Comment by IliaSmagloy** [comment]
Hi, thanks again for the quick response.

I do not use save in my example - save works good.
I use find, and find loses all of the Types, and I want to recover them - that's what I'm saying.
I gave the kitten class example just to show you that the Types are lost on the DocumentType already.

The bottom line question is - how can I recover\cast the type of my object after a successful `find()` gives me an object with correct values but wrong types (`Object` instead of any custom class)

**Comment by hasezoey** [comment]
sorry that i didnt see this earlier, i dont know if that are the problems, but i see that:
- you try to cast it to `InstanceType<T>`, which is not correct, it would be `DocumentType<T>`
and
- without `.orFail()` it normally returns `DocumentType<T> | null`

**Comment by IliaSmagloy** [comment]
Hi!
I've added both of those, it indeed make it more elegant and correct - but still, the _type_ remains **Object** and not **KittenClass**. 

I've changed my find function to the following:
```
async find(filter: FilterQuery<DocumentType<InstanceType<T>>>): Promise<DocumentType<T>>{
    const wantedObject : DocumentType<T> = ((await this.classModel.find(filter).orFail())[0];
    const resultObject = wantedObject.toObject();
    result resultObject;
}
```

Now, VScode asked me to make the conversion the following way:

```
const kittenObject = doc.toObject() as unkown as KittenClass; //Trying to cast!
console.log(kittenObject instanceof KittenClass);
```
But still it prints false unfortunately.

**Comment by hasezoey** [comment]
> wantedObject.toObject();

this will convert the mongoose document into an POJO (Plain Old JavaScript Object), so it will not be an instance of anything other than `Object`

**Comment by IliaSmagloy** [comment]
> 
> 
> > wantedObject.toObject();
> 
> this will convert the mongoose document into an POJO (Plain Old JavaScript Object), so it will not be an instance of anything other than `Object`

Hi! Thanks again for the reply.
I understand what you wrote here but here's the question - how can I achieve correct object type in the result returned from `findOne` or `find`? Currently all I get are Objects with no type. Studio3T shows that mongoDB itself doesn't save the type. 
How can typegoose recover the type of the `find` result?

Thanks a lot!

**Comment by hasezoey** [comment]
if `this.classModel` has an correct type (`ReturnModelType<T>` and `T` being an class) and having `@types/mongoose` installed, then the return type (without `.orFail()`) should be `DocumentType<T> | null`

oh and i recommend to use `.findOne` if you only use the first result anyways

**Comment by IliaSmagloy** [comment]
> 
> 
> if `this.classModel` has an correct type (`ReturnModelType<T>` and `T` being an class) and having `@types/mongoose` installed, then the return type (without `.orFail()`) should be `DocumentType<T> | null`
> 
> oh and i recommend to use `.findOne` if you only use the first result anyways

Well, you saw all of my code and unfortunately even if it is DoumencType<T>, I don't understand how to convert it to T.
`as unknown as T` doesn't work for example

**Comment by hasezoey** [comment]
because i dont know your full code, i cannot fully tell what is wrong, but here some repro code that works for me:
```ts
// NodeJS: 14.15.1
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.4
import { AnyParamConstructor, DocumentType, ReturnModelType } from "@typegoose/typegoose/lib/types";
import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.1

class User {
  @prop()
  public username?: string;
}
const UserModel = getModelForClass(User);

class SomeClass<T extends AnyParamConstructor<any>> {
  constructor(
    public classModel: ReturnModelType<T>
  ) { }

  public async find(filter: mongoose.MongooseFilterQuery<DocumentType<InstanceType<T>>>): Promise<DocumentType<T>> {
    return this.classModel.findOne(filter).orFail().exec();
  }
}

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  await UserModel.create({ username: "hi" });
  const instance = new SomeClass(UserModel);

  const got = await instance.find({ username: "hi" });

  console.log("got", got);

  await mongoose.disconnect();
})();
```

**Comment by IliaSmagloy** [comment]
Hi, the following works for me too. For me the problem would be with the following code:

Consider in User you have 
```
constructor(username: string) {
   this.username = username;
}
```

And then You do a Jest test as following:

```
it(`basic db test', async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const user = new User("hi");

  const instance = new SomeClass(UserModel);
  
  instance.add(user)//Saving or creating whatever you like

  const got = await instance.find({ username: "hi" });

   expect(got).toEqual(user);

  await mongoose.disconnect();
}
```

Here it fails for me.
