### ISSUE TITLE
prop doesn't add entity methods (contrary to arrayProp)

### ISSUE THREAD

**Issue by Tobjoern** [typegoose/typegoose#431]
## Versions

- NodeJS: v10.16.0
- Typegoose(NPM): ^7.4.4
- mongoose: ^5.11.2
- mongodb:^3.6.3

## What is the Problem?
When embedding a Sub Entity B, which has a method M, in another entity A,
and using the @prop decoratior, instead of the @arrayProp decorator, the method M isn't available, once A is retrieved.

## Code Example
Please don't be distracted by the title.
https://github.com/Tobjoern/typegoose-virtual-autopop-bug

How to run:
1. git clone https://github.com/Tobjoern/typegoose-virtual-autopop-bug
2. cd ./typegoose-virtual-autopop-bug
3. npm i
4. npm run dev

```ts
class ExampleEntity extends TimeStamps {

    @prop({ required: true, unique: true, type: String })
    productId!: string;

    @prop({ required: true, type: () => [SubEntity] })
    subEntities!: SubEntity[]

    @arrayProp({ required: true, type: SubEntity })
    otherSubEntities!: SubEntity[]

}

export class SubEntity {

    @prop({ required: true })
    length!: number;

    public getInfo() {
        return 'this is some info!'
    }

}

  const exampleEntity = new ExampleEntityModel()

    const otherSubEnt = new SubEntity()

    otherSubEnt.length = 25

    const subEnt = new SubEntity()

    subEnt.length = 100

    exampleEntity.productId = 'blub'
    exampleEntity.subEntities = [subEnt]
    exampleEntity.otherSubEntities = [otherSubEnt]

 await exampleEntity.save()

    const retrieved = await ExampleEntityModel.findById(exampleEntity._id)

    if (retrieved) {
        console.log(retrieved)

        retrieved.otherSubEntities.forEach(retSubEnt => {
          //this works!
            console.log(retSubEnt.getInfo())
        })

        retrieved.subEntities.forEach(retSubEnt => {
           //this throws error, 'getInfo is not a function'
            console.log(retSubEnt.getInfo())
        })
    }
```

## Do you know *why* it happens?

*no*

**Comment by smolinari** [comment]
I can confirm this issue using the repo given. I looked for a test that covers this scenario and couldn't find one. 

Scott

**Comment by hasezoey** [comment]
sorry, i dont understand what should be different here, because since 7.0.0 `@arrayProp` is an *direct passthrough* to `@prop`

i modified the code to be an drop and run, and cannot reproduce the problem, code used:
```ts
// NodeJS: 14.15.1
// MongoDB: 4.2-bionic (Docker)
import { arrayProp, getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.4
import { TimeStamps } from "@typegoose/typegoose/lib/defaultClasses";
import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.1

class ExampleEntity extends TimeStamps {
  @prop({ required: true, unique: true, type: String })
  public productId!: string;

  @prop({ required: true, type: () => [SubEntity] })
  public subEntities!: SubEntity[];

  @arrayProp({ required: true, type: () => SubEntity })
  public otherSubEntities!: SubEntity[];
}

class SubEntity {
  @prop({ required: true })
  public length!: number;

  public getInfo() {
    return "this is some info!";
  }
}

const ExampleEntityModel = getModelForClass(ExampleEntity);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const exampleEntity = new ExampleEntityModel();

  const otherSubEnt = new SubEntity();

  otherSubEnt.length = 25;

  const subEnt = new SubEntity();

  subEnt.length = 100;

  exampleEntity.productId = "blub";
  exampleEntity.subEntities = [subEnt];
  exampleEntity.otherSubEntities = [otherSubEnt];

  await exampleEntity.save();

  const retrieved = await ExampleEntityModel.findById(exampleEntity._id).orFail().exec();

  console.log(retrieved.toJSON({ virtuals: true }));

  retrieved.otherSubEntities.forEach(retSubEnt => {
    // this works!
    console.log(retSubEnt.getInfo());
  });

  retrieved.subEntities.forEach(retSubEnt => {
    // this throws error, 'getInfo is not a function' // this error dosnt come for me
    console.log(retSubEnt.getInfo());
  });

  await mongoose.disconnect();
})();
```

output given:
```
(node:6519) [TDEP0001] DeprecationWarning: "@arrayProp" is deprecated, use "@prop" instead
(Use `node --trace-deprecation ...` to show where the warning was created)
{
  _id: 5fca0a1d343f251977daea60,
  subEntities: [
    {
      _id: 5fca0a1d343f251977daea61,
      length: 100,
      id: '5fca0a1d343f251977daea61'
    }
  ],
  otherSubEntities: [
    {
      _id: 5fca0a1d343f251977daea62,
      length: 25,
      id: '5fca0a1d343f251977daea62'
    }
  ],
  productId: 'blub',
  createdAt: 2020-12-04T10:06:21.079Z,
  updatedAt: 2020-12-04T10:06:21.079Z,
  __v: 0,
  id: '5fca0a1d343f251977daea60'
}
this is some info!
this is some info!
```

[here is the branch on testing](https://github.com/typegoose/typegoose-testing/tree/verify431)

**Comment by Tobjoern** [comment]
> sorry, i dont understand what should be different here, because since 7.0.0 `@arrayProp` is an _direct passthrough_ to `@prop`
> 
> i modified the code to be an drop and run, and cannot reproduce the problem, code used:
> 
> ```ts
> // NodeJS: 14.15.1
> // MongoDB: 4.2-bionic (Docker)
> import { arrayProp, getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.4
> import { TimeStamps } from "@typegoose/typegoose/lib/defaultClasses";
> import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.1
> 
> class ExampleEntity extends TimeStamps {
>   @prop({ required: true, unique: true, type: String })
>   public productId!: string;
> 
>   @prop({ required: true, type: () => [SubEntity] })
>   public subEntities!: SubEntity[];
> 
>   @arrayProp({ required: true, type: () => SubEntity })
>   public otherSubEntities!: SubEntity[];
> }
> 
> class SubEntity {
>   @prop({ required: true })
>   public length!: number;
> 
>   public getInfo() {
>     return "this is some info!";
>   }
> }
> 
> const ExampleEntityModel = getModelForClass(ExampleEntity);
> 
> (async () => {
>   await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });
> 
>   const exampleEntity = new ExampleEntityModel();
> 
>   const otherSubEnt = new SubEntity();
> 
>   otherSubEnt.length = 25;
> 
>   const subEnt = new SubEntity();
> 
>   subEnt.length = 100;
> 
>   exampleEntity.productId = "blub";
>   exampleEntity.subEntities = [subEnt];
>   exampleEntity.otherSubEntities = [otherSubEnt];
> 
>   await exampleEntity.save();
> 
>   const retrieved = await ExampleEntityModel.findById(exampleEntity._id).orFail().exec();
> 
>   console.log(retrieved.toJSON({ virtuals: true }));
> 
>   retrieved.otherSubEntities.forEach(retSubEnt => {
>     // this works!
>     console.log(retSubEnt.getInfo());
>   });
> 
>   retrieved.subEntities.forEach(retSubEnt => {
>     // this throws error, 'getInfo is not a function' // this error dosnt come for me
>     console.log(retSubEnt.getInfo());
>   });
> 
>   await mongoose.disconnect();
> })();
> ```
> 
> output given:
> 
> ```
> (node:6519) [TDEP0001] DeprecationWarning: "@arrayProp" is deprecated, use "@prop" instead
> (Use `node --trace-deprecation ...` to show where the warning was created)
> {
>   _id: 5fca0a1d343f251977daea60,
>   subEntities: [
>     {
>       _id: 5fca0a1d343f251977daea61,
>       length: 100,
>       id: '5fca0a1d343f251977daea61'
>     }
>   ],
>   otherSubEntities: [
>     {
>       _id: 5fca0a1d343f251977daea62,
>       length: 25,
>       id: '5fca0a1d343f251977daea62'
>     }
>   ],
>   productId: 'blub',
>   createdAt: 2020-12-04T10:06:21.079Z,
>   updatedAt: 2020-12-04T10:06:21.079Z,
>   __v: 0,
>   id: '5fca0a1d343f251977daea60'
> }
> this is some info!
> this is some info!
> ```
> 
> [here is the branch on testing](https://github.com/typegoose/typegoose-testing/tree/verify431)
> 
> PS: if the info given is correct, then you ignored the version range typegoose requires for mongoose, highest supported is 5.10.18

You were right about the version, I simple ran 'npm i -s mongoose', thus installing a mongoose version, which isn't offically supported (btw. I may be useful to add 'npm i -s mongoose@version' in the README.md, so these kind of mistakes are less likely).
 Hence I downgraded to mongoose@5.10.18 in the repo (and added a console.log logging the actual mongoose version, to confirm it isn't some caching issue), but the described issue still persisted, until I dove into the source code.
You are absolutely right arrayProp is completely equivalent to prop, so this couldn't be the issue. The issue was using:
`type: () => SubEntity` instead of `type: SubEntity`. The [documentation](https://typegoose.github.io/typegoose/docs/api/decorators/prop) states that the type property accepts 'any | () => any', but in my updated repo the arrow function notation doesn't work as intented (the original issue).

1. git clone https://github.com/Tobjoern/typegoose-virtual-autopop-bug
2. cd ./typegoose-virtual-autopop-bug
3. npm i
4. npm run dev

**Comment by Tobjoern** [comment]
Furthermore there is an issue with using arrow functions to resolve references:

```
    @prop({ ref: ReferenceEntity, required: true })
    referenceEntityA: Ref<ReferenceEntity>

    @prop({ ref: () => ReferenceEntity, required: true })
    referenceEntityB: Ref<ReferenceEntity>

     .......
    
    // this works
    const retrieved = await ExampleEntityModel.findById(exampleEntity._id).populate('referenceEntityA')

    // This fails! Error: MissingSchemaError: Schema hasn't been registered for model "ref".
    // const retrievedB = await ExampleEntityModel.findById(exampleEntity._id).populate('referenceEntityB')
```
I have also added this to the original repo, but have uncommented it, so it can be tested by removing two comments.
This further issue is another hint, that there is a problem with using arrow functions/functions specifically.

**Comment by hasezoey** [comment]
ran your code, ran my code, no errors, code used:
```ts
// NodeJS: 14.15.1
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, isDocument, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.4
import { TimeStamps } from "@typegoose/typegoose/lib/defaultClasses";
import { assertion } from "@typegoose/typegoose/lib/internal/utils";
import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.1

class SubEntity {
  @prop({ required: true })
  public length!: number;

  public getInfo() {
    return "this is some info!";
  }
}

class ExampleEntity extends TimeStamps {
  @prop({ required: true, unique: true, type: String })
  public productId!: string;

  @prop({ ref: SubEntity, required: true })
  public referenceEntityA: Ref<SubEntity>;

  @prop({ ref: () => SubEntity, required: true })
  public referenceEntityB: Ref<SubEntity>;
}

const SubEntityModel = getModelForClass(SubEntity);
const ExampleEntityModel = getModelForClass(ExampleEntity);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  await mongoose.connection.db.dropDatabase();

  const exampleEntity = new ExampleEntityModel();

  const otherSubEnt = await SubEntityModel.create({ length: 25 });

  const subEnt = await SubEntityModel.create({ length: 100 });

  exampleEntity.productId = "blub";
  exampleEntity.referenceEntityA = subEnt;
  exampleEntity.referenceEntityB = otherSubEnt;

  await exampleEntity.save();

  const retrieved = await ExampleEntityModel.findById(exampleEntity._id).populate("referenceEntityA referenceEntityB").orFail().exec();

  console.log(retrieved.toJSON({ virtuals: true }));

  assertion(isDocument(retrieved.referenceEntityA));
  assertion(isDocument(retrieved.referenceEntityB));

  console.log(retrieved.referenceEntityA.getInfo());
  console.log(retrieved.referenceEntityB.getInfo());

  await mongoose.disconnect();
})();
```

ran your code a bit modified:
```ts
import mongoose from 'mongoose'
import { ExampleEntityModel } from './Example.entity'
import { ReferenceEntityModel } from './Reference.entity'
import { SubEntity } from './SubEntity'


console.log('The mongoose version:')
console.log(mongoose.version)

mongoose.connect('mongodb://localhost:27017/typegoose-bug-3', {
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
    useUnifiedTopology: true
}).then(async connection => {
    await mongoose.connection.db.dropDatabase();

    console.log('Connected!')

    await ExampleEntityModel.deleteMany({})

    await ReferenceEntityModel.deleteMany({})

    const exampleEntity = new ExampleEntityModel()

    const otherSubEnt = new SubEntity()

    otherSubEnt.length = 25

    const subEnt = new SubEntity()

    subEnt.length = 100

    const referenceEntity = new ReferenceEntityModel()

    referenceEntity.productId = 'product-id'

    await referenceEntity.save()

    exampleEntity.productId = 'blub'
    exampleEntity.subEntities = [subEnt]
    exampleEntity.otherSubEntities = [otherSubEnt]
    exampleEntity.referenceEntityA = referenceEntity
    exampleEntity.referenceEntityB = referenceEntity


    await exampleEntity.save()

    console.log('Getting entity A')
    const retrieved = await ExampleEntityModel.findById(exampleEntity._id).populate('referenceEntityA')

    // This fails! In order to test the Reference issue, uncomment the following two lines.
    console.log('Getting entity B')
    const retrievedB = await ExampleEntityModel.findById(exampleEntity._id).populate('referenceEntityB')

    if (retrieved) {
        // console.log(retrieved)

        console.log('Using normal type')
        retrieved.otherSubEntities.forEach(retSubEnt => {
            console.log(retSubEnt.getInfo())
        })
        console.log('Using arrow function type')
        retrieved.subEntities.forEach(retSubEnt => {
            console.log(retSubEnt.getInfo())
        })
    }

    await mongoose.disconnect();
})
```

---

can you confirm you have all the requirements that typegoose needs?
like having tsconfig `target` being `es6` and having the other options enabled?

**Comment by Tobjoern** [comment]
> ran your code, ran my code, no errors, code used:
> 
> ```ts
> // NodeJS: 14.15.1
> // MongoDB: 4.2-bionic (Docker)
> import { getModelForClass, isDocument, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.4
> import { TimeStamps } from "@typegoose/typegoose/lib/defaultClasses";
> import { assertion } from "@typegoose/typegoose/lib/internal/utils";
> import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.1
> 
> class SubEntity {
>   @prop({ required: true })
>   public length!: number;
> 
>   public getInfo() {
>     return "this is some info!";
>   }
> }
> 
> class ExampleEntity extends TimeStamps {
>   @prop({ required: true, unique: true, type: String })
>   public productId!: string;
> 
>   @prop({ ref: SubEntity, required: true })
>   public referenceEntityA: Ref<SubEntity>;
> 
>   @prop({ ref: () => SubEntity, required: true })
>   public referenceEntityB: Ref<SubEntity>;
> }
> 
> const SubEntityModel = getModelForClass(SubEntity);
> const ExampleEntityModel = getModelForClass(ExampleEntity);
> 
> (async () => {
>   await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });
> 
>   await mongoose.connection.db.dropDatabase();
> 
>   const exampleEntity = new ExampleEntityModel();
> 
>   const otherSubEnt = await SubEntityModel.create({ length: 25 });
> 
>   const subEnt = await SubEntityModel.create({ length: 100 });
> 
>   exampleEntity.productId = "blub";
>   exampleEntity.referenceEntityA = subEnt;
>   exampleEntity.referenceEntityB = otherSubEnt;
> 
>   await exampleEntity.save();
> 
>   const retrieved = await ExampleEntityModel.findById(exampleEntity._id).populate("referenceEntityA referenceEntityB").orFail().exec();
> 
>   console.log(retrieved.toJSON({ virtuals: true }));
> 
>   assertion(isDocument(retrieved.referenceEntityA));
>   assertion(isDocument(retrieved.referenceEntityB));
> 
>   console.log(retrieved.referenceEntityA.getInfo());
>   console.log(retrieved.referenceEntityB.getInfo());
> 
>   await mongoose.disconnect();
> })();
> ```
> 
> ran your code a bit modified:
> 
> ```ts
> import mongoose from 'mongoose'
> import { ExampleEntityModel } from './Example.entity'
> import { ReferenceEntityModel } from './Reference.entity'
> import { SubEntity } from './SubEntity'
> 
> 
> console.log('The mongoose version:')
> console.log(mongoose.version)
> 
> mongoose.connect('mongodb://localhost:27017/typegoose-bug-3', {
>     useNewUrlParser: true,
>     useCreateIndex: true,
>     useFindAndModify: false,
>     useUnifiedTopology: true
> }).then(async connection => {
>     await mongoose.connection.db.dropDatabase();
> 
>     console.log('Connected!')
> 
>     await ExampleEntityModel.deleteMany({})
> 
>     await ReferenceEntityModel.deleteMany({})
> 
>     const exampleEntity = new ExampleEntityModel()
> 
>     const otherSubEnt = new SubEntity()
> 
>     otherSubEnt.length = 25
> 
>     const subEnt = new SubEntity()
> 
>     subEnt.length = 100
> 
>     const referenceEntity = new ReferenceEntityModel()
> 
>     referenceEntity.productId = 'product-id'
> 
>     await referenceEntity.save()
> 
>     exampleEntity.productId = 'blub'
>     exampleEntity.subEntities = [subEnt]
>     exampleEntity.otherSubEntities = [otherSubEnt]
>     exampleEntity.referenceEntityA = referenceEntity
>     exampleEntity.referenceEntityB = referenceEntity
> 
> 
>     await exampleEntity.save()
> 
>     console.log('Getting entity A')
>     const retrieved = await ExampleEntityModel.findById(exampleEntity._id).populate('referenceEntityA')
> 
>     // This fails! In order to test the Reference issue, uncomment the following two lines.
>     console.log('Getting entity B')
>     const retrievedB = await ExampleEntityModel.findById(exampleEntity._id).populate('referenceEntityB')
> 
>     if (retrieved) {
>         // console.log(retrieved)
> 
>         console.log('Using normal type')
>         retrieved.otherSubEntities.forEach(retSubEnt => {
>             console.log(retSubEnt.getInfo())
>         })
>         console.log('Using arrow function type')
>         retrieved.subEntities.forEach(retSubEnt => {
>             console.log(retSubEnt.getInfo())
>         })
>     }
> 
>     await mongoose.disconnect();
> })
> ```
> 
> can you confirm you have all the requirements that typegoose needs?
> like having tsconfig `target` being `es6` and having the other options enabled?

I found the culprit: I had target: "es5" in the tsconfig.json. Sorry for the confusion
