### ISSUE TITLE
Update to work with mongoose 5.12 / 5.13

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#432]
## Which feature

Since these versions mongoose has included its own typescript definitions

**Comment by hasezoey** [comment]
work has started in branch https://github.com/typegoose/typegoose/commits/update_mongoose5.11, but i have no clue on how to fix these types while not fully rewriting typegoose's types
-> the only "fixes" i could make would be very inconvenient to use much

**Comment by otroboe** [comment]
I think it's a duplicate with https://github.com/typegoose/typegoose/issues/424

**Comment by smolinari** [comment]
@otroboe - It's not.

Scott

**Comment by hasezoey** [comment]
@otroboe #424 is about "typegoose not working with old types" (the types in the issue were `@types/mongoose@5.5.x`, while typegoose requires `@types/mongoose@5.10.2`)

**Comment by orblazer** [comment]
Its not perfect and this still bug for `create` but its an first step.

```ts
export type DocumentType<T extends AnyParamConstructor<any>> = T extends AnyParamConstructor<infer U> ? mongoose.Document & U : mongoose.Document
export type ModelType<T extends AnyParamConstructor<any>> = mongoose.Model<DocumentType<T>>
export type ReturnModelType<T extends AnyParamConstructor<any>> = ModelType<T> & T;

// This is new and is an util
export type QueryMethod<ResultType, DocType extends AnyParamConstructor<any>> = mongoose.Query<ResultType | null, DocumentType<DocType>>
```

The points i have try to fix :
- [ ] No require `typeof` (e.g `DocumentType<Account>` instead of `DocumentType<typeof Account>`)
  This is visibly very hard to fix
- [ ] In the new `QueryMethod` find an way to specify only 1 arg for the end result `QueryMethod<Account>` or `QueryMethod<Account[]>` (if is not an `findOne`)

**Comment by hasezoey** [comment]
@orblazer did you already try to run the tests and ran the script `build:tests` without any error?

**Comment by orblazer** [comment]
@hasezoey I have explore more deep and i think the current types in `mongoose` its not fully compatible and i go check to this in the next days.

My current state :
```ts
// This is temporary unless my PR accept
type InternalDocumentType<T> = (T extends {_id?: RefType } ? Omit<mongoose.Document, '_id'> : mongoose.Document) & T

export type DocumentType<T extends AnyParamConstructor<any>> = T extends AnyParamConstructor<infer U> ? InternalDocumentType<U> : InternalDocumentType<T>;
export type ReturnModelType<U extends AnyParamConstructor<any>> = mongoose.Model<DocumentType<U>> & U;
```

But with this the `create` method is broken. This method is my big problem currently, i think we need modify current `mongoose` type for fix our case or we need extends all class with `mongoose.Document` (but this require a lot changes).


I have start to improve the types of `mongoose` : https://github.com/Automattic/mongoose/pull/9698, https://github.com/Automattic/mongoose/pull/9699, https://github.com/Automattic/mongoose/pull/9700

**Comment by hasezoey** [comment]
@orblazer any update with the types?

**Comment by orblazer** [comment]
No sorry, i don't have enough time for find an easy way except if we extends the class with `mongoose.Document`

**Comment by hasezoey** [comment]
Updated branch to 5.11.9 and tried to upgrade again, this time `Document` with `DocumentType` was possible, but for many cases https://github.com/Automattic/mongoose/pull/9753 is still nedded, further testing & refactoring needed (and test references (`Ref` type))

**Comment by smolinari** [comment]
@hasezoey - looks like your PR got merged. Nice work! Hopefully it is a good next step to getting back to compatible with the newer versions of Mongoose.

Scott

**Comment by hasezoey** [comment]
@smolinari yes it is good, but there are many more problems, like:
- https://github.com/Automattic/mongoose/issues/9817 (this is issue is closed, but the main issue not fixed - read the comments to know what the problem is)
- https://github.com/Automattic/mongoose/issues/9818 (this is one major point i could transition yet to the new types)

**Comment by smolinari** [comment]
I've thumbs-upped 👍 the issues that are still open. Wish there is more I could do.

Scott

**Comment by poppa** [comment]
Do you guys have any suggestions as how to circumvent this issue, albeit temporarily?

**Comment by hasezoey** [comment]
@poppa the only solutions currently are:
- dont use typegoose when using mongoose 5.10.19+
- stay at mongoose 5.10.18 with typegoose

**Comment by poppa** [comment]
> @poppa the only solutions currently are:
> 
> * dont use typegoose when using mongoose 5.10.19+
> * stay at mongoose 5.10.18 with typegoose

Thanks @hasezoey, I was afraid that would be the answer 😁 

Keep up the good work 👍

**Comment by blatoo** [comment]
Hi guys, what's the plan of typegoose? organise a rewrite for the new version mongoose or stay at the mongoose lower version?

**Comment by hasezoey** [comment]
> Hi guys, what's the plan of typegoose? organise a rewrite for the new version mongoose or stay at the mongoose lower version?

as explained in comments above, i am currently waiting for mongoose's official types to support everything that the old types have (like query helpers), and to get an universal way for references (if possible, otherwise transition help) as explained earlier

**Comment by tar-aldev** [comment]
It still gives `any` type event if I follow the suggestion and use
"mongoose": "^5.10.18",
"@typegoose/typegoose": "^7.4.8",
 @types/mongoose: "^10.3.0"

**Comment by CallMeLaNN** [comment]
```
"@typegoose/typegoose": "^7.4.8",
"mongoose": "5.10.18",
"@types/mongoose": "^5.10.3",
```

All are latest except mongoose. At least `await *Model.update*()`, `await *Model.distinct()` return `any` type, but most `getDiscriminatorModelForClass` models function including `find()` is not working. It return `any` type.

**Comment by wz930206** [comment]
> ## Which feature
> Since these versions mongoose has included its own typescript definitions
https://blog.csdn.net/wz_coming/article/details/113859565

**Comment by TwoAbove** [comment]
Yo!
Thanks for the project :smiley: 

Any ways I can help push this forward?

**Comment by hasezoey** [comment]
@TwoAbove sorry, not really

**Comment by smolinari** [comment]
@TwoAbove   - You could also +1 the issues noted by @hasezoey above. In fact, everyone could/should, who gets to this issue. 😃 

Scott

**Comment by ggurkal** [comment]
Just to update, my PR for query methods (https://github.com/Automattic/mongoose/pull/9896) got accepted which will be included in the next mongoose version (according to their milestones). After that, it should be fairly simple to update typegoose after the mongoose release.

**Comment by hasezoey** [comment]
currently trying to update again to 5.11, i came across:
- https://github.com/Automattic/mongoose/issues/9980

but this dosnt impact porting progress

**Comment by hasezoey** [comment]
It seems like things got compatible, made an PR #497, but needs independent testing

**Comment by harveyconnor** [comment]
When do you plan on releasing 8.0 on npm?

**Comment by hasezoey** [comment]
@harveyconnor because its an major version, i plan on doing some things, but when the PR (#497) gets merged, an beta version will be released (semantic-release will add an comment here)

**Comment by SpiraMira** [comment]
FYI if you're implementing a MEAN stack with typegoose + latest NestJS v7 + @nestjs/mongoose, the following works with latest typegoose and latest @types/mongoose:

    "@nestjs/mongoose": "~7.1.0" in package.json dependencies

this will limit the module's mongoose peer dependency to 5.10.18 (as suggested and while we wait for a possible fix)

**Comment by smolinari** [comment]
@SpiraMira - What's the reasoning behind using both Typegoose and Mongoose Nestjs modules?

Scott

**Comment by SpiraMira** [comment]
> @SpiraMira - What's the reasoning behind using both Typegoose and Mongoose Nestjs modules?
> 
> 
> 
> Scott

The Nestjs mongoose modules don’t provide the same mongoose model wrappers, they are not redundant and integrate well (with a little work) We have a Nestjs mongo server that worked well with Typegoose until we upgraded to Nestjs v7.2+ which depends on the latest mongoose 5.11+. Hence this slight retrograde recommendation. Just wanted to share our experience for those doing the same.

**Comment by smolinari** [comment]
@SpiraMira  - So, if Typegoose can get back to running with the most modern Mongoose versions (which is soon to happen), would you be dropping the NestJS Mongoose module?

Scott

**Comment by SpiraMira** [comment]
@smolinari - Not at all, as I said, they are complementary in our architecture. The NestJS mongoose module is part of the NestJS framework providing tighter mongoose and NestJS integration. Dropping the NestJS Mongoose module would simply mean handcrafting the same features directly in Mongoose as described [here](https://docs.nestjs.com/techniques/mongodb) We still want Typegoose's streamlined model development.

**Comment by smolinari** [comment]
@SpiraMira - Ahh.. I understand now. I would guess you hadn't ran into this little gem then? 😁  

https://kpfromer.github.io/nestjs-typegoose/

Scott

**Comment by SpiraMira** [comment]
@smolinari - yes I did a while ago. Opted out after closer inspection of outstanding issues and PRs. I also wouldn’t be surprised if it suffers from the same issues with NestJS v7 + latest Typegoose + latest mongoose. I think updating Typegoose (if at all possible) is fundamental.

**Comment by SpiraMira** [comment]
@hasezoey and @smolinari - can confirm that goose 8b2 works great with latest mongoose and my NestJS v7@latest modules. 

Great job and thanks again.

I had to remove @types/mongoose though - will that be the case going forward or should we expect an updated @types/mongoose in the near future? (Not sure why we would need to since mongoose provides its own d.ts ...)

Regards

**Comment by hasezoey** [comment]
@SpiraMira thats the reason on why its an major change, because `@types/mongoose` is not needed anymore (actually, it interferes with the official types)

**Comment by SpiraMira** [comment]
@hasezoey - it does indeed - much cleaner - thank you all again for the great support! Looking forward to v8-final!

**Comment by hasezoey** [comment]
closing, because fixed in beta
