### ISSUE TITLE
Types suddenly messed up with .lean() function calls?

### ISSUE THREAD

**Issue by shahidcodes** [typegoose/typegoose#435]
Any `find` or `findOne` with `.lean()` call started to return type `any` which earlier was the model itself. Even using passing type to `.lean<Type>` returns the same `any` type.  This issue popped suddenly after I ran clean `npm i` on the local machine. 

## Versions

- System:  windows 
- NodeJS: 12.14.0
- Typescript: 4.0.3

- Compiler / Transpiler: tsc  
- Typegoose(NPM): ^7.3.5 
- mongoose: ^5.9.9 
- mongodb: ^3.5.5

---
## Screenshots
Without `.lean<Type>`
![image](https://user-images.githubusercontent.com/17620737/101239480-a1940d80-3709-11eb-8b6e-20fbcc1acc78.png)

With `.lean<Type>`
![image](https://user-images.githubusercontent.com/17620737/101239511-cc7e6180-3709-11eb-8585-5f17f687c165.png)

**Comment by hasezoey** [comment]
what is the version of `@types/mongoose`?

**Comment by shahidcodes** [comment]
It is `5.7.36`.
`    "@types/mongoose": "^5.7.36", `

**Comment by hasezoey** [comment]
if downgrading `@types/mongoose` dosnt work, then maybe try upgrading to latest supported by typegoose  and manually assigning the value (i mean lean returns an POJO, not an model - so the types are kinda correct)

**Comment by shahidcodes** [comment]
Upgrading to the latest `typegoose` and typegoose supported versions `mongoose` and `@types/mongoose` seems to be working. But still, no idea why out of sudden with no change in package.json or version of any library it started returning any for all `.lean()`.
