### ISSUE TITLE
Return type of find is DocumentType<Entity> instead of mongoose.Document

### ISSUE THREAD

**Issue by mateja176** [typegoose/typegoose#437]
## Versions

- System: linux 
- NodeJS: 14.0.3
- Typescript: 4.0.3

- Compiler / Transpiler: tsc / ts-node / ts-jest 
- Typegoose(NPM): 7.4.5 
- Typegoose(GIT): commithash
- mongoose: 5.10.18 
- mongodb: 3.6.3

## What is the Problem?

Find return type is `Promise<DocumentType<Entity>>` isntead of `mongoose.Document`. For example `prop` can be accessed on `doc._doc.prop` but is `undefined` in case of `doc.prop`

## Code Example

```ts
const doc = await TestModel.find({ prop: true })

doc.prop === undefined

doc._doc.prop // TypeScript error
```

## Do you know *why* it happens?

The type definitions are incorrect compared to the runtime.

---

**Comment by hasezoey** [comment]
> The type definitions are incorrect compared to the runtime.

nope, they are correct - the property `_doc` normally dosnt exist in plain mongoose, the only times i could observe it being an actual property is when `class-transformer` is / was used

> Find return type is Promise<DocumentType<Entity>> isntead of mongoose.Document

this type is correct, normal `mongoose.Document` dosnt have the properties of the class, and `DocumentType` is an AND of the class's properties and `mongoose.Document`

**Comment by mateja176** [comment]
> > The type definitions are incorrect compared to the runtime.
> 
> nope, they are correct - the property `_doc` normally dosnt exist in plain mongoose, the only times i could observe it being an actual property is when `class-transformer` is / was used
> 
> > Find return type is Promise<DocumentType> isntead of mongoose.Document
> 
> this type is correct, normal `mongoose.Document` dosnt have the properties of the class, and `DocumentType` is an AND of the class's properties and `mongoose.Document`

With your hint, I figured it out:

```ts
(async () => {
  await mongoose.connect(env.mongodbURI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  const { ...user } = await UserModel.findOne({
    _id: '5fce9eb570e8348435692acc',
  });

  console.log(user);

  await mongoose.connection.close();
```

Returns

```ts
{
  '$__': InternalCache {
    strictMode: true,
    selected: {},
    shardval: undefined,
    saveError: undefined,
    validationError: undefined,
    adhocPaths: undefined,
    removing: undefined,
    inserting: undefined,
    saving: undefined,
    version: undefined,
    getters: {},
    _id: '5fce9eb570e8348435692acc',
    populate: undefined,
    populated: undefined,
    wasPopulated: false,
    scope: undefined,
    activePaths: StateMachine {
      paths: [Object],
      states: [Object],
      stateNames: [Array]
    },
    pathsToScopes: {},
    cachedRequired: {},
    session: undefined,
    '$setCalled': Set(0) {},
    ownerDocument: undefined,
    fullPath: undefined,
    emitter: EventEmitter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: 0,
      [Symbol(kCapture)]: false
    },
    '$options': { skipId: true, isNew: false, willInit: true, defaults: true }
  },
  isNew: false,
  errors: undefined,
  '$locals': {},
  '$op': null,
  _doc: {
    _id: '5fce9eb570e8348435692acc',
  },
  '$init': true
}
```

Instead of `DocumentType<User>`

*Notice* that the key part is `...user`. The only logical solution is to avoid [rest/spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) with `DocumentTypes`'s.

**Comment by Dan-X** [comment]
avoiding spread sometimes seems to make merging much more completed:

```js
const foundUser = await UserModel.findOne({
    _id: '5fce9eb570e4348435692acc',
 });
  
/*{_id: '5fce9eb570e4348435692acc',
    name: '123'
   age: 23
}  */
const newInfo = {age:24}
foundUser = {...foundUser,  ...newInfo}
foundUser.save()
```
something like this won't work.
I used to do like 

```js
foundUser = {...foundUser._doc,  ...newInfo}
```
is there by chance a better way to update document/subdocuments?
Thanks!
