### ISSUE TITLE
How to use mongodb Client-Side Field Level Encryption

### ISSUE THREAD

**Issue by meirkl** [typegoose/typegoose#445]
Is there a way to use [mongoose-field-encryption](https://github.com/wheresvic/mongoose-field-encryption) with typegoose?
Or is there another way to use Client-Side Field Level Encryption?

Thanks!

## Versions

- System: windows 
- NodeJS: 14.15.1
- Typescript: 4.1.2

- Compiler / Transpiler: tsc 
- Typegoose(NPM): 7.4.1 
- mongoose: 5.10.10 
- mongodb: 4.2.11

---

**Comment by hasezoey** [comment]
i dont see a reason on why it shouldnt work

you can add plugins with the [`@plugin`](https://typegoose.github.io/typegoose/docs/api/decorators/plugins) class decorator
-> more examples can be seen [here](https://typegoose.github.io/typegoose/docs/guides/advanced/common-plugins)

**Comment by meirkl** [comment]
Yes. It works... was missing the secret so my nestjs project didn't start.

```
import { fieldEncryption } from 'mongoose-field-encryption';

@plugin(fieldEncryption, {
  fields: ['foo'],
  secret: process.env.ENCRYPTION_KEY,
})
export class Foo {}
```
