### ISSUE TITLE
default prop function "this" should refer to document (types)

### ISSUE THREAD

**Issue by JohnDeved** [typegoose/typegoose#453]
## Versions

- System: linux
- NodeJS: 14.15.3
- Typescript: ^4.0.2

- Compiler (not related)
- Typegoose(NPM): ^7.4.5
- mongoose: 5.10.2
- mongodb: 3.6.0

## What is the Problem?

default prop function "this" should refer to document, but refers to "BasePropOptions | BasePropOptions | ..."
https://mongoosejs.com/docs/defaults.html#default-functions-and-this

## Code Example
![image](https://user-images.githubusercontent.com/24187269/102763589-2faefb80-437a-11eb-8441-dbefaed716b2.png)

```ts
import { getModelForClass, prop } from '@typegoose/typegoose' // @typegoose/typegoose@7.4.5
import * as mongoose from 'mongoose' // mongoose@5.10.18 @types/mongoose@5.10.2

class User {
  @prop({ default () { this. } }) ranking?: number
}
const UserModel = getModelForClass(User);

(async () => {
  await mongoose.connect('mongodb://localhost:27017/', { useNewUrlParser: true, dbName: 'verifyMASTER', useCreateIndex: true, useUnifiedTopology: true })

  const doc = new UserModel({ username: 'user1' })

  console.log(doc)

  await mongoose.disconnect()
})()

```

## Do you know *why* it happens?

most likely missing types for the default function

---

**Comment by hasezoey** [comment]
currently:
https://github.com/typegoose/typegoose/blob/f299fcc4a2f8291271ad6727704d88aa27b1ca87/src/types.ts#L79-L80

because i dont know of all possible variations it can have

**Comment by JohnDeved** [comment]
alright.
for anybody else who wants to type "this" correctly inside the default function, here is how to do it:
![image](https://user-images.githubusercontent.com/24187269/102773942-55440100-438a-11eb-97ca-8e4ef70492c8.png)
https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters

**Comment by hasezoey** [comment]
i recommend using `DocumentType<Class>` for correct & full types

PS: from my knowledge, decorators cannot automatically get the type of the class they are on, so even if it would have this, it would be needed to manually provide it

**Comment by JohnDeved** [comment]
Right. I see, and then the default would also have to be a finite union type, which might not be possible here...

I think you can close this issue.
(Ideally after mentioning how to type "this" in the documentation and jsdocs)

**Comment by JohnDeved** [comment]
If you don't mind, I could create a pull request for that later today

**Comment by hasezoey** [comment]
closing because #456 is merged
