### ISSUE TITLE
Getting "Error: First param to `schema.plugin()` must be a function, got "object"" when using plugin 'mongoose-findorcreate' with Typegoose

### ISSUE THREAD

**Issue by axcosta** [typegoose/typegoose#454]
## Versions

- System: linux
- NodeJS: 14.15.1
- Typescript: 4.0.2
- Compiler / Transpiler: tsc / ts-node
- Typegoose(NPM): 7.4.5
- mongoose: 5.10.2
- mongodb-memory-server: 6.6.7

## What is the Problem?

Getting "Error: First param to `schema.plugin()` must be a function, got "object"" when using plugin 'mongoose-findorcreate' with Typegoose.

## Code Example

```ts
import { prop, plugin, defaultClasses, getModelForClass } from '@typegoose/typegoose';
import * as findOrCreate from 'mongoose-findorcreate';

@plugin(findOrCreate)
export class Category extends defaultClasses.FindOrCreate {
   @prop({ required: true, unique: true })
   public description!: string;
}

const CategoryModel = getModelForClass(Category);

export default CategoryModel;
```

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
could you provide your tsconfig?

**Comment by axcosta** [comment]
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["es2019"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": false,
    "esModuleInterop": true,
    "inlineSourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
  "include": ["src/**/*"],
  "exclude": ["node_modules", "tests/**/*.spec.ts"]
}
```

**Comment by hasezoey** [comment]
@axcosta maybe instead of `* as findorcreate` try `{ findorcreate }`
or try with the current `findorcreate.default` or something

**Comment by axcosta** [comment]
@hasezoey , thanks!

It worked with:
```ts
import * as findOrCreate from 'mongoose-findorcreate';
@plugin(findOrCreate.default)
```

**Comment by axcosta** [comment]
Maybe that plugins section of document can be updated to this.

**Comment by axcosta** [comment]
Using plugin `mongoose-findorcreate` with code below does not pop up error reported originally. As a suggestion, Typegoose help page "Common Plugins", at section https://typegoose.github.io/typegoose/docs/guides/advanced/common-plugins/#mongoose-findorcreate could be updated with this information.
```ts
import * as findOrCreate from 'mongoose-findorcreate';
@plugin(findOrCreate.default)
```
