### ISSUE TITLE
Marking type as array forces the field to be created in MongoDB

### ISSUE THREAD

**Issue by WeebHiroyuki** [typegoose/typegoose#466]
## Versions
- System: Linux (Ubuntu 20.04.1) and Windows 10
- NodeJS: 14.15.3
- Typescript: 4.1.3

- Compiler / Transpiler: tsc 
- Typegoose(NPM): ^7.4.5 
- mongoose: ^5.11.9 
- mongodb: 4.4.2 (Community Edition)

## What is the Problem?
Optional fields that are arrays are for some reason force created in MongoDB. Basically, even if I run `await User.create({ username: 'John' });`, an empty array under the `nicknames` field is created for some reason.

## Code Example
```ts
import { prop, getModelFromClass } from '@typegoose/typegoose';

class UserClass {
  @prop()
  username: string;

  @prop({ type () => [String] })
  nicknames?: string[];
}

const User = getModelForClass(UserClass);

await User.create({ username: 'John' }); // Running this is ONLY supposed to create a new document with the username "John". It does that but it adds on an empty array under the nicknames field as well.
```

## Do you know *why* it happens?
No.

**Comment by hasezoey** [comment]
from my knowledge this is default mongoose behaviour, if this can be disabled, you need to search in the mongoose documentation

PS: i think you search for [this stackoverflow](https://stackoverflow.com/questions/43934652/how-to-make-mongoose-not-insert-empty-array-or-object-fields-into-a-document/52824032) question

**Comment by WeebHiroyuki** [comment]
Hi there. Yes, I believe that it isn't a typegoose issue. I think you can disable it by doing this when defining your model:
```ts
class User {
  @prop()
  username: string;

  @prop({ default: undefined, type () => [String] }) // The "default undefined" makes it use undefined as the default value instead of an empty array.
  nicknames?: string[];
}
```

**Comment by theDanielJLewis** [comment]
I know this is old, but I just want to say that 2 years later, adding `default: undefined` fixed this problem for me.
