### ISSUE TITLE
Add aggregate hook

### ISSUE THREAD

**Issue by albaquarto** [typegoose/typegoose#468]
In hook definition there isn't "aggregate". If I add a pre or post hook like @pre('aggregate', preFunc) or @post('aggregate', postFunc) I have a type error "Argument of type '"aggregate"' is not assignable to parameter of type 'RegEx | "update" | "remove" ... And 16 more..." because the string 'aggregate' is not present in QDM,DM and others "methods" types.
If you add something like this in file  hook.ts  mongoose  aggregate middleware will be provided.

// file hook.ts

type AggregateMethod = 'aggregate';
type MultipleMethod = 'find' | 'update' | 'deleteMany' | 'aggregate';

type PreFnWithAggregate<T> = (this: Aggregate<T>, next: (error?: Error) => ReturnVoid, done: EmptyVoidFn) => ReturnVoid;

 pre<T>(method: AggregateMethod, fn: PreFnWithAggregate<T>): ClassDecorator;
```

**Comment by hasezoey** [comment]
what is that you want to try to suggest?

(i modified your question into an code block, to be better readable)

**Comment by albaquarto** [comment]
In hook definition there isn't "aggregate". If I ad a pre or post hook for like @pre('aggregate', preFunc) or @post('aggregate', postFunc)  I have a type error because the string 'aggregate' is not present. Mongoose provide aggregation middleware, typegoose don't.
