### ISSUE TITLE
[Request] Don't enforce suffix on model name

### ISSUE THREAD

**Issue by ChrisLahaye** [typegoose/typegoose#47]
Hello,

Model names are being suffixed with the collection name when `schemaOptions.collection` is passed as model options.

We dynamically use these model names and therefore prefer to have control over them. If I name my model X, then it should be named X, nonetheless of whether I specify a collection name. I think it is better to not make any decisions for the user of how models should be named, but instead use the class name as model name while providing an option to override it.

```
function getName(cl) {
    const options = Reflect.getMetadata(constants_1.DecoratorKeys.ModelOptions, cl) || {};
    const baseName = cl.name;
    const suffix = (options.options ? options.options.customName : undefined) ||
        (options.schemaOptions ? options.schemaOptions.collection : undefined);
    return suffix ? `${baseName}_${suffix}` : baseName;
}
```

Maybe use `customName` as name instead of suffix.

I humbly request you to reconsider,

Chris

**Comment by hasezoey** [comment]
thanks for asking, would 7114498fb8357c90185bdeda4a7dde81b8ba35d2 solve your request?

**Comment by ChrisLahaye** [comment]
I can work with that but I think those are still weird default semantics. Why not make suffixing opt-in? If you don't want to do that, maybe  don't require a customName but fallback to the base name / class name when disabling automatic names.

**Comment by hasezoey** [comment]
i think about adding "global" settings, but not in 6.0.0

**Comment by hasezoey** [comment]
closed, because added in 7114498fb8357c90185bdeda4a7dde81b8ba35d2

**Comment by ChrisLahaye** [comment]
> i think about adding "global" settings, but not in 6.0.0

Would you be open to accept contributions for my proposal of:
- making suffixing opt-in
- using the class name as default base name
- allowing the base name to be overwritten

Unless you disagree of course.

**Comment by hasezoey** [comment]
> using the class name as default base name

it currently does, when not using collection or customName

> making suffixing opt-in

its currently opt-out, but like i said i plan on doing global settings

> allowing the base name to be overwritten

already possible with `automaticName: false` and a customName

---

PS: it is currently an opt-out because of not clashing with https://typegoose.github.io/typegoose/guides/advanced/models-with-same-name/

**Comment by ChrisLahaye** [comment]
I intended to say, make class name the default model name. This should be the default behavior like it has been in all prior versions.

I understand that you want to 'solve' the issue of name clashing but you don't do this by enforcing new weird default semantics. The current behavior (without suffixing) was fine for 99% of the cases, in the remaining 1% when name clashing happens someone wants to have mechanisms available to solve this, but in my opinion this shouldn't change the default behavior to something that is irreversible and drastically different than before.

Now in order to acquire the old behavior everyone needs to annotate with:
```
@modelOptions({ options: { automaticName: false, customName: 'ClassA' } })
class A
```

Another implication is that people have been dealing with recursive references as follows:
```
@prop({ ref: { name: 'ClassB' }, required: true })
public something!: Ref<ClassB>;
```

Now the name changes to `ClassB_collectionName`. 

I appreciate the work you put in maintaining this fork and I would like to upgrade to your fork as you have welcome additions, but once more I would like to ask you to reconsider. Most people haven't updated yet to 6.0 as its a major release and not the default on GitHub, but I am certain that once they do, they will run into similar problems.

**Comment by hasezoey** [comment]
so to collect thing & be on the same level, you want to "reverse" automaticName, to be opt-in instead of opt-out and that customName so-or-so will override the default name?

**Comment by hasezoey** [comment]
does 6bc907ddd1cb6b70ee469beb3ed18f0e372c64a7 now fully answer your question?

**Comment by ChrisLahaye** [comment]
> does [6bc907d](https://github.com/typegoose/typegoose/commit/6bc907ddd1cb6b70ee469beb3ed18f0e372c64a7) now fully answer your question?

For me this would work as the model name now matches the class name by default. 

Now, lets consider other users. First, some remarks on the proposed commit:
- `customName` is used as base/model name, unless `automaticName` is true, then it is used as suffix. This logic is *abracadabra* which we don't want.
- `suffix` can be undefined, resulting in a name `BaseName_undefined`

> so to collect thing & be on the same level, you want to "reverse" automaticName, to be opt-in instead of opt-out and that customName so-or-so will override the default name?

Indeed, so what makes more sense is the following:
- `automaticNames` is opt-in, when enabled model (base) names are suffixed with the collection name
- `customName` overrides the model (base) name

```typescript
export function getName<T, U extends AnyParamConstructor<T>>(cl: U) {
  const options: IModelOptions = Reflect.getMetadata(DecoratorKeys.ModelOptions, cl) || {};
  const baseName = options.options && options.options.customName
    ? options.options.customName
    : cl.name;

  if (options.options && options.options.automaticName) {
    const suffix = options.schemaOptions && options.schemaOptions.collection;

    if (suffix) {
      return `${baseName}_${suffix}`;
    }
  }

  return baseName;
}
```

Although, I would expect most people to use a `customName` instead of `automaticName` as it fulfils the same goal while giving control over the model name, unless `automaticName` is a global option. 

Maybe keep it simple while still giving users the tools to work around name clashes:
```typescript
export function getName<T, U extends AnyParamConstructor<T>>(cl: U) {
  const options: IModelOptions = Reflect.getMetadata(DecoratorKeys.ModelOptions, cl) || {};
  
  return options.options && options.options.customName
    ? options.options.customName
    : cl.name;
}
```

**Comment by hasezoey** [comment]
> suffix can be undefined, resulting in a name BaseName_undefined

yes it can be undefined, but then it just returns the normal class name, as it worked before automaticName

> Maybe keep it simple while still giving users the tools to work around name clashes:

i want to keep automaticName for users that use the same class name (i still dont understand why), but a different collection

> This logic is abracadabra which we don't want.

i wanted to preserve the functionality from *before* `automaticName`, which i think could be useful
