### ISSUE TITLE
getModelForClass returns any

### ISSUE THREAD

**Issue by iamchathu** [typegoose/typegoose#473]
## Versions

- System: macos
- NodeJS: 14.15.1
- Typescript: 4.1.3

- Compiler / Transpiler: tsc / ts-node 
- Typegoose(NPM): ^7.4.6 
- mongoose: 5.11.11 

## What is the Problem?

`getModelForClass()` returns any

## Code Example

```ts
import { getModelForClass, prop } from '@typegoose/typegoose';

export class Sample {
  @prop()
  name!: string;
}

const Samples = getModelForClass(Sample);

export default Samples;

```

## Do you know *why* it happens?

*no*

---

**Comment by smolinari** [comment]
@iamchathu - Make sure you stick your Mongoose version to 5.10.18. There are unfortunately breaking changes to Typegoose for every version after that. 

Scott

**Comment by hasezoey** [comment]
Closing in favor of #432
