### ISSUE TITLE
Allowing custom `id` schema property

### ISSUE THREAD

**Issue by rr-codes** [typegoose/typegoose#476]
## Which feature

- [Allowing custom `id` schema property](https://mongoosejs.com/docs/guide.html#id)

## Code Examples

This is my schema in normal Mongoose:

```ts
export const StripeProductSchema: Schema = new Schema({
  id: String,
  active: Boolean,
  metadata: Schema.Types.Mixed,
  name: String,
}, {
  id: false,
});
```

By setting `id: false`, I remove the normal `id` alias to `_id`, and instead have my own `id` property (which is completely unrelated to `_id`). This works perfectly fine.

However, when I translate it to Typegoose:

```ts
@modelOptions({ schemaOptions: { id: false }})
@index({ id: 1 })
class StripeProductClass {
    @prop({ required: true, unique: true })
    public id: string

    @prop({ required: true })
    public active: boolean

    @prop({ required: true })
    public metadata: Record<string, string>

    @prop({ required: true })
    public name: string
}
```

and try to create a new instance via 

```ts
const product = await StripeProduct.create({
    id: 'myId', // <- error here
    active: true,
    name: 'test',
    metadata: { }
})
```

I get an error saying `No overload matches this call.`. When I remove `id: 'myId'`, the type error goes away, however I am no longer able to specify the `id` that I want.

## Versions
* `mongoose 5.10.18`
* `@typegoose/typegoose 7.4.7`
* `@types/mongoose 5.10.3`
* `typescript 4.0.3`

**Comment by hasezoey** [comment]
missing versions, what are you using? `mongoose`, `@types/mongoose`, `@typegoose/typegoose`, `typescript`

**Comment by richardrobinson0924** [comment]
@hasezoey Apologies, just edited the post

**Comment by hasezoey** [comment]
confirmed, however it cannot be changed by typegoose, only workarounds:
- rename your property to not be `id`
- use an `as Class` cast (`.create({} as Class)`)
