### ISSUE TITLE
getModelForClass does not has any type

### ISSUE THREAD

**Issue by contrerascoder** [typegoose/typegoose#480]
Hi, I am using typegoose 7.4.8 in my typescript project and used the getModelForClass so I get my User model but does not return any type, and dont have intellisense

Any suggest to this? Thanks!!

**Comment by hasezoey** [comment]
Maybe this is an duplicate of #432

**Comment by contrerascoder** [comment]
Is this not fixed?

**Comment by hasezoey** [comment]
no, it cant really be fixed with the new types, and there is no way to replace it with the old types on the new version

**Comment by tar-aldev** [comment]
@hasezoey You mentioned that in docs, that mongoose should be not higher than 5.10.19.
However, even with mongoose 5.10.7 every type of getModelForClass returns any

**Comment by hasezoey** [comment]
@tar-aldev do you have the latest version of `@types/mongoose` installed?

**Comment by tar-aldev** [comment]
@hasezoey  It looks like the latest separate typing package is @types/mongoose: 5.10.3;

**Comment by hasezoey** [comment]
>  What would be the latest compatible versions of all these packages?

latest `@typegoose/typegoose`, latest `@types/mongoose`, and `mongoose@5.10.18` (because `5.10.19` already adds the new types)

>  I mean any type is not useful at all(

could you give some code examples (class, and function call) and a bit more about your environment

**Comment by CallMeLaNN** [comment]
```
"@typegoose/typegoose": "^7.4.8",
"mongoose": "5.10.18",
"@types/mongoose": "^5.10.3",
"typescript": "3.9"
```

All are latest except mongoose. At least `await *Model.update*()`, `await *Model.distinct()` return `any` type, but most `getDiscriminatorModelForClass` models function including `find()` is not working. It return `any` type.

Node: lts/erbium
VSCode

**Comment by hasezoey** [comment]
@CallMeLaNN could you provide your classes and how|what functions you use?
