### ISSUE TITLE
Bulkwrite typings

### ISSUE THREAD

**Issue by underfisk** [typegoose/typegoose#483]
## Describe what you need | want
So when we use bulkWrites the types are pretty easy to document, MongoDB has it fixed on its official bulkWrite documentation but it would be good to see support for this in bulkWrite params and the bulkWrite result in order to offer more typings, its very easy and often to commit mistakes using it. Not sure if this is something thought or if its something related with mongoose itself but it would be good to have interfaces to interact with our models

## Do you have already an idea for the implementation?
There are some common operations such as updateOne, insert etc etc and those can be easily implemented, the interface of them is also simply, filter and the update/action we want, it would need to read our model class/interface and provide partially or not the model fields into the filter/update operation, i think its kinda complex at least in update but would make a lot of sense having typings for this. (just a side node, Aggregation is way harder due to the fact you can create pipes types but not what's going to be done inside as mongodb compass does but what i'm requesting here is just for bulkWrites, in my use case its very used to prevent write conflicts with save when overriding sub-documents)

**Comment by hasezoey** [comment]
sorry, but i dont understand what you are talking about, please provide an link to the documentation mentioned and code examples of what works and what dosnt

Note: this package (typegoose) **does not** provide typings for functions provided by mongoose, use `@types/mongoose` for that

PS: Currently highest supported mongoose version is 5.10.18 (#432)

**Comment by underfisk** [comment]
Okay let me try to make the request clear. There is no typings for bulkWrite in mongoose but even if there were it would not be compatible (probably) with the typegoose models for field scanning
As you can see in the docs of mongo: https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/ 
there are only a few valid operations that makes it easy to create an interface and the <document> can be replaced with typegoose model to provide better typing support
About mongoose version, yes i'm aware but this has nothing to do with the versions, it works fine even in older than 5
I'm not sure if this answer was clear but we the idea is to have bulkWrite typings on top of typegoose for our models

**Comment by hasezoey** [comment]
from what i can see, `bulkWrite` is typed [as can be seen here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/00337f857887f695e18fbeaf0e09764831488868/types/mongoose/index.d.ts#L3245-L3256), only thing is that param1 (operations) is typed to `any` and that the return is typed to `BulkWriteOpResultObject` where `.result` is also set to `any`

but this has nothing to do with typegoose, you would need to change it in the `@types/mongoose` repository

**Comment by hasezoey** [comment]
closing because stale
