### ISSUE TITLE
how do we represent bitsallset

### ISSUE THREAD

**Issue by nhhockeyplayer** [typegoose/typegoose#484]
can someone show how to model a TYPEGOOSE property as one of these ?

https://docs.mongodb.com/manual/reference/operator/query/bitsAllSet/#examples

**Comment by nhhockeyplayer** [comment]
here is a node.js blip

https://thecodebarbarian.com/node-perspective-on-mongodb-3.2-bitwise-query-operators.html

**Comment by nhhockeyplayer** [comment]
what I have so far in typescript is my own BitSet.ts

this works for me in my app and its not immediately apparent to me how this will shoe into a typegoose property

```
/**
 *  models a set of bits
 */

type BitType = true | false

export class BitSet {
    private _vector: Array<BitType>

    constructor(size: number) {
        this._vector = new Array<BitType>(size + 1)
        this.resetAll()
    }

    resize(newSize: number) {
        this._vector = new Array<BitType>(newSize + 1)
    }

    get(position: number) {
        return this._vector[position]
    }

    set(position: number) {
        this._vector[position] = true
    }

    reset(position: number) {
        this._vector[position] = false
    }

    setAll() {
        for (let i = 0; i < this._vector.length; i++) {
            this._vector[i] = true
        }
    }

    resetAll() {
        for (let i = 0; i < this._vector.length; i++) {
            this._vector[i] = false
        }
    }

    size() {
        return this._vector.length
    }

    getArray() {
        return this._vector
    }

    isClear() {
        for (let i = 0; i < this._vector.length; i++) {
            if (this.get(i)) {
                return false
            }
        }
        return true
    }
}

```

**Comment by nhhockeyplayer** [comment]
Im also tempted to take my whole typescript BitSet.ts object instance and just persist the whole thing as a property but Im missing something here conceptually... my apologies

does anyone have some clarification on how this would happen

Thanks in advance

**Comment by nhhockeyplayer** [comment]
so yeah... I want to HONK the whole thing into a property and store it

and then later YANK the whole thing out intact and use it as-is

from a typegoose class property

**Comment by hasezoey** [comment]
i have not used (or even heard of) this feature, so my answer might be vague
-> i will translate the mongoose example into an typegoose one

---

mongoose example:
```ts
var userSchema = new mongoose.Schema({
  name: String,
  booked: {
    type: Buffer,
    validate: function(v) {
      return v.length === 365 * 24 / 8; // buffer length in bytes
    }
  }
});
```
translated to typegoose:
```ts
class User {
  @prop()
  public name?: string;

  @prop({
    validate(v: Buffer) { // using "object literal shorthand", this is an different writing style to "validate: function(v) {"
      return v.length === 365 * 24 / 8; // buffer length in bytes
    }
  })
  public booked?: Buffer;

  // and example from your class
  // this function returns "undefined" if property "booked" does not exist
  public get(this: DocumentType<User>, position: number): number | undefined {
    return this.booked?.[position]; // using "optional chaining" to simplify code, could also just throw an error instead of returning "undefined" if wanted
  }
}
const UserModel = getModelForClass(User);
```

PS: you have to set an custom `this` type in every class function in typegoose, because the default cannot be changed for the whole class

**Comment by nhhockeyplayer** [comment]
Thanks friend

Im on typegoose 4/5 from previous repo

is that THIS constraint new?

**Comment by hasezoey** [comment]
> is that THIS constraint new?

no it is not, only this those versions there was no documentation for this

> I noticed when I create a pre hook for save it fails compilation

instead of `!value`, use `isNullOrUndefined(value)` (either the deprecated version included in nodejs, or the one provided by typegoose, or implement that function yourself (with types))

**Comment by nhhockeyplayer** [comment]
sorry but the nullcheck is vestigial

the assignment fails compilation as well

I have meta flags set in tsconfig

    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,

?

here seems to be another flag somewhere causing this

**Comment by nhhockeyplayer** [comment]
well any assist is appreciated here

I modeled it like this
```
    @prop({
        default: '0101010',
        validate(v: Buffer) {
            return v.length === 365 * 24 / 8
        }
    })
    bits?: Buffer
```

I am receiving this on boot

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:333:9)
    at new Buffer (buffer.js:289:17)
```

**Comment by nhhockeyplayer** [comment]
actually I just changed the type to 

string[]

ad its booting up 

will see

thanks for the push

**Comment by hasezoey** [comment]
@nhhockeyplayer if i understand it correctly, you will need to have the type be an `Buffer`, the error says that the default value provided cannot be used to create an buffer, maybe try `default: 'YourStringHere'` or `default: [0,1,0,1]` or `default: Buffer.from('SomethingHere')`

**Comment by nhhockeyplayer** [comment]
Thanks

Buffer wont fly with typegoose

I had to go with string[] which works for png files and media

so its running now with string[]

I gave enough code for you to produce your own test

I will keep working this

and yes I already tried those options you had suggested

if you get it to work advise please
thank
