### ISSUE TITLE
how to set timestamps in nested array?

### ISSUE THREAD

**Issue by tingshuai** [typegoose/typegoose#485]
## Versions

- System: windows 10 
- NodeJS: v12.16.2
- Typescript: v 4.1.3

- Compiler / Transpiler: tsc 
- Typegoose(GIT): commithash
- mongoose: 5.10.18 
- nestjs / nestjs-typegoose: 7.5.1 / 7.1.38 

# My question is how to set timestamps in nested arrays;
## Example code here

>I tried the code:
```ts
@ModelOptions({ schemaOptions: { timestamps: true } })
class childModel {
  @prop()
  param:String
}

class parentModel {
  @prop({ type: childModel})
  child:childModel[]
}
```
> when i saved this model: ' parentModel.create( [{ param: 'xxx' }] ) ' , then the result is:
```js
{
child:[
  {
    param:'xxx',
    "createdAt": "2021-02-06T03:36:02.806Z",
    "updatedAt": "2021-02-06T03:36:02.806Z"
  }
]
}
```
>but what i want is:
```js
{
child:[
  [
    {
    param:'xxx',
    "createdAt": "2021-02-06T03:36:02.806Z",
    "updatedAt": "2021-02-06T03:36:02.806Z"
    }
  ]
]
}
```
>then i tried the code :
```ts
@ModelOptions({ schemaOptions: { timestamps: true } })
class childModel {
  @prop()
  param:String
}

class parentModel {
  @prop({type:[[childModel]]})
  child:childModel[][]
}

```
>saved like this ' parentModel.create( [ [ { param: 'xxx' } ] ] ) ' and result is:
```js
{
child:[
  [
    {
      param:'xxx'
    }
  ]
]
}
```
>no timestamps here,why?
---

I have seen some other similar questions, but I still don't understand ; maybe my English is too poor to understand, if you know, please tell me straightly; thanks a lot;

**Comment by hasezoey** [comment]
> when i saved this model: ' parentModel.create( [{ param: 'xxx' }] ) ' , then the result is:
 
i dont see an reason on why this result should be wrong

> but what i want is:

why do you want an 2D Array where all entries are documents?

> no timestamps here,why?

could you provide [typegoose debug log](https://typegoose.github.io/typegoose/docs/guides/advanced/logger)?

**Comment by tingshuai** [comment]
>i dont see an reason on why this result should be wrong

 I mean the result is not what I want, not a error output.

> why do you want an 2D Array where all entries are documents?
#### This is my page and the JSON data structure I need
![1612617458(1)](https://user-images.githubusercontent.com/23158246/107119178-d31f8580-68c0-11eb-90f6-67e4620c843a.png)
#### So I need a two-dimensional array and time stamp information for each subdocument.

> could you provide [typegoose debug log](https://typegoose.github.io/typegoose/docs/guides/advanced/logger)?

The console doesn't have any output about typegoose. I just want to know how to include timestamp information in every document of this two-dimensional array;

**Comment by hasezoey** [comment]
> This is my page and the JSON data structure I need
sorry, but i dont really understand (even with the image) for what that data structure should be

> The console doesn't have any output about typegoose and I just want to know how to include timestamps information in every document of this two-dimensional array;
this is why i ask for debug output, because guessing from the options, it should have the correct output - but it seems to be broken / wrong, and to see what that is i need the debug log

**Comment by tingshuai** [comment]
> sorry, but i dont really understand (even with the image) for what that data structure should be

```
@ModelOptions({ schemaOptions: { timestamps: true } })
class childModel {
  @prop()
  param:String
}

class parentModel {
  @prop({type:[[childModel]]})
  child:childModel[][]
}

```
#### all of my questions and i want to konw is that What do I have to do to get this result？（mean: It is a two-dimensional array with time stamp when i created or updated this model .）
```
child:[
  [
    {
      param:'xxx',
      "createdAt": "XXXX XXXX XXXX",
      "updatedAt": "XXXX XXXX XXXX"
    }
  ]
]
```

**Comment by hasezoey** [comment]
> all of my questions and i want to konw is that What do I have to do to get this result？（mean: It is a two-dimensional array with time stamp when i created or updated this model .）

like i said, the class is not really wrong, i ask for the debug log because *this is exactly what should be happening*, but it is not - and i would like to know why

**Comment by tingshuai** [comment]
> like i said, the class is not really wrong, i ask for the debug log because _this is exactly what should be happening_, but it is not - and i would like to know why
### this is the log of 'TRACE':
![1612625289(1)](https://user-images.githubusercontent.com/23158246/107122639-d5d7a600-68d3-11eb-95a5-9f373562b83e.png)
### this is the 'Model' :
![1612625359(1)](https://user-images.githubusercontent.com/23158246/107122652-e8ea7600-68d3-11eb-910c-1b721f7aaf43.png)
### this is the input message in swagger:
![1612625458(1)](https://user-images.githubusercontent.com/23158246/107122713-526a8480-68d4-11eb-9194-4c921b4144a2.png)

### this is the output message  in swagger:
![1612625458(1)](https://user-images.githubusercontent.com/23158246/107122678-146d6080-68d4-11eb-8127-8fa151537265.png)

**Comment by hasezoey** [comment]
thanks, could confirm same with provided code

code used:
```ts
// NodeJS: 14.15.3
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, modelOptions, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.7
import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.3
import { inspect } from "util";

@modelOptions({ schemaOptions: { timestamps: true } })
class Child {
  @prop()
  public param?: string;
}

class Parent {
  @prop({ type: [[Child]] })
  public child?: Child[][];
}
const ParentModel = getModelForClass(Parent);
```

i could now confirm that typegoose is working correctly

from my investigation i could find that mongoose correctly add the 2 timestamp paths to the nested schema, but dosnt add any value to it on an actual save
-> this might be an mongoose problem

used mongoose code (equivalent to the typegoose generated):
```ts
const ParentModel = mongoose.model("ParentModel", new mongoose.Schema({
  child: [
    [
      {
        type: new mongoose.Schema({ param: String }, { timestamps: true })
      }
    ]
  ]
}));
```
the output is the same (paths added, but no values added)

**Comment by tingshuai** [comment]
> the output is the same (paths added, but no values added)

Ok, I got it.
