### ISSUE TITLE
Document.populate().execPopulate() return type is not correct / not complete

### ISSUE THREAD

**Issue by tar-aldev** [typegoose/typegoose#490]
## Versions

- System: macos 
- NodeJS: 14
- Typescript: 4.1.5

- Compiler / Transpiler:ts-node / ts-jest 
- Typegoose(NPM): 7.4.6 
- Typegoose(GIT): commithash
- mongoose: 5.10.18 
- mongodb: ^3.6.4
- nestjs / nestjs-typegoose: 0.0.0 / 0.0.0 
- grahpql / type-graphql: 0.0.0 / 0.0.0 

## What is the Problem?
When performing .populate().execPopulate() on `DocumentType<MyDocument>` return type is just `Document`

## Code Example

```ts
export class MyModel {
  @prop({ required: true })
  _id: Types.ObjectId;
  @prop({ required: true })
  name: string;
  @prop({
    ref: TestRef
  })
  testId: Ref<TestRef>;
}

// in my code
const result = await MyModel.findById('someId') // typeof result is DocumentType<MyModel>;

result.populate('testId').execPopulate() // typeof is just Document
```
therefor aI cannot access any properties anymore (e.g. doing `result.name` gives typescript error)
## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
known error, cannot really be fixed by typegoose (return type of `execPopulate/populate` is just wrong)

simple workaround: dont use the return of this call, because it modifies the input variable directly - use the input variable directly

```ts
const result = await MyModel.findById('someId') // typeof result is DocumentType<MyModel>;

result.populate('testId').execPopulate() // typeof is just Document
// use the input variable
result // typeof result is DocumentType<MyModel>;
```

or at least that is how its supposed to work, but didnt encounter any problem with it

**Comment by nguyentruong17** [comment]
I think the same happens with save() method, the return type is Promise<Document>.
`constructor(
    @InjectModel(Book) private readonly bookModel: ReturnModelType<typeof Book>,
  ) {}

  async addBook(book: Book): Promise<Book> {
    const addedBook = new this.bookModel(book); // typeof addedBook is DocumentType<Book>
    const result = await addedBook.save() // typeof result is Document, not Book as expected!
    //the product object in @param fn type is also Document
    return result //ts throws error TS2739
  }`

**Comment by hasezoey** [comment]
Update:
This is only affecting the unofficial types (so typegoose <8.0.0), but with `8.0.0-beta.2` typegoose supports mongoose `^5.11.19` - where the types of `populate().execPopulate()` and `.save()` have the correct return types

**Comment by nguyentruong17** [comment]
Thanks for clearing the confusion!

**Comment by hasezoey** [comment]
closing, because typegoose 8.0.0 (with mongoose 5.13+) got released and mongoose has proper types for `execPopulate`
