### ISSUE TITLE
Can we use same model for multiple collections? 

### ISSUE THREAD

**Issue by manveetb** [typegoose/typegoose#493]
I am trying to use the same model to be stored in mongoDB in two different collections, is there a way in typegoose to store it. I have a template and payment module which I am trying to store in mongo db in two different collections but using the same model `PaymentModel`. I tried to create two modules for two different collections like below by using the `forFeature` in nestjs-typegoose but it only attach the first module while loading and everything gets stored in the Payment collection. If i change the order of modules in the app-module.ts to have `TemplateModule` defined above the `PaymentModule`, then everything gets stored in Templates collection. Is there a way to store everything inside both the collections based upon the service call like from `TemplateService` or `PaymentService`.

-------------------------------------------------------------------------------
```ts
// app.module.ts
Module({
  imports: [
    ConfigModule,
    PaymentModule,
    TemplateModule,
    TypegooseModule.forRoot(config.get('mongodb.mongodburi'), {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

-------------------------------------------------------------------------------
```ts
// PayModule
@Module({
  imports: [
    TypegooseModule.forFeature([
      {
        typegooseClass: PaymentModel,
        schemaOptions: {
          timestamps: true,
          collection: 'Payment'
        },
        discriminators: [
          Wire, 
          ACH,
          IntraBank
        ],
      },
    ]),
  ],
  controllers: [PaymentController],
  providers: [PaymentService],
}) 
export class PaymentModule {}
```
-------------------------------------------------------------------------------
```ts
// Template Module
@Module({
  imports: [
    TypegooseModule.forFeature([
      {
        typegooseClass: PaymentModel,
        schemaOptions: {
          timestamps: true,
          collection: 'Templates'
        },
        discriminators: [
          Wire, 
          ACH,
          IntraBank
        ],
      },
    ]),
  ],
  controllers: [TemplatesController],
  providers: [TemplatesService],
}) 
export class TemplateModule {}
```
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
```ts
// TemplatesService

import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from 'nestjs-typegoose';
import {
  Payment    
} from '@sor/shared/model';
import { ReturnModelType } from '@typegoose/typegoose';
import { Logger } from '@nasp/core';

@Injectable()
export class TemplatesService {
  private readonly logger = new Logger(TemplatesService.name);

  constructor(    
    @InjectModel(PaymentModel)
    private readonly PaymentModel: ReturnModelType<typeof PaymentModel>    
  ) {}

  async insertTemplate(template: Payment) {    
    const newPayment = new this.PaymentModel(template);
    return await newPayment.save();
  } 
}

```
-------------------------------------------------------------------------------
```ts
// PaymentService

import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from 'nestjs-typegoose';
import {
  Payment    
} from '@sor/shared/model';
import { ReturnModelType } from '@typegoose/typegoose';
import { Logger } from '@nasp/core';

@Injectable()
export class PaymentService {
  private readonly logger = new Logger(PaymentService.name);

  constructor(    
    @InjectModel(PaymentModel)
    private readonly PaymentModel: ReturnModelType<typeof PaymentModel>    
  ) {}

  async insertTemplate(payment: Payment) {    
    const newPayment = new this.PaymentModel(payment);
    return await newPayment.save();
  } 
}
```
-------------------------------------------------------------------------------

**Comment by smolinari** [comment]
@manveetb - Can you put your different code blocks in two sets of three backticks please?

https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Scott

**Comment by manveetb** [comment]
> @manveetb - Can you put your different code blocks in two sets of three backticks please?
> 
> https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
> 
> Scott

done

**Comment by smolinari** [comment]
What's the purpose of the discriminator?

Scott

**Comment by manveetb** [comment]
> What's the purpose of the discriminator?
> 
> Scott
Hi @smolinari ,
There are three discriminators I have got, for different payment types WIRE, ACH and Internal Transfer. For simplicity purpose i just added the payment type in above example but now corrected it actual requirement.

**Comment by smolinari** [comment]
Have you tried using Typegoose's option property with `customName` for each model creation? Use that for the injection instead of the class name?

https://typegoose.github.io/typegoose/docs/api/decorators/model-options/#options-1

Scott

**Comment by manveetb** [comment]
> Have you tried using Typegoose's option property with `customName` for each model creation? Use that for the injection instead of the class name?
> 
> https://typegoose.github.io/typegoose/docs/api/decorators/model-options/#options-1
> 
> Scott
Hi @smolinari ,

I tried that and it is giving me **Invalid model object** on the module when I added below code
```
// Template Module
@Module({
  imports: [
    TypegooseModule.forFeature([
      {
        typegooseClass: getModelForClass(PaymentModel), // on this line it gives error
        schemaOptions: {
          timestamps: true,
          collection: 'Templates'
        },
        discriminators: [
          Wire, 
          ACH,
          IntraBank
        ],
      },
    ]),
  ],
  controllers: [TemplatesController],
  providers: [TemplatesService],
}) 
export class TemplateModule {}
```
```
@pluginUpdate(updateIfCurrentPlugin)
@modelOptions({ options: { customName: 'TemplatesModel', automaticName: false  } })
export class PaymentModel {
  constructor(type: PaymentType) {
    this.__t = type;
  }

  get id() {
    return `${(this as any)._id}`;
  }

  get version() {
    return `${(this as any).__v}`;
  }

 @prop()
  @IsNotEmpty()
  createdBy: string;

  @prop()
  @IsNotEmpty()
  updatedBy: string;

  @prop()
  @IsNotEmpty()
  @ValidateTrackChanges()
  trackChanges: boolean;
}
```


Error: Invalid model object
    at invalidObject (/home/iid/ProjectPay/node_modules/nestjs-typegoose/dist/typegoose.providers.js:51:11)
    at Object.convertToTypegooseClassWithOptions (/home/iid/ProjectPay/node_modules/nestjs-typegoose/dist/typegoose.providers.js:37:12)
    at /home/iid/ProjectPay/node_modules/nestjs-typegoose/dist/typegoose.module.js:28:75
    at Array.map (<anonymous>)
    at Function.forFeature (/home/iid/ProjectPay/node_modules/nestjs-typegoose/dist/typegoose.module.js:28:40)

**Comment by smolinari** [comment]
Hmm.. nevermind. It looks like Nestjs-typegoose doesn't pass the `options` prop to Typegoose. So, that idea won't work. 

You might want to ask about that in their repo. 

Scott

**Comment by hasezoey** [comment]
from what i can tell, your are already calling `getModelForClass`, this will return the compiled model, and then the extra `schemaOptions` that are besides there cannot be applied, try to either remove that call, or change that the `schemaOptions` are the second parameter for `getModelForClass`

**Comment by smolinari** [comment]
Good point @hasezoey. With nestjs-typegoose, you don't need to call `getModelForClass` at all. The Typegoose module does that automatically (or calls `getDiscriminatorModelForClass`) for you, when you inject the model into a service (and why I personally like using it). The nestjs-typegoose module basically abstracts away the model instantiation process into Nest's DI instantiation process. 

Scott
