### ISSUE TITLE
Unknown type: ConditionalType

### ISSUE THREAD

**Issue by Mahan-F** [typegoose/typegoose#494]
## Versions

- System: windows 
- NodeJS: 14.15.5
- Typescript: 4.1.3

- Compiler / Transpiler: tsc 
- Typegoose(NPM): 7.4.8 
- mongoose: 5.10.18 
- mongodb: 4.2.0

## What is the Problem?
I have two models defined as per the examples and documentation and I need one model to reference the other but I get the below error message:

```
There was a problem resolving type of 'Ref<Hospitals>'.
There was a problem resolving type of 'Notifications'.
Generate routes error.
 Error: Unknown type: ConditionalType
At: ...\node_modules\@typegoose\typegoose\lib\types.d.ts:284:284.
This was caused by '(R extends {
    _id?: RefType;
} ? NonNullable<R['_id']> : mongoose.Types.ObjectId)'
```

## Code Example

```ts
export class Hospitals  {

  @prop({ type: String, required: true, unique: true })
  public name!: string
  
}

export class Notifications  {
  
  @prop({ ref: () => Hospitals })
  public hospitals?: Ref<Hospitals>[]

}
```

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
never encountered this error and it dosnt seem to be from tsc / ts-node, could you tell more about your environment?

**Comment by Mahan-F** [comment]
I'm using ts-node with nodemon to run the code in dev environment. Below is my nodemon config: 

```
{
  "verbose": true,
  "watch": [ "src" ],
  "ext": ".ts,.js",
  "exec": "ts-node ./app.ts"
}
```

And for the project, I'm using [tsoa](https://tsoa-community.github.io) to create APIs which use these models. 
Is there any other information I can provide?

**Comment by Mahan-F** [comment]
After looking into the issue more, the error is from tsoa but I'm not sure what is causing it still. I found this issue from the tsoa github: https://github.com/lukeautry/tsoa/issues/618

The issue is not exactly related to this one but the author is doing a Ref by doing this
```ts
@arrayProp({
    default: [],
    itemsRef: DatasourceVersion
  })
  public versions!: Ref<DocumentType<DatasourceVersion>>[]
```
arrayProp is now deprecated so I tried to use the below:
```ts
export class Notifications  {
  
  @prop({ ref: () => Hospitals })
  public hospitals?: Ref<DocumentType<Hospitals>>[]

}
```
But I still got the same error. But after I did the below, the error is gone
```ts
export class Notifications  {
  
  @prop({ ref: () => Hospitals })
  public hospitals?: string[]

}
```
This is not a solution but helps to see where the error is coming from. Is this something that can be resolved through Typegoose or do I need to make an issue with Tsoa?

**Comment by hasezoey** [comment]
@Mahan-F from what i can tell `tsoa` cannot deal with conditional types, and your example (`public hospitals?: Ref<DocumentType<Hospitals>>[]`) is an "very" old version of typegoose, since then the `Ref` type became more conditional / complex (it has nothing to do with the decorator)

**Comment by Mahan-F** [comment]
@hasezoey Thanks for the response. `public hospitals?: Ref<DocumentType<Hospitals>>[]` is not my solution, just what I found on tsoa github. What I am doing is `public hospitals?: Ref<Hospitals>[]`. 

When you say `cannot deal with conditional types` do you mean that the field cannot be optional? I don't think I understand exactly what you mean.
If I do `public favoritePatients!: Ref<Hospitals>` I am still getting the same error. I also tried the rules for `required` and `default` but still no luck.

**Comment by hasezoey** [comment]
> `public hospitals?: Ref<DocumentType<Hospitals>>[]` is not my solution, just what I found on tsoa github. What I am doing is `public hospitals?: Ref<Hospitals>[]`.

i know, i just said that what you found was for an very old typegoose version, where the types were not so complex

> When you say cannot deal with conditional types do you mean that the field cannot be optional? I don't think I understand exactly what you mean.

no, i meant that the type `Ref` is too complex for `tsoa`

> I also tried the rules for required and default but still no luck.

changing prop option dosnt change the typescript type

**Comment by Mahan-F** [comment]
> no, i meant that the type Ref is too complex for tsoa

Thanks I got it now. So is there a good way to get around this? What I need is for the hospitals to be an array of `_id` from the hospitals entries. Can I just have `string[]` as the type for the property? 

And from what I understand from Typegoose, the typescript type wont affect stuff like `populate` since the `ref` is set in the `@prop` decorator. Is this right?

**Comment by hasezoey** [comment]
> And from what I understand from Typegoose, the typescript type wont affect stuff like populate since the ref is set in the @prop decorator. Is this right?

yes

**Comment by Mahan-F** [comment]
Thanks @hasezoey the reference works now but now I have another issue.
```ts
@prop({ ref: () => Hospitals })
public hospitals?: string[]
```
Even tho it is defined as a string array when I actually set the value it is changed to string. I tested it and populate works as expected but it just has 1 value instead of an array. I then tried the below
```ts
@arrayProp({ ref: () => Hospitals })
public hospitals?: string[]
```
and this works exactly as it should. Since arrayProp is deprecated, how can I get this result by using prop? The documentation indicates that by just specifying `string[]` it should work but it doesn't.

**Comment by hasezoey** [comment]
> Since arrayProp is deprecated, how can I get this result by using prop?

if you would look in the code, `arrayProp` is literally just `return prop(options, WhatIsIt.ARRAY);`

but that it is an Array should normally be detected, do you have `emitDecoratorMetadata` enabled?

**Comment by Mahan-F** [comment]
> but that it is an Array should normally be detected, do you have emitDecoratorMetadata enabled?

That was it.. I had `experimentalDecorators` enabled but not `emitDecoratorMetadata`. Thanks a lot for the help!
