### ISSUE TITLE
getModelForClass does not use the provided existingConnection

### ISSUE THREAD

**Issue by schdck** [typegoose/typegoose#495]
Not sure if this is a bug or I'm doing something wrong, but here it goes:

## Versions

- System: linux
- NodeJS: 12.19.0
- Typescript: 4.2.2
- Compiler / Transpiler: tsc
- Typegoose(NPM): 7.4.8
- mongoose: 5.10.18

## What is the Problem?

I'm creating a multi-tenant application and trying to use the same connection, but to different databases, to create the schemas. However, Typegoose does not seem to use the `existingConnection` I pass to `getModelForClass`.

## Code Example

```ts
import mongoose from 'mongoose';
import { prop } from '@typegoose/typegoose';
import { getModelForClass } from '@typegoose/typegoose';

class User {
    @prop()
    public username?: string;
}

(async () => {
    const mongoUri = '[mongodb connection string here]';

    const connection = await mongoose.createConnection(mongoUri, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        useCreateIndex: true,
    });

    const connectionToDatabaseA = connection.useDb('database-a');
    const modelOnDatabaseA = getModelForClass(User, {
        existingConnection: connectionToDatabaseA,
    });

    const connectionToDatabaseB = connection.useDb('database-b');
    const modelOnDatabaseB = getModelForClass(User, {
        existingConnection: connectionToDatabaseB,
    });

    console.log(`Database of connection A: ${connectionToDatabaseA.name}`);
    console.log(`Database of model A: ${modelOnDatabaseA.db.name}`);

    console.log(`Database of connection B: ${connectionToDatabaseB.name}`);
    console.log(`Database of model B: ${modelOnDatabaseB.db.name}`);
})();
```

### Expected output

```
Database of connection A: database-a
Database of model A: database-a
Database of connection B: database-b
Database of model B: database-b <----- see here
```

### Received output

```
Database of connection A: database-a
Database of model A: database-a
Database of connection B: database-b
Database of model B: database-a <----- and here
```

## Do you know *why* it happens?

No.

**Comment by schdck** [comment]
I've checked Typegoose's code and it _seems_ to be OK, since it is trying to use the provided connection before anything else:

```
const model =
    roptions?.existingConnection?.model.bind(roptions.existingConnection) ??
    roptions?.existingMongoose?.model.bind(roptions.existingMongoose) ??
    mongoose.model.bind(mongoose);
```

While checking  `existingConnection`'s content, I've found that `base.connections` is an array of length 2. Maybe somewhere on the codebase (maybe mongoose's?) the first connection is used?

**Comment by schdck** [comment]
I think I might have found the issue. At the beginning of Typegoose's `getModelForClass`, there's this code:

``` ts
const name = getName(cl);

if (models.has(name)) {
    return models.get(name) as ReturnModelType<U, QueryHelpers>;
}
```

The code checks if a model has already been generated for this class and, if so, returns it from cache. 

However, the cache key uses only the class name (in the example `User`). So, for both cases, the code is returning the same model, even though it shouldn't.

I'm able to help fixing this once someone with more experience confirms that this is actually the issue.

**Comment by hasezoey** [comment]
> The code checks if a model has already been generated for this class and, if so, returns it from cache.

this is also to prevent mongoose from erroring, in mongoose all model names are unique

**Comment by schdck** [comment]
How can I do that when calling `getModelForClass`? It doesn't seem to use the name I pass via `options.customName`, only the `customName` provided directly on the class via decorators (which I can't do, because I need to use the connection name). 

See the call [here](https://github.com/typegoose/typegoose/blob/master/src/typegoose.ts#L78).

Is this a bug?

**Comment by hasezoey** [comment]
true, currently the name cannot be changed in an `getModelForClass` call, recommended is to use an "dummy" class with an `@modelOptions` call for each different name

**Comment by schdck** [comment]
In my case, I can't do that since I don't know how many different databases I'm gonna access. I can make a pull request to fix this. 

What do you think it's best for Typegoose: implement support for changing the name at `getModelForClass`, using connection info to generate the model name (and avoiding this cache mistake) or both?
