### ISSUE TITLE
Expression produces a union type that is too complex to represent.

### ISSUE THREAD

**Issue by harveyconnor** [typegoose/typegoose#499]
Hi I'm getting the error: `Expression produces a union type that is too complex to represent.`. I get the error when I call the `.create()` method on a model.
These are my versions:
- Typescript: 4.2.2
- @typegoose/typegoose: 7.5.0
- @types/mongoose: 5.10.3
- mongoose: 5.10.18

This is stopping me from getting any type definitions for my models so everything is as if I'm coding in plain js..

**Comment by hasezoey** [comment]
could you give an code example?

**Comment by ezracelli** [comment]
@hasezoey I'm also running into this error on `TModel.create()` call (playground link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQEYCsCmBjGBJAEzgF84AzKCEOAIlQGcIA7GgbgChRJZE4BzTDACyEApgA2AMWgBhcQEN69ADRwwlMHEVwAChsywAniXKVqNAAIxDYTHwgR6mAPTXb9x5jbt2mAB7c8NgKSnAAqk5QiOxwsXBQmPIEzOLGAPrABAD8AFwoGDj4BBwxcRZ6ELZGABRICQCOAK7ACQR5MFCNmKpumHnVAJRwALwAfHAAIvIwmCQDpbHYCdOYBACCMACEeVMzJXFw5fo1SL39Q2OTK3MLcGLigqsb21czcAA+cEyN4uL7ZRUqtZavFME0Wqt2p1ZsR5gdMCB5MBxC96B1gEw+P9YkdKgZgXUwc1WlCuj0bH04IMRuNdjC4XFGmACCt1lsditsYdAfjDCCGsTIXAOl0bgdGpEmPIQJhUejMVzcUC+YTwSThdCxXEwIp6AB3aAEOVQDFY9jEHz+QJwbDMNHhSIie4jfiCJ0SaRQOS66oRAwDEp+qDu8QAOiWiRmtVuEdZGzyTEwetemEGylu90ebITP3E6fhiOReRoNHzjOZcZgCaTKbTtwlBilMuLpduOqUBqgbVordhQA)):

```ts
import { ObjectId } from "bson";
import { getModelForClass, prop as Property } from "@typegoose/typegoose";

export class User {
    readonly _id?: ObjectId;

    @Property({ required: true, type: () => Date })
    createdAt!: Date;

    @Property({ type: () => Date })
    deletedAt!: Date | null;

    @Property({ required: true })
    email!: string;

    @Property({ required: true, type: () => Date })
    updatedAt!: Date;

    @Property({ required: true })
    username!: string;

    @Property({ required: true })
    password!: string;
}

export const UserModel = getModelForClass(User);

UserModel.create({
    createdAt: new Date(),
    deletedAt: null,
    email: "",
    updatedAt: new Date(),
    username: "",
    password: "",
})
```

Output:

```
error TS2590: Expression produces a union type that is too complex to represent.
```

**Comment by hasezoey** [comment]
@ezracelli does the error still appear when using the right ObjectId type that is `mongoose.Types.ObjectId`?

and what versions are you using:
- typescript
- typegoose
- mongoose
- @types/mongoose (if used)

**Comment by ezracelli** [comment]
@hasezoey Yep, unfortunately the error persists when using `mongoose.Types.ObjectId`. Here's my (truncated) `package.json`:

```json
{
  "dependencies": {
    "@typegoose/typegoose": "^7.6.0",
    "bson": "^4.3.0",
    "mongoose": "5.10.18"
  },
  "devDependencies": {
    "@types/mongoose": "^5",
    "typescript": "^4.2.4"
  }
}

```

Should I be pinning `@types/mongoose` to a specific version as well?

**Comment by hasezoey** [comment]
sorry for the late reply, but i cannot reproduce this problem

<details>
<summary>Code Used</summary>

```ts
// NodeJS: 16.1.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@7.6.0
import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.5

export class User {
  public readonly _id?: mongoose.Types.ObjectId;

  @prop({ required: true, type: () => Date })
  public createdAt!: Date;

  @prop({ type: () => Date })
  public deletedAt!: Date | null;

  @prop({ required: true })
  public email!: string;

  @prop({ required: true, type: () => Date })
  public updatedAt!: Date;

  @prop({ required: true })
  public username!: string;

  @prop({ required: true })
  public password!: string;
}

export const UserModel = getModelForClass(User);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const doc = await UserModel.create({
    createdAt: new Date(),
    deletedAt: null,
    email: "y",
    updatedAt: new Date(),
    username: "y",
    password: "y",
  });

  console.log(doc);

  await mongoose.disconnect();
})();
```

</details>

Reproduction repo: https://github.com/typegoose/typegoose-testing/tree/verify499

**Comment by hasezoey** [comment]
@harveyconnor @ezracelli does this issue still persist in typegoose 8.3 or typegoose 9.0 beta?

**Comment by harveyconnor** [comment]
@hasezoey Hi we haven't migrated yet, just been using it without typings

**Comment by hasezoey** [comment]
Closing this issue because it is stale (for quite a long time), i had kept this open until now because of https://github.com/actions/stale/issues/766 to have a issue to test with
