### ISSUE TITLE
10 second cold start time on serverless

### ISSUE THREAD

**Issue by JohnDeved** [typegoose/typegoose#501]
## Versions

- System: vercel serverless
- Compiler / Transpiler: tsc 
- Typegoose(NPM): 7.4.8 
- mongoose: 5.10.3 

## What is the Problem?

cold start takes typegoose by default around 10 seconds
further details (code & logs) can be found here:
https://github.com/vercel/vercel/discussions/5930

## Do you know *why* it happens?
the internal heartbeat breaks in older versions of mongoose when used in serverless
https://github.com/Automattic/mongoose/issues/9179

**Comment by hasezoey** [comment]
from what i can tell, it is fixed with mongoose version `5.10.13`, typegoose's supported range is `5.10.0 - 5.10.18`

and `mongodb` (the nodejs driver) is not an dependency of typegoose

**Comment by JohnDeved** [comment]
not sure how I overlooked that. I somehow thought I already was on the newest supported version of mongoose.
will try and update and see if it fixes it, thanks 👍

**Comment by JohnDeved** [comment]
Updating mongoose seems to have fixed it
