### ISSUE TITLE
Array types for documents in model and their methods.

### ISSUE THREAD

**Issue by AlexZeDim** [typegoose/typegoose#509]
## Versions

- System: windows
- NodeJS: 15.0.0
- Typescript: 4.1.5
- Compiler / Transpiler: tsc / ts-node  
- Typegoose(NPM): 7.4.5 
- Typegoose(GIT): commithash
- mongoose: 5.10.18
- mongodb: 4.4.4

## What is the Problem?

I am not sure, that this is a bug. But I guess this question requires a clarification at least.

There are various `array` methods in mongoose. [There are many of them](https://mongoosejs.com/docs/api/array.html) and typegoose doesn't modify them. But, when I create an array field (doesn't matter primitives or with embedded docs), [according to typegoose examples](https://typegoose.github.io/typegoose/docs/guides/quick-start-guide). I receive the following warning from TS: `TS2339: Property 'addToSet' does not exist on type 'string[]'`

*In this case, I am trying to use an `.addToSet` method on `string[]` field.*
![addToSet](https://user-images.githubusercontent.com/907696/110750579-c1305a00-8253-11eb-9d89-c08aafc73a1d.png)

**BUT!**

If I determine the field as a `mongoose.Types.Array<string[]>` it gives no warning at all.

## Code Example

*gives no warning on mongoose array methods*
```ts
class Item {
  @prop({ required: true, type: () => [String], default: [] })
  public asset_class!: mongoose.Types.Array<string>;
}
```

*gives warning*

```ts
class Item {
  @prop({ required: true, type: () => [String], default: [] })
  public asset_class!: string[];
}
```

## Do you know *why* it happens?

Well, I guess it's easy to understand the reason for such behavior. Mongoose arrays fields aren't plain JS arrays themselves. So, when I am declaring the array field with typegoose, the TS thought, that it's a simple js array.

My question is about: How to fix it? Should I define somewhere in my code, when I am requesting a mongoose document via `find` or `new Document()` some kind of special type?

**And yes, I am absolutely sure that I am not requesting a `lean()` document.**

Example code:

```ts
//inside any async function
let item = await ItemModel.findById(_id);
if (!item) return
item.asset_class.addToSet('AnyValue');
```

---

**Comment by hasezoey** [comment]
the type `type[]` or `Array<type>` is just easier to write in most cases, that is why its used in the documentation - other types are also allowed, like `mongoose.Types.Array<type>` or `mongoose.Schema.Types.Array<type>`
-> if you would probe the array at runtime, these methods already exist (because an array is always an mongoose array), it is just more convenient to write the shorter type instead of the longer if the functions are not used

PS: its `mongoose.Types.Array<string>` and not `mongoose.Types.Array<string[]>`

**Comment by AlexZeDim** [comment]
@hasezoey Thanks a lot for such a quick answer. So, I guess I'll close the issue them, But before doing that, I'd to ask, can I make a PR for updating the defaults docs with this snippet example, just a bit? 

And if the answer is `yes` do you have any recommendation for me, how you'd like to see those changes?

**Comment by hasezoey** [comment]
> I'd to ask, can I make a PR for updating the defaults docs with this snippet example, just a bit?

yes, as long as [CONTRIBUTING](https://github.com/typegoose/typegoose/blob/master/.github/CONTRIBUTING.md) is followed
