### ISSUE TITLE
[Request] make model configuration classes throw when new()ing by default

### ISSUE THREAD

**Issue by captaincaius** [typegoose/typegoose#51]
## Describe what you need | want

Model configuration classes (a term i just made up) are easy to be used accidentally instead of the model itself.

I know r6 seemed to make efforts to avoid decorators on the classes themselves, but I think it would be useful to have them.

I know it's not a HUGE deal, but it's pretty easy to implement.

## Do you have already an idea for the implementation?

yes... for example:

```typescript

@typegoosemodelconfig()
class CarConfig {
  @prop()
  passengers: number;
  @prop()
  name: string;
}
```
typegoosemodelconfig can decorate the constructor so it throws (the behavior can be disabled w/ options).  Also, the prop processors can throw if some metadata that typegoosemodelconfig sets isn't set.

Actually... technically, prop's decorator can do it too and avoid the decorator, since you have access to target - but I'm not sure I'd prefer that approach.

**Comment by hasezoey** [comment]
i think i will not add such thing, because some users use typegoose with libraries like `type-graphql` and / or `nestjs`, and i dont want to block the constructor for it

**Comment by captaincaius** [comment]
Okay.  I also thought that sharing the classes elsewhere might be a reason against it, but I thought the return value of getModelByClass might be usable in those cases too.  You know better than I do so I'll close it :).

Thanks!
