### ISSUE TITLE
Why does Ref work with a string and not with an arrow function for two-way referencing.

### ISSUE THREAD

**Issue by ChristopherMedaille** [typegoose/typegoose#518]
Hello,
I'm working on a project using Typegoose and I faced an "issue" : 

When creating my schemas , if I use Ref with string (Ref: 'SchemaName' ) for 2 schemas referencing each-other , everything is fine. But if I'm calling the "recommended" method (regarding documentation, Ref () => SchemaName) , seems like I'm having circular dependencies.

Example : 

**Working**

```ts
export class Container extends Resource {

    constructor() {
        super();
        this.services = [];
    }

    @prop({ ref: 'Service' })
    public services: Ref<Service>[];

}

export class Service extends Resource {

    public static entries: Map<string, Service> = new Map<string, Service>();

    constructor() {
        super();
        this.container = null;
    }

    @prop({ ref: 'Container' })
    public container: Ref<Container>;

}
```

**Not working**

```ts
export class Container extends Resource {

    constructor() {
        super();
        this.services = [];
    }

    @prop({ ref: () => Service })
    public services: Ref<Service>[];

}

export class Service extends Resource {

    public static entries: Map<string, Service> = new Map<string, Service>();

    constructor() {
        super();
        this.container = null;
    }

    @prop({ ref: ()=> Container })
    public container: Ref<Container>;

}
```

_Resource is an abstract schema container_

I was wondering if it was an intended behavior or a real problem.

## Versions

- System: linux / windows 
- NodeJS: 14.15.0
- Typescript: 4.1.5

- Compiler / Transpiler: tsc / ts-node 
- Typegoose(NPM): 7.4.8 
- mongoose: 5.10.18 
- mongodb: 3.6.5

---

**Comment by smolinari** [comment]
The last sentence[ in the docs](https://typegoose.github.io/typegoose/docs/guides/advanced/reference-other-classes#common-problems) on this says it all I think.

> When you get errors about references, try making the name of the referenced class a string.

Scott

**Comment by hasezoey** [comment]
sorry, but `() => Class` is to help with Circular Dependencies, but cannot eliminate them, so the only ways are:
- use the string version `() = 'ClassName'` or `'ClassName'`
- use an central file where the models are generated (the `buildSchema` or `getModelForClass` calls in an central file) (that works because when imports are the first thing in the file, all of the references (`() => This`) get resolved)
