### ISSUE TITLE
[Request] Prevent implicit "Mixed" by default

### ISSUE THREAD

**Issue by captaincaius** [typegoose/typegoose#52]
## Describe what you need | want

We have a code path that adds "Mixed" fields.  These can be a bit dangerous IMO because you might think you have a field that's guaranteed to be of a certain type, but literally anything can be jammed into it.

I can see how some applications might be okay with Mixed, but I think it should always be explicit (there was an issue on mongoose's issue queue where vkarpov was discussing this too).

Mongoose itself was talking about deprecating implicit mixed too.  I think typegoose should step with the best foot forward on r6 and throw in the "Mixed" branch by default (unless some "implicitMixedOkay" option is set).  Or just disallow implicit mixed altogether.

## Do you have already an idea for the implementation?

Yes - mentioned above.

**Comment by hasezoey** [comment]
i think yes there should be an warning for it, i could add one (via the logger), but no "heavy" error or so, at least not for 6.0.0

**Comment by captaincaius** [comment]
Cool.

I believe it's here: https://github.com/typegoose/typegoose/blob/master/src/prop.ts#L244

**Comment by hasezoey** [comment]
shouldnt this translate to "Object" instead of "Mixed"?

**Comment by hasezoey** [comment]
in the next version of typegoose (6.1.0) you can now use the global options to set it to `ERROR` or `WARN`(default) or `ALLOW`
