### ISSUE TITLE
TypeScript Array SubDocument

### ISSUE THREAD

**Issue by schwamic** [typegoose/typegoose#522]
Hi,
I have problems to get Array-SubDocuments working.

## What to include in your Questions

My Code:
```ts
import { prop, getModelForClass, Ref } from '@typegoose/typegoose'
import { Base } from '@typegoose/typegoose/lib/defaultClasses'

export class Pool extends Base {
  @prop({ required: true })
  public name!: string
}

export class Bath extends Base {
  @prop({ required: true, unique: true })
  public id!: string
  
  @prop({ ref: () => Pool, required: true, default: [] })
  public pools!: Pool[]
}
```

Problem: The type seems to be some kind of array instead of array-subdocument. I would expect functions like [mongoose.subdocumens-api](https://mongoosejs.com/docs/subdocs.html) and [mongoose-array-api](https://mongoosejs.com/docs/api/array.html)

```ts
bath.pools.id('myid') // -> Error: Property 'id' does not exist on type 'Pool[]'
bath.pools.set('myid', {}) // -> Error: Property 'set' does not exist on type 'Pool[]'.
```

I also tried the following, which still not allows to use the subdocuments-api.

```ts
mongoose.Types.Array<Pool>
```

## Versions

"mongoose": "5.10.18"
"@typegoose/typegoose": "7.4.8"

**Comment by hasezoey** [comment]
(not related to the question):
if you want an reference, you need to change the type to `Ref<Class>`, but if you want an subdocument, you need to remove the option `ref` (or change it to `type`)

---

it is generally [recommended for ease-of-use](https://typegoose.github.io/typegoose/docs/api/decorators/prop#array-options) to use the short array (`Type[]`), but if mongoose functions are needed, you would need to use `mongoose.Types.Array<Class>`

i dont see any special type for subdocument-arrays, so `mongoose.Types.Array<Class>` should have them

PS: if you want special sub-document functions, you would probably also need to do `Class & mongoose.Types.Embedded` (final: `mongoose.Types.Array<Class & mongoose.Types.Embedded>`)

**Comment by schwamic** [comment]
Hi @hasezoey thank you for your response! Sorry, there is a typo... I only use `Bath` as a collection, `Pool` is a subdocument of `Bath`.

I implemented your solution and updated `Types.Array` to `Types.DocumentsArray`, now I can use the mongoose.subdocuments-api and mongoose-array-api; e.g. (`bath.pools.id()`, `bath.pools.set()`, ...)

```ts
export class Pool extends Base {
  @prop({ required: true })
  public name!: string
}

export class Bath extends Base {
  @prop({ required: true, unique: true })
  public id!: string
  
  @prop({ type: () => Pool, required: true, default: [] })
  public pools!: mongoose.Types.DocumentArray<Pool & mongoose.Types.Embedded>
 }

export const BathModel = getModelForClass(Bath)
```

**Comment by hasezoey** [comment]
sorry, forgot `mongoose.Types.DocumentArray` existed, for this type you need to use `mongoose.Types.DocumentArray<DocumentType<Class>>`

**Comment by schwamic** [comment]
Thank you for your help! This works for me:

```ts
import { prop, getModelForClass, DocumentType, mongoose } from '@typegoose/typegoose'
import { Base } from '@typegoose/typegoose/lib/defaultClasses'

export class Pool extends Base {
  @prop({ required: true })
  public name!: string
}

export class Bath extends Base {
  @prop({ required: true, unique: true })
  public id!: string
  
  @prop({ required: true, default: [] })
  public pools!: mongoose.Types.DocumentArray<DocumentType<Pool>>
 }

export const BathModel = getModelForClass(Bath)
```

```ts
const pool = bath.pools.id('123') -> DocumentType<Pool>
```

**Comment by hasezoey** [comment]
> Would be happy to help you updating the docs, if you like :-)

if you want, PR's are always welcome (though i already added it to prop#array-options in b35b540ac22f7cc602e58db257addb299313f95d) - but it may be better if there is an dedicated example for this (i never really used these types before, so i dont know capabilities and production use-cases)
