### ISSUE TITLE
Cannot edit/update document using findOneAndUpdate and findByIdAndUpdate

### ISSUE THREAD

**Issue by ashalfarhan** [typegoose/typegoose#524]
## Versions

- System: macos  
- NodeJS: 14
- Typescript: 4.2.0

- Typegoose(NPM): ^7.6.0 
- mongoose: 5.10.18 
- grahpql / type-graphql: ^15.5.0 / 1.1.1 

## What is the Problem?

Cannot use `findOneAndUpdate` and `findByIdAndUpdate` i dont'know why but i've set my account as admin in MongoDB Atlas

## Code Example

`Resolvers`
```ts
@Mutation(() => Report)
  async editReport(@Arg("id") id: string, @Arg("data") data: EditInput) {
    const after = await ReportModel.findOneAndUpdate(
      { _id: id },
      { ...data },
      {
        new: true,
      }
    );
    await after.save();
    console.log("after saved: ", after);
    const foundSaved = await ReportModel.findById(id);
    console.log("foundSaved saved: ", foundSaved);
    return after;
  }
```
`index.ts`
```ts
await connect(process.env.MONGO_URI!, {
    useUnifiedTopology: true,
    useNewUrlParser: true,
    useCreateIndex: true,
  })
```

`in terminal`
```bash
after saved:  {
  createdAt: 2021-04-17T08:44:30.231Z,
  updatedAt: 2021-04-17T08:44:30.231Z,
  _id: 607aa056be25dde8af8cbb10,
  name: 'Add new book22',
  reporterId: '607a6caacd1a6acf081251a9',
  detail: {
    _id: 607aa056be25dde8af8cbb11,
    stuff: 'Education Book',
    price: 250
  },
  __v: 0
}
foundSaved saved:  {
  createdAt: 2021-04-17T08:44:30.231Z,
  updatedAt: 2021-04-17T08:44:30.231Z,
  _id: 607aa056be25dde8af8cbb10,
  name: 'Add new book22',
  reporterId: '607a6caacd1a6acf081251a9',
  detail: {
    _id: 607aa056be25dde8af8cbb11,
    stuff: 'Education Book',
    price: 250
  },
  __v: 0
}
```
`Report` type
```ts
@ObjectType({ simpleResolvers: true })
class ReportData {
  @Field(() => String)
  @prop()
  public stuff: string;

  @Field(() => Int)
  @prop()
  public price: number;
}

@ObjectType()
export class Report {
  @Field(() => ID)
  readonly _id: ObjectId;

  @Field(() => Date)
  @prop({ type: () => Date, default: new Date() })
  public createdAt?: Date;

  @Field(() => Date)
  @prop({ type: () => Date, default: new Date() })
  public updatedAt?: Date;

  @Field(() => ReportData, { simple: true })
  @prop({ type: () => ReportData })
  public detail: ReportData;

  @Field()
  @prop()
  public name: string;

  @Field(() => ID, { nullable: true })
  @prop({ type: () => String })
  public reporterId?: string;

  @Field(() => User, { nullable: true })
  @prop({ ref: () => User, type: () => User })
  public reporter?: Ref<User> | null;
}

export const ReportModel = getModelForClass(Report);
```
## Do you know *why* it happens?

*no*

---

**Comment by smolinari** [comment]
What error are you getting?

Scott

**Comment by ashalfarhan** [comment]
There's no error occurs, but when i checked my document after update it with one of `findOneAndUpdate` or `findByIdAndUpdate` is not actually update them

**Comment by hasezoey** [comment]
so when i understand right, your are asking why the return (of the mentioned functions) is not the updated document, right?

this is an known feature of mongoose (actually mongodb), you need to call these functions with the option `{ new: true }`

**Comment by ashalfarhan** [comment]
I've tried using that option, but it doesn't edit even return the edited document

**Comment by hasezoey** [comment]
from the example console logs, i cannot see an difference (because the output from the mentioned functions were not provided (before save)?)

could you provide what the data is before the update and directly after the update (what got returned by the mentioned functions (before the save))

PS: sorry didnt see that the option was already in the example code provided

---

btw, did you already try and different mongoose version? (like an lower or higher version (for higher, you need to use the typegoose beta))

**Comment by ashalfarhan** [comment]
```ts
@Mutation(() => Report)
  async editReport(@Arg("id") id: string, @Arg("data") data: EditInput) {
    const before = await ReportModel.findById(id);
    console.log("before saved: ", before);
    const after = await ReportModel.findOneAndUpdate(
      { _id: id },
      { ...data },
       // Here i pass the option
      {
        new: true,
      }
    );
    await after.save();
    console.log("after saved: ", after);
    return after;
  }
```
`logs`

```bash
before saved:  {
  createdAt: 2021-04-17T08:44:30.231Z,
  updatedAt: 2021-04-17T08:44:30.231Z,
  _id: 607aa056be25dde8af8cbb10,
  name: 'Add new book22',
  reporterId: '607a6caacd1a6acf081251a9',
  detail: {
    _id: 607aa056be25dde8af8cbb11,
    stuff: 'Education Book',
    price: 250
  },
  __v: 0
}
after saved:  {
  createdAt: 2021-04-17T08:44:30.231Z,
  updatedAt: 2021-04-17T08:44:30.231Z,
  _id: 607aa056be25dde8af8cbb10,
  name: 'Add new book22',
  reporterId: '607a6caacd1a6acf081251a9',
  detail: {
    _id: 607aa056be25dde8af8cbb11,
    stuff: 'Education Book',
    price: 250
  },
  __v: 0
}
```
Also when i check my collection in Atlas, it doesn't updated

I've tried to upgrade my typegoose to 8.x.x-beta.x, and mongoose to 5.12.x
and it gives me error, so i decide to stick with this version.

**Comment by hasezoey** [comment]
so if i understand correctly now, you are asking why the "update" does update nothing? when yes, please also provide what your data to update is (`data` value)

btw, is there an reason on why its `{ ...data },` and not `data,`?

**Comment by ashalfarhan** [comment]
Oh, this just my bad, the `EditInput` is include the reporterId, so i should separate the mutation, also the field that i want to edit is `detail`, but i'm just pass the data that is not specify where the field is, and it should be:

```ts
const after = await ReportModel.findOneAndUpdate(
      { _id: id },
      // Not this
      // { ...data },
      // Should be:
      { detail: data }
      {
        new: true,
      }
    );
```

i'm really sorry, but thanks for taking your time 🙏🏼
