### ISSUE TITLE
Compound index not working

### ISSUE THREAD

**Issue by yruben** [typegoose/typegoose#525]
## Versions

- System: windows 
- NodeJS: 14.15.2
- Typescript: 4.2.3

- Compiler / Transpiler: ts-node 
- Typegoose(NPM): 7.6.0 
- Typegoose(GIT): ec17fd8
- mongoose: 5.10.18 
- mongodb: 4.4.2
- grahpql / type-graphql: 15.4.0 / 1.1.0 

## What is the Problem?
I'm trying to add a product to my database having that can't exist a product with the same slug, department, and provider combination in my database so I'm trying to create a compound index, but when I try to create a new product with the same values combination it get stored succesfully. I don't know why, but it must give me an error. Here is the code I used in my ObjectType.

## Code Example

```ts
import { Field, ID, Int, Float, ObjectType } from 'type-graphql';
import { ObjectId } from 'mongodb';
import { getModelForClass, prop as Property, Ref, index, plugin, pre } from '@typegoose/typegoose';
import mongooseAutoPopulate from 'mongoose-autopopulate';
import slugify from 'slugify';
import { DepartmentEnum } from "../../helpers/department.enum";
import Category from '../category/category.type';
import Meta from './meta.type';
import Gallery from '../gallery/gallery.type';
import Rate from '../rate/rate.type';
import Provider from '../provider/provider.type';
import schemaOptions from '../../helpers/schemaOptions';

@pre<Product>('save', function () {
  this.slug = slugify(this.name,{lower: true});
})

@ObjectType()
@index({ slug: 1, department: 1, provider: 1 }, { unique: true })
@plugin(mongooseAutoPopulate as any)
export default class Product {
  @Field(() => ID, {name: 'id'})
  readonly _id: ObjectId;

  @Field(() => Date)
  readonly createdAt: Date;

  @Field(() => Date)
  readonly updatedAt: Date;

  @Field(() => Date)
  @Property({required:true, default: new Date()})
  publishedDate!: Date

  @Field()
  @Property({required:true})
  name: string;

  @Field()
  @Property({ index:true })
  slug?: string;

  @Field(() => DepartmentEnum)
  @Property({ required: true, enum: DepartmentEnum })
  department: DepartmentEnum;

  @Field()
  @Property({required:true})
  image: string;

  @Field()
  @Property({required:true})
  unit: string;

  @Field(() => [Category])
  @Property({ref: () => Category, required:true, autopopulate: true})
  categories: Ref<Category>[];

  @Field(() => Float)
  @Property({required:true})
  price: number;

  @Field(() => Int)
  @Property({default:0})
  discountInPercent: number;

  @Field(() => Int, { defaultValue: 1 })
  @Property({default:1})
  per_unit: number;

  @Field(() => Int, { defaultValue: 1 })
  @Property({default:1})
  quantity: number;

  @Field(() => Int, { nullable: true })
  @Property({default:0})
  views?: number;

  @Field(() => Int, { nullable: true })
  @Property({default:0})
  sales?: number;

  @Field({ nullable: true })
  @Property({default:''})
  description?: string;

  @Field(() => Provider)
  @Property({ref: ()=>Provider, required: true, autopopulate:true })
  provider: Ref<Provider>;

  @Field(() => Meta, { nullable: true })
  @Property()
  meta?: Meta;

  @Field(() => [Gallery])
  @Property({ type: () => Gallery })
  gallery: Gallery[];

  @Field(() => [Rate], { defaultValue:[]})
  @Property({ type: () => Rate, default:[] })
  ratings: Rate[];
}

export const ProductModel = getModelForClass(Product,{schemaOptions: schemaOptions});
```
And here is my mongo Config:

```ts
await connect(MONGO_DB_URL,{useNewUrlParser:true,
    useUnifiedTopology:true,
    useFindAndModify: false,
    useCreateIndex:true})
```
## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
does the collection already exist when you tried testing it? because mongoose does not update / create / delete indexes on an already existing collection (you would need to call `await Model.syncIndexes()` to sync the indexes)

**Comment by yruben** [comment]
@hasezoey Thanks for your quick answer. I found the reason why it was not working but I don't know if it is intended to work like that or if it is just a malfunction. Here is my solution:

```ts
@ObjectType()
@plugin(mongooseAutoPopulate as any)
@index({ slug: 1, department: 1, provider: 1 }, { unique: true })
export default class Product {
```

I just changed the decorator order, leaving the @index decorator for last. I don't know why, but if it is not last it doesn't work, at least for me...!!!
Thanks anyway.... And you are doing a great job.!!!

**Comment by hasezoey** [comment]
> I just changed the decorator order, leaving the @Index decorator for last. I don't know why, but if it is not last it doesn't work, at least for me...!!!

i just looked again, there shouldnt be any differences when using an different order (all typegoose class-decorators use different metadata keys, so they dont conflict, and on build, the build order dosnt change either way)
