### ISSUE TITLE
Cannot reference other class correctly in typegoose (mongoose) and save reference (ObjectId) only?

### ISSUE THREAD

**Issue by jamesweb1** [typegoose/typegoose#529]
## Versions
- System: macos 
- NodeJS: 14.16.1
- Typescript: 4.0.5

- Compiler / Transpiler: nest
- Typegoose(NPM): 7.6.0
- Typegoose(GIT): commithash
- mongoose: 5.10.18
- mongodb: 4.0.5
- nestjs / nestjs-typegoose: 7.5.1 / 7.1.38
- grahpql / @nestjs/graphql: 15.5.0 / 7.10.3

## What is the Problem?

I try to save some of fields in ObjectId only in the mongo db, but I find the following not working correctly:

```typescript
@ObjectType()
export class User {
  @prop()
  @Field()
  name: string;

  @prop({ ref: () => OtherClassA })
  @Field()
  otherClassA: OtherClassA;

  @prop()
  @Field()
  otherClassB: OtherClassB;
}

@ObjectType()
export class OtherClassB {

  @prop()
  @Field()
  name: string;

  @prop({ ref: () => OtherClassB1 })
  @Field()
  otherClassB1: OtherClassB1;

  @prop({ ref: () => OtherClassB2 })
  @Field()
  otherClassB2: OtherClassB2;
}
```

I found the data stored in the mongo db as following:
```
user {
  _id
  name
  otherClassA: ObjectId("607910cdf9961b0dcf50b5d8")
  otherClassB {
    otherClassB1 {
      // the whole object of otherClassB1
    }
    otherClassB2 {
      // the whole object of otherClassB2
    }
  }
}
```
which is not what I expected....

I expected:
```
user {
  _id
  name
  otherClassA: ObjectId("607910cdf9961b0dcf50b5d8")
  otherClassB {
    otherClassB1: ObjectId("607910cdf1231b0dcf51a456")
    otherClassB2: ObjectId("607910cdf1231b0dcf51a5bf")
  }
}
```

How can I save the reference only in such structure in typegoose(mongoose)?

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
Just for reference: https://stackoverflow.com/questions/67240804/how-to-reference-other-class-correctly-in-typegoose-mongoose-and-save-referenc

**Comment by hasezoey** [comment]
tested with code below, output is as expected - could not reproduce

```ts
// NodeJS: 14.16.1
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@7.6.0
import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.5

class OtherClassB { // reorganize, otherwise it would error with "use before init"
  @prop()
  public name?: string;

  @prop({ ref: () => OtherClassB1 })
  public otherClassB1?: Ref<OtherClassB1>;

  @prop({ ref: () => OtherClassB2 })
  public otherClassB2?: Ref<OtherClassB2>;
}

class User {
  @prop()
  public name?: string;

  @prop({ ref: () => OtherClassA })
  public otherClassA?: Ref<OtherClassA>;

  @prop()
  public otherClassB?: OtherClassB;
}

class OtherClassA {
  @prop()
  public dummy0?: string;
}
class OtherClassB1 {
  @prop()
  public dummy1?: string;
}
class OtherClassB2 {
  @prop()
  public dummy2?: string;
}

const UserModel = getModelForClass(User);
const OtherClassAModel = getModelForClass(OtherClassA);
const OtherClassB1Model = getModelForClass(OtherClassB1);
const OtherClassB2Model = getModelForClass(OtherClassB2);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify529", useCreateIndex: true, useUnifiedTopology: true });

  const ocb2 = await OtherClassB2Model.create({ dummy2: "hello2" });
  const ocb1 = await OtherClassB1Model.create({ dummy1: "hello1" });
  const oca = await OtherClassAModel.create({ dummy0: "hello0" });

  const userdoc = await UserModel.create({ name: "someuser", otherClassA: oca, otherClassB: { name: "someB", otherClassB1: ocb1, otherClassB2: ocb2 } });

  const found = await UserModel.findById(userdoc).orFail().exec();

  console.log("found", found);

  await mongoose.disconnect();
})();
```
output:
```
found {
  _id: 608659f00c6081247709482c,
  name: 'someuser',
  otherClassA: 608659f00c6081247709482b,
  otherClassB: {
    _id: 608659f00c6081247709482d,
    name: 'someB',
    otherClassB1: 608659f00c6081247709482a,
    otherClassB2: 608659f00c60812477094829
  },
  __v: 0
}
```

please modify the code to reproduce what you said it would do

**Comment by jamesweb1** [comment]
'''typescript
// NodeJS: 14.16.1
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@7.6.0
import * as mongoose from "mongoose"; // mongoose@5.10.18 @types/mongoose@5.10.5

class OtherClassB { // reorganize, otherwise it would error with "use before init"
  @prop()
  public name?: string;

  @prop({ ref: () => OtherClassB1 })
  public otherClassB1?: Ref<OtherClassB1>;

  @prop({ ref: () => OtherClassB2 })
  public otherClassB2?: Ref<OtherClassB2>;
}

class User {
  @prop()
  public name?: string;

  @prop({ ref: () => OtherClassA })
  public otherClassA?: Ref<OtherClassA>;

  @prop()
  public otherClassB?: OtherClassB[];
}

class OtherClassA {
  @prop()
  public dummy0?: string;
}
class OtherClassB1 {
  @prop()
  public dummy1?: string;
}
class OtherClassB2 {
  @prop()
  public dummy2?: string;
}

const UserModel = getModelForClass(User);
const OtherClassAModel = getModelForClass(OtherClassA);
const OtherClassB1Model = getModelForClass(OtherClassB1);
const OtherClassB2Model = getModelForClass(OtherClassB2);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify529", useCreateIndex: true, useUnifiedTopology: true });

  const ocb2 = await OtherClassB2Model.create({ dummy2: "hello2" });
  const ocb1 = await OtherClassB1Model.create({ dummy1: "hello1" });
  const oca = await OtherClassAModel.create({ dummy0: "hello0" });

  // const userdoc = await UserModel.create({ name: "someuser", otherClassA: oca, otherClassB: { name: "someB", otherClassB1: ocb1, otherClassB2: ocb2 } });
  
  const ocb = new OtherClassB();
  ocb.name = 'OtherClassB';
  ocb.otherClassB1 = ocb1;
  ocb.otherClassB2 = ocb2;

  const user = new User();
  user.name = "user";
  user.otherClassA = oca;
  user.otherClassB = [ ocb, ocb ]; // chanage the otherClassB to an arraylist

  const userdoc = await UserModel.create(user);
  const found = await UserModel.findById(userdoc).orFail().exec();

  console.log("found", found);

  await mongoose.disconnect();
})();
'''

Thanks for your example, and I found one of the structure I provided is not correct. If OtherClassB is an array, the children of otherClassB will be the whole object instead of using reference.

<img width="364" alt="screenshot" src="https://user-images.githubusercontent.com/6868915/116062685-b7a16b00-a6b6-11eb-8677-e38423ff96fc.png">

**Comment by smolinari** [comment]
Try it like this @jamesweb1 :

```ts
  @prop({ type: () => [OtherClassB] })
  public otherClassB?: OtherClassB[];

```

Scott

**Comment by hasezoey** [comment]
for reference to what @smolinari said, read the note [here](https://typegoose.github.io/typegoose/docs/api/decorators/prop#array-options)

**Comment by jamesweb1** [comment]
@smolinari Appreciate for you. I solved this issue from your solution. You can close this issue now.

**Comment by lokendra-chaulagain** [comment]
Thank you for  the valuable insight , It helped . I was getting lots of type error may be because of that  type mixed, Now all good.
