### ISSUE TITLE
How do I make something `required`, but keeping the default value set?

### ISSUE THREAD

**Issue by uWynell** [typegoose/typegoose#534]
Hello!
I have a Server class:
```ts
export class Server implements IServer {
  @prop({ required: true, index: true })
  public server!: string

  @prop({ default: 'uniq ' })
  public prefix?: string

  @prop({ default: '#FFFFFF', validate: /^#[0-9A-F]{6}$/ })
  public defaultColor?: string

  @prop({ default: '%nickname%' })
  public defaultName?: string
}

export const ServerModel = getModelForClass(Server)
```
And since `prefix`, `defaultColor` and `defaultName` have default values **and** are optional, I don't have to set them when creating a new instance, so I can do things like this:
```ts
const server = await ServerModel.create({ server: 'some value' }).exec()
```
In this example, `server.prefix` is optional. But if I made it required, then I'd have to specify the value while creating a new document, even though I have already set the default one:
```ts
/* class Server:
  public: prefix!: string
  // instead of prefix?: string
*/
const server = await ServerModel.create({ server: 'some value' }).exec() // <- Error, I didn't specify the value for `prefix`, even though I've set the default value
```

What to do in this situation? How do I make something `required`, but keeping the default value set, so I don't have to set it every time I creating a new instance

## Versions

- System: linux / macos / windows 
- NodeJS: 15.9.0
- Typescript: 4.2.4
- Compiler / Transpiler: tsc / ts-node
- Typegoose(NPM): 7.6.0
- mongoose: 5.10.18

---

**Comment by smolinari** [comment]
@uWynell 

> But if I made it required, then I'd have to specify the value while creating a new document, even though I have already set the default one

Just because you've set a default, it doesn't mean it fulfills a required property. Or put another way, if the property is required, then the default is useless. It will never be set. The two sort of negate each other. 

Scott

**Comment by uWynell** [comment]
> @uWynell
> 
> > But if I made it required, then I'd have to specify the value while creating a new document, even though I have already set the default one
> 
> Just because you've set a default, it doesn't mean it fulfills a required property. Or put another way, if the property is required, then the default is useless, because there has to be an input to fill the property. The two sort of negate each other.
> 
> Scott

My wish now is to convince TypeScript, that the value *does* exist in any case (like even if not in the DB, then as the default value, right?)
But if I write those properties with `!` exclamation mark, then I will also have to specify them, when inserting a document...

My wish is to be able to do so:
```ts
// The Server class blah blah blah
class Server implements IServer {
  @prop({ default: 'uniq ' })
  prefix!: string // So this property is guaranteed to exist!
}

// But (I wish) I don't have to specify it since it has the default value:
await Server.create({}).exec()
```

**Comment by hasezoey** [comment]
@uWynell the only way is to use `?`, because decorators cannot affect types (and having an `default` does not mean that it can be empty)

example:
```ts
// NodeJS: 14.16.1
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@8.0.0-beta.5
import * as mongoose from "mongoose"; // mongoose@5.12.5
import { MongoMemoryServer } from "mongodb-memory-server";
import { assertion } from "@typegoose/typegoose/lib/internal/utils";

class User {
  @prop()
  public username?: string;

  @prop({ default: "none", type: String }) // explicitly set "String", otherwise "Mixed"
  public alias?: string | undefined; // this "| undefined" is just to show that *it is possible*

  @prop({ required: true, default: "testy" }) // just to show that "required" and "default" dont negate eachother
  public test?: string;
}
const UserModel = getModelForClass(User);

(async () => {
  const server = await MongoMemoryServer.create();
  await mongoose.connect(server.getUri(), { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const doc = new UserModel({ username: "user1" });
  assertion(doc.alias === 'none');
  assertion(doc.test === 'testy');
  await doc.save();
  assertion(doc.alias === 'none');
  doc.alias = undefined;
  assertion(doc.alias === undefined);
  await doc.save();
  assertion(doc.alias === undefined);
  assertion(doc.test === 'testy');
  console.log(doc);

  await mongoose.disconnect();

  await server.stop();
})();
```

@smolinari `required` and `default` dont really negate eachother

basically `require` makes values like `undefined` and `null` not allowed on the property, and `default` only applies initially when the value is `undefined` or `null`

**Comment by smolinari** [comment]
@hasezoey - I stand corrected. 😊 

Scott

**Comment by uWynell** [comment]
I found a workaround for this:
 ```ts
const server = await ServerModel.create({ server: 'str' }) as DocumentType<Required<IServer>>
```
