### ISSUE TITLE
Error 005

### ISSUE THREAD

**Issue by pgsfredda** [typegoose/typegoose#539]
## Versions

- System: macos 
- NodeJS: 10.15.3
- Typescript: 4.2.4
- no option like "transpileOnly" is used
- Compiler / Transpiler: tsc 
- Typegoose(NPM): 7.6.0 
- Typegoose(GIT): commithash
- mongoose: 5.10.18 
- mongodb: 4.4.3

## What is the Problem?
After the transpiling phase, before the server process starts the error message is logged. 

The [guide](https://typegoose.github.io/typegoose/docs/guides/error-warnings-details#assertion-error-e019) says:
*'This Error should never show up, if it does report it'*

The complete error stack is:
~~~
/path/node_modules/@typegoose/typegoose/lib/internal/utils.js:491
            throw error !== null && error !== void 0 ? error : new Error('Assert failed - no custom error [E019]');
            ^
    
    Error: Option "ref" for "pgModel.createdBy" is null/undefined! [E005]
        at Object.processProp (/path/node_modules/@typegoose/typegoose/lib/internal/processProp.js:112:67)
        at Object._buildSchema (/path/node_modules/@typegoose/typegoose/lib/internal/schema.js:38:27)
        at Object.buildSchema (/path/node_modules/@typegoose/typegoose/lib/typegoose.js:129:20)
        at Object.processProp (/path/node_modules/@typegoose/typegoose/lib/internal/processProp.js:84:21)
        at Object._buildSchema (/path/node_modules/@typegoose/typegoose/lib/internal/schema.js:38:27)
        at buildSchema (/path/node_modules/@typegoose/typegoose/lib/typegoose.js:129:20)
        at Object.getModelForClass (/path/node_modules/@typegoose/typegoose/lib/typegoose.js:76:39)
        at Object.<anonymous> (/path/dist/pg-server-objects/pg-server-models/pg-admin-perm.model.js:47:40)
        at Module._compile (internal/modules/cjs/loader.js:701:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        at Module.load (internal/modules/cjs/loader.js:600:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
        at Function.Module._load (internal/modules/cjs/loader.js:531:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.<anonymous> (/path/dist/pg-server-objects/pg-server-models/pg-admin-group.model.js:14:31)
~~~
 

## Code Example
A code example is too complex to show here.

I can show the class listed in the error stack (pgAdminGroup) that uses two plugins and an another class previously defined.

```ts
import { prop, plugin, getModelForClass, Ref } from '@typegoose/typegoose';
import { pgAdminPerm, pgAdminPermModel } from './pg-admin-perm.model';
import { pgModel }     from './pg-model.model';
import { pgPopulationPath } from './classes/pg-population-path.class';
import { pgSetExtRefSchema } from './../pg-server-models/classes/pg-meta-related-docs.class';

let pgExtendedFind = require('./../pg-server-models/plugins/pg-extended-find.plugin');
let pgCheckRelated = require('./../pg-server-models/plugins/pg-check-related.plugin');

@plugin(pgCheckRelated)
@plugin(pgExtendedFind)
export class pgAdminGroup {
    @prop( { required: true, index: true, unique: true } ) name : string;
    @prop( { itemsRef: pgAdminPerm } ) perms ?: Ref<pgAdminPerm>[];
    @prop( ) model: pgModel;

    public static pgExtendedFind(options){};
    public static pgCheckRelated(options){};

    static populationPaths(): pgPopulationPath[] { return [...pgModel.populationPaths(), {path: 'perms', select: 'permit routerFunction'}] };
}

export const pgAdminGroupModel = getModelForClass(pgAdminGroup, { schemaOptions: { collection: 'pg-admin-groups'}});

pgAdminGroupModel.ensureIndexes();
```
---
```ts
import { pgUser }       from './pg-user.model';
import { pgPopulationPath } from './classes/pg-population-path.class';

export class pgModel {
    @prop( { ref: () => pgUser }) createdBy?: Ref<pgUser>;
    @prop( { index: true } ) createdAt?: Date;
    @prop( { ref: () => pgUser }) updatedBy?: Ref<pgUser>;
    @prop( { index: true }) updatedAt?: Date;

    static populationPaths(): pgPopulationPath[] { return [{path: 'model.createdBy', select: 'username email'}, {path: 'model.updatedBy', select: 'username email'}] };
}
```

## Do you know *why* it happens?

*no, I'm sorry*

---

I decided to update the version of mongoose (from 4 to 5) and typegoose (from <5.9 to the latest).
I followed all the guide prescritions for the migration typegoose.
I'm using grunt to automatize the transpiling during the development.

**This new version of Typegoose is very very advanced respect the <5.9. Thank you!!!**

**Comment by hasezoey** [comment]
it seems people are confused about how nodejs reports errors, the line where `E019` is shown, is *the line is the same where the **custom error** is thrown*, your error (as you can see in the error message) is `E005`  and the `E019` is just an fallback

**Comment by pgsfredda** [comment]
Thank you. I'm sorry.
Now I used the string in the ref function for pgUser and the problem seems solved
```ts
import { pgUser }       from './pg-user.model';
import { pgPopulationPath } from './classes/pg-population-path.class';

export class pgModel {
    @prop( { ref: () => 'pgUser' }) createdBy?: Ref<pgUser>;
    @prop( { index: true } ) createdAt?: Date;
    @prop( { ref: () => 'pgUser' }) updatedBy?: Ref<pgUser>;
    @prop( { index: true }) updatedAt?: Date;

    static populationPaths(): pgPopulationPath[] { return [{path: 'model.createdBy', select: 'username email'}, {path: 'model.updatedBy', select: 'username email'}] };
}
```
But I have to make this update for all the classes the uses the 'pgUser' and a *Mixed* warning is logged.
Is a good practice?

Thank you

**Comment by hasezoey** [comment]
> and a Mixed warning is logged.

cant help without knowing what property is affected

> But I have to make this update for all the classes the uses the 'pgUser'

it would be better and more dynamic to use the workaround of putting all `getModelForClass` call into one file (classes can still be seperated), this is sadly not an issue typegoose can fix (while still trying to be dynamic)

**Comment by pgsfredda** [comment]
The "mixed" warning is, i.e., for the follow class for the property `perms`:
```ts
@plugin(pgCheckRelated)
@plugin(pgExtendedFind)
export class pgAdminGroup {
    @prop( { required: true, index: true, unique: true } ) name : string;
    @prop( { itemsRef: pgAdminPerm } ) perms ?: Ref<pgAdminPerm>[];
    @prop( ) model: pgModel;

    public static pgExtendedFind(options){};
    public static pgCheckRelated(options){};

    static populationPaths(): pgPopulationPath[] { return [...pgModel.populationPaths(), {path: 'perms', select: 'permit routerFunction'}] };
}
```
---
> it would be better and more dynamic to use the workaround of putting all getModelForClass call into one file (classes can still be seperated), this is sadly not an issue typegoose can fix (while still trying to be dynamic)

Thank you for the suggestion; I read it in the guide but I was hoping for another solution.

**Comment by hasezoey** [comment]
> The "mixed" warning is, i.e., for the follow class for the property perms:

if its the property `perms`, then it probably because `itemsRef` is not yet transitioned to `ref` - which basically makes it an plain `Array`

**Comment by pgsfredda** [comment]
I thought so too and now I have used `ref` but the warning remains.

**Comment by hasezoey** [comment]
if its not because of `itemsRef`, then i dont know without debug logs, [here an guide on the logger](https://typegoose.github.io/typegoose/docs/guides/advanced/logger)

**Comment by pgsfredda** [comment]
I changed the property array as below:
```ts
@prop( { ref: () => pgAdminPerm } ) perms ?: Ref<pgAdminPerm>[];
```
**The code for me means: `perms` is an array property where the items are referiment to `pgAdminPerm` documents**

Now neither errors nor warnings are logged. All is clean.
I have to test all my server but now it is transpilled and all seams ok.

Thank you!!!

**Comment by hasezoey** [comment]
@pgsfredda if you did `ref: Class` instead of `ref: () => Class` its basically like you didnt define the property at all, because at the time `Class` was still `undefined` (circular dependencies, its just how nodejs works)

**Comment by pgsfredda** [comment]
ok.
I have changed the prop definition as below:
```ts
@prop( { ref: pgAdminPerm } ) perms ?: Ref<pgAdminPerm>[];
```
Thanks

**Comment by hasezoey** [comment]
@pgsfredda i think you misunderstood, i said `ref: Class` was bad, and `ref: () => Class` was good

**Comment by pgsfredda** [comment]
Ok, I'm sorry. I reused the function form of prop ref definition:
```ts
@prop( { ref: () => pgAdminPerm } ) perms ?: Ref<pgAdminPerm>[];
```
Thank you
