### ISSUE TITLE
[Bug] References in array schemas translate to Mixed instead of ObjectID

### ISSUE THREAD

**Issue by ChrisLahaye** [typegoose/typegoose#55]
Hello,

References in array schemas translate to Mixed instead of ObjectID.

Consider the following code:

```typescript
export class ChatChannelGroup {
  @prop({ enum: ChatChannelGroupType, required: true })
  public type!: ChatChannelGroupType;

  @prop({ ref: TEvent, required: true })
  public id!: Ref<TEvent>;
}

export class ChatChannel {
  @arrayProp({ _id: false, items: ChatChannelGroup, required: true })
  public access_groups!: ChatChannelGroup[];
}
```

When inspecting `ChatChannel.schema.paths.access_groups.schema.paths.id` I get a type of instance Mixed:
```
    "id": {
      "path": "id",
      "instance": "Mixed",
      "validators": [
        {
          "message": "Path `{PATH}` is required.",
          "type": "required"
        }
      ],
      "getters": [],
      "setters": [],
      "options": {
        "required": true
      },
      "_index": null,
      "isRequired": true,
      "originalRequiredValue": true,
      "$isUnderneathDocArray": true
    }
  },
```

When passing the class instead of the class name on line https://github.com/typegoose/typegoose/blob/master/src/prop.ts#L116 it correctly translates into ObjectID:
```
    "_id": {
      "path": "_id",
      "instance": "ObjectID",
      "validators": [],
      "getters": [],
      "setters": [
        null
      ],
      "options": {
        "auto": true
      },
      "_index": null,
      "$isUnderneathDocArray": true
    }
```

Best regards

**Comment by hasezoey** [comment]
i never really touched this section, i didnt even know that mongoose would accept classes, and because you could pass it in as a string (because of javascripts reference issues) i thought it would still be valid to be converting it to string

**Comment by ChrisLahaye** [comment]
@hasezoey I believe that in previous versions the ref value was passed as-is.

In my example TEvent can be any class. Do note that it refers to the class itself and not to the model.  It does have a model created for it though.

Regarding your note, I wasn't referring to the type property but to the passed object, and then in particular the instance property.

**Comment by hasezoey** [comment]
@ChrisLahaye is #59 the same problem as here?

**Comment by ChrisLahaye** [comment]
@hasezoey The decorator options are mutating. This is a problem when a class uses a subclass more then once. If this is the case, the function `baseProp` is called multiple times for each property in class. This function mutates the original options as you are attempting to copy the object as follows `rawOptions = Object.assign({}, rawOptions);` which doesn't actually change the reference. This causes the final schema to be constructed without the properties ref, refPath, etc. when the subclass is used more than once.

**Comment by RyannGalea** [comment]
Looks like this should fix my issues also @hasezoey

**Comment by hasezoey** [comment]
@RyannGalea sorry if this was your issue you had, this "referencing" is why i ditched C/C++, will look into it
