### ISSUE TITLE
Nested Array in Array when created a Array of Item

### ISSUE THREAD

**Issue by litfung** [typegoose/typegoose#550]
## Versions

- System: windows
- NodeJS: 12.18.3.
- Typescript: 4.0.3
- Compiler / Transpiler: tsc / ts-node
- Typegoose(NPM): 7.4.1
- Typegoose(GIT): commithash
- mongoose: 5.10.7
- mongodb: 4.4.0
- nestjs / nestjs-typegoose: 7.0.0

## What is the Problem?
When i declare a @Prop array, the data created using this schema will have nested array inside array.
example Field: `string[]`
Current: Field: `[["Test1"], ["Test2"]]`
Expected: Field: `["Test1", "Test2"]`

## Code Example
Schema
```ts
export class RawItem {
  @prop({ ref: () => Seal })
  SealID?: Ref<Seal>;

  @prop({ ref: () => Box })
  BoxID?: Ref<Box>;
}

export class Process extends BaseModel {
  @prop()
  ProcessStart: Date;

 @prop({ Type: RawItem })
  Items: RawItem[]
}
```

Data Created
```
{ 
    "_id" : ObjectId("60af9cb116c6d14ae8d90951"), 
    "Items" : [
        [
            {
                "BoxID" : ObjectId("6051c8d6f541fb2be4fdbb80"), 
                "SealID" : ObjectId("5ffc27d6ecdc1f62b8501901"), 
            }
        ], 
        [
            {
                "BoxID" : ObjectId("6051c8d6f541fb2be4fdbb81"), 
                "SealID" : ObjectId("5ffc27d6ecdc1f62b8501901"), 
            }
        ], 
        [
            {
                "BoxID" : ObjectId("6051c8d6f541fb2be4fdbb82"), 
                "SealID" : ObjectId("5ffc27d6ecdc1f62b8501901"), 
            }
        ]
    ], 
    "ProcessStart" : ISODate("2021-05-24T08:25:42.331+0000"), 
}
```

## Do you know *why* it happens?
No

**Comment by hasezoey** [comment]
did you get an "mixed" warning or is it disabled?

anyway, the options inside the decorators are case-sensitive, so you need to use `type` instead of `type`

**Comment by litfung** [comment]
Thank you, with the new version, i get the mixed warning and it help to fixed the double nesting issue.
