### ISSUE TITLE
@typegoose/typegoose@7.6.1 has incorrect peer dependency mongoose@5.10.0 - 5.10.18

### ISSUE THREAD

**Issue by Juan-hwt** [typegoose/typegoose#557]
## Versions

- System: linux / macos / windows 
- NodeJS: 0.0.0
- Typescript: 0.0.0

- Compiler / Transpiler: tsc / ts-node / ts-jest 
- Typegoose(NPM): 0.0.0 
- Typegoose(GIT): commithash
- mongoose: 0.0.0 
- mongodb: 0.0.0
- nestjs / nestjs-typegoose: 0.0.0 / 0.0.0 
- grahpql / type-graphql: 0.0.0 / 0.0.0 

---

run:
`yarn add mongoose @types/mongoose @typegoose/typegoose nestjs-typegoose`
give me this:
```
[3/4] Linking dependencies...
warning " > @typegoose/typegoose@7.6.1" has incorrect peer dependency "mongoose@5.10.0 - 5.10.18".
```
It can run, but how can I fix the problem? thank you

**Comment by smolinari** [comment]
Follow the instructions (and order of installation):

> npm i -s @typegoose/typegoose # install typegoose itself
> npm i -s mongoose # install peer-dependency mongoose
> npm i -D @types/mongoose # install all types for mongoose - this is required for typegoose to work in TypeScript

Scott
