### ISSUE TITLE
Both updatedBy and CreatedBy are getting updated after update operation on model object 

### ISSUE THREAD

**Issue by manveetb** [typegoose/typegoose#560]
In Mongoose model I am using schemaOptions timestamps: true to enable the mongo to record the `createdAt` and `updatedAt` timestamps. I was under impression that `createdAt` will always remain same and will not change after update operations but it keeps on changing same as `updatedAt` even after update. Any suggestions on how to correct it?
## Versions

- System: linux / macos / windows 
- NodeJS: 14.5.0
- Typescript: 4.0.5

- Compiler / Transpiler: tsc / ts-node / ts-jest 
- Typegoose(NPM): 7.4.6
- mongoose: 5.10.4
- mongodb: 3.6
- nestjs / nestjs-mongoose: 7.6.3 / 7.0.4 

---

**Comment by hasezoey** [comment]
could you provide an code example (common reproduction repository: https://github.com/typegoose/typegoose-testing )
