### ISSUE TITLE
[question] What does the `done` callback in pre query hooks do?

### ISSUE THREAD

**Issue by onichandame** [typegoose/typegoose#561]
## Versions

- System: linux 
- NodeJS: 15.10.0
- Typescript: 4.2.4

- Compiler / Transpiler: N/A 
- Typegoose(NPM): 7.6.1 
- Typegoose(GIT): N/A
- mongoose: 5.12.14 
- mongodb: N/A
- nestjs / nestjs-typegoose: 7.6.17 / 7.1.38 

---

![屏幕截图(8)](https://user-images.githubusercontent.com/23728505/122153088-da6d2600-ce94-11eb-89b9-a522d216a9ad.png)
In the typing of the pre query hook, the second argument(the callback function) takes 2 parameters: next and done. Both are callback functions but I cannot find any resource stating the difference.

`next` calls the subsequent middleware, as stated in the mongoose documentation, but the `done` function is not documented anywhere. What does it do?

**Comment by smolinari** [comment]
@onichandame - The older docs explain the done function. https://mongoosejs.com/docs/3.8.x/docs/middleware.html

Scott

**Comment by onichandame** [comment]
@smolinari thx. In the docs, `done` seems to be related only to parallel middleware. But in the latest mongoose 5.x it seems that the concept of "parallel" is gone. So I guess the `done` is not relevant anymore?

**Comment by hasezoey** [comment]
yes, true, i couldnt find any reference to `done` in the current mongoose code / documentation / types definition

so i will add this for 8.0x to be removed

**Comment by hasezoey** [comment]
closing, because released on beta since `8.0.0-beta.15`
