### ISSUE TITLE
add option "castNonArrays"

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#568]
## Which feature

support `prop` option `castNonArrays`

no documentation yet, see https://github.com/Automattic/mongoose/issues/10397

## Code Examples

```ts
// NodeJS: 16.3.0
// MongoDB: 4.2-bionic (Docker)
// import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@8.0.0-beta.16
import * as mongoose from "mongoose"; // mongoose@5.12.14

const schema1 = new mongoose.Schema({
  someArray: [{
    type: String,
    castNonArrays: false
  }]
});

const model1 = mongoose.model("model1", schema1);

(async () => {
  await mongoose.connect(`mongodb://localhost:44361/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const newdoc = await model1.create({ someArray: "hello" }); // no validation error

  const found = await model1.findById(newdoc);

  console.log(found);

  await mongoose.disconnect();
})();
```

(Note: this is currently broken code)

**Comment by smolinari** [comment]
@hasezoey - Interesting. Shouldn't this issue have been auto-closed with that release or with the PR?

Scott

**Comment by hasezoey** [comment]
> Interesting. Shouldn't this issue have been auto-closed with that release or with the PR?

github only closes issues that are fixed in an commit in the default branch (here its `master`), but currently its only in `beta`

**Comment by hasezoey** [comment]
form new info in https://github.com/Automattic/mongoose/issues/10398, it seems like this option has to be removed again, because it is actually not an property option, but an static option for all `SchemaArrays`
