### ISSUE TITLE
Code of ReturnModelType documentation results in TS2344 and TS2742

### ISSUE THREAD

**Issue by dirkbolte** [typegoose/typegoose#57]
I'm adapting my Nest.js application to the latest typegoose . One issue I stumbled upon was that my static methods didn't transpile anymore.

I had to use "typeof" (like in the test classes of typegoose) to address TS2344 and an explicit return type to address TS2742.

**Comment by hasezoey** [comment]
yes sorry, forgot to add it into the documentation,

i didnt find a way to not need "typeof"
