### ISSUE TITLE
findOneAndReplace not existing on a model

### ISSUE THREAD

**Issue by oof2win2** [typegoose/typegoose#577]
## Versions

- System: macos
- NodeJS: 16.4.1
- Typescript: 4.3.5

- Compiler / Transpiler: ts-node
- Typegoose(NPM): 7.6.3 (latest) 
- mongoose: 5.10.18 
- mongodb: 3.6.3

## What is the Problem?

When I attempt to use the `findOneAndReplace` method on a model, it shows up as non-existent

## Code Example

```ts
@modelOptions({
	schemaOptions: {
		collection: "webhooks"
	}
})
export class WebhookClass {
	@prop()
	id!: string
	@prop()
	token!: string
	@prop()
	guildId!: string
}

const WebhookModel = getModelForClass(WebhookClass)
WebhookModel.findOneAndReplace({ id: "a"}, {
  id: "a"
  token: "bb",
  guildId: "12345"
} // doesn't work, findOneAndReplace shows up as non existent
```

## Do you know *why* it happens?

not at all

---

**Comment by hasezoey** [comment]
please post the full error, and also is this an typescript or an runtime error?

if its an typescript error, do you have `@types/mongoose@5.10.x` (with the version) installed?

**Comment by oof2win2** [comment]
This is a typescript error I believe. I have provided a different example initially because it was easier to see, but the code is essentially the same. Provided the other code too, but it's the same error.
```
TSError: ⨯ Unable to compile TypeScript:
src/routes/communities.ts:91:51 - error TS2339: Property 'findOneAndReplace' does not exist on type 'ReturnModelType<typeof ConfigClass, BeAnObject>'.

91  let CommunityConfig = await CommunityConfigModel.findOneAndReplace({ guildId: OldConfig.guildId }, {
```
other code:
```ts
const CommunityModel = getModelForClass(CommunityClass)
CommunityModel.findOne({}).then((found) => {
	if (!found) return
	CommunityModel.findOneAndReplace({contact: found.contact}, {
		...found,
		contact: "different contact"
	})
})
```
And yes, I do have `@types/mongoose@5.10.5` installed.

**Comment by hasezoey** [comment]
from what i can tell, the function `findOneAndReplace` just does not exist in `@types/mongoose`, but at runtime

this is not an typegoose problem (so i will close it)
the workarounds are:
- define the function yourself (either in `declare` or in the class directly)
- use the typegoose beta, which supports the latest mongoose (`5.13.2`) with the new types

**Comment by oof2win2** [comment]
Yep that worked, thanks 👍
