### ISSUE TITLE
Property 'typegooseName' is missing in type.

### ISSUE THREAD

**Issue by MwareSolutons** [typegoose/typegoose#581]
I am facing an issue while adding a model to the database. It is giving an error 

> No overload matches this call.
  The last overload gave the following error.
    Argument of type 'AppPackage' is not assignable to parameter of type 'Pick<{ _id: any; name: string; typegooseName: {}; } & { _id: any; }, "name" | "typegooseName"> & { _id?: any; }'.
      Property 'typegooseName' is missing in type 'AppPackage' but required in type 'Pick<{ _id: any; name: string; typegooseName: {}; } & { _id: any; }, "name" | "typegooseName">'.ts(2769)
types.d.ts(490, 5): 'typegooseName' is declared here.
index.d.ts(3470, 9): The last overload is declared here.

Following are the version packages I am using in my app

> "devDependencies": {
    "@types/bcrypt": "^5.0.0",
    "@types/cors": "^2.8.10",
    "@types/cron": "^1.7.3",
    "@types/download": "^6.2.4",
    "@types/express": "^4.17.13",
    "@types/express-fileupload": "^1.1.6",
    "@types/extract-zip": "^1.6.2",
    "@types/js-base64": "^3.0.0",
    "@types/lodash": "^4.14.168",
    "@types/mime": "^2.0.3",
    "@types/mime-types": "^2.1.0",
    "@types/mongoose": "^5.7.28",
    "@types/mongoose-autopopulate": "^0.10.1",
    "@types/mongoose-paginate-v2": "^1.3.8",
    "@types/node": "^14.0.12",
    "@types/passport": "^1.0.6",
    "@types/passport-jwt": "^3.0.5",
    "@types/qs": "^6.9.6",
    "@types/swagger-jsdoc": "^3.0.2",
    "@types/swagger-ui-express": "^4.1.2",
    "@types/uuid": "^8.3.0",
    "@types/woocommerce__woocommerce-rest-api": "^1.0.1",
    "nodemon": "^2.0.12",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.4"
  },
  "dependencies": {
    "@bugsnag/js": "^7.1.1",
    "@bugsnag/plugin-express": "^7.1.1",
    "@google-cloud/translate": "^6.1.0",
    "@octokit/rest": "^18.5.3",
    "@sendgrid/mail": "^7.4.4",
    "@typegoose/typegoose": "^7.4.1",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.3.1",
    "class-transformer-validator": "^0.9.1",
    "class-validator": "^0.12.2",
    "cors": "^2.8.5",
    "cron": "^1.8.2",
    "dotenv": "^8.2.0",
    "download": "^8.0.0",
    "edgegrid": "^3.0.8",
    "express": "^4.17.1",
    "express-fileupload": "^1.2.1",
    "extract-zip": "^2.0.1",
    "http-status-codes": "^1.4.0",
    "linq": "^3.2.3",
    "lodash": "^4.17.21",
    "mime": "^2.5.2",
    "mime-types": "^2.1.29",
    "mongoose": "^5.9.20",
    "mongoose-autopopulate": "^0.12.3",
    "mongoose-paginate-v2": "^1.3.9",
    "node-bigcommerce": "^4.1.0",
    "opencart-manager": "^0.1.2",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "prestashop-api-nodejs": "^1.0.3",
    "qs": "^6.10.1",
    "read-excel-file": "^5.2.4",
    "referral-code-generator": "^1.0.8",
    "serialize-error": "^7.0.1",
    "shopify-api-node": "^3.6.12",
    "swagger-jsdoc": "^4.0.0",
    "swagger-ui-express": "^4.1.4",
    "twilio": "^3.63.1",
    "uuid": "^8.3.2",
    "woocommerce-api": "^1.5.0",
    "xml-js": "^1.6.11",
    "xml2js": "^0.4.23",
    "xss": "^1.0.8"
  }

My NodeJS version v14.16.0
Typescript Version 4.2.3

Can anybody suggest why the above issue is coming?

**Comment by hasezoey** [comment]
solved?

if not, please provide the code where its happening on too, the error alone is not enough

**Comment by MwareSolutons** [comment]
`let packageModel = getModelForClass(AppPackage);
      let modelToSave = <AppPackage>model;
      let result = await packageModel.create(modelToSave);`
Please see the image below
![image](https://user-images.githubusercontent.com/26382632/127175477-320b250a-741e-4fad-85f4-ff655f8f50e2.png)

**Comment by hasezoey** [comment]
@MwareSolutons please try to upgrade to the latest versions currently supported:
- typegoose to `7.6.3`
- mongoose to `5.10.18` (hard, no `^` or `~`)
- @types/mongoose to `~5.10.x` (the `~` to prevent it from going to 5.11, where the package is empty and does not provide any types anymore)

or try the typegoose beta:
- typegoose to `beta` (tag) or `^7.0.0-beta.22`
- mongoose to `^5.13.3`
- no mongoose types package

**Comment by MwareSolutons** [comment]
Fixed.

> "dependencies": {
    "@typegoose/typegoose": "7.6.3",
    "mongoose": "5.10.18",
    "ts-node": "^10.1.0",
    "typescript": "^4.3.5"
  },
  "devDependencies": {
    "@types/mongoose": "~5.10.x"
  }

Thanks for quick guiding.
