### ISSUE TITLE
Typescript typechecking not working with Typegoose 8 releases

### ISSUE THREAD

**Issue by taranvohra** [typegoose/typegoose#590]
## Versions

- System:  windows
- NodeJS: 14.5.1,  NPM v7.9.0
- Typescript: 4.3.5

- Compiler / Transpiler: tsc
- Typegoose(NPM): 8.1.1
- Typegoose(GIT): 219095f26b444c1491b65a713b330561628b9f1f
- mongoose: 5.13.5
- mongodb: 3.6.10

## What is the Problem?

The typechecking is completely broken and not kicking in. I'm attaching an example where you can see I have a `User` class 
with `2 required fields` but you can see that while using the `.create` function on the `UserModel` not only I skipped one of the fields but I also provided a value of incorrect type on the provided field. Typescript is saying **no errors**

## Code Example

![example](https://user-images.githubusercontent.com/8937991/128624837-f99d8bda-3ae1-4acd-aac5-13195483f196.png)

```ts
import { prop, getModelForClass } from '@typegoose/typegoose';

class User {
  @prop()
  public foo!: number;

  @prop()
  public bar!: string;
}

const UserModel = getModelForClass(User);

UserModel.create({ foo: '1' });
```

## Do you know *why* it happens?

*no*

---

My `package.json` looks like this. Everything is in accordance with the versions mentioned in the docs to get started
```js
{
  "name": "typg-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@typegoose/typegoose": "8.1.1",
    "mongoose": "~5.13.3",
    "typescript": "^4.3.5"
  }
}
```

**Comment by hasezoey** [comment]
is this issue just about `create` (/`new`)? when yes, then typegoose can not much do about it, because this is defined by the (now official) mongoose types, which makes every value for these *optional* (via `Partial`)

**Comment by taranvohra** [comment]
So far yes, this issue is about `create` because my experience with older versions was that `create` would be strict but as you're saying it has to do with official mongoose types now (which I don't understand why they've made it `Partial` for every value), I guess we will have to live with it

**Comment by hasezoey** [comment]
closing, because it is not a typegoose issue
