### ISSUE TITLE
'class Something extends Document' hangs find queries

### ISSUE THREAD

**Issue by Victordmdb** [typegoose/typegoose#591]
I needed to extend classes with mongoose `Document ` to make them compatible with another plugin being used,
but it caused `find` queries to stop working, while `create` and `countDocuments` worked fine.

As solution, I instead just created an interface with the same name as the class and extend that instead.

**Comment by hasezoey** [comment]
`extends Document` is not supported in typegoose (and also in plain mongoose)
for the types to work, you need to use `DocumentType<YourClass>`

also, please will out the [bug issue template](https://raw.githubusercontent.com/typegoose/typegoose/master/.github/ISSUE_TEMPLATE/bug.md)
