### ISSUE TITLE
`DocumentType<T>` can be cast to any type V as long as it is nullable

### ISSUE THREAD

**Issue by agrattaqrypt** [typegoose/typegoose#597]
After upgrading to Typescript 4.3.5 from 4.2.x, I noticed a strange issue where a compile error was not appearing on code that was obviously incorrect.

Assume we have defined some Typegoose classes and models: Organization and OrgModel, Subscription and SubscriptionModel. The fields they have are irrelevant, but you can assume that Organization is not compatible with Subscription (you cannot cast one from the other).

### The following snippets correctly throw a compile error on the `as` cast:
```ts
const orgDoc: DocumentType<Organization> = new OrgModel();
const subscription = orgDoc as Subscription;
```

```ts
const orgDoc: Organization = new OrgModel();
const subscription = orgDoc as Subscription | null;
```

### The following snippets strangely do NOT lead to any compile errors when using Typescript 4.3.5:
```ts
const orgDoc: DocumentType<Organization> = new OrgModel();
const subscription = orgDoc as Subscription | null;
```

```ts
const orgDoc: DocumentType<Organization> = new OrgModel();
const subscription = orgDoc as number | null;
```

```ts
const orgDoc: DocumentType<Organization> = new OrgModel();
const subscription = orgDoc as null;
```

Essentially, if I am casting a DocumentType<T>, I can cast it (implicitly or explicitly) to any other type V as long as it is nullable. Obviously this can lead to mistakes in code. 

I don't understand the issue completely, but my best guess is that the `DocumentType<T>` type definition is no longer behaving appropriately with a TypeScript compiler change in 4.3.x described here: [Contextual Narrowing for Generics](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3-rc/#contextual-narrowing-for-generics)

**Comment by hasezoey** [comment]
i tried to reproduce your mentioned "claims", but could not many of them:
reproduction repository & branch: https://github.com/typegoose/typegoose-testing/tree/verify597
(there are 4 cases)

- 17dfbddecce8450918b7680df4406748f4c6b7e9 is typescript 4.2.4, which does error in 2 cases
- 2da465ac518755df22315ff341f2bb9be0ed1284 is typescript 4.3.5, which does not error in any case
- 543c59bc0ab7685aff755a3ec8c6cf3cc09551ea is typescript 4.4.2, which does error in 2 cases again (like in typescript 4.2.4)

**Comment by agrattaqrypt** [comment]
That is interesting that the errors come back if you upgrade TypeScript even further to 4.4.2.
So something strange is going on with TypeScript 4.3.5 specifically.
At this point I'm convinced this is actually a bug with TypeScript itself, which is pretty unbelievable.
I had a suspicion that the `&` syntax in the `DocumentType` definition was the root of the problem, so I tried testing this on some very simple interfaces:

```
interface A {
    a: string;
}

interface B {
    b: string;
}

const objA: A = { a: "hello" }
const objB: B = { b: "hello" }
const objAB: A & B = { a: "hello", b: "world" }

const castA = objA as null; // always an error
const castB = objB as null; // always an error
const castAB = objAB as null; // error on TypeScript 4.4.2, not an error on TypeScript 4.3.5
```

Closing this report as there is nothing that can be done on the typegoose side.
Thanks for investigating.

**Comment by agrattaqrypt** [comment]
Wrote a bug report for TypeScript [here](https://github.com/microsoft/TypeScript/issues/45640)
