### ISSUE TITLE
Bad assertion: does not have a get / set function

### ISSUE THREAD

**Issue by KensingtonTech** [typegoose/typegoose#599]
## Versions
- Typegoose(NPM): 8.2.0

## What is the Problem?
In ProcessProp.ts, lines 202 - 204 are two assertions:

```
if (!utils.isNullOrUndefined(rawOptions.set) || !utils.isNullOrUndefined(rawOptions.get)) {
    utils.assertion(typeof rawOptions.set === 'function', new TypeError(`"${name}.${key}" does not have a set function! [E007]`));
    utils.assertion(typeof rawOptions.get === 'function', new TypeError(`"${name}.${key}" does not have a get function! [E007]`));
```

My @prop is like so:
```
 @prop({
    type: () => Schema.Types.Mixed,
    set: myCoolTransform
  }) someProperty: SomeType[];
```

What these are doing is making both getters and setters mandatory for `@props` if either a getter or a setter is present.  This behaviour doesn't jive with Mongoose's behaviour, which allows getters and setters in an either/or manner, which is a valid use case.  E.g. I want to transform a value when getting, but not when setting, or transform when setting but not when getting.  This is interfering with my porting Mongoose models that use this pattern.

I respectfully request that these assertions be removed.  I can submit a PR if you'd like.

**Comment by KensingtonTech** [comment]
As a follow-up, from the Mongoose documentation @ [](https://mongoosejs.com/docs/tutorials/getters-setters.html) (emphasis mine:

Mongoose setters are different from ES6 setters because they allow you to transform the value being set. With ES6 setters, you would need to store an internal _email property to use a setter. With Mongoose, you do not need to define an internal _email property **or define a corresponding getter** for email.

**Comment by hasezoey** [comment]
at the time i wrote the get/set implementation, there was somehow always some error with mongoose, so i added these errors - but i might remove them again when doing some refactoring (though i dont exactly recall the reasons at the moment)

Note: changed from `bug` to `enhancement & parity`

**Comment by KensingtonTech** [comment]
Thanks for the quick reply!

**Comment by KensingtonTech** [comment]
By the way, when I say 'interfering', that doesn't mean it's really a blocker.  All that needs to be done to workaround it is return the original value in a getter.
