### ISSUE TITLE
Add test cases and documentation to use @deepkit/type

### ISSUE THREAD

**Issue by smolinari** [typegoose/typegoose#601]
## Describe what you need | want

Because it seems `class-transformer` is abandoned, we might need an alternative. @deepkit/type is one.

## Do you have already an idea for the implementation?

Yes. Tests and docs already finished. 

Scott

**Comment by hasezoey** [comment]
closing because tests & documentation are included in beta & master (9.0.0)

---

@smolinari could you update the tests & examples when deepkit goes out of alpha / beta? (when `1.0.0` releases)

**Comment by smolinari** [comment]
> @smolinari could you update the tests & examples when deepkit goes out of alpha / beta? (when 1.0.0 releases)

Sure will. 

Scott
