### ISSUE TITLE
Cascade

### ISSUE THREAD

**Issue by kamalkech** [typegoose/typegoose#606]
As i mention in the title, how can use cascade with this package ??

there is another way instead of  example bellow, same other configuration of model ??

```typescript
// First delete item
const res = await this.userModel.deleteOne({ _id }).exec();
// Cascade: then delete profile of user
await this.profileService.deleteByUser(_id);
return res;
```

**Comment by smolinari** [comment]
Firstly, there is a "Discussons" forum open for questions. Please use that in the future. Issues are reserved for bugs and suggestions of improvement. 

To answer your question, you could do what you've come up with or you could set up a remove hook. 
This article describes it: https://dev.to/kwabenberko/implementing-sql--like-cascades-in-mongoose-bap

Or, there are a couple of plugins built for this, like this one:
https://github.com/QuantumGlitch/mongoose-references-integrity-checker

I count vouch for the plugin. I just found it looking for a possible plugin for such a feature. 

You can search the Mongoose plugins nach "Cascade" to find the others. 
https://plugins.mongoosejs.io/

Scott
