### ISSUE TITLE
6.0 usage with class-transformer

### ISSUE THREAD

**Issue by duro** [typegoose/typegoose#61]
Pre 6.0 we were using our model schema along with the library [class-transformer](https://github.com/typestack/class-transformer) in order to hide/expose certain properties when they were serialized for use in a response.

We were able to annotate our schema like so:

```
import { Expose, Exclude } from 'class-transformer'

@Exclude()
@index('parent', { sparse: true })
export class Organization extends Typegoose {
  @Expose()
  public readonly _id: Types.ObjectId

  @Expose()
  @prop({ required: true })
  public name: string

  @Expose()
  @prop({ default: null })
  public parent: Ref<Organization> | null
}
```

My hope with 6.0 was to get rid of having to use things like `DeepPartial` in order to use the class model definition type as an argument type to enforce the right data to functions that acted on the model.

My main issue is with the `@Expose` on the `_id` field. Since that field is present when dealing with a document, but not at object creation time. Now when trying to pass in a plain object with  properties that match all the other class properties to an argument that is typed to `Organization` TS complains that my object does not have an _id.

Imagine a function like this:

```
class SomeService {
  public createNewOrganization(data: Organization) {
    //
  }
}
```

And then trying to call it:

```
const data = {
  name: 'TheOrg',
  parent: null
}
someService.createNewOrganization(data)
```

Any idea on how to get around this? I know this may not be specifically a typegoose issue, but since this was a heavy use case in our past usage of Typegoose, I figured I would pose the question here.

**Comment by duro** [comment]
I'm running into similar trouble using things like properties which have a default value.

**Comment by hasezoey** [comment]
no we currently dont have such a thing (for create, new, and custom function) in place, but you could "steal" it from my side project (please dont try to use it) the types

https://github.com/hasezoey/typegoose-v2/blob/2b8c1137ddc88e977337e450a67235dab3a69c30/src/model.ts#L12-L33

**Comment by duro** [comment]
@hasezoey Thanks for passing that along, it was very helpful.

**Comment by hasezoey** [comment]
because the types are a bit "hacky" (/ at least i dont fully understand them) i didnt add them here in the main project

**Comment by hasezoey** [comment]
-> i will let this issue open for future re-consideration & to notify other people searching for such thing

**Comment by hasezoey** [comment]
Update: read more on https://github.com/typegoose/typegoose/issues/96#issuecomment-549031131 & below

**Comment by hasezoey** [comment]
Added an "known-issue" in bcfadc9bf5c25726efc91708e62b4e5f4c62ca6c (with a "workaround"), view them at https://typegoose.github.io/typegoose/guides/known-issues/

**Comment by hasezoey** [comment]
i'm closing this in favor of #108 

-> if wrongly closed, please comment
