### ISSUE TITLE
staticMethod, with or without decorator still doesn't work

### ISSUE THREAD

**Issue by patarapolw** [typegoose/typegoose#62]
## Versions

- NodeJS: 10.16.0
- Typegoose(NPM): 6.0.0 (@typegoose/typegoose)
- Typegoose(GIT): commithash
- mongoose: 5.7.3

## Code Example

```ts
class Post {
  @prop() _id!: string;
  @prop({ required: true, unique: true }) title!: string;
  @prop() date?: Date;
  @prop({ default: [] }) tag!: string[];
  @prop({ required: true }) content!: string;

  async findByQ(q: string, offset: number = 0, limit: number | null = 10, sort?: ISortOptions<Post>) {
    ...
    return {count, data};
  }
}

const PostModel = getModelForClass(Post);
// PostModel.findByQ = new Post().findByQ;  // TypeScript will complain findByQ is not a function, without this line.
```

Adding decorator `@staticMethod` doesn't help.

## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
you know that you must add the word `static` to the function to be a static function?

`static async findByQ`, otherwise it is an instance method

**Comment by patarapolw** [comment]
It works, but anyways, typing is wrong to suggest it, to make it seems like it is available on `ReturnModelType<typeof Post, unknown>`. Should only be shown on `DocumentType<Post>`.

**Comment by hasezoey** [comment]
> It works, but anyways, typing is wrong to suggest it, to make it seems like it is available on `ReturnModelType<typeof Post, unknown>`. Should only be shown on `DocumentType<Post>`.

i know, but without many typescript intermediate types, it is not possible, (how typescript handels some types is still not clear to me)
