### ISSUE TITLE
replace Promise's with Observables

### ISSUE THREAD

**Issue by nhhockeyplayer** [typegoose/typegoose#631]
I was one of the first to spot typegoose early on version 4/5 and released a product fairly rapidly fluid no issues fast and its been bulletproof since.

I settled on typeorm recently and found I cannot develop as fluid as I wished. My development is currently halted with typeorm and my scaffold due to minut issues that have no business being part of any codebase.

Promises were the solution to callback hell. Async Await though comes into the fold and is not immune to async/await hell.

So Im wondering... why did the typeorm folks settle on Promise. 

**Speculation...**

- Likely because async/await is built on promises and they needed asynchronous
- he wanted an async leg of execution by wanting to separate the logic so the main system could move on
- async await already does this and Promises are required to use those
- so its obvious Promises are coming from the async/await

**Issue**

- the Async/Await and Promises are clutter to the logic and impact everything from the backend up to the front end UI
- why does our clean concise beautiful biz logic need to be impacted as such

**Facts**
Observables are elegant and 

- asynchronous and work beautifully fluidly end to end

**Benefits of Observable**

- Whats so difficult about operating an Observable and passing that around thru the end to end spectrum of logic?
- Legs of execution can pass Observables fluidly end to end
- Legs of execution is free to subscribe to fluidly end to end
- pipelines of Observables can be customized on the fly for any leg of execution frontend or backend

**Questions**

- If needing an async leg of execution on the back end ORM system is needed why cant that be isolated internally AWAY from the business logic of the ORM and its surrounding operating logic of models/consumers/users of models? Or even tucked away in an automated base class or interface?

The async leg of execution is already part of the nature of the http bridge but seems its ignored isolated purely to http and other libraries or packages cake on more asynch legs of execution when it need not be introduced and imposed onto the code of application developers. Why cant we reduce and eliminate as much async legs of execution instead of imposing it onto the developers code? Wouldn't things go more fluidly? AT most we should ONLY be operating the Observable if it were built on Observables.

I dont like promises its a solution to functional programmers and async await has its applicability but I feel they are being over used and abused everywhere creating more chaos to developer code.

I was disheartened to see typegoose copying the typeorm model built on Promises

there is a better way... has to be

**Comment by hasezoey** [comment]
> I was disheartened to see typegoose copying the typeorm model built on Promises

from what i know, typegoose does not use promises outside of tests

remember, typegoose is a library built on-top of mongoose, and from what i can tell, all typegoose functions are sync

**Comment by nhhockeyplayer** [comment]
Thanks Friend... thats good to know

Im looking at nestjs-typegoose  which looks like the ONLY fixture to wire typegoose into nestJS
and he has promises being sent back from back end over http

in 2016 http began its defacto standard of using Observables

so Im scratching my head why these developers are copying from what they see before

at a minimum they could at least make it optional to have whats sent back over http an Observable

I dont know if its being casted or converted to an observable but. its all rigged on Promises

when http's NOW standard is obviously Observables

can you take a peek at https://github.com/kpfromer/nestjs-typegoose

and let me know if he COULD have done it with Observables?

I think Promises and async await should be ditched it all came from functional javascripter's non fluent in Object Oriented and closure camp's and I have seen whole companies bit the dust and go chapt 11 from their widespread impact of chaos async threads and inability to get any of it under control

If typegoose folks can produce a fixture for NestJS that would be the stanley cup to all of this

I will be the first to charge into the field and employ typegoose as an official solution to ORM because its gotten positive attention already and the decorators are fleet none done before like the founder did

The field is still struggling and I see alot and what Im seeing here is an open door for typegoose to take this ground rather easily

all we need is a NestJS fixture

please let know what can be done

Thanks !

**Comment by hasezoey** [comment]
> and let me know if he COULD have done it with Observables?

> please let know what can be done

sorry, but i dont have experience in nestjs or observables

**Comment by hasezoey** [comment]
i will close this, because it is not related to typegoose itself
