### ISSUE TITLE
next method on @Pre middleware as undefined type

### ISSUE THREAD

**Issue by henriquetatagiba** [typegoose/typegoose#64]
![Screen Shot 2019-10-02 at 13 56 43](https://user-images.githubusercontent.com/16236873/66064803-81245e00-e51c-11e9-9cb5-b4ea49048264.png)

## Versions

- NodeJS: 12.10
- Typegoose(NPM): 6.0
- mongoose: 5.7.3

## Code Example

```ts
@Pre<User>('save', function(next) {
  if (this.isModified('password')) {
    const salt = bcrypt.genSaltSync();
    this.password = bcrypt.hashSync(this.password, salt);
  }
  next();
})
```

## Do you know *why* it happenes?

```ts
declare type PreFnWithDT<T> = (this: DocumentType<T>, next?: EmptyVoidFn) => void;

// hooks.d.ts
```

type `next` as optional

**Comment by hasezoey** [comment]
i can reproduce this used code:

```ts
import { getModelForClass, pre, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@6.0.0
import * as mongoose from "mongoose"; // mongoose@5.7.3

@pre<User>("save", function(next) {
    next();
})
class User {
    @prop()
    public username?: string;
}
const UserModel = getModelForClass(User);
```

but i dont know how to fix this without making `next` necessary (not optional)
for now, use `async function()`  / a promise
