### ISSUE TITLE
Cannot read properties of undefined (reading 'ObjectId')

### ISSUE THREAD

**Issue by Mosquid** [typegoose/typegoose#651]
## Versions

- System: linux / macos / windows 
- NodeJS: v16.12.0
- Typescript: 4.3.5

- Compiler / Transpiler: tsc
- Typegoose(NPM): 9.3.1 
- Typegoose(GIT): commithash
- mongoose: 6.1.0 

## What is the Problem?

I'm unable to compile this example from the docs: https://typegoose.github.io/typegoose/docs/guides/advanced/using-objectid-type/.
It gives me `Cannot read properties of undefined (reading 'ObjectId')`

## Code Example

```ts
import * as mongoose from 'mongoose';
import { prop } from '@typegoose/typegoose';

class FooModel {
  @prop()
  userId: mongoose.Types.ObjectId;
}
```

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
this is weird, what system are you on? (linux (which distro) / mac / windows)
did you already try to delete `node_modules`?
could you provide the full error and also a [debug log](https://typegoose.github.io/typegoose/docs/guides/advanced/logger#enable-debug-logger)?

**Comment by Akash187** [comment]
I also faced the same issue. My Solution is below.
Error Message:- **Error: "User.email"'s Type is invalid! Type is: "undefined"**
```
export class User {
	@prop({ lowercase: true, required: true, unique: true })
	email: string
}
```

Right now the workaround is to add type in @prop decorator.
```
export class User {
	@prop({ type: String, lowercase: true, required: true, unique: true })
	email: string
}
```

**Solution**
Enable below options in `tsconfig.json`
```
"experimentalDecorators": true,
"emitDecoratorMetadata": true,
```

**Comment by hasezoey** [comment]
@Akash187 from what i can tell, you "issue" is unrelated to the original issue, see [Use without `emitDecoratorMetadata`](https://typegoose.github.io/typegoose/docs/guides/use-without-emitDecoratorMetadata)

**Comment by Akash187** [comment]
Maybe @hasezoey, but enabling that option fixed the issue for me since it seemed very relatable so I answered. Maybe it helps others with a similar issue.
