### ISSUE TITLE
Why is WhatIsIt exported from internal constants?

### ISSUE THREAD

**Issue by moniuch** [typegoose/typegoose#653]
## Versions

```json
    "@types/node": "^16.11.12",
    "@typegoose/typegoose": "^9.4.0",
    "mongoose": "^6.1.1",
    "typescript": "^4.5.4"
```
---

I am looking at the imports in my code:

```ts
import { pre, prop } from '@typegoose/typegoose';
import { WhatIsIt } from '@typegoose/typegoose/lib/internal/constants';
```

and I am wondering about the `WhatIsIt` import - shouldn't it be moved and exported/imported from the main namespace?
Because: if it is the lib's internal constant then why is it exported as public and referred to in docs, right?
Besides this logic, it would also shorten/simplify the code significantly. 
I double-checked the import is correct by trying to import it from `'@typegoose/typegoose'` but apparently it is not there.

**Comment by hasezoey** [comment]
> shouldn't it be moved and exported/imported from the main namespace?

true, forgot to do this

---

`WhatIsIt` is basically used as a second argument to `@prop`, to explicitly set what type the property is (currently, None (normal), Array and Map), see [@prop: WhatIsIt](https://typegoose.github.io/typegoose/docs/api/decorators/prop#whatisit)
