### ISSUE TITLE
Upgrade graphql library to v16

### ISSUE THREAD

**Issue by waynehaffenden** [typegoose/typegoose#659]
Upgrade the graphql dependency to v16 in parity with the latest release.

**Comment by smolinari** [comment]
@waynehaffenden - Did you catch the wrong repo? Typegoose doesn't have a GraphQL dependency. 

https://github.com/typegoose/typegoose/blob/master/package.json

Scott

**Comment by hasezoey** [comment]
@waynehaffenden this repository if for `@typegoose/typegoose`, which does not use graphql at all

**Comment by waynehaffenden** [comment]
I did catch the wrong repo, sorry guys ha ha!
