### ISSUE TITLE
Q: References - Population and Required

### ISSUE THREAD

**Issue by nea** [typegoose/typegoose#66]
Hi everyone

I looked in the issues here and tried to derive it myself from the documentation but wasn't able to fully cope the functionality.

I have a model with a ref `myReference!: Ref<MyReference>` annotated as `@prop({ required: true, ref: Customer})`. `MyReference` is just a class with `name` for testing purposes.

How, two problems I faced:
* When creating the model with passed data, I didn't have to add `myReference`. It worked without, the `required` did not pose an issue
* The other thing: I put the `MyReference` _id into the model, it stored fine and I can see the `$oid` saved in the model. If I retrieve the model I get the `$oid`. How can I populate `myReference` while loading? I tried the Virtual-Populate documentation but wasn't able to figure it out.

If anybody can maybe point me in the right direction it would be awesome.

Thanks a lot in advance

**Comment by RyannGalea** [comment]
when loading the parent model you will need to use
```
Model.findOne(_id).populate('myReference')
```

or there is the sample code in the docs for virtual.
```
class RefClass { @prop({ required: true, ref: Virtual }) public refToName: Ref<Virtual>; } class Name { @prop({ ref: RefClass, foreignField: 'refToName', localField: '_id', justOne: false }) public somevalue: Ref<RefClass>; }
```

**Comment by nea** [comment]
Hi @RyannGalea 

Thanks for the awesome quick reply.

I do not get where the `Virtual` is coming from. I referenced the `oid`, so I would like to ref via the `_id` of course. Do I have to another import or anything?

Sorry if the questions come off as stupid.


Thanks

**Comment by RyannGalea** [comment]
So you have:
```
@prop({ required: true, ref: Customer})
myReference!: Ref<MyReference>
```

What are you trying to do, simply populate myReference with a customer?

**Comment by nea** [comment]
Hi @RyannGalea 

Yes, of course in my case Ref is of course also typed to Customer, that was just for example reasons, so I have:

ˋˋˋ
@prop({ required: true, ref: Customer})
customer!: Ref<Customer>
ˋˋˋ

I can call ˋ.populate(customer)ˋ which does work of course. But I would like to have it implicitly populated when finding an object of that class, if possible.


Thanks

**Comment by hasezoey** [comment]
@nea 
>  do not get where the Virtual is coming from

it is "Virtual" because it does **not** get stored on the database, it executes a find query with the specified parameters `@prop({ ref: RefClass, foreignField: 'refToName', localField: '_id', justOne: false })`

---

> When creating the model with passed data, I didn't have to add myReference. It worked without, the required did not pose an issue

do you mean `required` is ignored?

---

> I can call ˋ.populate(customer)ˋ which does work of course. But I would like to have it implicitly populated when finding an object of that class, if possible.

not possible without using a mongoose plugin

**Comment by nea** [comment]
Hi @hasezoey 

Thanks for the explanation. Yes, required was ignored, so I was able to store an entity without setting myReference.

Ok, implicit loading that would then be something for e.g. mongoose-autopopulate.


Thanks a lot

**Comment by hasezoey** [comment]
@nea mongoose issue is closed with "working as intended" mongoose only throws an error when saving OR running `.validate()`
