### ISSUE TITLE
Typeguard not working (isDocument)

### ISSUE THREAD

**Issue by Sandroggy** [typegoose/typegoose#675]
Hi !
I got Property 'xxx' does not exist on type 'ObjectId' when using isDocument()

````ts
class Dog {
  @prop()
  public name: string;
}


class Cat {
  @prop({ ref: () => Dog })
  public partner: Ref<Dog>;

  public hasPartner(this: DocumentType<Cat>) {
    this.populate("partner")
    if (isDocument(this.partner)) {
      this.partner.name; // Property 'name' does not exist on type 'ObjectId'
    }
  }
}
````

## Versions

- System: linux
- NodeJS: 17.5.0
- Typescript: 4.5.5

- Compiler / Transpiler: tsc 
- Typegoose(NPM): 9.7.0
- mongoose: 6.2.3

---

**Comment by hasezoey** [comment]
>  I got Property 'xxx' does not exist on type 'ObjectId' when using isDocument()

where does this error come from?:
- runtime
- tsc compile
- IDE Error

**Comment by hasezoey** [comment]
> import { DocumentType, Ref, ReturnModelType } from '@typegoose/typegoose';
> const { prop, modelOptions, getModelForClass, isDocument } = typegoose['default'] || typegoose;

that is a weird way of importing things, like where does the `typegoose` variable come from?

---

cannot reproduce, see [verify675](https://github.com/typegoose/typegoose-testing/tree/verify675) for full repository

---

aside from you using ESM (and me not getting it work ... again), i dont see anything wrong with the code

**Comment by Sandroggy** [comment]
I've also manage to make it work with this https://github.com/Sandroggy/typegoose

But your way is way simpler 🙂
The auto import from vscode doesn't work : `import { DocumentType, getModelForClass, isDocument, prop, Ref } from '@typegoose/typegoose';`
I don't know if it should be concidered a bug but i think it's intended to work this way ?

So this throw an error
```
import { isDocument } from '@typegoose/typegoose';
...
isDocument(cat);
```
But not this
```
import typegoose from '@typegoose/typegoose';
...
typegoose.isDocument(cat);
```

**Comment by hasezoey** [comment]
>  I don't know if it should be concidered a bug but i think it's intended to work this way ?

this is because typegoose is currently a CJS (CommonJS) package, and you are using ESM (EcmaScriptModule), which are "incompatible", see #214 for more

> But not this

yes, i also encountered this in my testing, see #214

**Comment by Sandroggy** [comment]
> this is because typegoose is currently a CJS (CommonJS) package

My solution should work to have both commonjs and ESM export (juste by changing 'module' in tsconfig) if it is of any help (https://github.com/Sandroggy/typegoose)

Thank a lot for your help and time !

**Comment by hasezoey** [comment]
> My solution should work to have both commonjs and ESM export (juste by changing 'module' in tsconfig) if it is of any help (https://github.com/Sandroggy/typegoose)

see #214, especially https://github.com/typegoose/typegoose/issues/214#issuecomment-1057984132, if you have any knowledge about this, then i would be happy add ESM to typegoose
