### ISSUE TITLE
No type for "this" in "findOneAndUpdate" post hook

### ISSUE THREAD

**Issue by Vista1nik** [typegoose/typegoose#694]
## Versions

- System: linux / macos
- NodeJS: 17.7.2
- Typescript: 4.4.4

- Compiler / Transpiler: ts-node
- Typegoose(NPM): 9.2.0
- mongoose: 6.0.12 
- mongodb: 5.0.7

## What is the Problem?

There is no type for "this" in "findOneAndUpdate" post hook and compiler throws error.
According to console.log executed on "this" with ts-ignore enabled, type of "this" is [mongoose Query](https://mongoosejs.com/docs/api.html#Query)

On pre hook "this" is defined properly.

## Code Example

https://codesandbox.io/s/typegoose-hook-bug-8oxyc8
```ts
import { connect } from "mongoose";
import { prop, getModelForClass, post } from "@typegoose/typegoose";

(async () => {
  try {
    // Insert here your own MognoDB Connection string
    // For this reproduction I use free database from MongoDB Atlas
    await connect("insert here mongodb connection string");

    @post<KittenClass>("findOneAndUpdate", function (kitten, next) {
      // "this" does not has proper defined types, but actually is "Query" object from Mongoose
      //@ts-ignore
      console.log(this);
    })
    class KittenClass {
      @prop()
      public name!: string;

      @prop()
      public age!: number;
    }

    const KittenModel = getModelForClass(KittenClass);

    // Get existing kitten
    const existingKitten = await KittenModel.findOne({
      name: "Tom"
    });

    if (existingKitten) {
      await KittenModel.findOneAndDelete({
        name: "Tom"
      });
    }

    const newKitten = new KittenModel({
      name: "Tom",
      age: 1
    });

    await newKitten.save();

    // Update for triggering broken hook
    await KittenModel.findOneAndUpdate(
      {
        name: "Tom"
      },
      {
        age: 2
      }
    );
  } catch (e) {
    console.log(e);
  }
})();
```

## Do you know *why* it happens?

*no*

---

I discovered this bug when tried to execute specific actions when certain fields of document is updated, maybe usage of "this" in post hook is not intended by mongoose creators.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/16061243/164333417-20320ee8-2aed-490e-9a1c-2577066150da.png">

**Comment by hasezoey** [comment]
> I discovered this bug when tried to execute specific actions when certain fields of document is updated, maybe usage of "this" in post hook is not intended by mongoose creators.

no, currently typegoose uses its own custom types for pre/post hooks, so this is entirely on typegoose

---

thanks for reporting, will be fixed soon
