### ISSUE TITLE
IModelOptions in getDiscriminatorModelForClass similar to getModelForClass

### ISSUE THREAD

**Issue by hnviradiya** [typegoose/typegoose#713]
## Describe what you need | want

`getModelForClass` function is having `IModelOptions` as second parameter, but `getDiscriminatorModelForClass` is not having such options.

## Do you have already an idea for the implementation?

Not sure if we can re use similar interface for `getModelForClass`  in `getDiscriminatorModelForClass`

**Comment by hasezoey** [comment]
I have added support for this with 1c7460e9c20821cb007a709ab25320904dac72d6 (9.9.0), but i currently dont really have a use-case where this would actually be required, could you maybe test if this is correctly working?

**Comment by hnviradiya** [comment]
That works perfectly fine. Typegoose has been all of my research conclusion on how one perfectly typed (that is also optionally typed and so flexible) ORM should be. Thanks a lot for such a wonderful framework @hasezoey.

**Comment by hasezoey** [comment]
Note for next-time: when the issue is mentioned through a commit (and has the prefix `fixes` or `closes`) and a version is released on the master branch it will close this issue automatically - no need to manually close it before then
