### ISSUE TITLE
Populate and private functions in model class

### ISSUE THREAD

**Issue by malins** [typegoose/typegoose#717]
Hello,

I have private functions in my model classes, and when using populate(...) as port of a query, the type of the returned objects are not assignable to the model class, because they miss the private functions.

Example:

```
const books = await BookModel.find({
  topic: 'engineering'
}).populate('authors').exec();
```

Type of `books` is now:

`Omit<mongoose.Document<string, BeAnObject, any> & Book & IObjectWithTypegooseFunction & {_id: string}, never>[]`

When assigning one of these obejcts to Book (my model class), TypeScript complains about missing private methods.

`... is missing the following properties from type 'Book': somePrivateMethod_`

When not using populate(), everything works as expected.

I' using TypeScript 4.7.3, Typegoose 9.9.0 and Mongoose 6.3.5.

Thank you,
Manuel

**Comment by hasezoey** [comment]
i dont quite understand your issue, could you provide more code and where the error exactly is happening and what your class looks like?

PS: you cannot (or at least should not) assign anything mongoose returns to the plain class type, use the wrapper `DocumentType<Class>`for documents (eg what `.find().orFail()` returns) or `ReturnModelType<typeof Class>` for the model type

**Comment by malins** [comment]
Hello,

it's also not assignable to `DocumentType<Book>`. Once I change all private functions to public ones in my model class, everything works.

```
class Book {

    @prop()
    public _id: string;

    @prop()
    public topic: string;

    @prop({ref: () => Author, type: () => String})
    public authors: Ref<Author, string>[];
    
    private somePrivateMethod_() {
        // Do something private
    }
}
```

**Comment by hasezoey** [comment]
did you also already try doing the `populate` call on a separate line (wont really affect performance from what i know, because all populate calls are their own query), like:

```ts
const books = await BookModel.find({
  topic: 'engineering'
}).exec();
await books.populate('authors');
```

**Comment by malins** [comment]
I'm doing a populate on each returned book now as a workaround. Your sample doesn't work because there is no populate() available on the array itself.

**Comment by hasezoey** [comment]
> Your sample doesn't work because there is no populate() available on the array itself.

right, forgot it was `find` and not `findOne`

> I'm doing a populate on each returned book now as a workaround.

i am assuming you mean loop over the array and calling `populate`? if this does work correctly then it seems like a problem with the populate types, maybe consider opening a issue in mongoose

btw what is the return type set to be of your functions?
