### ISSUE TITLE
Type-safety is broken on create/update/remove and more 

### ISSUE THREAD

**Issue by akanoce** [typegoose/typegoose#719]
## Versions

- System: Dockerized nodejs
- NodeJS: 16.15.1 (tried even 18)
- Typescript: 4.7.3

- Typegoose(NPM): 9.9.0 (tried also to downgrade)
- mongoose: 6.3.5 (tried also to downgrade)

**was using transpileOnly with ts-node-dev, right now with nodemon -r**
## What is the Problem?

I've been using typegoose since a while and until a few week ago, everything had always worked fine. 
Right now, in every my project using typegoose, it looks like type-safety is broken.
To be specific, the types are correctly inferred from the model (and so the results from find for ex.), but the type-safety of update/create/delete methods are literally broken. 
What i mean, is that i am able to create or update an empty document  even if the model is correctly defined.
This was not happening before, as i was receiving errors immediately if i were performing a query with the wrong types and/or were creating a document with non-valid keys.

The issue occurs even during build time, where despite having some wrong queries the build pass with no issues.
 

### Model declaration 

```ts
import { modelOptions, prop, Severity, pre, DocumentType, getModelForClass, Ref } from "@typegoose/typegoose";
import { User } from "model/user";

@pre<SamlAuthRequests>("save", async function () {
    return;
})
@modelOptions({
    schemaOptions: {
        timestamps: true,
        collection: 'saml.auth.requests'
    },
    options: {
        allowMixed: Severity.ALLOW
    }
})
export class SamlAuthRequests {
    @prop({ required: true })
    authCode!: string

    @prop({ required: false, default: true })
    userAllowed?: boolean

    @prop({ required: false })
    errorMessage?: string

    @prop({ ref: () => User, required: false })
    user_id?: Ref<User>

}

const SamlAuthRequestsModel = getModelForClass(SamlAuthRequests)

export default SamlAuthRequestsModel
```

### Model usage 
```ts
await SamlAuthRequestsModel.updateOne({}, { lorem: 'ipsum' })
await SamlAuthRequestsModel.create({ lorem: 'ipsum' })
await SamlAuthRequestsModel.create()
await SamlAuthRequestsModel.create({})
// All of this works, despite it shouldn't. 
// When i started using typegoose, i received errors by doing something like this. 
// If i perform these calls the documents are inserted in the collection succesfully
```

Thanks in advance for your time, hope there is a solution to this because it's not possible to write correct code without this type-safety check.

**Comment by hasezoey** [comment]
>  This was not happening before, as i was receiving errors immediately if i were performing a query with the wrong types and/or were creating a document with non-valid keys.

this is not a issue with typegoose from what i can tell, but with the types mongoose now provides.

currently mongoose allows any (even non-existent) keys in the `create` / `new` without error and only works as a suggestion, the only workaround currently is to do a `as Class` (if it wants function, they will have to be removed)

> (tried also to downgrade)

to which versions were you trying to downgrade to?

**Comment by akanoce** [comment]
Thanks so much for the tip. I was unsure it was related to typegoose but i did not find much informations about.
The strange thing is that it does neither throw any error at runtime.
I tried to downgrade to typegoose@9.5.0 and mongoose@6.1.3 with no luck.
Do you remember if this was working once? I remember for sure it was throwing me errors at real-time up to some weeks ago.

**Comment by akanoce** [comment]
> > This was not happening before, as i was receiving errors immediately if i were performing a query with the wrong types and/or were creating a document with non-valid keys.
> 
> this is not a issue with typegoose from what i can tell, but with the types mongoose now provides.
> 
> currently mongoose allows any (even non-existent) keys in the `create` / `new` without error and only works as a suggestion, the only workaround currently is to do a `as Class` (if it wants function, they will have to be removed)
> 
> > (tried also to downgrade)
> 
> to which versions were you trying to downgrade to?
Thanks so much for the tip. I was unsure it was related to typegoose but i did not find much informations about.
The strange thing is that it does neither throw any error at runtime.
I tried to downgrade to typegoose@9.5.0 and mongoose@6.1.3 with no luck.
Do you remember if this was working once? I remember for sure it was throwing me errors at real-time up to some weeks ago.

**Comment by hasezoey** [comment]
> Anyway, isn't it possible for typegoose to increase mongoose type-safety in functions?

this is something that typegoose explicitly does not do, because patching types can get really tricky fast and with updates to the original types may become with mongoose's structure invalid in just patch updates

>  The strange thing is that it does neither throw any error at runtime.

mongoose will not error at runtime at unknown properties, but depending on if [`strict`](https://mongoosejs.com/docs/guide.html#strict) (enabled by default) is enabled or not, those keys will be saved to the database or just ignored

>  Do you remember if this was working once? I remember for sure it was throwing me errors at real-time up to some weeks ago.

it was never throwing errors on unknown keys in the mongoose native types, but in the old types (`@types/mongoose`) they were throwing errors ... sometimes, but that package is now obsolete and does not work with higher versions of mongoose

Note: if i remember correctly, mongoose has native types since ~5.11 (but they were kinda broken and only became functional at ~5.13)

>  I tried to downgrade to typegoose@9.5.0 and mongoose@6.1.3 with no luck.

see [Mongoose Compatibility](https://typegoose.github.io/typegoose/docs/guides/mongoose-compatibility) for typegoose-mongoose version relationship

**Comment by hasezoey** [comment]
> Another way of doing it would be to create an interface

this would kinda defeat the purpose of typegoose

> So is there any workaround for this? It kinda defeats the purpose of typescript if there isn't any kind of type-checking when creating the model...

this is kinda how mongoose works in runtime so the types only try to show that, aside from that it should be opened as a issue in mongoose (if there is none)

**Comment by AestasLonewolf** [comment]
> > Another way of doing it would be to create an interface
> 
> this would kinda defeat the purpose of typegoose

Yeah, ideally it would work and provide type-checking without providing more stuff than needed, but it seems like there isn't much else I can do until mongoose fixes this
