### ISSUE TITLE
refers to a value, but is being used as a type here for Ref

### ISSUE THREAD

**Issue by rained23** [typegoose/typegoose#72]
Hi

I have the following models parent-child relationship

```ts
class Kitten {
  @prop()
  name?: string;
}

const KittenModel = getModelForClass(Kitten);

export default KittenModel;
```

```ts
import Kitten from './Kitten';

class Person {
  @prop()
  name?: string;

  @arrayProp({ itemsRef: Kitten})
  kittens?: Ref<Kitten>[];
}

const PersonModel = getModelForClass(Person);
export default PersonModel;
```

I receive an error `'Kitten' refers to a value, but is being used as a type here`.
The error gone only if I export the Class not Model.

To remove the red line error, I can export the `Kitten` class instead of model, but this will need me to `getModelForClass(Kitten)` if I want to use the model, or probably I missed the important documentation in 6.0

**Comment by WessCoby** [comment]
try this:
```js
@arrayProp({ itemsRef: "Kitten" })
kittens?: Ref<Kitten>[];
```

**Comment by rained23** [comment]
@WessCoby I tried it as string but still same.

**Comment by hasezoey** [comment]
probably `import Kitten from './Kitten';` is wrong when you dont default-export it, try `import { Kitten } from './Kitten';`

otherwise, please give the output of the following (replace the code from the starting line)
```ts
const KittenModel = getModelForClass(Kitten);
console.log(KittenModel.modelName);
```

**Comment by rained23** [comment]
I am now confused on which one should I export default, the Kitten class or the KittenModel from `getModelFromClass`, or do I need to export both of it the `KittenModel` and `Kitten` class.

The output as you asked is `Kitten`

**Comment by hasezoey** [comment]
>  or do I need to export both of it the KittenModel and Kitten class.

you need to export the model for making and retrieving documents, and the class for types

**Comment by hasezoey** [comment]
> The output as you asked is Kitten

so, this shouldnt happen then when using the reference as a string, did you already look at the documentation|guides for references? ( https://typegoose.github.io/typegoose/guides/advanced/reference-other-classes/ )

**Comment by rained23** [comment]
Yes, I followed the documentation on that, but I only export my KittenModel, not the class.

I change my Kitten into the following

```
export class Kitten {
  @prop()
  name?: string;
}

const KittenModel = getModelForClass(Kitten);

export default KittenModel;
```
and import the it as this `import { Kitten } from './Kitten'` , now the error on `Ref<Kitten>[]` fixed.

**Comment by hasezoey** [comment]
i dont use default imports, so i dont know if it is true:
so you default exported the model, and did not export the class at all, right?
then when doing `import Kitten from './Kitten';` you imported the model as `Kitten`, do i understand that right?, when yes, you did wrong, because the types only accept the Class, and not the Model

**Comment by rained23** [comment]
Yes you are correct, at first I thought like the Model do the magic for typegoose, but now I realize the class is kinda like the Interface if you didnt use typegoose for mongoose.

**Comment by hasezoey** [comment]
because it is solved now, i will close this
