### ISSUE TITLE
Elasticsearch routing pass at runtime using Typegoose with Mongoosastic

### ISSUE THREAD

**Issue by hnviradiya** [typegoose/typegoose#724]
I am trying to create a Typegoose model with Mongoosastic as a plugin to it.

My current code is as below where I have passed routing as 'some_key' as a hard-coded string, but I need to pass it runtime dynamically.

```typescript
import mongoosastic from 'mongoosastic'

@plugin(mongoosastic, { routing: 'some_key' })
export class DocumentFieldTextValue extends ModelBase {
  @prop()
  fieldId: number;

  @prop()
  documentId: number;

  @prop()
  value: string;

  @prop()
  document: Ref<Document>;
}
```

I need to provide `routing` to index at run time. 

How/Where can we provide `routing` to Mongoosastic using Typegoose? 

I am unable to find it from Mongoosastic documentation. Or maybe the question is more related to Typescript on how to pass decorator values at runtime?

I have posted the same on StackOverflow and trying to find some way around this but am unable to figure.
https://stackoverflow.com/questions/72733698/elasticsearch-routing-pass-at-runtime-using-typegoose-with-mongoosastic

**Comment by hasezoey** [comment]
> but I need to pass it runtime dynamically.

the `@plugin` decorator is not much different than the `schema.plugin` call, so the only way to actually defer it would be if you could reconfigure at runtime or have it as a generator / deferred function, but i can not find any documentation on the option `routing`

**Comment by hnviradiya** [comment]
So how do we do `schema.plugin` call in typegoose at runtime? I was trying with mongoosastic and that routing option was suggested by typescript definition. May be I can test with that. I couldn't know the way to apply plugin at runtime using `schema.plugin`

**Comment by hasezoey** [comment]
> So how do we do schema.plugin call in typegoose at runtime?

i dont really know what you are trying to achieve, so could you maybe give me a pure mongoose example of how you would do it?

**Comment by hasezoey** [comment]
Update: if i understand to the types for `routing` correctly, it is a function instead of a plain string, which gives one argument `Document` and expects `any` back

https://github.com/mongoosastic/mongoosastic/blob/49ff5ba9daf6704f8ac7adcc83392c8033d33687/lib/types/index.ts#L28-L30
https://github.com/mongoosastic/mongoosastic/blob/49ff5ba9daf6704f8ac7adcc83392c8033d33687/lib/types/index.ts#L113

**Comment by hnviradiya** [comment]
> > So how do we do schema.plugin call in typegoose at runtime?
> 
> i dont really know what you are trying to achieve, so could you maybe give me a pure mongoose example of how you would do it?

Currently, I am indexing as below. So I am doing this at every place after that MongoDB (using typegoose) operation. So I want to do this using mongoosastic so that I don't have to write this elasticsearch code at every place.

I have a multi-tenant application. so for elastic search, I have divided routing per tenant (`projectId.toString()` below, project id consider as tenantid)

```typescript
import { Client } from '@elastic/elasticsearch';

 const client = new Client({
            node: Config.elasticsearchConnectionString,
          });

          await client.index({
            id: fieldId.toString(),
            index: 'project_documents_textfielddata',
            body: {
              FieldId: fieldId,
              DocumentId: documentId,
              Value: fieldData.fieldHTMLText,
            },
            routing: projectId.toString(),
          });
```

**Comment by hnviradiya** [comment]
> Update: if i understand to the types for `routing` correctly, it is a function instead of a plain string, which gives one argument `Document` and expects `any` back
> 
> https://github.com/mongoosastic/mongoosastic/blob/49ff5ba9daf6704f8ac7adcc83392c8033d33687/lib/types/index.ts#L28-L30 https://github.com/mongoosastic/mongoosastic/blob/49ff5ba9daf6704f8ac7adcc83392c8033d33687/lib/types/index.ts#L113
> 
> like you would have to define `routing: (doc) => { /* do something here */}`, but i have no clue what it expects back, because the expected return type is `any`

That makes sense. How doc can be used as routing as in plain elasticsearch client, it expects string.

**Comment by hnviradiya** [comment]
[As per mongoosastic code](https://github.com/mongoosastic/mongoosastic/issues/604#issuecomment-1167547712), it seems I will have to take one field in typegoose without @prop in it. And that same field also not indexed without property `es_indexed` in mongoosastic. This way I should be able to achieve routing the way they have provided option. I will check this option once I get time from my day job.

**Comment by hnviradiya** [comment]
Seems mongoosastic is not considering the fields which are not present in schema even if we provide that field. Looks like I will have to maintain one field in every model which is for the purpose of routing in mongoosastic anf that will stay in every mongodb document as well.

**Comment by hnviradiya** [comment]
Now how do we convert Typegoose model to Mongoosastic model?

I am using Typegoose's `getModelForClass` and getting following error.

`'ReturnModelType<typeof DocumentFieldTextValue, BeAnObject>' is not assignable to parameter of type 'MongoosasticModel<MongoosasticDocument<any>>'`

Following is what works with mongoose. So don't know how following maps to typegoose.
`mongoose.model<ITask, MongoosasticModel<ITask>>('Task', TaskSchema)`

**Comment by hnviradiya** [comment]
Ok. Seems I do not require additional typings of mongo for now. To confirm, there is no way we can pass this plugin thing at runtime right?

**Comment by hasezoey** [comment]
> To confirm, there is no way we can pass this plugin thing at runtime right?

i dont quite understand your question, though i will try some things:
- plugins in mongoose can only applied to the schema before compiling it into a model
- Mongoosastic from what i know for option `routing` supports being deferred (being a function), though i dont know when it is getting called or how often

**Comment by hnviradiya** [comment]
The thing is I also need to pass other parameters as well. One example is the index name. The following StackOverflow conversation, suggests using one single index for all the collections. By default, it takes a model name as an index name.

https://stackoverflow.com/a/72846167/9263418

If I use pure mongoose then it allows me to pass that plugin at runtime, so I can pass tenantid as index name as well. So all collections will stay in one index and I don't have to make "joins" among them.

**Comment by hasezoey** [comment]
> If I use pure mongoose then it allows me to pass that plugin at runtime, so I can pass tenantid as index name as well. So all collections will stay in one index and I don't have to make "joins" among them.

sorry, but i still dont understand what you can do in mongoose that you cant do in typegoose

Note: i have never used elasticsearch in any way, so i dont know what is required or what is wanted to be set where

**Comment by hnviradiya** [comment]
e.g. I can pass `tenantId` as following in mongoose. How do I do this in Typegoose?

```typescript
var UserSchema = new Schema({
    name: String,
    email: String,
    city: String
})

const tenantId = req.body.tenantId;

UserSchema.plugin(mongoosastic, {
    index: tenantId
})

const User = mongoose.model<IUser, MongoosasticModel<IUser>>('User', UserSchema)
// I will use above model for save, find etc.
```
How do I pass it in following typegoose decorator?
```typescript
@plugin(mongoosastic, {
  esClient: Config.esClient,
  routing: (doc: DocumentFieldTextValue) => {
    return doc.projectId.toString();
  },
})
```

**Comment by hasezoey** [comment]
> How do I pass it in following typegoose plugin decorator?

the same as in the normal mongoose `.plugin` call, typegoose's `@plugin` decorator works like the mongoose `.plugin` function, where the first parameter is the plugin function / object itself and the second being the plugin options, only difference in typegoose is that typegoose automatically infers plugin's options if available for types

your following code:
```js
var UserSchema = new Schema({
    name: String,
    email: String,
    city: String
})

const tenantId = req.body.tenantId;

UserSchema.plugin(mongoosastic, {
    index: tenantId
})

const User = mongoose.model<IUser, MongoosasticModel<IUser>>('User', UserSchema)
// I will use above model for save, find etc.
```

would be equal to
```ts
@plugin(mongoosastic, { index: req.body.tenantId })
// the following is to set it to model name "User" and collection "users", like in original example
@modelOptions({ options: { customName: 'User' } })
class UserClass {
  @prop()
  public name?: string;

  @prop()
  public email?: string;

  @prop()
  public city?: string;
}

// you might need to overwrite the type of the returned model to your plugin's
const User = getModelForClass(UserClass);
```

**Comment by hnviradiya** [comment]
But decorators are not allowed inside the function. See below. `req.body.tenantId` is something that will come as function params. But it will complain as `Modifiers cannot appear here.`

![image](https://user-images.githubusercontent.com/12680915/177149112-b8ef3efc-287b-4653-8178-3a94a29b4072.png)

**Comment by hasezoey** [comment]
> But decorators are not allowed inside the function

from what i can tell, this is not mentioned before / in the example code.
aside from that, this always creates a new schema & model for each request.

but if you need it in a function, then yes, you cannot do that with typegoose, maybe try to ask the maintainer of `mongoosastic` to make the `index` option a generator / deferred function (if you know how it is currently implemented, you could workaround it with a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) or [`Object.defineProperty` with `get`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty))

**Comment by hasezoey** [comment]
> will that not be possible to pass this plugin in getModelForClass somehow as a parameter?

no i will not make that change, though you can manually modify the schema, see [Manual Schema Modification](https://typegoose.github.io/typegoose/docs/guides/advanced/manual-schema-modification)

**Comment by hnviradiya** [comment]
Oh ok. Great. I will try that. Seems that will solve my problem.
