### ISSUE TITLE
mongoose peer deps 6.3.5

### ISSUE THREAD

**Issue by fasenderos** [typegoose/typegoose#733]
I think you forgot to update also the mongoose peer deps [here ](https://github.com/typegoose/typegoose/commit/15588515b22cc8fd1733931f0ef624319063502e)

**Comment by hasezoey** [comment]
i forgot to do it again, i always forget yarn upgrades the dependency but not the peer-dependency, thanks for reporting (9.10.1 will be up in a few minutes)
