### ISSUE TITLE
Allow populate on getters

### ISSUE THREAD

**Issue by j-waters** [typegoose/typegoose#739]
## Describe what you need | want

Not sure if this is a bug, if I'm not doing it right or if it's impossible but I'd love to be able to call populate on virtuls.

As an example, I'm using this pattern to allow a user to override the result of an automated system:

```typescript
class Test {
  @prop({
    ref: () => Entity,
  })
  predictedEntity?: Ref<Entity>;

  @prop({
    ref: () => Entity,
  })
  manualEntity?: Ref<Entity>;

  get entity(): Ref<Entity> | undefined {
    return this.manualEntity ?? this.predictedEntity;
  }
}
```

Things fail when I try to do `test.populate('entity')`, I get the error: `If you are populating a virtual, you must set the localField and foreignField options`. This makes sense I suppose since mongoose doesn't know how to populate the field.

I also can't add a prop decorator to give it this information: ` Virtual path "entity" conflicts with a real path in the schema`

This makes the above pattern a lot less useful!

## Do you have already an idea for the implementation?

*no* - but if you have any ideas I'd be happy to work on a PR

**Comment by hasezoey** [comment]
currently typegoose does not handle get/set (ES6 class keywords) and instance and static methods anymore, these are directly handled by mongoose (via `sch.loadClass`), and they also dont take any options anyways (that i know of)

are you maybe searching for [Virtual Populate](https://typegoose.github.io/typegoose/docs/api/virtuals/#virtual-populate)?

**Comment by j-waters** [comment]
Ah I missed the dynamic bit of virtual populate - very useful!

Got it working now thank you very much, leaving an example here for posterity:

```typescript
  @prop({
    ref: () => Entity,
    foreignField: '_id',
    localField: (doc: DocumentType<Test>) => {
      if (doc.manualEntity) {
        return 'manualEntity';
      } else {
        return 'predictedEntity';
      }
    },
    justOne: true,
  })
  entity: Ref<Entity>;
```
