### ISSUE TITLE
move repository codebase to @nrwl/nx

### ISSUE THREAD

**Issue by nhhockeyplayer** [typegoose/typegoose#746]
@nrwl/nx is now a staple in the field for developing anything shared beit libraries, apps, servers with comprehensive ESM/APF projection support in an elite automated fashion.

https://github.com/typegoose/typegoose was prototyped built on the @nrwl/nx platform 
https://github.com/smolinari/nestjs-typegoose was also prototyped built on the @nrwl/nx platform 

repositories for both are below for reference so this can occur coming out of ticket https://github.com/typegoose/typegoose/issues/214

Nx Platform prototype repositories
https://github.com/nhhockeyplayer/nx-typegoose
https://github.com/nhhockeyplayer/nx-nestjs-typegoose

this will secure eliminate alot of the roll your own baggage that accommodates npm/webpack grade libraries and reduce the footprint of the repository by a huge factor but moreso will standardize typegoose and its the future for the immediate and longterm

**Comment by smolinari** [comment]
Um, nice you think Nx is a way to go, but using a monorepo for either of these libraries is overkill and adds very little advantage IMHO. If anything, I like Rush better than Nx. So, if I had to choose, I'd choose Rush over Nx. But, like I said, a monorepo just for a library is overkill. 

Oh, and my repo for nestjs-typegoose that is being kept up-to-date is in this one: https://github.com/m8a-io/m8a 

...which is a Rush monorepo. :grin:  

You can get the latest version here: https://www.npmjs.com/package/@m8a/nestjs-typegoose

...which reminds me, I need to upgrade the package. 

Scott

**Comment by hasezoey** [comment]
i agree with @smolinari, and i will also close this issue as "wont fix" because monorepo is overkill for this project and not everyone likes how nx / angular do stuff, so i will stay with the current model

**Comment by nhhockeyplayer** [comment]
Overkill can be argued yes... elimination of the footprint in exchange for standard precision automation can also.
But Im fine either way.
Thanks for the attention.

Nice to know where the actual repo is appreciate that.

**Comment by nhhockeyplayer** [comment]
Thanks Scott... just to firm up
when you mean upgrade... do you mean complying with ESM? I hope so. Any head sup is appreciated.
I tried to do your project for ESM and hit a few hurdles with exports in package.json
looking forward to your best

**Comment by smolinari** [comment]
@nhhockeyplayer -  Upgrade means getting the dependencies up-to-date. 

Scott

**Comment by nhhockeyplayer** [comment]
> @nhhockeyplayer - Upgrade means getting the dependencies up-to-date.
> 
> Scott

any chance of releasing that ESM compliant?
