### ISSUE TITLE
Discriminator on Map values

### ISSUE THREAD

**Issue by malins** [typegoose/typegoose#749]
Hello,

is there a way to have discriminators on Map values?

```
@prop({
    type: Map,
    of: Vehicle,
    discriminators: () => [Car, Truck, Tractor]
})
public vehicles: Map<string, Vehicle> = new Map();
```

I'm getting the following error:

`Path "Model.vehicles" does not have a function called "discriminator"! (Nested Discriminator cannot be applied) [E031]`

Thank you,
Manuel

**Comment by hasezoey** [comment]
Discriminators on Map are currently not possible, see https://github.com/Automattic/mongoose/issues/8361

The error basically says that the function `.discriminator` does not exist for this schema-type (in this case `Map`), which in turn means that no discriminators can be applied
