### ISSUE TITLE
Generic class model

### ISSUE THREAD

**Issue by sakulstra** [typegoose/typegoose#75]
## Versions

- NodeJS: 10.0.0
- Typegoose(NPM): 6.0.1
- mongoose: 5.7.4
- mongodb: 3.3.2

## Code Example

I'm trying to implement a user model, where there's a different profile subschema based on the role field. The idea was to define role as a discriminator and implement different profile classes for each of them.

```ts
export class DefaultProfile {
  @prop()
  firstName?: string;
}

export class AdminProfile {
  @prop()
  title?: string;
}

@modelOptions({
  schemaOptions: {
    collection: "users",
    discriminatorKey: "role",
    timestamps: true,
  },
})
export class GenericUserSchema<T extends DefaultProfile = DefaultProfile> {
  @prop({ required: true, enum: USER_ROLE })
  role?: USER_ROLE;

  @prop()
  profile?: T;
}

export class UserSchema extends GenericUserSchema<DefaultProfile> {}

export default getModelForClass(UserSchema);

it("should contain additional fields inside the mongoose model", async () => {
    expect(User.schema.obj.profile.type.obj.firstName).toBeTruthy();
});
```

Appearently `getModelForClass(UserSchema)` returns a model which has profile declared as `Mixed` instead of the explicit Model I defined above.

## Do you know *why* it happenes?

Not sure if i'm perhaps misusing ts :disappointed: or if there's a bug in typegoose.

**Comment by B-Stefan** [comment]
@sakulstra  Try to use 

```
  @prop({type: DefaultProfile})
```

**Comment by sakulstra** [comment]
@B-Stefan, doesn't seem to work as well :thinking: 

When I statically set it to:
```ts
@prop()
  profile?: DefaultProfile;
```

it works, but then Admin.profile will not accept another profile property, but use the DefaultProfile instead :(
```ts
export class AdminSchema extends GenericUserSchema {
  @prop()
  profile: AdminProfile;
}

export default getDiscriminatorModelForClass(User, AdminSchema, USER_ROLE.ADMIN);

it("should contain additional fields inside the mongoose model", async () => {
    /**
     * To verify the model is correctly extended we're checking if the getter for salary exists
     */
    expect(User.schema.obj.profile.type.obj.firstName).toBeTruthy(); // <- works now
    expect(Admin.schema.obj.profile.type.obj.firstName).toBeFalsy(); // it's true instead
    expect(Admin.schema.obj.profile.type.obj.lastName).toBeTruthy(); // it's false instead
  });
```

**Comment by B-Stefan** [comment]
@sakulstra  I think you are looking for the discriminator feature (https://mongoosejs.com/docs/discriminators.html). Unfortunately, typegoose doesn't support nested discriminators.  

I've tried to integrate this feature in typgoose but it will take some time and testing. If your class structure is based on Inheritance and uses generics I would recommend using mongoose without typegoose.

**Comment by sakulstra** [comment]
> Unfortunately, typegoose doesn't support nested discriminators.
Reading the docs i'am not sure if we actually use a *nested* discriminators?
```js
{
  role: 'ADMIN' | 'USER'
  profile: BasedOnRole
}
```

> I've tried to integrate this feature in typgoose but it will take some time and testing. If your class structure is based on Inheritance and uses generics I would recommend using mongoose without typegoose.

Typegoose is such an awesome package that we won't seriously consider dropping it just because this one thing doesn't work :). We'd be glad to test/help with any canary of this though.

**Comment by hasezoey** [comment]
> mongoose: 5.7.6

are you sure? because 5.7.5 just released one hour ago

---

> export default getModelForClass(UserSchema);

is it imported as `User` again in the `it` test?

---

i dont use discriminators so i might not be a big help, but there are some tests for it:
- https://github.com/typegoose/typegoose/blob/master/test/models/discriminators.ts (normal discriminators with default key)
- https://github.com/typegoose/typegoose/blob/master/test/models/inheritanceClass.ts ("advanced" discriminators with custom key)

**Comment by sakulstra** [comment]
> are you sure? because 5.7.5 just released one hour ago

No you're right, we're on 5.7.4, I just mixed it up with the dependency version from the dependency below in package.json :( shouldn't matter to much though.

> is it imported as User again in the it test?

yes it is :+1:

Thanks for pointing me to the test. I'll try to look into the current implementation/will open a pr with at least a failing test to verify it doesn't work properly atm.
