### ISSUE TITLE
对象模型映射失败   版本 "@typegoose/typegoose": "^9.11.0",   "mongoose": "^6.5.2",

### ISSUE THREAD

**Issue by ooijopk** [typegoose/typegoose#750]
![%{QQY GU)4N (`{J6RMFHVY](https://user-images.githubusercontent.com/73647670/184111384-3ea10b5c-f983-4a27-9ce9-f25f70461384.png)
创建一个这样的模型，获取数据获取不到，完全按照官方文档来的

**Comment by ooijopk** [comment]
获取数据获取失败

**Comment by hasezoey** [comment]
Please keep every issue here in english

this issue will be closed if not changed

**Comment by ooijopk** [comment]
Create such a model and obtain the data. The data acquisition fails. It is completely based on the official documents

**Comment by ooijopk** [comment]
Create such a model and obtain the data. The data acquisition fails. It is completely based on the official documents

**Comment by hasezoey** [comment]
> Create such a model and obtain the data. The data acquisition fails. It is completely based on the official documents

in what way does it fail? because i dont see any problems with the provided code-screenshot, did you follow [Quick Start Guide](https://typegoose.github.io/typegoose/docs/guides/quick-start-guide)?

**Comment by ooijopk** [comment]
No error was reported, but the corresponding data could not be obtained

**Comment by hasezoey** [comment]
> but the corresponding data could not be obtained

please be more specific and / or provide data output and what would be expected

**Comment by ooijopk** [comment]
expect  1：
![image](https://user-images.githubusercontent.com/73647670/184113636-311588ce-c98b-4514-9923-ef1da26a5058.png)
now  2：
![image](https://user-images.githubusercontent.com/73647670/184115079-531e8d31-35f3-4178-8937-90f8f117ccab.png)

The one output is written in another way. I can't get it from the official document

**Comment by hasezoey** [comment]
are those 2 the same document fetched from the database? are they somehow fetched differently, like different a different query?

**Comment by ooijopk** [comment]
1: ![image](https://user-images.githubusercontent.com/73647670/184116331-a6e433d6-f19a-44e6-94a9-beeafe5f2158.png)
2:![image](https://user-images.githubusercontent.com/73647670/184116558-795d1ca7-8deb-43ca-99e5-01305d533828.png)

The same document , different methods,I can't understand why the form of < ref > can't be obtained

**Comment by hasezoey** [comment]
> The same document , different methods,I can't understand why the form of < ref > can't be obtained

the first is a sub-document, meaning it is part of the parent document
the second is a reference to another document (only storing the id), and `.populate()` needs to be called, and by mongoose's behavior it removes the property after a populate, if it cannot find the corresponding document
