### ISSUE TITLE
Find dont return array referece

### ISSUE THREAD

**Issue by chechoreyes** [typegoose/typegoose#765]
Hi!

Y have this:

Models: 

```ts
import {
    prop,
    pre,
    DocumentType,
    ReturnModelType,
    Ref,
} from '@typegoose/typegoose';
import validator from 'validator';
import bcrypt from 'bcrypt';
import { Role } from './Role';

@pre<User>('save', async function () {
    const user = this;
    if (!user.isModified('password')) return;

    const salt = await bcrypt.genSalt(10);
    const hash = await bcrypt.hash(user.password!, salt);
    user.password = hash;
})
export class User {
    @prop({
        type: String,
        required: true,
        lowercase: true,
        trim: true,
        validate: {
            validator: function (v: string) {
                return validator.isEmail(v);
            },
            message: "It's not a valid email",
        },
    })
    public email?: string;

    @prop({ type: String, required: true })
    public username?: string;

    @prop({ ref: () => Role })
    public car?: Ref<Role>[];

    @prop({ type: String, required: true })
    public name?: string;

    @prop({ type: String, required: true })
    public surname?: string;

    @prop({ type: String, required: true, minlength: 6 })
    public password?: string;

    @prop({ type: String })
    public profilePic?: string;

    //Instance method
    public async comparePassword(
        this: DocumentType<User>,
        password: string
    ): Promise<boolean> {
        return await bcrypt.compare(password, this.password!)!;
    }

    // Static method
    public static async encryptPassword(
        this: ReturnModelType<typeof User>,
        password: string
    ) {
        const salt = await bcrypt.genSalt(10);
        const hash = await bcrypt.hash(password!, salt);
        return hash;
    }
}
```

```ts
import { prop, ReturnModelType } from '@typegoose/typegoose';
import { ERoles } from 'shared/enums';

export class Role {
    @prop({
        type: String,
        enum: ERoles,
        unique: true,
        required: true,
    })
    public name?: string;

    static async insertRoles(this: ReturnModelType<typeof Role>) {
        return this.insertMany([
            { name: ERoles.ADMIN },
            { name: ERoles.MANAGER },
            { name: ERoles.SENIOR },
            { name: ERoles.USER },
        ]);
    }

    static async findAllRoles(this: ReturnModelType<typeof Role>) {
        const roles = await this.find();
        return roles;
    }
}
```

I'm using Next and Typegoose:

My api restpoint is:

```ts
        case 'POST':
            try {
                const statusUser = EStatusUser.VERIFIED;
                const newUser = new UserModel({
                    email: email,
                    username: username,
                    name: name,
                    surname: surname,
                    password: password,
                    status: statusUser,
                });

                await newUser.save();

                if (roles.length === 1) {
                    const objectRol = await RoleModel.findOne({
                        name: req.body.roles.toString(),
                    });
                    const roleObjectString = objectRol?.id.toString();

                    await UserModel.findOneAndUpdate(
                        { email: email },
                        { $push: { car: roleObjectString } }
                    );
                } else {
                    roles.forEach(async (rol: string) => {
                        const roleObject = await getRoleID(rol);
                        const roleObjectString = roleObject?.id.toString();

                        await UserModel.findOneAndUpdate(
                            { email: email },
                            { $push: { car: roleObjectString } },
                            { new: true }
                        );
                    });
                }
```

And my GET request is:

```ts
        case 'GET':
            try {
                const users = await UserModel.find();
                console.log('users :>> ', users);
                return res.status(200).json({
                    success: true,
                    message: 'All Users',
                    data: users,
                });
            } catch (error) {
                return res.status(200).json({
                    success: false,
                    message: 'Error in get Users',
                });
            }
```

And my response dont return the array reference de Car (what is the roles reference)

>Version typegoose: 9.10.1

**Comment by hasezoey** [comment]
Please dont ignore the issue template, also this case of question is better asked [in GIthub Discussions](https://github.com/typegoose/typegoose/discussions/categories/q-a), [Stackoverflow](https://stackoverflow.com/questions/tagged/typegoose) or [the Typegoose discord server](https://github.com/typegoose/typegoose#join-our-discord-server)

---

Like @smolinari already said, you will need to use `.populate`, see typegoose's documentation [Reference other Classes](https://typegoose.github.io/typegoose/docs/guides/advanced/reference-other-classes)

**Comment by chechoreyes** [comment]
I did the exercise again:

The data in DB is:

**Comment by chechoreyes** [comment]
I did the exercise again:

And the data in DB is:

![imagen](https://user-images.githubusercontent.com/19411589/195340847-7d4f8a7b-1eeb-4f2d-b483-105071034a91.png)

RoleModel:

```
import { prop, ReturnModelType, getModelForClass } from '@typegoose/typegoose';
import { ERoles } from 'shared/enums';

export class Role {
    @prop({
        type: String,
        enum: ERoles,
        unique: true,
        required: true,
    })
    public name?: string;

    static async insertRoles(this: ReturnModelType<typeof Role>) {
        return this.insertMany([
            { name: ERoles.ADMIN },
            { name: ERoles.MANAGER },
            { name: ERoles.SENIOR },
            { name: ERoles.USER },
        ]);
    }

    static async findAllRoles(this: ReturnModelType<typeof Role>) {
        const roles = await this.find();
        return roles;
    }
}

export const RoleModel = getModelForClass(Role);

UserModel:

```
import { RoleModel } from 'models';
import { UserModel } from 'models/UserModel';
import { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
    req: NextApiRequest,
    res: NextApiResponse
) {
    const { method, body } = req;
    const { email, role } = body;

    switch (method) {
        case 'POST':
            const newUser = await new UserModel({ email: email });

            const newUserSaved = await newUser.save();

            const userID = newUser._id.toString();

            if (role.length === 1) {
                const objectRol = await RoleModel.findOne({
                    name: role.toString(),
                });

            } else {
                role.forEach(async (rol: string) => {
                    const roleObject = await RoleModel.findOne({ name: rol });
                    const roleObjectString = roleObject!._id.toString();

                    await UserModel.findByIdAndUpdate(
                        userID,
                        {
                            $push: { role: roleObjectString },
                        },
                        { new: true }
                    );
                });
            }

            return res.status(200).json({
                success: true,
                message: 'User created successfully',
                data: newUserSaved,
            });

        case 'GET':
            try {
                const allUsers = await UserModel.find().populate('role').exec();

                return res.status(200).json({
                    success: true,
                    message: 'All Users',
                    data: allUsers,
                });
            } catch (error) {
                console.log('error :>> ', error);
            }

        default:
            return res.status(400).json({
                success: false,
                message: 'This method is not supported',
            });
    }
}

With populate included.

And the response is the same :(


```


```

**Comment by hasezoey** [comment]
> And the response is the same :(

could you maybe provide what data you are expecting where and what data you are getting?

also, from what i can tell you are trying to populate path `role` in model `UserModel`, but at least in the provided `User` class, i dont see such a path, only path `car` which is a `Ref` to `Role`
