### ISSUE TITLE
[Question] Ref - How to parse a key and return id?

### ISSUE THREAD

**Issue by vanishdark** [typegoose/typegoose#77]
Hello guys, I'm new with typegoose. 

I'm trying to accomplish this. I have one model SLA that has a priority ref.
Ex:
**SLA model**
```ts
@prop({
    required: [true, 'priority required'],
    unique: false,
    ref: Priority
})
priority!: Ref<Priority>;
```

**Priority Model**
```ts
@prop({
    required: [true, 'id required'],
    unique: true,
    type: Number,
})
id!: number;

@prop({
    required: [true, 'key required'],
    unique: true,
    type: String,
    trim: true,
    uppercase: true
})
key!: string;
```

I wanna input like a key and storage the id instant of the key;

**Input**

```json
{
	"hours": 3,
	"priority": "CRITICAL",
	"impact": 1,
	"urgency": 1
}
```
**Return Fail**
```json
{
	"hours": 3,
	"priority": "CRITICAL",
	"impact": 1,
	"urgency": 1
}
```
**Return expected**
```json
{
	"hours": 3,
	"priority": 1,
	"impact": 1,
	"urgency": 1
}
```
It is possible if so how can i do it?

**Comment by hasezoey** [comment]
> model SLA

what do you mean with `SLA`?

---

and i dont understand what you are trying to accomplish

**Comment by vanishdark** [comment]
SLA is just a name :smile: 

It's like in the input i say priority: "CRITICAL" i wanna set in mongo priority: 1

**Comment by hasezoey** [comment]
> It's like in the input i say priority: "CRITICAL" i wanna set in mongo priority: 1

this wont work out-of-the-box, you need to implement it yourself in validation (/ any hook)

but when you use typescript, you probably dont want to do this inside an model / class, you should use typescript's `enum`

**Comment by vanishdark** [comment]
the values come from the database so I need somehow do this conversion. So this priority is related to priority document.

**Comment by hasezoey** [comment]
like i said, you have to do this yourself, it is not natively supported by mongoose and typegoose

**Comment by vanishdark** [comment]
ok will try and put the result here so if anyone else come to look for same solution.

**Comment by hasezoey** [comment]
the easiest i could image is making a find-hook which will try to lookup an enum if it is an string, and reassigns it as a number

**Comment by vanishdark** [comment]
can you post an example I do not see what you mean with find-hook

**Comment by hasezoey** [comment]
please know that this is very basic and handles not all cases, it is just meant as an example:

```ts
// NodeJS: 12.10.0
// MongoDB: 4.2-bionic (Docker)
import { DocumentType, getModelForClass, post, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@6.0.3
import * as mongoose from "mongoose"; // mongoose@5.7.4
import { isNullOrUndefined } from "util";

enum Prioritys {
    "CRITICAL" = 1,
    "NOT" = 0
}

function assign(doc: DocumentType<User> | number) {
    if (typeof doc === "number") return;

    if (!isNullOrUndefined(doc.priority)) {
        if (doc.priority === "CRITICAL") {
            doc.priority = Prioritys.CRITICAL;
        } else {
            doc.priority = Prioritys.NOT;
        }
    }
}

@post<User>(/^find/mi, (doc) => {
    if (!isNullOrUndefined(doc)) {
        if (Array.isArray(doc)) {
            doc.forEach(assign);
        } else {
            assign(doc);
        }
    }
})
class User {
    @prop()
    public username?: string;

    @prop()
    public priority?: number | string;
}
const UserModel = getModelForClass(User);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify26" });

    const user = await UserModel.create({ username: "user1", priority: "CRITICAL" });
    console.log(user); // expected is "CRITICAL"

    console.log(await UserModel.find({}).exec()); // expected is "1"

    await mongoose.disconnect();
})();
```

**Comment by vanishdark** [comment]
Ok, I got you to know what you mean. Thanks for the example
