### ISSUE TITLE
How do I define Ref for array of objects?

### ISSUE THREAD

**Issue by mad-coder-365** [typegoose/typegoose#774]
Usually when we define a model with ref we do something like 

```
class A {
    @Prop({ref: () => Test})
    testId: Ref<Test>
}
```

I was checking the docs but couldn't find anything on how to do the same with an array of objects like

```
class B {
    @Prop({allowMixed: Severity.ALLOW, ref: () => Test}, PropType.ARRAY)
    tests: {
        testId: Ref<Test>
        pass: boolean
    }[]
}
```

In the above model this ```ref: () => Test``` doesn't work in @Prop()

## Versions

NodeJS: 18.12.0
Typescript: 4.9.3
Typegoose: 9.13.1
mongoose: 6.7.3
mongodb: 6.0.1

**Comment by smolinari** [comment]
Do you want an array of objects? Or, do you want an array of refs?

Scott

**Comment by mad-coder-365** [comment]
I want an array of objects with one of the params being object ID.

```
tests: [{
        testId: Ref<Test>
        pass: boolean
}]
```

I any trying to populate the testId for each object inside an array. I am not sure how to achieve that.

**Comment by smolinari** [comment]
So, you want basically a test collection (with id and pass properties), and in your Class B, you want an array of those tests. Right?

Scott

**Comment by mad-coder-365** [comment]
Consider the following example

I have a Test collection (with properties - name, level)

I have another collection User (with properties - username, pass)

Lastly, I have a UserTest collection (with properties -  userId, tests:(Array of Object){testId, passed}

```
UserTest {
    userId: 123,
    tests: [
        {testId: 999, passed: true},
        {testId: 888, passed: false},
    ]
}
```

I am trying to populate all the testIds with something like

```
UserTest {
    userId: 123,
    tests: [
        {testId: {_id: 999, name: 'Test 1', Level: 'A1'}, passed: true},
        {testId: {_id: 888, name: 'Test 2', Level: 'A2'}, passed: false},
    ]
}
```

**Comment by smolinari** [comment]
Ok. You'll need a class for the object in the array of `tests` property too. 

```ts
class TestResult {
    @Prop({ref: () => Test})
    testId: Ref<Test>
  
    @Prop()
    passed: boolean
}
```

Then your `UserTest` would be:

```ts
class UserTest {
  @Prop()
  userId: number  
  
  @Prop({ type: () => [TestResult] })
  tests: TestResult[]
}
```

Scott

p.s. next time, use either [discussions here](https://github.com/typegoose/typegoose/discussions) or [use the Discord server ](https://discord.gg/EtnCwWYb) for questions. The issues should only be for bugs or suggestions for improvement. Thanks.

**Comment by mad-coder-365** [comment]
Thanks
