### ISSUE TITLE
Multiple Class Inheritence wrong Documentation

### ISSUE THREAD

**Issue by JakeAi** [typegoose/typegoose#78]
According to [https://typegoose.github.io/typegoose/guides/defaultClasses/](https://typegoose.github.io/typegoose/guides/defaultClasses/) you can `extends Timestamps, Base` but in practice it does not work. Is this a mistake? Am I missing something?

**Comment by hasezoey** [comment]
thanks for pointing this out, when i looked it up initial for the documentation, it seemed that this was possible in typescript, but now it dosnt seem so anymore...

[look here for an workaround](https://stackoverflow.com/questions/26948400/typescript-how-to-extend-two-classes)

-> will update documentation later

**Comment by JakeAi** [comment]
So I have this Model/Class called Category/CategoryModel. When I do `const newCategory = new CategoryModel()` and console log this object, I get `{"_id":"5da9cca44a3b334b3844a40b"}`. If I place applyMixins after `export const CategoryModel = getModelForClass(Category);` and console log, I get 
```TS
{
    categoryType: ""
    description: ""
    image: ""
    name: ""
    url: ""
    _id: "5da9ccfeecb7754838671c7b"
}
```

It doesn't seem like it works as intended/documented. The full code is below. I think this needs to be looked into more. I've used applyMixins for a bluetooth app and it was a challenge to get it to work as intended. All of the properties are undefined when following the typegoose documentation.

```TS
import {getModelForClass, prop, Ref} from "@typegoose/typegoose";
import {Base, TimeStamps} from "@typegoose/typegoose/lib/defaultClasses";
import {applyMixins} from "rxjs/internal-compatibility";

export interface Category extends Base, TimeStamps {

}

export class Category {
  @prop({default: "", required: true}) name: string;
  @prop({default: "", required: true}) description: string;
  @prop({default: "", required: false}) image?: string;
  @prop({default: "", required: true}) categoryType: string;
  @prop({default: "", required: true}) url: string;
  @prop({ref: Category}) public category: Ref<Category>;
}

applyMixins(Category, [Base, TimeStamps]);


export const CategoryModel = getModelForClass(Category);


```

**Comment by hasezoey** [comment]
> `import {applyMixins} from "rxjs/internal-compatibility";`

that is probably not the right "applyMixins"

---

otherwise, i now tested it more, at first i thought `applyMixins` is a global function supplied by typescript, but it is not, [and the function on the website](https://www.typescriptlang.org/docs/handbook/mixins.html) from typescript, dosnt event work (in the meaning of that it has an type-mismatch error & when ignoring it, it dosnt produce the right schema)

for now, use the following code, it will work because the "Base" class does only add typings, not  actual functions or options

```ts
export interface Category extends Base { }

export class Category extends TimeStamps {
    @prop({ default: "", required: true }) public name!: string;
    @prop({ default: "", required: true }) public description!: string;
    @prop({ default: "", required: false }) public image?: string;
    @prop({ default: "", required: true }) public categoryType!: string;
    @prop({ default: "", required: true }) public url!: string;
    @prop({ ref: Category }) public category?: Ref<Category>;
}
```

**Comment by marcandrews** [comment]
@hasezoey, this seems to be not working for virtuals.

For example:
```typescript
export interface Category extends TimeStamps { }
export class Category extends Base {
  // ...

  get dates() {
    return {
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    }
  }
}

// category.dates === { createdAt: undefined, updatedAt: undefined } 
```

In the meantime, I just created my own class that includes everything from `class Base` and `class TimeStamps`, and use that instead.
```typescript
import { Types } from 'mongoose'

import { modelOptions } from '@typegoose/typegoose'
import { RefType } from '@typegoose/typegoose/lib/types'

@modelOptions({ schemaOptions: { timestamps: true } })
export abstract class Base<T_ID extends RefType = Types.ObjectId> {
  public _id!: T_ID
  // tslint:disable-next-line:variable-name
  public __v!: number
  // tslint:disable-next-line:variable-name
  public __t!: undefined | string | number

  public createdAt!: Readonly<Date>
  public updatedAt!: Readonly<Date>
}
```

ES7 has support for multiple class inheritance and could be included in TypeScript soon. It may be useful to include all combinations of the default classes, `Base`, `TimeStamps` and `FindOrCreate`, until multiple class inheritance is supported.

By the way, I love this library and appreciate all the work you've put into it ❤️

**Comment by hasezoey** [comment]
@marcandrews thanks for testing this and notifying me for ES7 multiple inheritance, which i wasnt aware of

>  It may be useful to include all combinations of the default classes, Base, TimeStamps and FindOrCreate, until multiple class inheritance is supported.

sorry, but i wont do that

> this seems to be not working for virtuals.

it may not be working in the latest typescript anymore, but did in some older versions
btw, the method i suggested (and your first example) only inherits the types of both, not the actual classes, which means in your example, that you wanted to access `createdAt` and `updatedAt`, which are not actual runtime values (from what you provided) - where as the Base class are actually just types (like _id, __v and so, not runtime things) that is why i made the example where `Base` is only extended in the interface
