### ISSUE TITLE
lean() return type includes methods even though they are not there

### ISSUE THREAD

**Issue by muametgrooby** [typegoose/typegoose#781]
## Versions

- System: linux  
- NodeJS: 16.14.2
- Typescript: 4.9.3

- Compiler / Transpiler: tsc 
- Typegoose(NPM): 10.0.0 
- Typegoose(GIT): bb941f22a2b4bb9f7a3289e92babb2e6052c3641
- mongoose: 6.8.0 
- mongodb: no idea but irrelevant

## What is the Problem?

 .lean() return type includes declared methods even though they are not actually present, the perfect example is .typegooseName(), it is in the return type but it is actually undefined

## Code Example

```ts
    const test = await SomeModel.findOne().lean();

    if (test) {
      console.log(test.typegooseName); // output: undefined
    }
```

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
for now i have created a mongoose issue as https://github.com/Automattic/mongoose/issues/12880

though i will try to update the types to be more in line with what mongoose expects (though it may be hard to do so)

**Comment by hasezoey** [comment]
resolution to https://github.com/Automattic/mongoose/issues/12880 was that mongoose wont do this automatically, and for typegoose i dont want to break the types *yet*, so for now there is [`FilterOutFunctionKeys<T>`](https://typegoose.github.io/typegoose/docs/api/types/utility-types/#filteroutfunctionkeyst)

also see https://github.com/typegoose/typegoose/issues/825
