### ISSUE TITLE
Typegoose + mongoose: how to push tuple to array?

### ISSUE THREAD

**Issue by PinkFromTheFuture** [typegoose/typegoose#784]
I'm working on the following code:

```ts
import { prop, modelOptions, DocumentType, getModelForClass } from "@typegoose/typegoose";
import dbConnect from "src/lib/dbConnect";
import mongoose from 'mongoose';


@modelOptions({ schemaOptions: { timestamps: true } })
class Kitten {
  @prop()
  public name?: string;

  @prop({ type: String, required: true, default: [] })
  public events!: mongoose.Types.Array<[string, Date]>;
  // also doesn't work:
  // public events!: [string, Date][];


  // instance method:
  public async addEvent(this: DocumentType<Kitten>, _eventName: string) {

    const tuple : [string, Date] = [_eventName, new Date()];

    this.events.push(tuple);
    await dbConnect();
    await this.save();
  }
}

export const KittenModel = getModelForClass(Kitten);

```

and when I call `addEvent` I get the following error when executing `this.events.push(tuple);` :

```
error - CastError: Cast to string failed for value "[
  '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001',
  2023-01-11T05:02:21.462Z
]" (type Array)
```

It seems that the method push is trying to convert the tuple into a string for some reason...

My environment is:

"@typegoose/typegoose": "^10.0.0",

"mongoose": "^6.8.3",

nodejs --version :v16.18.1

**Comment by PinkFromTheFuture** [comment]
import { prop, modelOptions, DocumentType, getModelForClass } from "@typegoose/typegoose";
import dbConnect from "src/lib/dbConnect";
import mongoose from 'mongoose';


@modelOptions({ schemaOptions: { timestamps: true } })
class Kitten {
  @prop()
  public name?: string;

  @prop({ type: mongoose.Types.Array<[string, Date]>, required: true, default: [] })
  public events!: mongoose.Types.Array<[string, Date]>;

  // instance method:
  public async addEvent(this: DocumentType<Kitten>, _eventName: string) {

    const tuple : [string, Date] = [_eventName, new Date()];

    this.events.push(tuple);
    await dbConnect();
    await this.save();
  }
}

export const KittenModel = getModelForClass(Kitten);

**Comment by hasezoey** [comment]
just for reference, the following will not affect anything in typegoose
```ts
@prop({ type: mongoose.Types.Array<[string, Date]> /*<----*/, required: true, default: [] })
// the above is basically the same as
@prop({ type: mongoose.Types.Array, required: true, default: [] })
```
defining a typescript type inside `@prop` will not affect anything at runtime

also using `Array` or `mongoose.Types.Array` will result in a `Mixed` property, which is also likely not what you want.

mongoose & typegoose do not support tuple arrays unless it is `Mixed` (no validation whatsoever) or values are of the same type, in cases where you would use tuples, i would personally recommend just using a nested document (class) with proper property names
