### ISSUE TITLE
failed to get correct querying when using virtual populates with nested discriminator

### ISSUE THREAD

**Issue by ghostoy** [typegoose/typegoose#796]
## Versions
10.3.0

- System: macos 
- NodeJS: 16.18.0
- Typescript: 4.8.4

- Compiler / Transpiler: tsc / ts-node
- Typegoose(NPM): 10.3.0
- mongoose: 6.10.0
- mongodb: 4.14.0

## Code Example
```typescript
// message.entity.ts
@modelOptions({
  schemaOptions: {
    discriminatorKey: 'type',
    _id: false,
  },
})
class BodyBase {
  @prop({ required: true })
  type: string;
}

class BodyText extends BodyBase {
  @prop({ required: true })
  type: 'text';

  @prop({ required: true })
  text: string;
}

class BodyFile extends BodyBase {
  @prop({ required: true })
  type: 'file';

  @prop({ ref: () => File, required: true })
  file: Ref<File>;
}

class Message {
  @prop({
    type: () => BodyBase,
    discriminators: () => [
      { type: BodyFile, value: 'file' },
      { type: BodyText, value: 'text' },
    ],
  })
  body: BodyFile | BodyText;
}
// file.entity.ts
class File {
  @prop({
    ref: () => Message,
    localField: '_id',
    foreignField: 'body.file',
    justOne: true,
  })
  message: Ref<Message>;
}
```
When querying file with message, it will ignore `body.file` condition and generate querying as below, which returns all messages in the collection.
```
Mongoose: messages.find({}, { skip: undefined, limit: undefined, perDocumentLimit: undefined })
```
Once added `match: { 'body.type': 'file' }` to the virtual populates, it will still ignore the `body.file` condition and generate something like:
```
Mongoose: messages.find({ '$or': [ { 'body.type': 'file' }, { 'body.type': 'file' }, { 'body.type': 'file' } ]}, { skip: undefined, limit: undefined, perDocumentLimit: undefined})
```
Onced added `match: file => ({ 'body.type': 'file', 'body.file': file._id })`, it throws an error like `Uncaught TypeError: Cannot read properties of undefined (reading 'path')` at https://github.com/Automattic/mongoose/blob/6.10.2/lib/cast.js#L123.

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
> `Mongoose: messages.find({}, { skip: undefined, limit: undefined, perDocumentLimit: undefined })`

that looks like a `strictQuery` problem, try setting `mongoose.set('strictQuery', false)` and see if it is still there (when yes, then mongoose only looks at the properties from the base for the removal of unknown keys)

**Comment by hasezoey** [comment]
can reproduce in typegoose 10.2.0 and mongoose 6.10.0, and setting `strictQuery` to `false` fixes the issue
Note: it is recommended to set `strictQuery` to `false` again (which in mongoose 7.0.0 it is again)

Code used: https://github.com/typegoose/typegoose-testing/tree/verify796

log (only relevant parts):
```txt
Mongoose: messages.find({ 'body.file': { '$in': [ new ObjectId("64087cfcd26fc7853573d643") ], [Symbol(mongoose#trustedSymbol)]: true }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined })
found {
  _id: new ObjectId("64087cfcd26fc7853573d643"),
  __v: 0,
  message: {
    _id: new ObjectId("64087cfcd26fc7853573d647"),
    body: { type: 'file', file: new ObjectId("64087cfcd26fc7853573d643") },
    __v: 0,
    id: '64087cfcd26fc7853573d647'
  },
  id: '64087cfcd26fc7853573d643'
}
```
