### ISSUE TITLE
Cant resolve circular dependency issue even with the docs recommendations

### ISSUE THREAD

**Issue by angelhodar** [typegoose/typegoose#806]
Hi, I am just wondering how can I resolve circular dependency issue because I have tried all posible methods and still cant figure out how to continue. I am trying to refactor a js project that has mongoose and graphql to a typescript project with typegoose (amazing project btw) and typegraphql. Here are some specs of what im using in case it helps:

- NodeJS: 18.15.0
- Typescript: 5.0.2
- Compiler / Transpiler: ts-node
- Typegoose(NPM): 10.3

I am trying to upload a stackblitz container so you can test the project but for now I am going to explain the problem so maybe you can see it in a blink of an eye.

I have a folder called **resources** that contains an ``index.ts`` file and a subfolder for each resource in my API. Each folder includes the typegoose model, the typegraphql resolver, etc (``user.model.ts``, ``user.resolver.ts``, etc). Each of these folders also includes an ``index.ts`` that simply does the following to re-export the contents and abstract the module internals:

```ts
// resources/user/index.ts
export * from "./user.model"
```

The problem comes with the base ``index.ts`` file in my resources folder. Its the file that exports the typegoose compiled models as you recommend in the docs. It also re-exports each resource so it can be used as a bridge for resources to import another (or by external modules in the project). I took the idea from [this article](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de)

```ts
// resources/index.ts
import {
  getDiscriminatorModelForClass,
  getModelForClass,
} from "@typegoose/typegoose";

export * from "./user";
export * from "./staff";
//...

import { User } from "./user";
import { Staff } from "./staff";
//...

export const UserModel = getModelForClass(User);
export const StaffModel = getDiscriminatorModelForClass(UserModel, Staff);
//...
```

So for example if I want the staff user to extend the base ``User`` class I import it like this:

```ts
// resources/staff/staff.model.ts
import { prop } from "@typegoose/typegoose";
import { ObjectType, Field, registerEnumType } from "type-graphql";
import { User } from ".."; // This refers to the base index.ts in the resources folder

@ObjectType()
export class Staff extends User {
  @Field()
  @prop({ required: true })
  name!: string;
  
 // ...
}
```

But no matter what I try I always get the typical ``TypeError: Cannot read properties of undefined`` because of circular dependency issue. I have tried the ``import type`` way to just import the class type but the typegoose and typegraphql requires the values instead of types:

```ts
import type { User } from ".."; // Error using it in code
```

So what am I doing wrong? I am completely stuck because I dont know how to solve the issue. Any help will be appreciated.

Thanks in advance!!

**Comment by hasezoey** [comment]
> TypeError: Cannot read properties of undefined

this does not say much by itself and the code provided does not look particularly broken, could you provide the full stack trace?

**Comment by angelhodar** [comment]
@hasezoey Thank you so much for your fast response! I am trying to create a codesandbox but I am having lots of problems with it (not related to the problem of this issue). I have figured it out in a stackblitz container but I am getting another type of error different from what I get in local:

![imagen](https://user-images.githubusercontent.com/26228709/228025720-22ae6012-326b-4cab-bca9-e397498b4a2e.png)

Here you have the container in case you want to test: https://stackblitz.com/edit/node-gqggrs

**Comment by angelhodar** [comment]
Oh I didnt see that part in the docs, I will check tomorrow what happens if I remove the config paths. Do I have to completely remove that feature or only when importing something related to typegoose in the code? Also I dont truly understand why the pattern of re-exporting everything in the index.ts should fix circular dependencias, do you see it ok?

**Comment by hasezoey** [comment]
> And what if I need a compiled model from getModelForClass inside a model class method?

i think this works, as long as it is done within a function, and that function is not called until all the required models have been resolved, also possible is to use a cache like `const models: Map<string, Model>; const yourModel = models.get('name')`

**Comment by hasezoey** [comment]
> So the error seems to be with the PostFormat enum

this is probably the same because of circular dependencies, for this problem you can use `default: () => PostFormat.POST`

> and now stackblitz gives a weird mongoose error

somehow stackblitz mangles names (for example `_0x31f54c`) which makes debugging it hard

> But it seems very fragile because if I start from another file (for example a test script that imports a single model) then I get another circular dependency error because of how the dependencies are getting resolved...

i dont quite know what you mean from "another file", but you have to keep in mind to always only import from the `index` file instead of the models directly and that you have to use "deferred functions" wherever possible (as in never use `type: Directly` instead use `type: () => Directly` for all options that support it)

**Comment by angelhodar** [comment]
> this is probably the same because of circular dependencies, for this problem you can use default: () => PostFormat.POST

So this has solved the compile error without needing to change the import order! I went to this:

```ts
@Field(() => PostFormat)
@prop({ type: String, required: true, enum: PostFormat, default: () => PostFormat.POST })
format!: PostFormat;
```
But now I dont understand is why the rest doesnt fail (the ``enum: PostFormat`` and ``format!: PostFormat`` if ``PostFormat`` is supposed to be ``undefined`` when imported... Should I change that to base string type whenever possible?

>i dont quite know what you mean from "another file", but you have to keep in mind to always only import from the index file instead of the models directly and that you have to use "deferred functions" wherever possible (as in never use type: Directly instead use type: () => Directly for all options that support it)

By creating another file I mean creating another script in the package.json called ``ts-node src/test.ts`` to start the app from another entry point instead of ``src/index.ts``. I tried to import models in different order and it failed so thats why i said that the solution of chaning import orders seemed fragile.

Anyway I will review all the @prop decorators to check that they all have arrow functions. What properties support that?

**Comment by hasezoey** [comment]
> Edit: What if I transform it to this?

i assume you mean removing option `enum` and only rely on typescripts way of telling problems?
when yes, then if you dont manually validate it, it is possible for input to get in there that is not the enum (like directly using user input)

**Comment by angelhodar** [comment]
> > Edit: What if I transform it to this?
> 
> i assume you mean removing option `enum` and only rely on typescripts way of telling problems? when yes, then if you dont manually validate it, it is possible for input to get in there that is not the enum (like directly using user input)

What do you mean by user input? Anyway in the docs you always set it to string so I suppose that what I said is not valid. Then if enum is undefined what happens later when setting that value or getting its type in code?

**Comment by hasezoey** [comment]
> Then if enum is undefined what happens later when setting that value or getting its type in code?

i dont understand what you mean, please explain what you would "get" later

**Comment by angelhodar** [comment]
For example lets say I have the enum PostFormat with 3 values, and I do this in code:

```ts
const post  = await PostModel.findById(id)
post.format = "randomstring" // What would typescript say here if model was compiled with PostFormat being undefined?
```

**Comment by hasezoey** [comment]
> What would typescript say here if model was compiled with PostFormat being undefined?

typescript would probably complain, because it is *compile time checking*, but would cause no problems at runtime or when being casted through `any` (or something like that)

**Comment by angelhodar** [comment]
> typescript would probably complain, because it is _compile time checking_, but would cause no problems at runtime or when being casted through `any` (or something like that)
Alright now I understand! Above all thanks for answering me that fast, you are a legend! I will tell you If I keep finding strange bugs about circular dependencies. In case you want to add this to the circular dependencies docs I found 2 tools really useful: [dpdm](https://www.npmjs.com/package/dpdm) and [madge](https://www.npmjs.com/package/madge). Again, thanks for your support!
