### ISSUE TITLE
disableLowerIndexes option did not work in v11.

### ISSUE THREAD

**Issue by mrfy** [typegoose/typegoose#808]
## Versions
11.0.0

* System: Windows
* NodeJS: v16.19.1
* Typescript: 4.9.5

* Compiler / Transpiler: tsc / ts-node
* Typegoose(NPM): 11.0.0
* mongoose: 7.0.3
* mongodb: 6.0.5

## What is the Problem?

Unfortunately, the **disableLowerIndexes** flag does not work. I experimented with the example from the documentation(https://typegoose.github.io/typegoose/docs/api/decorators/model-options/#disablelowerindexes) and it always creates indexes of the base class. I have not tested in previous versions of the typegoose.

**Comment by hasezoey** [comment]
the documentation example is a literal copy of one of the tests:
https://github.com/typegoose/typegoose/blob/3f0b7d1c8446421beb80d60111679a1b0190b501/test/tests/indexes.test.ts#L126-L154

i also dont see anything wrong with it, please provide a reproduction example, best would be if you could fork [typegoose-testing](https://github.com/typegoose/typegoose-testing) and link your new branch here

**Comment by hasezoey** [comment]
this issue has been stale for 2 weeks, closing
