### ISSUE TITLE
Intellisense and types

### ISSUE THREAD

**Issue by wasya243** [typegoose/typegoose#816]
Could you please help me with the following issue? Here is the code

```ts
import { prop, getModelForClass, Ref, DocumentType } from '@typegoose/typegoose';
import mongoose from 'mongoose';

class Vendor {
    _id!: mongoose.Types.ObjectId;

    @prop()
    disabled?: boolean;

    @prop({
        ref: () => Invoice,
        foreignField: 'vendorId',
        localField: '_id'
    })
    public invoices?: Ref<Invoice>[];

    public getInvoices(): Promise<DocumentType<Invoice>[]> {
        const vendorId = this._id;
        const invoiceModel = getModelForClass(Invoice);

        return invoiceModel.find({ vendorId }).exec();
    }
}

class Invoice {
    @prop({ required: true })
    created!: Date

    @prop({
        ref: () => Vendor, 
        required: true,
        foreignField: '_id',
        localField: 'vendorId',
        justOne: true
      })
      public vendor!: Ref<Vendor>;
    
      @prop({ required: true })
      public vendorId!: string;
}

const VendorModel = getModelForClass(Vendor, {
    schemaOptions: {
      toJSON: { virtuals: true },
      toObject: { virtuals: true }
    }
});

const InvoiceModel = getModelForClass(Invoice, {
    schemaOptions: {
        toJSON: { virtuals: true },
        toObject: { virtuals: true }
      }
})

async function start() {
    try {
        await mongoose.connect('mongodb://localhost:27017/', {dbName: 'migration-to-typegoose'});
       
        const vendor = await VendorModel.create({
            disabled: false
        });

        const invoice = await InvoiceModel.create({
            created: new Date()
        });


        const queriedVendor1 = await VendorModel.findOne().populate<{invoices: Invoice[]}>('invoices');

        console.log('queriedVendor1', queriedVendor1);
        console.log('await queriedVendor1?.getInvoices()', await queriedVendor1?.getInvoices());

        process.exit(0);
    } catch(err) {
        console.log(err);
        process.exit(1);
    }
}

start();
```

How should I create docs in order to have IDEA (I tried both webstorm and vs code) properties suggestions popup to appear? When I create doc like InvoiceModel.create I do not have 'created' property in the list. Same for VendorModel.create 'disabled' property. How should I change my code so that when I start typing 'cr' then 'created' appears in the list?

**Comment by hasezoey** [comment]
> When I create doc like InvoiceModel.create I do not have 'created' property in the list

depends on what you want to achieve an where, in the `.create({ HERE })` list, it will only ever be a *suggestion* and not *enforced*, but when doing `doc.yourProperty` it should have suggestions and warn on unknown properties

i dont see anything obviously wrong, what versions are you using? (typegoose, mongoose, typescript)

note: if your type also includes something like `null` or `undefined`, you may need to check for that first before any property appears in the list

could you clarify where in the code you expect to have suggestions? (like adding a comment at the line(s))

**Comment by wasya243** [comment]
I use typegoose 11 and mongoose 7. Let's say my class (model whatewher you call it) has the following properties: aaa, bbb and ccc. So, when I create an instance of (for example via .create method) I expect to appear aaa, bbb and ccc in the suggestion list. Right now it does not happen.

**Comment by hasezoey** [comment]
> So, when I create an instance of (for example via .create method)

so you mean you dont have suggestions in `.create({ HERE })`, right? then i dont really know what is wrong, because your code looks fine to me.

also locally testing your code seems to work just fine with suggestions:

![repro](https://user-images.githubusercontent.com/10911626/231102737-d7a65fb9-27ec-436c-8024-67627d899af4.png)

[Reproduction repository & Branch](https://github.com/typegoose/typegoose-testing/tree/verify816)

using vscode 1.77.0

**Comment by wasya243** [comment]
I've reinstalled VS code to the latest version and it started working. Really strange... But in the end it works)) Thanks for your time.

**Comment by hasezoey** [comment]
> I've reinstalled VS code to the latest version and it started working. Really strange

did you have a older version installed? when yes, maybe consider switching vscode to use the project's typescript install instead of the vscode provided one

**Comment by wasya243** [comment]
okey, let's try, but reinstall and update to the latest version helped.
