### ISSUE TITLE
create, find, findById... return a Document and not a DocumentType

### ISSUE THREAD

**Issue by Sandroggy** [typegoose/typegoose#818]
We are in the process of migrating to typegoose 11 and we don't understand why all the methods on a Model now return Document and not DocumentType Object.

Is this the expected behaviour ?

```
const user = await User.Model.findById(userId);
user.methodFromUser(); // <-- user is of type Document<User> and no method from User is available
 
const user2 = await User.Model.findById<DocumentType<User>>(userId); // <-- To work in typegoose 11, I had to add the type DocumentType<User>
user2.methodFromUser(); // <-- user is of type DocumentType<User> methode are available (this is how it worked in typegoose 9.8.1)
```

It might be related to: https://github.com/typegoose/typegoose/issues/815

## Versions

- System: macos / windows
- NodeJS: 18.12.1
- Typescript: 4.9.5
- mongoose: 7.0.3

**Comment by hasezoey** [comment]
please provide what `User.Model` is

**Comment by Sandroggy** [comment]
User.Model is declared like this:
`static Model: ReturnModelType<typeof User, BeAnObject> = null;`

And set like this: 
`User.Model = getModelForClass(User, {
  existingConnection: MongoDB.getPortal(),
});`

**Comment by hasezoey** [comment]
> User.Model is declared like this:
> `static Model: ReturnModelType<typeof User, BeAnObject> = null;`

then if you type is actually something akin to 
```txt
mongoose.Document<unknown, BeAnObject, User> & Omit<User & {
    _id: mongoose.Types.ObjectId;
}, "typegooseName"> & IObjectWithTypegooseFunction
```

then nothing is wrong with your type, it seems to be just typescript not wanting to use the type name (`DocumentType`) and instead uses its definition (probably because it is passed through some generics)

https://github.com/typegoose/typegoose/blob/5fad338efccee5e1f770668b1c7ea7e282e49712/src/types.ts#L17-L19

**Comment by Sandroggy** [comment]
Thanks for the reply 🙂

Yes the type is akin to
```
mongoose.Document<unknown, BeAnObject, User> & Omit<User & {
    _id: mongoose.Types.ObjectId;
}, "typegooseName"> & IObjectWithTypegooseFunction
```

We will stay on typegoose 9 for now and try to make a minimal repo to reproduce when why got time to.
