### ISSUE TITLE
setGlobalOptions not effective

### ISSUE THREAD

**Issue by teyra** [typegoose/typegoose#827]
app.module.ts
import { setGlobalOptions } from '@typegoose/typegoose';
setGlobalOptions({
  schemaOptions: {
    timestamps: true
  },
});
 cat.model.ts 
import { modelOptions } from '@typegoose/typegoose';
@modelOptions({}) must be 

How to solve global settings schemaOptions?please

**Comment by teyra** [comment]
"@typegoose/typegoose": "^11.0.2",

**Comment by hasezoey** [comment]
please use the proper issue template and also [please use code-blocks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

---

also your reproduction code is not really enough

but i can reproduce it with the following code:

```ts
// NodeJS: 18.10.0
// MongoDB: 5.0 (Docker)
// Typescript 4.9.5
import { getModelForClass, prop, setGlobalOptions } from '@typegoose/typegoose'; // @typegoose/typegoose@11.0.2
import * as data from '@typegoose/typegoose/lib/internal/data';

setGlobalOptions({
  schemaOptions: {
    timestamps: true,
  },
});

class User {
  @prop()
  public username?: string;
}

const UserModel = getModelForClass(User);

console.log("options", (UserModel.schema as any).options); // missing "timestamps"
```

**Comment by teyra** [comment]
I just tried 11.0.3 and it's ok, thank you
