### ISSUE TITLE
Error when trying to update primitives at the bottom of multidimensional arrays

### ISSUE THREAD

**Issue by Spade-and-Archer** [typegoose/typegoose#828]
## Versions

- System: windows 
- NodeJS: 17.9.1
- Typescript: 5.0.4
I am not aware of a "transpile only" option, but I do not believe I am doing anything weird in that regard
- Compiler / Transpiler: ts-jest 
- Typegoose(NPM): 11.1.0 
- mongoose: 7.1.0 
- mongodb: 4.4.21
- grahpql / type-graphql: 15.8.0 / 1.1.1 

## What is the Problem?

When attempting to modify a multidimensional array of primitives  (e.g. `Number[][]`), changing the values and attempting a save causes an error:

```
The positional operator did not find the match needed from the query.
MongoServerError: The positional operator did not find the match needed from the query
```

## Code Example
```ts
class RecentDataPoint {
    @prop()
    public date?: Date;

    @prop()
    public value?: number;
}
@modelOptions({})
class TestingMultiDimArrays {
    @prop({ type: Number, items: Number, dim: 2})
    public intArray?: number[][];

    @prop({ type: String, items: String, dim: 2})
    public strArray?: string[][];

    @prop({ type: RecentDataPoint , items: RecentDataPoint , dim: 2})
    public objArray?: RecentDataPoint [][];
}
const TestingMultiDimArraysModel = getModelForClass(TestingMultiDimArrays);

let testObj = new TestingMultiDimArraysModel({
    intArray: [[1,2], [3,4]],
    strArray: [["a", "b"], ["c", "d"]],
    objArray: [
        [
            {date: new Date(Date.now()), value: 1},
            {date: new Date(Date.now()), value: 2},
        ],
        [
            {date: new Date(Date.now()), value: 3},
            {date: new Date(Date.now()), value: 4},
        ]
    ],
})
await testObj.save();
testObj = await TestingMultiDimArraysModel.findById(testObj._id);

//works
//testObj.getChanges() returns: {"$set":{"objArray.0.0.value":3}}
testObj.objArray[0][0].value = 3;
await testObj.save();
testObj = await TestingMultiDimArraysModel.findById(testObj._id);
expect(testObj.objArray[0][0].value).toBe(3);

//works
//testObj.getChanges() returns {"$set":{"objArray.0.0":{"date":"2023-05-03T00:25:28.100Z","value":3,"_id":"6451a9f83e792f2678d175e4"}}}
testObj.objArray[0][0] = {date: new Date(Date.now()), value: 3};
await testObj.save();
testObj = await TestingMultiDimArraysModel.findById(testObj._id);
expect(testObj.objArray[0][0].value).toBe(3);

//works
//testObj.getChanges() returns: {"$set":{"strArray.0":["j","d"]},"$inc":{"__v":1}}
testObj.strArray[0] = ["j", "d"];
await testObj.save();
testObj = await TestingMultiDimArraysModel.findById(testObj._id);
expect(testObj.strArray[0][0]).toBe("j");

//works
//testObj.getChanges() returns: {"$set":{"intArray.0":[9,9]},"$inc":{"__v":1}}
testObj.intArray[0] = [9, 9];
await testObj.save();
testObj = await TestingMultiDimArraysModel.findById(testObj._id);
expect(testObj.intArray[0][0]).toBe(9);

//fails
//testObj.getChanges() returns: {"$set":{"intArray.$.0":[[null,null],[null,null]]},"$inc":{"__v":1}}
//The positional operator did not find the match needed from the query.
// MongoServerError: The positional operator did not find the match needed from the query
testObj.intArray[0][0] = 9;
await testObj.save();
testObj = await TestingMultiDimArraysModel.findById(testObj._id);
expect(testObj.strArray[0][0]).toBe(9);


//fails
//testObj.getChanges() returns: {"$set":{"strArray.$.0":[[null,null],[null,null]]},"$inc":{"__v":1}}
//The positional operator did not find the match needed from the query.
// MongoServerError: The positional operator did not find the match needed from the query
testObj.strArray[0][0] = "z";
await testObj.save();
testObj = await TestingMultiDimArraysModel.findById(testObj._id);
expect(testObj.strArray[0][0]).toBe("z");


```

## Do you know *why* it happens?

no

---

I have tried every schema declaration variation possible. I've tried:

1) `{type: [[Number]]}` 

2) `{type: [[mongoose.Schema.Types.Number]]}` 

3) `{type: [[Number]], dim: 2}`

4) `{type: Number, dim: 2}`

5) `{type: Number}`

6) `{type: [[Number]], items: Number}` 

7) `{type: [[Number]], items: Number, dim: 2}`

8) `{type: Number, items: Number, dim: 2}`

9) `{type: Number, items: Number}`

10) `{items: Number, dim: 2}`

and every other permutation of the above that I could think of. While a few of these permutations obviously produce incorrect schemas, most seem to produce a schema like this:
```
obj : {
    intArray : {
        type: [[ { type: ()=> Number } ]]
    },
    strArray : {
        type: [[ { type: ()=> String} ]]
    },
    objArray : {
        type: [[ { type: {obj, paths, aliases...} } ]]
    },
}
```
To my eye, this schema looks correct. 

I believe the problem is something to do with how the update command is generated, it seems to loose all sense of what the array is. Looking at the `getChanges()` (which I have documented in the code sample) It seems like it's not even sure where in the array it's trying to set the values and it's also trying to put an entire empty shell of the original object shape into a single slot in the array.

One other note: I was having the same problem in version 8 of typegoose. I upgraded versions hoping that would fix it. I don't have as thorough documentation of what was going wrong in version 8, so I can't be confident that nothing has changed about the bug, but based on this I feel confident saying this wasn't caused by a recent change.

Related issues: 

Support for multidimensional array types in typegoose https://github.com/typegoose/typegoose/issues/65

Similar problem in Mongoose from 2020: https://github.com/Automattic/mongoose/issues/8926

Additionally; I am not sure if this is a typegoose issue or a mongoose issue. But I believe it is a typegoose issue because mongoose apparently fixed this issue sometime ago. I am currently testing to see if this happens with regular mongoose.

**Comment by Spade-and-Archer** [comment]
In the moments after writing this, I realized it might be a mongoose issue and it is. I am a fool and in the wrong place.

**Comment by hasezoey** [comment]
can confirm, even just limited to `intArray`, could also reproduce in plain mongoose

Reproduction branch: https://github.com/typegoose/typegoose-testing/tree/verify828

repro typegoose commit: https://github.com/typegoose/typegoose-testing/commit/0a52ba326494e4412c5fb0fc2eedbfe9e5a00f95
repro mongoose commit: https://github.com/typegoose/typegoose-testing/commit/d3173d3a76fa324ba1faaf51adf91d557ef21622

this is a issue with mongoose, if you should open one up it would be good to link it here (mention it in the mongoose issue for reference)

PS: in the failing `intArray` example, you are testing `strArray` instead of `intArray`

**Comment by Spade-and-Archer** [comment]
> PS: in the failing `intArray` example, you are testing `strArray` instead of `intArray`

Thanks, I'll fix that. Since it crashes before reaching the expect I guess I never noticed.
