### ISSUE TITLE
How to use Dependency Injection?

### ISSUE THREAD

**Issue by suriyadi15** [typegoose/typegoose#829]
how to inject service into model and i will use it in virtual getter?

example: 

```
public get url() {
    return `${this.configService.get('MEDIA_URL')}/media/${this._id}/file`;
  }
```

**Comment by hasezoey** [comment]
in typegoose there is no dependency injection, if you need functions that rely on anything outside of the model, variables should either be globally accessible or the function should be in your service / business logic
