### ISSUE TITLE
Is there a way to do "Instance methods" in typegoose?

### ISSUE THREAD

**Issue by Gilgamesh22** [typegoose/typegoose#83]
According to the Mongoose [Docs](https://mongoosejs.com/docs/guide.html#methods) you can have "instance methods". I was wondering if we can do this in Typegoose? If so can you show an example.

**Comment by hasezoey** [comment]
do you mean
```ts
class Something {
  public something() { // instance method
    return "i dont know";
  }

  public static something2() {
    return "i dont know2";
  }
}
```
?

and btw the decorators `@instanceMethod` & `@staticMethod` got fully removed in 6.1.0, because they were completely obsolete

**Comment by hasezoey** [comment]
PS: https://mongoosejs.com/docs/api.html#schema_Schema-loadClass is used for this since v6.0.0

**Comment by Gilgamesh22** [comment]
yes but "this" is not type DocumentType

**Comment by Gilgamesh22** [comment]
my sultion for this right now is to simply 
````typescript
class Something {
  public something() { // instance method
    const thiz = this as any as DocumentType<Something>;
    // something
    thiz.save();
  }
}
````

**Comment by hasezoey** [comment]
```ts
class Something {
  public something(this: DocumentType<Something>) { // instance method
    return "i dont know";
  }
}
```

no other solution

**Comment by hasezoey** [comment]
i take this question as solved

-> if not, please reply with what is still wrong

**Comment by OoDeLally** [comment]
> ```ts
> class Something {
>   public something(this: DocumentType<Something>) { // instance method
>     return "i dont know";
>   }
> }
> ```
> 
> no other solution

If you have to pass `this` anyway, what is the point of instance methods? It seems to me that they should all be static then?

**Comment by hasezoey** [comment]
@OoDeLally i dont understand, in typescript you can set the `this` type for an function if you make it the first parameter in the function (it will be removed for runtime)

**Comment by ruohki** [comment]
Id like to piggyback on the question and ask for the correct and intended way to implement static methods

**Comment by hasezoey** [comment]
@ruohki like an normal class-static

```ts
class Something {
  @prop()
  public someDocumentValue: string;

  public someInstanceFunction() {}

  public static someStaticFunction() {}
}
```

since 6.0 it dosnt need an redundant decorator anymore (thanks to `schema.loadClass` from mongoose)

**Comment by ruohki** [comment]
but then i need to basically access the Model before it gets initialized?

**Comment by hasezoey** [comment]
@ruohki yes, i didnt add this because i thought you just asked on *how* to do an static function, not on the types - sorry
but yes, setting `this` needs to be done in every function to have the correct types [more here](https://typegoose.github.io/typegoose/docs/types/returnModelType/)

**Comment by ruohki** [comment]
Ah great thanks for the clarification :)

**Comment by MarianoOrsi** [comment]
Hi, I have the following instance method:
`public async checkPassword(password: string): Promise<boolean> { ...... }`

But then when I get an instance of the model and call the instance method, typescript fails with:
`user.checkPassword is not a function`

Any clue?
Thanks in advance!

Project info:
`"@typegoose/typegoose": "^7.1.3"`
`"mongoose": "^5.9.14"`

**Comment by hasezoey** [comment]
@MarianoOrsi the provided information is not enough for this "error", could you provide the class & how you make an instance?

**Comment by MarianoOrsi** [comment]
```ts
export class User {
  @prop({ required: true })
  public firstName: string;

  @prop({ required: true })
  public lastName: string;

  @prop({ required: true })
  public email: string;

  @prop({ required: true })
  public password: string;

  public async checkPassword(password: string): Promise<boolean> {
    some logic here
  }
}

export const UserModel = getModelForClass(User);
```
Then I have a data layer that get the user
```ts
async getUserByEmail(email: string): Promise<User | null> {
    const user = await UserModel.findOne({ email })
      .lean()
      .exec();
    return user;
  }
```

And finally a middleware use this layer and then call the instance method:
```ts
const user = await userService.getUserByEmail(req.body.email);

if (!user) {
  return res.status(401).send(invalid);
}

const match = await user.checkPassword(req.body.password);
```

The problem is when the code call to `user.checkPassword` in the last line

**Comment by hasezoey** [comment]
@MarianoOrsi you use `.lean` which returns an *POJO* instead of an *instance*

**Comment by MarianoOrsi** [comment]
> @MarianoOrsi you use `.lean` which returns an _POJO_ instead of an _instance_

Thanks @hasezoey ! Your are right, that was the problem. :)

**Comment by chaseadamsio** [comment]
@hasezoey the link in [this comment above](https://github.com/typegoose/typegoose/issues/83#issuecomment-605627844) is broken, this looks like the new path for [return model type](https://typegoose.github.io/typegoose/docs/api/types/return-model-type/)
