### ISSUE TITLE
Get id prop as string instead of Buffer from Ref<>

### ISSUE THREAD

**Issue by angelhodar** [typegoose/typegoose#830]
Hi! Just a simple and fast questions as I havent found anything in the discussions nor issues. Is there a way to get the ``id`` prop from Ref<X> as string instead of Buffer? I have a base class which is working fine getting the id as string, but it only works when document is populated:

```ts
import { Types } from "mongoose";
import { Base } from "@typegoose/typegoose/lib/defaultClasses";
import { prop, modelOptions } from "@typegoose/typegoose";
import { Field, ID, ObjectType } from "type-graphql";

@ObjectType({ isAbstract: true })
@modelOptions({
  schemaOptions: {
    timestamps: true,
    toObject: { virtuals: true },
  },
})
export class BaseEntity implements Base {
  @Field(() => ID)
  readonly _id!: Types.ObjectId;

  @Field(() => ID)
  readonly id!: string;

  @prop()
  @Field()
  public updatedAt!: Date;

  @prop()
  @Field()
  public createdAt!: Date;
}

export default BaseEntity;
```

If the prop is not populated, for now I have to do ``document.refField._id.toString()``, because id is a Buffer.

**Comment by hasezoey** [comment]
i dont fully understand the question based on the code example, but only the `_id` as a alias is available when a property is unpopulated, so you will have to manually call it (and this alias is only available if the type is a `ObjectId`)

you could theoretically add a getter yourself on the `ObjectId` class named `id` which automatically calls toString, like the normal `id` virtual does

also your type is not a Buffer, it is a `ObjectId`, which automatically implements `toString()` for most cases (like `JSON.stringify`)

**Comment by angelhodar** [comment]
> you could theoretically add a getter yourself on the ObjectId class named id which automatically calls toString, like the normal id virtual does

How would I implement this in the ObjectId class?

Ok let me give you the simplified example that caused my question. Lets say I have this classes:

```ts
@ObjectType()
export class First extends Base {
  @Field(() => [ID])
  @prop({ ref: () => Category, required: true })
  categories: Ref<Category>[];
}
```

```ts
@ObjectType()
export class Second extends Base {
  @Field(() => [ID])
  @prop({ ref: () => Category, required: true })
  categories: Ref<Category>[];
}
```

Now suppose I do this:

```ts
const first = await First.findById(/* suppose valid id */).populate("categories")
const second = await Second.findById(/* suppose valid id */)
```

If I want to check if both documents share a category in their respective arrays, I would do:

```ts
const firstCategories = first.categories.map(c => c.id) // Array of string
const secondCategories = second.categories.map(c => c.id) // Array of Buffer
return firstCategories.some((c) => secondCategories.includes(c)); // Fails always
```

The return is always false because the secondCategories is an array of Buffer and the firstCategories is an array of strings. To fix it I have to do use the ObjectId ``equals`` method:

```ts
const firstCategories = first.categories.map(c => c._id)
const secondCategories = second.categories.map(c => c._id)
return firstCategories.some((c) => secondCategories.some(x => x.equals(c)); // Now it works
```

When hovering the id prop of Ref it says the type is any, I was expecting string:

![Sin título](https://user-images.githubusercontent.com/26228709/236196055-5e5dcfc7-874a-4ee8-8fd8-b9519860a9d8.png)

I suppose I just have to use the toString() method of Ref or use _id.toString(), but having id always as string would be very helpful to avoid this equality issues. I dont know If I have explained it better but if something isnt still clear just tell me!

**Comment by hasezoey** [comment]
> When hovering the id prop of Ref it says the type is any, I was expecting string:

didnt know that `id` was already a existing property on `ObjectId`, seems like the workaround i mentioned will not be working in this case

so yes, you will have to use the `toString()` method in this case or use the `equals` method on objectids

**Comment by angelhodar** [comment]
@hasezoey Sorry for late response. Then its perfect, I just thought there was a built-in way to have the ``_id`` already casted as ``id`` string prop. Thanks anyway!
