### ISSUE TITLE
Classes diagram

### ISSUE THREAD

**Issue by vasyl97kharchenko** [typegoose/typegoose#832]
I have a question, is it possible to automatically build classes diagram (using some tool or IDEA) defined in typegoose?

**Comment by hasezoey** [comment]
i dont use one and i did not test the following, but there seems to be a typescript UML class generator [TsUML2](https://github.com/demike/TsUML2) which you could try and use

aside from that, no typegoose does not have a way to build a diagram from its classes, and a normal class diagram should be enough (assuming your classes are defined correctly, like properly matching `type` with the typescript property type)
