### ISSUE TITLE
Return type of findById, findOne, .etc of a model

### ISSUE THREAD

**Issue by wasya243** [typegoose/typegoose#838]
Hello, can you please explain what is the return method of model methods. Here is the code

```ts
import { prop, getModelForClass, Ref } from "@typegoose/typegoose";
import mongoose from "mongoose";

class User {
    @prop({ required: true })
    firstName!: string;

    @prop({ required: true })
    lastName!: string;
}

const UserModel = getModelForClass(User, {
    schemaOptions: {
        collection: 'users',
        toJSON: { virtuals: true },
        toObject: { virtuals: true }
    }
});

// or should I use DocumentType<User>?
async function someCustomMethod(userId: mongoose.Types.ObjectId): Promise<User | null> {
    const user = await UserModel.findById(userId);

    // some logic

    return user;
}

async function run() {
    try {
        await mongoose.connect('mongodb://localhost:27017', {dbName: 'test-return-type'});

        const user = await UserModel.create({
            firstName: 'vasyl',
            lastName: 'kharchenko'
        });

        const qUser = await someCustomMethod(user._id);

        console.log('qUser', qUser);

        process.exit(0);
    } catch (err) {
        console.log(err);
        process.exit(1);
    }
}

run();
```

What return type should be for a **someCustomMethod**? User or DocumentType[User]? If I use User and try to reference _id on qUser I get an error that it does not exist. If I use DocumentType[User] -> it works. Still I want to understand when to user User as a type and when DocumentType<User>. Please help.

**Comment by hasezoey** [comment]
the correct return type is to use `DocumentType<User>` instead of `User`

always use:
- `DocumentType<User>` if you want to get the *type of a document of model User*
- `ReturnModelType<typeof User>` if you want to get the *type of model User*
- `User` if you use `new User()` somewhere, otherwise dont use it

**Comment by wasya243** [comment]
Okey, thanks a lot
