### ISSUE TITLE
What is the return type for find operations

### ISSUE THREAD

**Issue by HenryWu01** [typegoose/typegoose#862]
I'm using typegoose with ``strictNullChecks`` enabled, however when I want to speicfy return type, it never gets right. I have created a base typegoose ``model`` and ``service`` for others to extend from.  
**base.model.ts**
```typescript
import { modelOptions, prop } from '@typegoose/typegoose';

@modelOptions({
    schemaOptions: {
        id: false,
        toJSON: {
            getters: true,
            virtuals: true,
            versionKey: false
        }
    }
})
export abstract class BaseModel {
    public _id: string;

    @prop({ index: true, default: Date.now })
    createdAt: Date;

    @prop({ index: true, default: Date.now })
    updatedAt: Date;
}
```

**base.service.ts**
```typescript
import { ReturnModelType } from '@typegoose/typegoose';
import { AnyParamConstructor, DocumentType } from '@typegoose/typegoose/lib/types';
import { FilterQuery, UpdateQuery } from 'mongoose';
import { BaseModel } from './base.model';

export abstract class BaseService<T extends BaseModel> {
    protected model: ReturnModelType<AnyParamConstructor<T>>;

    protected constructor(model: ReturnModelType<AnyParamConstructor<T>>) {
        this.model = model;
    }

    findOne(filter: FilterQuery<T>) {
        return this.model.findOne(filter);
    }

    findAll(filter: FilterQuery<T>) {
        return this.model.find(filter);
    }

    findById(id: string) {
        return this.model.findById(id);
    }

    aggregate() {
        return this.model.aggregate();
    }

    create(item: Partial<T>) {
        return this.model.create(item);
    }

    delete(filter: FilterQuery<T>) {
        return this.model.findOneAndDelete(filter);
    }

    deleteById(id: string) {
        return this.model.findByIdAndDelete(id);
    }

    update(filter: FilterQuery<T>, item: UpdateQuery<DocumentType<T, object>>) {
        return this.model.findOneAndUpdate(filter, item, { new: true });
    }

    updateById(id: string, item: UpdateQuery<DocumentType<T, object>>) {
        return this.model.findByIdAndUpdate(id, item, { new: true });
    }

    count(filter: FilterQuery<T>) {
        return this.model.countDocuments(filter);
    }

    async findOneAsync(filter: FilterQuery<T>): Promise<T> {
        return this.findOne(filter);
    }

    async findAllAsync(filter: FilterQuery<T>) {
        return this.findAll(filter);
    }

    async findByIdAsync(id: string) {
        return this.findById(id);
    }

    async createAsync(item: Partial<T>) {
        return this.create(item);
    }

    async deleteAsync(filter: FilterQuery<T>) {
        return this.delete(filter).exec();
    }

    async deleteByIdAsync(id: string) {
        return this.deleteById(id).exec();
    }

    async updateAsync(filter: FilterQuery<T>, item: UpdateQuery<DocumentType<T, object>>) {
        return this.update(filter, item).exec();
    }

    async updateByIdAsync(id: string, item: UpdateQuery<DocumentType<T, object>>) {
        return await this.updateById(id, item).exec();
    }

    async countAsync(filter: FilterQuery<T>) {
        return await this.count(filter);
    }
}
```

I want to add the return type ``Promise<T | null>`` to functions like ``findByIdAsync``, however it gave me this incredibly long error:
```
Type 'IfAny<T, any, Document<unknown, BeAnObject, T> & Omit<Require_id<T>, "typegooseName"> & IObjectWithTypegooseFunction> | null' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'IfAny<T, any, Document<unknown, BeAnObject, T> & Omit<Require_id<T>, "typegooseName"> & IObjectWithTypegooseFunction> | null'.
```

Changing ``Promise<T>`` to ``Promise<DocumentType<T, object>>`` does not work as well, I don't know what is ``IfAny`` at all

## Versions
- System: windows
- NodeJS: 18.13.0
- Typescript: 4.9.4

- Compiler / Transpiler: tsc / ts-node
- Typegoose(NPM): 11.3.0
- mongoose: 7.3.1
- mongodb: 6.0.5
- nestjs / nestjs-typegoose: CUSTOM FORK

**Comment by hasezoey** [comment]
i am not sure which of the method you were testing (next time please only include the methods you talk about), so i assume you mean `findOne`, the proper return type should be `Promise<DocumentType<T> | null>`

```ts
async findOne(filter: mongoose.FilterQuery<T>): Promise<DocumentType<T> | null> {
  return this.model.findOne(filter);
}
```
unless `.orFail()` is used, a `| null` is added to the return type

**Comment by HenryWu01** [comment]
> i am not sure which of the method you were testing (next time please only include the methods you talk about), so i assume you mean `findOne`, the proper return type should be `Promise<DocumentType<T> | null>`
> 
> ```ts
> async findOne(filter: mongoose.FilterQuery<T>): Promise<DocumentType<T> | null> {
>   return this.model.findOne(filter);
> }
> ```
> 
> unless `.orFail()` is used, a `| null` is added to the return type, also note that if you explicitly define the type like this, typescript wont allow you to query-build from that function anymore

Thank you for anwersing! This works like a charm.  
I have an extra qustion:
My database model is defined as this:
```typescript
export class Comment extends BaseModel {
    @prop()
    content: string;

    @prop({ default: 0 })
    likeNumber: number;

    @prop({ default: 0 })
    commentNumber: number;

    @prop({ ref: () => User, index: true })
    user: Ref<User>;
}
```

Here is the return type (interface):
```typescript
import { UserInfo } from "../user";

export interface CommentInfo {
    content: string;

    likeNumber: number;

    commentNumber: number;

    user: UserInfo;
}
```

I'm using the sealed helper function above to query comments:
```typescript
return super.findAll(searchTerm)
            .populate('user')
            .populate({
                path: 'comments',
                select: 'content',
                populate: {
                    path: 'user'
                },
                perDocumentLimit: 4
            })
            .sort(searchTerm.sortBy)
            .limit(20);
```

And an error appeared:
```
Type 'Omit<Omit<Document<unknown, BeAnObject, Comment> & Omit<Comment & Required<{ _id: string; }>, "typegooseName"> & IObjectWithTypegooseFunction, never>, never>[]' is not assignable to type 'CommentInfo[]'.
  Type 'Omit<Omit<Document<unknown, BeAnObject, Comment> & Omit<Comment & Required<{ _id: string; }>, "typegooseName"> & IObjectWithTypegooseFunction, never>, never>' is not assignable to type 'CommentInfo'.
    Types of property 'user' are incompatible.
      Type 'Ref<User, string>' is not assignable to type 'UserInfo'.
        Type 'string' is not assignable to type 'UserInfo'.
```

Calling ``isDocument`` seems not working neither for ``findOne`` nor ``findAll``

**Comment by HenryWu01** [comment]
> > Calling isDocument seems not working neither for findOne nor findAll, what should I do to solve this issue?
> 
> depends on how you call it and return it, could you provide how you have done it? a proper way would be something like:
> 
> ```ts
> function find() {
>  const docs = /*find query*/;
>  assertion(docs.every(doc => isDocument(doc.yourPath)), new Error("custom error"); // like "node:assert" but with actual types
>  // or
>  if (docs.every(doc => isDocument(doc.yourPath))) {
>   // either change the value if you can, or return some kind of error or some different return result that is not for the "else" path
>  }
> 
>  return docs;
> }
> ```
> 
> the above maybe works with typescript inferring what the type should be, but if it is not, you may need to cast the types

Sure, here is the complete code:
```typescript
async getRootComments({ order = CommentOrder.OLDEST, filter = CommentFilter.ALL, message, startId }): Promise<CommentInfo[]> {
        const searchTerm: FilterQuery<Comment> = {
            match: {
                _id: {
                    $in: message.comments
                },
                ...(filter === CommentFilter.AUTHOR && { user: message.user })
            }
        };

        return super.findAll(searchTerm)
            .populate('user')
            .populate({
                path: 'comments',
                select: 'content',
                populate: {
                    path: 'user'
                },
                perDocumentLimit: 4
            })
            .sort(searchTerm.sortBy)
            .limit(20);
    }
```
![Code_nmEpky8Zrm](https://github.com/typegoose/typegoose/assets/99880210/cb2e2240-6766-49da-a17f-ffd7f05a6e26)
On another place, I have also used ``isDocument`` to check, but typescript still raise error as well
-------------------------------
**model.ts**
```typescript
export class Category extends BaseModel {
    @prop()
    name: string;

    @prop()
    description: string;

    @prop()
    cover: string;

    @prop({ ref: () => School })
    school: Ref<School>;

    @prop({ ref: () => User })
    manager: Ref<User>;

    @prop({ ref: () => User })
    subscribers: Ref<User>[];
}

```

**interface.ts**
```typescript
export interface CategoryInfo {
    name: string;

    description: string;
    
    cover: string;
}

export interface CategoryDetail extends CategoryInfo {
    manager: UserInfo;
}
```

complete logic code:
```typescript
async getCategoryDetail(categoryId: string): Promise<CategoryDetail> {
    const category = await super.findById(categoryId)
        .select('-subscribers')
        .populate('manager');
    if (!category) {
        throw new HttpException('Category does not exist', HttpStatus.NOT_FOUND);
    }
    if (!isDocument(category.manager)) {
        throw new HttpException('Unable to populate category manager', HttpStatus.INTERNAL_SERVER_ERROR);
    }

    return category;
}
```
![image](https://github.com/typegoose/typegoose/assets/99880210/65597dec-b117-4532-894c-5678e2285f57)

**Comment by hasezoey** [comment]
it seems like you need to do some manual casting, otherwise typescript will seemingly not allow it.
another options is to use `category.toObject()` which would be more correct, but also (along with the casting method) not protect against forgotten `isDocument` checks.

it seems like there is no proper method for typescript to check it with the current way things are done and allow casting a `Ref` to a interface, unless you explicitly do something like `const t: UserInfo = category.manager`

some example code:
```ts
async function getCategoryDetail(categoryId: string): Promise<CategoryDetail> {
  const category = await CategoryModel.findById(categoryId).select('-subscribers').populate('manager');

  if (isNullOrUndefined(category)) {
    throw new Error('Category does not exist');
  }

  // typescript error: Type 'ObjectId' has no properties in common with type 'UserInfo'
  // as expected
  const t1: UserInfo = category.manager;

  if (!isDocument(category.manager)) {
    throw new Error('Unable to populate category manager');
  }

  // no typescript error
  // as expected
  const t2: UserInfo = category.manager;

  // typescript error: "Type 'ObjectId' has no properties in common with type 'UserInfo'."
  // not as expected
  const t3: CategoryDetail = category;

  return category.toObject();
}
```

Full code at https://github.com/typegoose/typegoose-testing/tree/verify862

**Comment by HenryWu01** [comment]
> it seems like you need to do some manual casting, otherwise typescript will seemingly not allow it. another option is to use `category.toObject()` which would be more correct, but also (along with the casting method) not protect against forgotten `isDocument` checks.
> 
> it seems like there is no proper method for typescript to check it with the current way things are done and allow casting a `Ref` to a interface, unless you explicitly do something like `const t: UserInfo = category.manager`
> 
> some example code:
> 
> ```ts
> async function getCategoryDetail(categoryId: string): Promise<CategoryDetail> {
>   const category = await CategoryModel.findById(categoryId).select('-subscribers').populate('manager');
> 
>   if (isNullOrUndefined(category)) {
>     throw new Error('Category does not exist');
>   }
> 
>   // typescript error: Type 'ObjectId' has no properties in common with type 'UserInfo'
>   // as expected
>   const t1: UserInfo = category.manager;
> 
>   if (!isDocument(category.manager)) {
>     throw new Error('Unable to populate category manager');
>   }
> 
>   // no typescript error
>   // as expected
>   const t2: UserInfo = category.manager;
> 
>   // typescript error: "Type 'ObjectId' has no properties in common with type 'UserInfo'."
>   // not as expected
>   const t3: CategoryDetail = category;
> 
>   return category.toObject();
> }
> ```
> 
> Full code at https://github.com/typegoose/typegoose-testing/tree/verify862

Thank you so much for helping! ``toObject`` is indeed a way to resolve this issue for single item.  
How about an array, it seems like array does not have ``toObject`` method. What's more, does calling ``toObject`` have performance impact?

**Comment by hasezoey** [comment]
> How about an array, it seems like array does not have toObject method

depends, what array is it, a normal array or a mongoose array? a mongoose array has `toObject`, but it equivalent to `docs.map(doc = > doc.toObject())` anyway

> What's more, does calling toObject have performance impact?

yes, but that would be the correct way for you return type, otherwise change your return type to return a document type instead of a POJO
