### ISSUE TITLE
Where is `Base` class?

### ISSUE THREAD

**Issue by KeithGillette** [typegoose/typegoose#863]
The [With the Base Class](https://typegoose.github.io/typegoose/docs/guides/advanced/change-id-type/#with-the-base-class) section of the Change _id Type Guide includes an example of extending_a `Base` _class_ but does not show the import location. I can only find a `Base` _interface_ in the `defaultClasses` module. Does the `Base` class exist? If so, where?

**Comment by smolinari** [comment]
@KeithGillette - That is a mistake from the legacy way of using Base, where it used to be a class. It is only an interface now and no longer is a class.

https://typegoose.github.io/typegoose/docs/guides/default-classes/#base

Scott

**Comment by KeithGillette** [comment]
Thanks for the fast reply, @smolinari. It looks to me like [that Default Classes page](https://typegoose.github.io/typegoose/docs/guides/default-classes/#base) is also incorrect, as the code example for `Base` uses the `extends` keyword, which can only be used with a Class, instead of the `implements` keyword appropriate for an Interface.

**Comment by hasezoey** [comment]
> It looks to me like [that Default Classes page](https://typegoose.github.io/typegoose/docs/guides/default-classes/#base) is also incorrect, as the code example for Base uses the extends keyword,

what about the following example is wrong? (the same for the `change _id type` documentation)

```ts
interface Something extends Base {} // have the interface to add the types of "Base" to the class
class Something {} // have your class, OR
class Something extends TimeStamps {} // have your class extend some other class
```

a interface can *extend* a interface, those definitions are merged into 1 (in most editors at least, like vscode / tsc directly)

**Comment by KeithGillette** [comment]
My mistake, @hasezoey. I missed that `Something` was also an Interface and thought it was a Class. So it's just the [With the Base Class](https://typegoose.github.io/typegoose/docs/guides/advanced/change-id-type/#with-the-base-class) section of the Change _id Type Guide that's incorrect.

**Comment by hasezoey** [comment]
is https://typegoose.github.io/typegoose/docs/guides/advanced/change-id-type/#with-the-base-interface still incorrect?

**Comment by KeithGillette** [comment]
> is https://typegoose.github.io/typegoose/docs/guides/advanced/change-id-type/#with-the-base-interface still incorrect?

Yes, the anchor text section header is "With the Base Class" but the `Base` Class no longer exists.

**Comment by hasezoey** [comment]
> Yes, the anchor text section header is "With the Base Class" but the Base Class no longer exists.

i dont quite know what you mean

![Screenshot 2023-07-06 at 23-10-50 Change _id Type typegoose](https://github.com/typegoose/typegoose/assets/10911626/2ec26310-3fe5-4d80-9618-976ba567f701)


unless you mean the [10.x docs](https://typegoose.github.io/typegoose/versions/10.x/docs/guides/advanced/change-id-type#with-the-base-class) (or beta), which i have not updated yet

**Comment by KeithGillette** [comment]
This is what the linked section header looked like in the 11.x docs when I opened this issue:
<img width="1509" alt="image" src="https://github.com/typegoose/typegoose/assets/19915029/7b9be79a-9739-4277-adc2-61c43a5a4b9b">

Note also the text "There is also a Base interface typegoose provides". The "also" makes it sound like there is a Class and _also_ an Interface.
