### ISSUE TITLE
OverwriteModelError: Cannot overwrite model once compiled.

### ISSUE THREAD

**Issue by zineanteoh** [typegoose/typegoose#864]
## Versions

- System: macos
- NodeJS: 16.14.0
- Typescript: 5.1.6

- Compiler / Transpiler: nextjs 13.4.7 swc
- Typegoose(NPM): 11.3.0
- mongoose: 7.3.1
- mongodb: 5.6.0

## What is the Problem?

Using NextJS (13.4.7). Hot reload raises the error: 

![image](https://github.com/typegoose/typegoose/assets/58854510/67403a1c-70d6-45bf-88b5-0a25910cc48f)

## Code Example

```ts
// item.ts
import { Ref, prop } from "@typegoose/typegoose";
import { User } from "./User";

export class Item {
  @prop({ ref: () => User })
  public userId: Ref<User>;

  @prop()
  public width: number;

  @prop()
  public height: number;
}

// user.ts
import { Ref, prop } from "@typegoose/typegoose";
import { Item } from "./Item";

export class User {
  @prop()
  public name: string;

  @prop()
  public email: string;

  @prop({ ref: () => Item })
  public items: Ref<Item>[];
}


// index.ts
import { Item } from "./Item";
import { User } from "./User";
import { getModelForClass } from "@typegoose/typegoose";

export const ItemModel = getModelForClass(Item, {
  schemaOptions: {
    collection: "items",
  },
});
export const UserModel = getModelForClass(User, {
  schemaOptions: {
    collection: "users",
  },
});

```

## Do you know *why* it happens?

I know how to fix if I were using mongoose: https://nesin.io/blog/fix-mongoose-cannot-overwrite-model-once-compiled-error

But couldn't find any guide on typegoose. 

Help would be appreciated, thank you! 

---

**Comment by zineanteoh** [comment]
Ah, turns out the fix is just like mongoose! 

Added `mongoose.models.Item` and `mongoose.models.User` to use the model if it already exists: 

```ts
// ...
export const ItemModel = mongoose.models.Item || getModelForClass(Item, { ... });
export const UserModel = mongoose.models.User || getModelForClass(User, { ... });
```

**Comment by hasezoey** [comment]
just wanna note that using the method of `= mongoose.models.Model || getModelForClass(class)` means that if the class / model was changed, then it is *not* reloaded and the old version is still used that was added first

maybe consider using a `nestjs-typegoose` fork [`@m8a/nestjs-typegoose`](https://www.npmjs.com/package/@m8a/nestjs-typegoose) (i dont know if `nestjs-typegoose` actually reloads the models, because i have never used it)

**Comment by zineanteoh** [comment]
> just wanna note that using the method of `= mongoose.models.Model || getModelForClass(class)` means that if the class / model was changed, then it is _not_ reloaded and the old version is still used that was added first

Ah, that explains why I used to get out-of-date models when using NextJS with mongoose. I resorted to clearing the next cache by deleting .next/ folder. Now it makes sense… Thanks for the note! 

> maybe consider using a `nestjs-typegoose` fork [`@m8a/nestjs-typegoose`](https://www.npmjs.com/package/@m8a/nestjs-typegoose) (i dont know if `nestjs-typegoose` actually reloads the models, because i have never used it)

That seems to be for NestJS. Is there one for NextJS?

**Comment by hasezoey** [comment]
> That seems to be for NestJS. Is there one for NextJS?

didnt notice it was Ne**x**tJS and not Ne**s**tJS

i am not aware of such a package for typegoose for NextJS

**Comment by melvinotieno** [comment]
Experiencing this same issue. Going through the fix, seems like it is not the best option. But somehow this issue was closed, did you find a fix for this?

**Comment by zineanteoh** [comment]
@melvinotieno i fixed it by adding `mongoose.models.Item` as stated in my comment before closing the issue. had to also delete `.next` folder and restart server. 

is this “fix” not working for you?

**Comment by melvinotieno** [comment]
I haven't tried it yet. I was just concerned about this comment.

> just wanna note that using the method of = mongoose.models.Model || getModelForClass(class) means that if the class / model was changed, then it is not reloaded and the old version is still used that was added first

Does this means that I have to delete the .next file every time I make a change to a class?

**Comment by hasezoey** [comment]
> Does this means that I have to delete the .next file every time I make a change to a class?

i dont know how your hot-reloading system works, but if it does not actually restart the server (the node process with mongoose), then the model will be cached by mongoose, so either use the mentioned workaround, but dont get updated models if they are updated (until server restart) or use a somewhat more complex method of removing the model and re-adding it

**Comment by melvinotieno** [comment]
Aaah, alright thanks. I'll try it out to see how it works

**Comment by mogadanez** [comment]
for me 
```
export const ItemModel = mongoose.models.Item || getModelForClass(Item, { ... });
export const UserModel = mongoose.models.User || getModelForClass(User, { ... });
```

then it  loose type safety 

UserModel.findOne() returns any in this case

**Comment by hasezoey** [comment]
> Should we reopen? The only solution is a manual workaround in every model, which also loses type safety and functionality. > Feels like something Typegoose itself should handle.

This bug has been answered and i dont see it as a bug in typegoose.
Feel free to open a feature request though.

**Comment by hasezoey** [comment]
FYI:
```ts
const MyModelName = getName(MyModelClass);
if (process.env.NODE_ENV === 'development' && mongoose.modelNames().includes(MyModelName)) {
  deleteModel(MyModelName);
}
const MyModel = getModelForClass(MyModelClass);
```
[`getName`](https://typegoose.github.io/typegoose/docs/api/functions/get-name)  [`deleteModel`](https://typegoose.github.io/typegoose/docs/api/functions/delete-model)
