### ISSUE TITLE
'TG_ALLOW_MIXED' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by SaahilSabu** [typegoose/typegoose#865]
## Issue
I am trying to build my ts backend , as suggested in the docs , i am setting TG_ALLOW_MIXED=ALLOW to remove the error 
"Setting "Mixed" for property "Product.images"
Look here for how to disable this message: https://typegoose.github.io/typegoose/docs/api/decorators/model-options/#allowmixed",
but adding the above in my run script gives me the error "'TG_ALLOW_MIXED' is not recognized as an internal or external command, operable program or batch file".

## Versions

- System: windows 
- NodeJS: v18.16.1
- Typescript: 5.1.3
 
- transpileOnly: tried with and without does not help
- Compiler / Transpiler: tsc 
- Typegoose(NPM): 11.3.0 
- Typegoose(GIT): commithash
- mongoose: 7.3.1 

---

**Comment by hasezoey** [comment]
> i am setting TG_ALLOW_MIXED=ALLOW to remove the error
"Setting "Mixed" for property "Product.images"

i recommend to first check (if not already done so) that the properties actually should be Mixed

> but adding the above in my run script gives me the error "'TG_ALLOW_MIXED' is not recognized as an internal or external command, operable program or batch file".

assuming you are on windows, you need to set the following in a batch file
```batch
SET TG_ALLOW_MIXED="ALLOW"
```
in powershell:
```ps
$env:TG_ALLOW_MIXED = 'ALLOW'
```
linux bash:
```sh
export TG_ALLOW_MIXED=ALLOW
# or in bash
TG_ALLOW_MIXED=ALLOW npm run yourScript
```
(i dont know if setting the environment variable directly like in bash is available for batch or powershell)

if those above do not work, please refer to your script executables instructions on how to set environment variables

note that `allowMixed` can also be set for a individual class, a individual property or it can also be set globally
```ts
@modelOptions({ options: { allowMixed: Severity.ALLOW } })
class Test {}
// or for a individual property
class Test {
  @prop({ allowMixed: Severity.ALLOW })
  public yourProp?: Mixed;
}
// or globally
setGlobalOptions({ options: { allowMixed: Severity.ALLOW } });
```
 note that the global-options way needs to be set **before any classes are imported**

**Comment by SaahilSabu** [comment]
Thank you @hasezoey
