### ISSUE TITLE
How to use @plugin decorator for a simple mongoose plugin that adds a tenantId property to applied schema

### ISSUE THREAD

**Issue by mkgn** [typegoose/typegoose#866]
## Versions
- System: windows 
- NodeJS: 18.12.1
- Typescript: 5.1.5
- Compiler ts-node
- Typegoose(NPM): 11.3.0
- mongoose: 7.3.1
- mongodb: latest

This is to support multi-tenancy based at document level. So the requirement is that I create a plugin that adds a tenantId property to a given schema and also adds an index to the field. So far the simplest version I have is below

    const tenantDocumentPlugin = (schema: Schema) => {
      schema.add({
        ["tenantId"]: { index: true, type: String, required: true},
     });  
    };

    export default tenantDocumentPlugin;

Now I need to apply this to a typegoose model. A sample is below.

    @modelOptions({ schemaOptions: { collection: 'users',timestamps: false, versionKey: false } })
    @plugin(tenantDocumentPlugin)
    export class User {
      public _id?:mongoose.Types.ObjectId;
  
      @prop()
      public firstname: string;
  
      @prop()
      public lastname: string; 
    }

Now my problem is when trying to apply the plugin to above model based on the [guide here](https://typegoose.github.io/typegoose/docs/api/decorators/plugin) it doesn't seem to work. What I have tried is below;

    @modelOptions({ schemaOptions: { collection: 'users',timestamps: false, versionKey: false } })
    @plugin(tenantDocumentPlugin)
    export class User extends tenantDocumentPlugin{ <--this is the place I don't understand
      public _id?:mongoose.Types.ObjectId;
  
      @prop()
      public firstname: string;
  
      @prop()
      public lastname: string; 
    }

**extends tenantDocumentPlugin** does feel wrong because it's not a schema. So, how should I solve this? My expectation is something like;

1) Create a mongoose pugin that adds a tenantId field and an index to that field.
2) When using typegoose I use above plugin so that for every deocrated entity I can do **Entity.TenantId** and the property can be read/write and it should be identified by typescript system.

Sorry if this is a basic question. But I am doing this while learning TypeScript as well.

**Comment by hasezoey** [comment]
> `@plugin(tenantDocumentPlugin)`
> `export class User {`

that is correct

> `class User extends FindOrCreate {}`

this was for a earlier version of typegoose which provided a default class called `FindOrCreate` for the plugin `mongoose-findorcreate`, you can see a more up to date example for findorcreate example [here](https://typegoose.github.io/typegoose/docs/guides/integration-examples/common-plugins#mongoose-findorcreate) (along other plugins)

---

assuming the following what your plugin does:
```ts
schema.add({
  ["tenantId"]: { index: true, type: String, required: true},
}); 
```

then you will need to add a entry `public tenantId: string;` (without a `@prop`) to your class, otherwise you would not get the typing.

for some testing and looking how it works, you can try the [typegoose-examples](https://github.com/typegoose/typegoose-examples) (there are currently not many, but it should be enough for this case)

**Comment by mkgn** [comment]
@hasezoey thanks for the information. I  also noticed at another [place](https://nmajor.com/posts/multi-tenancy-with-expressmongoose) that similar tenant wise data storing is being done using discriminators. One question I have is in general when we use getModelForClass/getDiscriminatorModelForClass should they be called once and keep the models as constants through out the life time of the application or can we use these methods inside a class such as;

    export class UserRepository implements IUserRepository {
     _UserModel: any
     constructor(){     
          this._UserModel = getDiscriminatorModelForClass(getModelForClass(tenantModel),User);     
     }     
     async createUser (user: User): Promise<User> {
         return await this._UserModel.create(user);
     }
     }

Notice that in every repo instance I am calling  getDiscriminatorModelForClass(getModelForClass(tenantModel),User) to get the schema that is decorated with the tenantId. Is this correct? Are their any memory allocation/performance complications if I keep calling this on every new instance of the repository?

I am coming with a .Net background and seeing lot of **const <something>** in typescript is something I still trying to get used to.

**Comment by smolinari** [comment]
@mkgn - I personally don't think discriminators are a good fit for multi-tenancy. You'd have N number of models for each tenant. This won't scale well at all. 

Scott

**Comment by hasezoey** [comment]
> Notice that in every repo instance I am calling getDiscriminatorModelForClass(getModelForClass(tenantModel),User) to get the schema that is decorated with the tenantId. Is this correct

by default, each call to `get*ModelForClass` will at first return a new compiled model, and subsequently return the already compiled model.
but there are problem with the caching and the caching can also be disabled with [Disable Caching](https://typegoose.github.io/typegoose/docs/guides/advanced/models-with-same-name/#disable-caching) and it is recommended to use your own caching method suited to your needs

**Comment by mkgn** [comment]
Thank you @hasezoey and @smolinari. Well, in .Net world we would just create an interface to hold TenantID and apply it for any tenant enabled entities (or use attributes like decorators to mark an entity is tenant enabled). Then if using an ORM like EF, you would right a global query filter where any query running against the database considers the tenantId field in select,update etc... 

So, if I am avoiding discriminators then a simple method as above in .net world may work still I beleive. Found out that hooks are useful for me to fill the tenantId in "PreSave" event using typegoose **@Pre<Entity>** which is useful. Similarly can we intercept the queries and add a condition like **" and tenantid={user's tenant id}"**

Anyway, I will play around a bit and see. Tutorials regarding multi-tenancy with Mongo is a bit difficult to find and the only recent plugin I found was [this](https://github.com/dvdprrsh/mongoose-tenant) which is still for mongoose 6.

I will close the case since this is has now turned more into a architectural decision making. But I would love to hear if there are others who have gone through this path and what their solutions was.

**Comment by smolinari** [comment]
@mkgn - There are a number of plugins for Mongoose for adding the tenantId to do multi-tenancy. Go to the Mongoose docs and on their landing page, click on the "Discover plugins" button. Search for "multitenant". I wouldn't take the plugins you find for granted though i.e. don't assume the code will work and is good right off the bat. Look through the plugin code and you might find one you could fork, use and modify as you need it. Or, worst case, you can adopt their code to use in your own plugin. 

Scott
