### ISSUE TITLE
Model.deleteMany does not respect the writeConcern options

### ISSUE THREAD

**Issue by thongxuan** [typegoose/typegoose#867]
## Versions

- System: macos 
- NodeJS: 18.16.0
- Typescript: 5.0.4

- Compiler / Transpiler: ts-node 
- Typegoose(NPM): 11.0.0 
- Typegoose(GIT): commithash
- mongoose: 7.0.3 
- mongodb: 5.2.0
- grahpql / type-graphql: 15.5.0 / 1.1.1 

## What is the Problem?

Model.deleteMany does not respect the writeConcern options

## Code Example

I have a LogModel defined using

```
import { getModelForClass, modelOptions } from '@typegoose/typegoose';
@modelOptions({ schemaOptions: { writeConcern: { w: 0 } } })
export class Log {...}

export const LogModel = getModelForClass(Log);
```

the write concern here is to speedup the log write requests.

Now I would like to remove the logs inside a transaction with other models, and the error is:
`Cannot have explicit session with unacknowledged writes`

```
await withTransaction(async (session) => {
    ...other removal
    await LogModel.deleteMany({ user: user._id }, { session });
    ...other removal
});
```

I tried supply explicit write concern into the deleteMany query to override the setting in model, but same error occurs.

```
await withTransaction(async (session) => {
    ...other removal
    await LogModel.deleteMany({ user: user._id }, { session, writeConcern: { w: 'majority', j: true } });
    ...other removal
});
```

## Do you know *why* it happens?

*no*

---

**Comment by thongxuan** [comment]
Mongoose team confirmed and fixed this bug. Thanks.

**Comment by hasezoey** [comment]
for reference, i think https://github.com/Automattic/mongoose/issues/13592 is the one that was opened for this
