### ISSUE TITLE
Schema options not working 

### ISSUE THREAD

**Issue by kiprobinson** [typegoose/typegoose#87]
I'm trying to use [`toObject` and `toJSON` schema options](https://mongoosejs.com/docs/guide.html#toJSON) and I can't figure out how to make it work. These options should make it so that virtual fields are included when a result doc is serialized to JSON. The documentation [mentions schema options with @modelOptions](https://typegoose.github.io/typegoose/docs/decorators/modelOptions/) but I can't get it to work.

## Versions

- NodeJS: 10.16.0
- Typegoose(NPM): 6.0.4
- Typegoose(GIT): commithash
- mongoose: 5.7.5
- mongodb: 4.2.0

## Code Example

[Full code here: mongotest.zip](https://github.com/typegoose/typegoose/files/3740910/mongotest.zip)

```ts
import { prop, getModelForClass, modelOptions, DocumentType } from '@typegoose/typegoose';
import * as mongoose from 'mongoose';

// @ts-ignore
@modelOptions({options: { toObject: { getters:true, virtuals:true}, toJSON: { getters:true, virtuals:true} }})
class User {
	@prop({
		required: true,
		trim: true,
		minlength: 1,
	})
	firstName:string;
	
	@prop({
		required: true,
		trim: true,
		minlength: 1,
	})
	lastName:string;
	
	public get fullName():string {
		return `${this.firstName} ${this.lastName}`;
	}
	public set fullName(s:string) {
		throw("NOT SUPPORTED");
	}
}

const UserModel = getModelForClass(User); // UserModel is a regular Mongoose Model with correct types
interface UserDoc extends DocumentType<User> {};

(async ():Promise<void> => {
	await mongoose.connect('mongodb://localhost:27017/', { useNewUrlParser: true, useUnifiedTopology: true, dbName: "test" });
	
	const { _id: id } = await UserModel.create({ firstName: 'John', lastName: 'Doe' } as User); // an "as" assertion, to have types for all properties
	const user:UserDoc = await UserModel.findById(id).exec();
	
	console.log(user); // does not include "fullName" property
	console.log(JSON.stringify(user)); //does not include "fullName" property
	console.log(user.fullName); //prints "John Doe"
})()
	.then(() => process.exit(0));
```

## Do you know *why* it happens?

*no*

**Comment by hasezoey** [comment]
they are `schemaOptions`, use them like so
```ts
@modelOptions({ schemaOptions: { toObject: { getters: true, virtuals: true }, toJSON: { getters: true, virtuals: true } } })
```

the `options` option is for typegoose custom options

**Comment by kiprobinson** [comment]
Yes that does it, thanks!

I thought I tried exactly that syntax, but it must not have been right.
