### ISSUE TITLE
ReturnModelType type throwing errors when using mongoose.models.<class>

### ISSUE THREAD

**Issue by sleepinzombie** [typegoose/typegoose#881]
- System: macOS
- NodeJS: 18.13.0
- Typescript: 5.0.4

- Compiler / Transpiler: tsc / ts-node / ts-jest 
- Typegoose(NPM): ^11.5.0 
- Typegoose(GIT): commithash
- mongoose: ^7.5.1 
- mongodb: 0.0.0

---

First of all, I am loving Typegoose! Thank you to all those awesome contributors in building such an awesome and easy to use tool!

I am using Typegoose with Next.js 13 and I am encountering an issue with the `ReturnModelType`.
So I have created my class as below:

```
@modelOptions({ schemaOptions: { collection: 'users' } })
export class User {
  @prop({ auto: true })
  _id: mongoose.Types.ObjectId;

  @prop()
  email: string;

  @prop()
  password: string;

  @prop()
  isAdmin: boolean;
}

```

And I have exported the User Model using the below:
```
export const UserModel = mongoose.models.Status || getModelForClass(User);
```

As you can see above, I had to add the `mongoose.models.Status` or else Next.js throws me an error saying `Cannot overwrite 'User' model once compiled.`

But now I cannot use:
```
export const UserModel: ReturnModelType<typeof User> = mongoose.models.User || getModelForClass(User);
```
If I do, I get this error:
<img width="1241" alt="image" src="https://github.com/typegoose/typegoose/assets/39788411/04d1c841-5dac-4a35-aba4-00e7df94bad0">

Any idea on how to fix this? For now I am using the `any` type, but I really want to know how I can fix this.
Thanking you all in advance.

**Comment by hasezoey** [comment]
because the type stored in `mongoose.models` is `mongoose.Model` instead of the type `ReturnModelType` it would need to be manually casted, this can be fixed by either:
- `mongoose.models.Status as ReturnModelType<typeof User>`, or
- `mongoose.models.Status as any` (works because the type is already constrained by `UserModel: ReturnModelType<typeof User>`)

**Comment by sleepinzombie** [comment]
Hi @hasezoey, thank you for the recommendation, it actually works!
I'm happy with the answer, closing this issue now, thanks a lot!
