### ISSUE TITLE
How to add global query filter for soft deleted documents

### ISSUE THREAD

**Issue by angelhodar** [typegoose/typegoose#884]
Hey, I have just implemented soft deletion for any document in my database and just wanted to know if this is the proper way to do it. I have tested it and its working, the only problem I suppose is that it doesnt affect aggregations (but I think it could be better like that). If so, I think it could be useful to add to the documentation as a snippet or something like that :)

```ts
@ObjectType()
@modelOptions({
  schemaOptions: {
    timestamps: true,
    toObject: { virtuals: true },
  },
})
@pre<BaseEntity>(['find', 'findOne', 'countDocuments'], function() {
  // Add a default condition to filter out soft-deleted documents
  this.where({ deleted: { $ne: true } });
})
export class BaseEntity implements Base {
  @Field(() => ID)
  readonly _id: Types.ObjectId;

  @Field(() => ID)
  readonly id: string;

  @Field()
  @prop()
  public createdAt: Date;

  @Field()
  @prop()
  public updatedAt: Date;

  @Field({ nullable: true })
  @prop()
  public deleted?: boolean;

  @Field({ nullable: true })
  @prop()
  public deletedAt?: Date;

  async markDeleted(this: DocumentType<BaseEntity>) {
    this.deleted = true
    this.deletedAt = new Date()
    await this.save()
  }
}
```

**Comment by hasezoey** [comment]
looks proper to me, though also note that there is a plugin for this [`mongoose-delete`](https://www.npmjs.com/package/mongoose-delete), and i dont think this a proper thing to add to the typegoose documentation, you could add it to [typegoose-examples](https://github.com/typegoose/typegoose-examples) though.
