### ISSUE TITLE
Get original Class from NestedPath's

### ISSUE THREAD

**Issue by fabioformosa** [typegoose/typegoose#89]
Is possible to get the Type Class from an object of DocumentType?

```
const car: DocumentType<Car> = await CarModel.find(...);
const constructorName = car.constructor.name;
console.log(constructorName); // "model"
```

`console.log` prints "model" and not "Car". I need the  constructor of the actual class.
Any help?

**Comment by Ben305** [comment]
What about `car.modelName`?

**Comment by hasezoey** [comment]
does `getClassForDocument` not work?

when this fixes your issue, please let it open, i would re-tag this to "docs", because there isnt documentation about it *yet*

**Comment by hasezoey** [comment]
sorry i was wrong, there is documentation about it, just forgot to add it to the sidebar
https://typegoose.github.io/typegoose/docs/functions/getClassForDocument/

**Comment by fabioformosa** [comment]
> sorry i was wrong, there is documentation about it, just forgot to add it to the sidebar
> https://typegoose.github.io/typegoose/docs/functions/getClassForDocument/

Yes, it missed in documentation. Great, just that I was looking for!

**Comment by fabioformosa** [comment]
And... how can I get the class for a SingleNested/Embedded document?

**Comment by hasezoey** [comment]
> And... how can I get the class for a SingleNested/Embedded document?

currently not supported, sorry

**Comment by hasezoey** [comment]
@fabioformosa does #97 solve your question & request?

**Comment by fabioformosa** [comment]
you suggest this `getClassForSchema((doc.schema.path('testy') as any).schema)`, unfortunately in my function I haven't the `Document` but only the `SingleNested`.

I would like to do this:
```
class Parent{
   test: Test;
}

const parentDoc = ParentModel.findById(1);
const testSingleNested = parentDoc.test;

myFunction(testSingleNested);
```
```
myFunction(testSingleNested){
  console.log(getClassForDocument(testSingleNested)); //Test
}
```
At the moment is possible to call `getClassForDocument` only for Parent.
Is it possible to add to `constructors` also nested classes?

(if you would like find out my scenario, look at [this](https://github.com/fabioformosa/metamorphosis-nest#typegoose-support). It's an utility lib for conversion.

**Comment by hasezoey** [comment]
> Is it possible to add to constructors also nested classes?

it is, it currently takes the extra property `typegooseName` on the schema, to find the correct class in `constructors`, that is how i intended `getClassForSchema` to work

**Comment by fabioformosa** [comment]
Ok, if you have types of your example (Parent and Test) and you are in this function:
```
 myFunction(testSingleNested: SingleNested){
    //here I have not Parent Document and Parent Schema. How can I get Test class from SingleNested here?
}
```

**Comment by hasezoey** [comment]
i currently dont know how to hook into mongoose's nestedPath creation, without modifying it too much, that is why i went for schema

**Comment by hasezoey** [comment]
Update to it, i mean i dont currently know a why to modify "SingleNestedPath" & "MultiNestedPath" consistently / without too much code just for this

**Comment by hasezoey** [comment]
@fabioformosa does 7b39340a3e1380e675775e1e78493cd21dd6a0a2 fix it now? it is the only reliable solution i found - but it "pollutes" output if virtuals are enabled

**Comment by hasezoey** [comment]
created an "feature request" in mongoose https://github.com/Automattic/mongoose/issues/8284

**Comment by fabioformosa** [comment]
Interesting solution, I'll follow the feature request in mongoose.

**Comment by hasezoey** [comment]
I change the title to match the current "request"
