### ISSUE TITLE
Support mongoose 8.0.0

### ISSUE THREAD

**Issue by aletorrado** [typegoose/typegoose#892]
Hi, I'm opening this issue just to track support for `mongoose@8.0.0`.

**Comment by hasezoey** [comment]
as a note, some work has already been done in branch `feature/12.0` (like nodejs upgrade, typescript upgrade and mongoose upgrade)

**Comment by hasezoey** [comment]
[typegoose 12.0.0 has now been released](https://github.com/typegoose/typegoose/releases/tag/v12.0.0)
