### ISSUE TITLE
[BUG] - Using .lean() doesn't transform nested populate

### ISSUE THREAD

**Issue by SK-FComputer** [typegoose/typegoose#903]
## Versions

- System: linux
- NodeJS: 16.18.1
- Typescript: 5.3.2

- Compiler / Transpiler: tsc / ts-node
- Typegoose(NPM): 11.7.1 
- mongoose: 7.6.6 
- mongodb: 6.0.11

## What is the Problem?

Just to clarify from a start, yes i know this might be wrong usage:
Using this code to populate paths doesn't get transformed when populating paths with `.lean()` option.

## Code Example

Structure:
User.debtor[REF].discounts[ARRAY].discount[REF]

1. Get's populated, but not transformed
  ```ts
  UserModel.findById(id)
	  .populate({
		  path: 'debtor',
		  populate: {
			  path: 'discounts',
			  populate: {
				  path: 'discount',
			  },
		  },
	  }).lean();
  ```

2. This works as expected (Populated + transformed):
```ts
UserModel.findById(id)
	.populate({
		path: 'debtor',
		populate: {
			path: 'discounts.discount',
		},
	}).lean();
```

## Do you know *why* it happens?

*no*, but I'm guessing the code to populate supports the option while the code to transform/lean doesn't?

---

I can't upgrade to latest versions at current time, so I can't confirm but still suspect this is an issue there.

**Comment by hasezoey** [comment]
if your problem is about what `.populate` does at runtime, then you need to report this issue to mongoose instead of typegoose, because typegoose has no part in this (typegoose only "compiles" the class into a mongoose schema and model)

**Comment by hasezoey** [comment]
closing this issue as this is marked a "not a typegoose issue" and has been stale for quite a while.

for reference, the created mongoose issue is https://github.com/Automattic/mongoose/issues/14167
