### ISSUE TITLE
Select only fields explicitly declared in class

### ISSUE THREAD

**Issue by wasya243** [typegoose/typegoose#906]
Hello, I have question. Here is the code:

```ts
import {getModelForClass, setGlobalOptions, prop} from '@typegoose/typegoose';
import * as mongoose from 'mongoose';

setGlobalOptions({
  schemaOptions: {
    strict: 'throw'
  }
})

class User {
  @prop({ required: true })
  firstName!: string;

  @prop({ required: true })
  lastName!: string;
}

const UserModel = getModelForClass(User);

async function foo() {
  try {
    await mongoose.connect('mongodb://localhost:27017/test-invalid-data-from-db');

    // await UserModel.create({
    //   firstName: 'Vasyl',
    //   lastName: 'Kharchenko'
    // });

    // fetch doc from previous run above, but with manually added fields shitField1, shitField2
    const qU = await UserModel.findById('6589411bae7993a8900ee79b');

    /*
    here-qU {
      _id: new ObjectId('6589411bae7993a8900ee79b'),
      firstName: 'Vasyl',
      lastName: 'Kharchenko',
      shitField1: 'shitFieldValue1',
      shitField2: [ 1, 2, 3 ],
      __v: 0
    }
    */
    console.log('here-qU', qU);
    process.exit(0);
  } catch (err) {
    console.log('err', err);
    process.exit(1);
  }
}

foo();
```

So basically my question is it possible to somehow return only fields that are in schema/class? I've already seen such solution https://stackoverflow.com/questions/28063849/mongoose-select-only-fields-explicitly-declared-in-schema, but I would not like to manually modify all finds, .etc. Is there a config/flag to enable this behaviour?

**Comment by hasezoey** [comment]
try `await UserModel.findById('6589411bae7993a8900ee79b', { strict: true })`, this should help (i quickly tested it), but i dont know of a way to make this option "global"; maybe try opening a issue in mongoose to add a way for this
(note this `strict` is different than the schema level / global `strict` option and the `strictQuery` option)
