### ISSUE TITLE
Schema difference for class props that aren't mongoose documents

### ISSUE THREAD

**Issue by Ben305** [typegoose/typegoose#91]
## Versions

- NodeJS: 10.16.0
- Typegoose(NPM): 6.1.0-3
- mongoose: 5.7.5
- mongodb: 4.2.0
  
## What is the Problem?

Generated schema is different from Typegoose 5

## Code Example

```ts
class Image {
    url: string;
    alt: string
}

class Article {
    @prop()
    title: string;

    @prop()
    image: Image;
}

export const ArticleModel = getModelForClass(Article);
```

In Typegoose 5 the article schema path for image is `Mixed`, which is correct. In Typegoose 6 it becomes `SingleNested`, which is wrong, because Image is no Typegoose/Mongoose model!

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
> because Image is no Typegoose/Mongoose model!

it is, it becomes a schema, isnt it supposed to be so? because `Mixed` is implicit...

otherwise, did you try `@prop({ type: mongoose.Schema.Type.Mixed })` with Image?

**Comment by Ben305** [comment]
No, `Image` isn't supposed to become a schema. It's a class used throughout the code, but it has no collection nor ids.

Using `prop({ type: mongoose.Schema.Type.Mixed })` did not help. 

See #92 for a fix.

**Comment by hasezoey** [comment]
it didnt help? ok, i need to investigate this

**Comment by hasezoey** [comment]
@Ben305 could you try what i suggested with the latest master again (thanks to 17c0c05420190887bd60ff0547e72db08ce2eb7c)?

**Comment by Ben305** [comment]
@hasezoey Working fine, I have now finished migrating my biggest project to Typegoose 6 🎉

**Comment by Ben305** [comment]
@hasezoey Maybe you could add the tests i've written for #92 to the project.
