### ISSUE TITLE
isRefType function fails to identify wrapped ObjectId instances

### ISSUE THREAD

**Issue by manzonif** [typegoose/typegoose#924]
## Versions

NodeJS: 20.11.1
Typegoose (NPM): 12.0.0
mongoose: 8.0.3
mongodb: MongoDB

## What is the Problem?

The isRefType function in Typegoose seems to fail to identify ObjectId instances that are "wrapped" (boxed) by MongoDB. When checking if a document property is an ObjectId reference type, the isRefType function returns false even though the property appears to be a valid ObjectId.

Code Example

```typescript
import { isRefType } from '@typegoose/typegoose';
import mongoose from 'mongoose';

const doc = { company: new ObjectId("63a29391016fe22c0045abb9") };

console.log(mongoose.Types.ObjectId.isValid(doc.company)); // true
console.log(isRefType(doc.company, mongoose.Types.ObjectId)); // false (expected true)
```

## Do you know why it happens?

The issue appears to be caused by the way MongoDB "wraps" (boxes) ObjectId instances when returning them from the database. The isRefType function checks if the document property is an instance of mongoose.Types.ObjectId using the instanceof operator. However, the wrapped ObjectId instance is not a direct instance of the ObjectId class, so the instanceof check fails.

One potential solution could be to modify the isRefType function to handle these wrapped ObjectId instances. For example, by checking if the object has a _bsontype property with the value 'ObjectID', which is a known characteristic of wrapped ObjectId instances.

I would appreciate any guidance or insights you can provide on this issue and the appropriate way to handle wrapped ObjectId instances in Typegoose.

**Comment by hasezoey** [comment]
there is a known issue for mongoose 8.2.3, please try 8.2.2 or 8.2.4 https://github.com/Automattic/mongoose/pull/14463

**Comment by hasezoey** [comment]
sorry for the earlier message, i didnt read correctly.

yes, currently `isRefType` checks with a `instanceof`, which *should* be correct, but will fail if it is a instance of `(mongodb|bson).ObjectId`.
could you provide where you get the `new ObjectId` from? (as it is not listed in the imports)

**Comment by manzonif** [comment]
I get it fron nestjs resolveField:

```typescript
  @ResolveField(returns => Company)
  company(
    @Parent() news: News,
    @Args('lang') lang: string,
    @Loader(CompanyDataLoader.name)
    companyDataLoader: Dataloader<IntlDataLoaderKey<Company>, Company>,
  ): Promise<Company> {
    const doc: any = news.company; //actually company is:  company?: Ref<Company>; in the news model.
    ```

**Comment by hasezoey** [comment]
> I get it fron nestjs resolveField:

thanks, but i do not really understand what is coming from where, is the `ObjectId` in your case a `mongodb.ObjectId` (or `bson.ObjectId`) or something different?
also is `news` in your case a POJO (like gotten directly from JSON, and only contains JSON compatible types), instance of `News` (without further information i assume is a typegoose class), a mongoose Document, or a mongodb "document"?

Note: i mean the types at *runtime* not just *typescript types*

**Comment by manzonif** [comment]
Mongoose Document. 
```typescript
const news = await this.newsModel.findOne<NewsDocument>(criteria);
```

**Comment by hasezoey** [comment]
> Mongoose Document.

then the check should work without problems, to my knowledge at least; unless you somehow have mis-matching mongoose versions installed?

**Comment by manzonif** [comment]
I need to debug it and see how it came from, under the hood. This issue starts after several library updates. I will check more thoroughly.

**Comment by manzonif** [comment]
I have found a solution. To get the correct instance type for checking, I need to do something like this (which is not an ideal approach):
```typescript
    const doc: any = news.get ? news.get('company', Types.ObjectId) : null;
    if (doc && (isRefType(doc, Types.ObjectId))) {
      return  companyDataLoader.load({key: news.company.toString(), lang: lang});
    }
 ```
In this way, the adhoc.cast method performs the necessary work.

Isn't there a better way to cast the object within the isRefType function itself?

**Comment by hasezoey** [comment]
Guessing from the screenshots, i think those ObjectIds are a direct instance of `mongodb.ObjectId`(/`bson.ObjectId`).

I dont quite know the semantics of `cursor`, but in your case either your code is "wrong", or you are seemingly directly using mongodb's query instead of mongoose.
The reason for this is that in mongoose you dont have a `.next` function on a query until you call `.cursor()`, whereas mongodb's query always has a `.next()` as it is already a cursor.

Maybe check that the returned `doc` is actually a `doc instanceof mongoose.Document` and also try `yourObjectId instanceof mongodb.ObjectId` (or if you dont have mongodb directly installed `yourObjectId instanceof mongoose.mongo.ObjectId`).
Also try to check what `this._model` is on runtime. (example: `this._model.prototype instanceof mongoose.Model` should return `true`)
