### ISSUE TITLE
Error: Index already exist

### ISSUE THREAD

**Issue by Redskinsjo** [typegoose/typegoose#931]
Hi,

I have always an issue of index generation with conflicts. I try to define explicitly the name of the index, but it seems mongoose doesn't take that into account.

My code: 

```ts
export {};

import { index } from "@typegoose/typegoose";
import * as typegoose from "@typegoose/typegoose";
import type { Avatars } from "./types";
import { BetaUserSchema } from "./betaUsers";
import { BetaCompetencySchema } from "./betaCompetencies";
import { JobSchema } from "./jobs";
import mongoose from "mongoose";
mongoose.connect(`${process.env.MONGODB_URI}`);
mongoose.Promise = global.Promise;

@typegoose.modelOptions({
  schemaOptions: {
    timestamps: true,
    id: true,
  },
  options: {
    automaticName: false,
    customName: "BetaCandidate",
    allowMixed: typegoose.Severity.ALLOW,
  },
})

// tried also @index({ userId: 1 }, { name: "betacandidates_userid", unique: true })
export class BetaCandidateSchema {
  @typegoose.prop()
  public avatars: Avatars[];
  @typegoose.prop({ default: [], ref: () => "BetaCompetency" })
  public competencyIds: typegoose.Ref<BetaCompetencySchema>[];
  @typegoose.prop()
  public salaryExpected: string;
  @typegoose.prop()
  public type: string;
  @typegoose.prop()
  public bgImage: string;
  @typegoose.prop({ default: false })
  public confirmed: boolean;
  @typegoose.prop({
    ref: () => "BetaUser",
    index: { name: "betacandidates_userid", unique: true },
  })
  public userId: typegoose.Ref<BetaUserSchema>;
  @typegoose.prop({ ref: () => "Job" })
  public targetJobId: typegoose.Ref<JobSchema>;
  @typegoose.prop()
  public targetContractType: string;
  @typegoose.prop()
  public createdAt: Date;
  @typegoose.prop()
  public updatedAt: Date;
}

const model =
  mongoose.models.BetaCandidate ||
  typegoose.getModelForClass(BetaCandidateSchema);

model.createIndexes();

export default model;
```

## Versions

I am using version ^12.2.0

- System:  macos 
- NodeJS: 20.9.0
- Typescript: ^5.4.4
transpileOnly is not used
- Compiler / Transpiler: ts-node
- mongoose: ^8.3.0
- mongodb: not imported
- grahpql:^16.8.1

---

**Comment by Redskinsjo** [comment]
the error is ```MongoServerError: Index already exists with a different name: betacandidates_userId_key```

**Comment by hasezoey** [comment]
did you already try clearing the collections after adding your explicit name index?

also note that `createIndexes` will only create indexes, and error if they already exist (like under a different name).
maybe consider using [`syncIndexes`](https://mongoosejs.com/docs/api/model.html#Model.syncIndexes()) instead

**Comment by Redskinsjo** [comment]
@hasezoey great answer from you, thanks. I have just implemented a method to check indexes by looping over them with ```model.collection.getIndexes()```and dropping them when necessary (if name is not corresponding). I will check later if errors raise again.

Though I will investigate your solution thoroughly to learn more...

**Comment by Redskinsjo** [comment]
Please leave the issue open for now, I will come back to it and close it very soon if it's resolved ! thank you !
