### ISSUE TITLE
Babel to SWC: Inconsistent behavior when querying an undefined field

### ISSUE THREAD

**Issue by fromi** [typegoose/typegoose#942]
I am trying to switch my Next.JS project from babel to swc transpiler.
Everything works fine except for one thing: fields that are undefined in my mongodb database used to be replaced by the default class initialiser value. Now they are undefined.
For example:
```
  @prop()
  preferences: any = {}
```
With babel, I use to have "{}" in the field when it did not exist in the database.
Now with swc, I have "undefined".

What is the expected behavior, and do you have any idea why I have this regression? How would you workaround the issue?

## Versions

- NodeJS: 20.x
- Typescript: 5.4.5

- Compiler / Transpiler: tsc / swc
- Typegoose(NPM): 12.5.0 
- mongoose: 8.4.0 
- mongodb: 6.6.2
- grahpql / type-graphql: 15.5.0 / 1.1.1 

---

**Comment by hasezoey** [comment]
I have absolutely no clue why previously it would be `{}` as typegoose does not use class's defaults (`name = DEFAULT`), only defaults defined via `@prop({ default: YourDefaultHere })`, otherwise i think the default `default` is `undefined` in mongoose.

Also, if your code example is anything to go by, then your prop is implicitly of type `Mixed`, which is rarely wanted, see [`@prop: allowMixed`](https://typegoose.github.io/typegoose/docs/api/decorators/prop#allowmixed) and [Setting "Mixed" is not allowed [E017]](https://typegoose.github.io/typegoose/docs/guides/error-warning-details/#setting-mixed-is-not-allowed-e017).

To be more specific i would need to see the full actual class, and maybe even a reproduction repository for build-chain investigation.

**Comment by fromi** [comment]
This property is Mixed on purpose (generic structure for many different games), and it is not related with the issue: I have another example with the same issue:
```
  @prop({enum: GameSpeed, type: String})
  speed: GameSpeed = GameSpeed.Disabled
```
When I do a "find" query on that model, if the field is not defined in the database, it is undefined now. I was somehow overidden with the field initialiser with babel.

I don't think it is worth investigating with a reproduction repository. However I do have one question: is it possible to have a default value to replace "undefined" when query an existing document from the database?

- `@prop({ default: YourDefaultHere })` does not work: it is for creation time, not for query time.
- `@prop({get: value => value ?? {}, set: value => value})` does not work either for me, because I am immediately serializing the object using graphql, and getters are bypassed...

**Comment by hasezoey** [comment]
> because I am immediately serializing the object using graphql, and getters are bypassed...

how are you serializing? you may wanna look into using `doc.toJSON()` or [`doc.toObject()` with the options `getters: true`](https://mongoosejs.com/docs/api/document.html#Document.prototype.toObject())

**Comment by fromi** [comment]
Thanks! I was using `toObject()` without `getters: true`.
Unfortunately, I ran into another issue: I have another field which is not managed by typegoose:
```
@ObjectType()
export class GameOptions {
  [...]
  
  @Field(() => Int)
  maxSpareTime = MAX_SPARE_TIME 
}
```
With Babel, when I was querying this objet kind from the database (it is a sub document), I use to have all the default properties values defined.
With SWC, only the fields that exists in the database are defined.
So it is clearly not related with Typegoose, it is Mongoose that behave differently when building objects from the database using find queries. With Babel it looks like the class was initialized, and with SWC it is not...
Thanks for the help!

**Comment by hasezoey** [comment]
> So it is clearly not related with Typegoose, it is Mongoose that behaves differently when building objects from the database using find queries. With Babel it looks like the class was initialized, and with SWC it is not...

i also dont think that this is a mongoos issue, as mongoose does not initialize / construct any custom classes

**Comment by fromi** [comment]
It cannot be something else though, here is my code:
```
// file GameResolver.ts
  @Query(() => Game, { nullable: true })
  async game(@Arg('id') id: string) {
    const game = GameModel.findById(id)
    console.log(game.options.maxSpareTime)
    return game
  }
  
// file Game.ts
@ObjectType()
@modelOptions({ options: { allowMixed: Severity.ALLOW } })
export default class Game {
  @Field(() => GameOptions, { nullable: true })
  @prop({ _id: false })
  options?: GameOptions
}

// file GameOptions.ts
@ObjectType()
@modelOptions({options: {allowMixed: Severity.ALLOW}})
export class GameOptions {
  @prop({enum: GameSpeed, type: String})
  speed: GameSpeed = GameSpeed.Disabled

  maxSpareTime = MAX_SPARE_TIME
}
```
As you can see the only instruction is `GameModel.findById(id)`
With babel: `console.log(game.options.maxSpareTime) => MAX_SPARE_TIME`
With SWC: `console.log(game.options.maxSpareTime) => undefined`

**Comment by hasezoey** [comment]
> It cannot be something else though, here is my code:

there likely shouldnt be any difference, what is the type of `game` and `game.options` in both compilers? (try `console.log(game)`, `console.log(game instanceof Game)` and `console.log(game instanceof mongoose.Document)`)

**Comment by fromi** [comment]
That's interesting, I must have been misleaded by my first tests: now I have undefined with babel too.
So the culprit is Type-GraphQL, which is able to get the property initialiser values with Babel, but not with SWC.
Sorry for bothering you, and thank you for the help!
