### ISSUE TITLE
How to implement $search?

### ISSUE THREAD

**Issue by ofuochi** [typegoose/typegoose#95]
How do I implement text search using typegoose?

In mongoose, all I have to do is to add a `text:true` property on a field I want to search. How do I do this with typegoose? `text` property is not part of the `@prop` decorator

**Comment by ofuochi** [comment]
I found a way around this. I created an index with the fields I want (in my case, all fields, that's why I used the wild card `$**`) to search on the model collection like so.
```ts
public static get model() {
  const model = new User().getModelForClass(User, {
    schemaOptions: { collection: "Users", timestamps: true }
  });
  model.collection.createIndex({ "$**": "text" }); // this does it.
  return model;
 }
```
I hope it helps someone else

**Comment by hasezoey** [comment]
> text property is not part of the @prop decorator

please link me to the mongoose documentation that has the "text" option

---

>   model.collection.createIndex({ "$**": "text" }); // this does it.

you can probably do
```ts
@index({'$**': "text"}) // for your indexes
@modelOptions({schemaOptions:{collection: "Users"}) // for your options
class Something extends defaultClasses.TimeStamps {}
```

-> take [this](https://github.com/typegoose/typegoose/blob/master/test/models/indexweigths.ts) test as an example for it

**Comment by ofuochi** [comment]
Thank you @hasezoey 

> please link me to the mongoose documentation that has the "text" option

I think you got me wrong. I said it the `text` property is **not** part of the `@prop` decorator.

**Comment by hasezoey** [comment]
> I think you got me wrong. I said... text property is not part of the @prop decorator.

that is what i meant, do you mean an option like `index: true` / `unique: true`?, when yes, i will have a look into it

**Comment by ofuochi** [comment]
Yes, that's what I mean.

> please link me to the mongoose documentation that has the "text" option

[Here ](https://mongoosejs.com/docs/api.html#schematype_SchemaType-text)is a sample from mongoose documentation

**Comment by hasezoey** [comment]
this is probably just an tsdoc issue, the `text` property should work anyway, or am i wrong?

**Comment by ofuochi** [comment]
I don't think it will work because it's not included in the `@prop` decorator. Of course, there's a workaround like I did below
```js
model.collection.createIndex({ "$**": "text" });
```

**Comment by hasezoey** [comment]
i mean `@prop({ text: true })` should work, if it is included in tsdoc or not

**Comment by ofuochi** [comment]
But then my code won't compile successfully

**Comment by hasezoey** [comment]
> But then my code won't compile successfully

it should, because PropOptions allows to be any string with any type - this is for such an problem, to **not** have compile errors
-> which typegoose version do you use?

**Comment by hasezoey** [comment]
otherwise the fix will be included in `6.1.0-8`

**Comment by ofuochi** [comment]
When you try to do that, you'll get the below error.
> Argument of type '{ required: true; maxlength: number; trim: true; text: boolean; }' is not assignable to parameter of type 'PropOptionsWithNumberValidate | PropOptionsWithStringValidate | VirtualOptions | undefined'.
  Object literal may only specify known properties, and 'text' does not exist in type 'PropOptionsWithValidate'.

> which typegoose version do you use?
I use `@hasezoey/typegoose` version `5.9.2`

**Comment by hasezoey** [comment]
> I use @hasezoey/typegoose version 5.9.2

5.x is not supported anymore - at least in 6.0.0 your are allowed to use it without any compile error

**Comment by ofuochi** [comment]
I'll update now and revert

**Comment by hasezoey** [comment]
PS: you should use `@typegoose/typegoose` because `@hasezoey/typegoose` was just an intermediate for the transition / to test dev versions of 6.0.0

**Comment by ofuochi** [comment]
Thanks @hasezoey 

Although there are so many breaking changes from @hasezoey/typegoose and @typegoose/typegoose but it's worth the effort.

I was misled by the [readme](https://github.com/szokodiakos/typegoose). It will be useful to update the readme
