### ISSUE TITLE
Ref array error in Quick Start Guide

### ISSUE THREAD

**Issue by theDanielJLewis** [typegoose/typegoose#968]
In the [Quick Start Guide](https://typegoose.github.io/typegoose/docs/guides/quick-start-guide/), it gives the following examples regarding refs:

```js
class Car {
  @prop()
  public model?: string;
}

class User {
  // other examples

  @prop({ ref: () => Car })
  public mainCar?: Ref<Car>; // This is a single Reference

  @prop({ ref: () => [Car] })
  public cars?: Ref<Car>[]; // This is a Reference Array
}
```

However, that second example is incorrect, according to [the @prop decorators page](https://typegoose.github.io/typegoose/docs/api/decorators/prop/#ref).

Instead of `@prop({ ref: () => [Car] })`, which gives errors in TypeScript, it seems it should be `@prop({ ref: () => Car })`.

**Comment by theDanielJLewis** [comment]
What was fixed? Was it only the documentation, or is `@prop({ ref: () => [Car] })` correct?

**Comment by theDanielJLewis** [comment]
Well now I'm confused. Is it, or is it not necessary to add `type` to `@prop` when referencing an array of another class?

**Comment by hasezoey** [comment]
> Is it, or is it not necessary to add type to @prop when referencing an array of another class?

When using `ref`, unless you are changing the reference type from the default `ObjectId`, you dont need to set `type`, even if it is a array.
(The `type` example above was to showcase that `[SomeType]` is valid for `type`, but not for `ref`)
